<?php /* Smarty version 2.6.25, created on 2013-03-25 12:19:30
         compiled from tpl_body:notemplate */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%11^11A^11A30C36%%tpl_body%3Anotemplate.inc'] = '7cea1a25459c821b58ff8635adc509af';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'content', 'tpl_body:notemplate', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_7cea1a25459c821b58ff8635adc509af_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7cea1a25459c821b58ff8635adc509af','0');echo smarty_cms_function_content(array(), $_smarty);
}



?>
