<?php /* Smarty version 2.6.25, created on 2013-03-13 09:34:20
         compiled from tpl_head:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%19^194^194941AA%%tpl_head%3A22.inc'] = 'b5627ebfe42fccc5b7b848002bf61763';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_b5627ebfe42fccc5b7b848002bf61763_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5627ebfe42fccc5b7b848002bf61763','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
