<?php /* Smarty version 2.6.25, created on 2012-06-15 17:51:50
         compiled from siteprefs.tpl */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%1B^1B2^1B2DE232%%siteprefs.tpl.inc'] = '9d12e53bd762c47d0f21d0d59208c746';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'html_options', 'siteprefs.tpl', 25, false),)), $this); ?>
<?php
function _smarty_tplfunc_9d12e53bd762c47d0f21d0d59208c746_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d12e53bd762c47d0f21d0d59208c746','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['wysiwyg'],'selected' => $_smarty->_tpl_vars['frontendwysiwyg']), $_smarty);
}


function _smarty_tplfunc_9d12e53bd762c47d0f21d0d59208c746_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d12e53bd762c47d0f21d0d59208c746','1');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['themes'],'selected' => $_smarty->_tpl_vars['logintheme']), $_smarty);
}


function _smarty_tplfunc_9d12e53bd762c47d0f21d0d59208c746_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d12e53bd762c47d0f21d0d59208c746','2');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['templates'],'selected' => $_smarty->_tpl_vars['custom404template']), $_smarty);
}


function _smarty_tplfunc_9d12e53bd762c47d0f21d0d59208c746_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d12e53bd762c47d0f21d0d59208c746','3');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_attributes'],'selected' => $_smarty->_tpl_vars['basic_attributes']), $_smarty);
}



?>
