<?php /* Smarty version 2.6.25, created on 2013-03-25 03:57:46
         compiled from tpl_top:23 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%25^25E^25E0F81D%%tpl_top%3A23.inc'] = '01545d08769f4efb47a42ffd7a5ad3ab';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:23', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_01545d08769f4efb47a42ffd7a5ad3ab_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01545d08769f4efb47a42ffd7a5ad3ab','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
