<?php /* Smarty version 2.6.25, created on 2013-03-13 09:34:20
         compiled from tpl_top:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = 'b5d29fa13f1bc7c361ea4b1ec3636a74';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_b5d29fa13f1bc7c361ea4b1ec3636a74_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b5d29fa13f1bc7c361ea4b1ec3636a74','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
