<?php /* Smarty version 2.6.25, created on 2012-06-15 17:18:13
         compiled from systeminfo.tpl */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%54^54D^54D58E70%%systeminfo.tpl.inc'] = 'efaf199a08d4b9849620fbff6922e00d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'si_lang', 'systeminfo.tpl', 3, false),array('modifier', 'default', 'systeminfo.tpl', 44, false),)), $this); ?>
<?php
function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','0');echo systeminfo_lang(array('a' => 'copy_paste_forum'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','1');echo systeminfo_lang(array('a' => 'help_systeminformation'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','2');echo systeminfo_lang(array('a' => 'cms_install_information'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','3');echo systeminfo_lang(array('a' => 'cms_version'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','4');echo systeminfo_lang(array('a' => 'installed_modules'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','5');echo systeminfo_lang(array('a' => 'config_information'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','6');echo systeminfo_lang(array('a' => 'php_information'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','7');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','8');echo systeminfo_lang(array('a' => 'server_information'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','9');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','10');echo systeminfo_lang(array('a' => 'permission_information'), $_smarty);
}


function _smarty_tplfunc_efaf199a08d4b9849620fbff6922e00d_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efaf199a08d4b9849620fbff6922e00d','11');echo systeminfo_lang(array('a' => 'back'), $_smarty);
}



?>
