<?php /* Smarty version 2.6.25, created on 2013-03-25 12:38:11
         compiled from template:notemplate */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%5E^5E7^5E74AD9F%%template%3Anotemplate.inc'] = '0e872ff5ceca14504dc2a5a856198f74';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'content', 'template:notemplate', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_0e872ff5ceca14504dc2a5a856198f74_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0e872ff5ceca14504dc2a5a856198f74','0');echo smarty_cms_function_content(array(), $_smarty);
}



?>
