<?php /* Smarty version 2.6.25, created on 2013-03-13 09:34:20
         compiled from tpl_body:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/%%76^763^76313DB0%%tpl_body%3A22.inc'] = '7067556fcefe68f67b97747d9e67c516';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'anchor', 'tpl_body:22', 7, false),array('function', 'cms_selflink', 'tpl_body:22', 18, false),array('function', 'search', 'tpl_body:22', 22, false),array('function', 'menu', 'tpl_body:22', 37, false),array('function', 'NMS', 'tpl_body:22', 41, false),array('function', 'cms_module', 'tpl_body:22', 44, false),array('function', 'breadcrumbs', 'tpl_body:22', 53, false),array('function', 'oldprint', 'tpl_body:22', 54, false),array('function', 'title', 'tpl_body:22', 58, false),array('function', 'content', 'tpl_body:22', 61, false),array('function', 'global_content', 'tpl_body:22', 82, false),)), $this); ?>
<?php
function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','0');echo smarty_cms_function_anchor(array('anchor' => 'menu_vert','title' => 'Skip to navigation','accesskey' => 'n','text' => 'Skip to navigation'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','1');echo smarty_cms_function_anchor(array('anchor' => 'main','title' => 'Skip to content','accesskey' => 's','text' => 'Skip to content'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','2');echo smarty_cms_function_cms_selflink(array('dir' => 'start','text' => ($_smarty->_tpl_vars['sitename'])), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','3');echo smarty_cms_function_search(array('search_method' => 'post','resultpage' => 'search'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','4');echo smarty_cms_function_menu(array('template' => 'cssmenu_ulshadow.tpl'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','5');echo $_smarty->_plugins['function']['NMS'][0][0]->function_plugin(array('mode' => 'subscribe'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','6');echo smarty_cms_function_cms_module(array('module' => 'polls'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','7');echo smarty_cms_function_breadcrumbs(array('starttext' => '','root' => 'Home','delimiter' => '&gt;'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','8');echo smarty_cms_function_oldprint(array('showbutton' => true), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','9');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','10');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','11');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','12');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'login'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','13');echo smarty_cms_function_menu(array('template' => 'minimal_menu.tpl','start_level' => '1','number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_7067556fcefe68f67b97747d9e67c516_14(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7067556fcefe68f67b97747d9e67c516','14');echo smarty_cms_function_global_content(array('name' => 'footer'), $_smarty);
}



?>
