<?php /* Smarty version 2.6.25, created on 2012-06-19 10:10:26
         compiled from tpl_top:24 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%BB^BB8^BB846DBE%%tpl_top%3A24.inc'] = 'a5572e784737abf99b12dd345f324b42';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:24', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_a5572e784737abf99b12dd345f324b42_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a5572e784737abf99b12dd345f324b42','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
