<?php /* Smarty version 2.6.25, created on 2012-06-19 10:42:09
         compiled from tpl_top:29 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%C5^C53^C5351103%%tpl_top%3A29.inc'] = 'd8b27ab6144c0d6ac852a19a86e99dc4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:29', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_d8b27ab6144c0d6ac852a19a86e99dc4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d8b27ab6144c0d6ac852a19a86e99dc4','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
