<?php /* Smarty version 2.6.25, created on 2012-06-19 10:42:09
         compiled from tpl_body:29 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%E1^E1E^E1E3E438%%tpl_body%3A29.inc'] = 'ef1d4c4308ca0ee0bffc6c3cd25779f8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'menu', 'tpl_body:29', 20, false),array('function', 'oldprint', 'tpl_body:29', 25, false),array('function', 'breadcrumbs', 'tpl_body:29', 27, false),array('function', 'title', 'tpl_body:29', 29, false),array('function', 'content', 'tpl_body:29', 31, false),array('function', 'global_content', 'tpl_body:29', 42, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','0');echo smarty_cms_function_menu(array('start_level' => '3','template' => 'verticalmenu'), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','1');echo smarty_cms_function_oldprint(array('showbutton' => true), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','2');echo smarty_cms_function_breadcrumbs(array('starttext' => '','root' => 'icchome','delimiter' => '&gt;'), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','3');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','4');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','5');echo smarty_cms_function_menu(array('template' => 'minimal_menu.tpl','start_level' => '1','number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_ef1d4c4308ca0ee0bffc6c3cd25779f8_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef1d4c4308ca0ee0bffc6c3cd25779f8','6');echo smarty_cms_function_global_content(array('name' => 'footer'), $_smarty);
}



?>
