<?php /* Smarty version 2.6.25, created on 2012-06-09 17:05:45
         compiled from globalcontent:footer */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%EE^EE6^EE6D73C2%%globalcontent%3Afooter.inc'] = '1a251dfe438454590aa7ca69a2236207';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'custom_copyright', 'globalcontent:footer', 1, false),array('function', 'cms_version', 'globalcontent:footer', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_1a251dfe438454590aa7ca69a2236207_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a251dfe438454590aa7ca69a2236207','0');echo cms_tmp_custom_copyright_userplugin_function(array(), $_smarty);
}


function _smarty_tplfunc_1a251dfe438454590aa7ca69a2236207_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a251dfe438454590aa7ca69a2236207','1');echo smarty_cms_function_cms_version(array(), $_smarty);
}



?>
