<?php /* Smarty version 2.6.25, created on 2012-06-19 10:10:26
         compiled from tpl_head:24 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/%%F0^F02^F02AE49F%%tpl_head%3A24.inc'] = '9ac31369cef6b02ddf81002b647e458d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:24', 4, false),array('function', 'sitename', 'tpl_head:24', 4, false),array('function', 'metadata', 'tpl_head:24', 7, false),array('function', 'stylesheet', 'tpl_head:24', 14, false),array('function', 'cms_selflink', 'tpl_head:24', 17, false),)), $this); ?>
<?php
function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_9ac31369cef6b02ddf81002b647e458d_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ac31369cef6b02ddf81002b647e458d','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
