<?php /* Smarty version 2.6.25, created on 2012-06-14 12:35:11
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/190^%%70^707^707A8977%%content%3Acontent_en.inc'] = '09bb952b65546bfef12de3638f68e54a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_09bb952b65546bfef12de3638f68e54a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09bb952b65546bfef12de3638f68e54a','0');echo smarty_cms_function_cms_selflink(array('href' => 'Contest_korp_smi'), $_smarty);
}


function _smarty_tplfunc_09bb952b65546bfef12de3638f68e54a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09bb952b65546bfef12de3638f68e54a','1');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
