<?php /* Smarty version 2.6.25, created on 2013-03-07 15:58:15
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/191^%%70^707^707A8977%%content%3Acontent_en.inc'] = '1a0f2dc6186b4dc7ca1d8777d51bf56d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_1a0f2dc6186b4dc7ca1d8777d51bf56d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a0f2dc6186b4dc7ca1d8777d51bf56d','0');echo smarty_cms_function_cms_selflink(array('href' => 'Contest_korp_sites'), $_smarty);
}


function _smarty_tplfunc_1a0f2dc6186b4dc7ca1d8777d51bf56d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a0f2dc6186b4dc7ca1d8777d51bf56d','1');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
