<?php /* Smarty version 2.6.25, created on 2012-06-10 22:50:46
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/192^%%70^707^707A8977%%content%3Acontent_en.inc'] = '3057be3da0ddc47f03fe34263da3ad13';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 78, false),)), $this); ?>
<?php
function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','0');echo smarty_cms_function_cms_selflink(array('href' => 'Sokos'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','1');echo smarty_cms_function_cms_selflink(array('href' => 'luchshee-korporativnoe-izdanie-2010'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','2');echo smarty_cms_function_cms_selflink(array('href' => 'luchshij-korporativnyj-portal-2010'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','3');echo smarty_cms_function_cms_selflink(array('href' => 'antonchik-tatyana-vyacheslavovna'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','4');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','5');echo smarty_cms_function_cms_selflink(array('href' => 'artsishevskij-ivan-sergeevich'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','6');echo smarty_cms_function_cms_selflink(array('href' => 'vajnberg-oleg-maratovich'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','7');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','8');echo smarty_cms_function_cms_selflink(array('href' => 'kolesnikova-anna'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','9');echo smarty_cms_function_cms_selflink(array('href' => 'oksana-makarenko'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','10');echo smarty_cms_function_cms_selflink(array('href' => 'artem-savko'), $_smarty);
}


function _smarty_tplfunc_3057be3da0ddc47f03fe34263da3ad13_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3057be3da0ddc47f03fe34263da3ad13','11');echo smarty_cms_function_cms_selflink(array('href' => 'conf_2010_programm'), $_smarty);
}



?>
