<?php /* Smarty version 2.6.25, created on 2013-03-07 15:58:19
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/193^%%70^707^707A8977%%content%3Acontent_en.inc'] = '5745e2b2a1a07e88baf325dc2eab3a13';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','0');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','1');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','2');echo smarty_cms_function_cms_selflink(array('href' => 'artem-savko'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','3');echo smarty_cms_function_cms_selflink(array('href' => 'antonchik-tatyana-vyacheslavovna'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','4');echo smarty_cms_function_cms_selflink(array('href' => 'anzhelika-tihonova'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','5');echo smarty_cms_function_cms_selflink(array('href' => 'kolesnikova-anna'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','6');echo smarty_cms_function_cms_selflink(array('href' => 'vajnberg-oleg-maratovich'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','7');echo smarty_cms_function_cms_selflink(array('href' => 'artsishevskij-ivan-sergeevich'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','8');echo smarty_cms_function_cms_selflink(array('href' => 'luchshee-korporativnoe-izdanie-2010'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','9');echo smarty_cms_function_cms_selflink(array('href' => 'luchshij-korporativnyj-portal-2010'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','10');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','11');echo smarty_cms_function_cms_selflink(array('href' => 'oksana-makarenko'), $_smarty);
}


function _smarty_tplfunc_5745e2b2a1a07e88baf325dc2eab3a13_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5745e2b2a1a07e88baf325dc2eab3a13','12');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
