<?php /* Smarty version 2.6.25, created on 2013-03-07 15:57:36
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/194^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'eed622a95db213f7efde970903784b61';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 1, false),array('function', 'NeoGallery', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_eed622a95db213f7efde970903784b61_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eed622a95db213f7efde970903784b61','0');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}


function _smarty_tplfunc_eed622a95db213f7efde970903784b61_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eed622a95db213f7efde970903784b61','1');echo $_smarty->_plugins['function']['NeoGallery'][0][0]->function_plugin(array(), $_smarty);
}



?>
