<?php /* Smarty version 2.6.25, created on 2013-03-25 04:26:02
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/201^%%70^707^707A8977%%content%3Acontent_en.inc'] = '86c59ff86c8a6993e13ba85d0cd688fe';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_86c59ff86c8a6993e13ba85d0cd688fe_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('86c59ff86c8a6993e13ba85d0cd688fe','0');echo smarty_cms_function_cms_selflink(array('href' => 'poryadok-priema'), $_smarty);
}


function _smarty_tplfunc_86c59ff86c8a6993e13ba85d0cd688fe_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('86c59ff86c8a6993e13ba85d0cd688fe','1');echo smarty_cms_function_cms_selflink(array('href' => 'elena-georgievna-moll'), $_smarty);
}



?>
