<?php /* Smarty version 2.6.25, created on 2012-06-19 02:52:38
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/203^%%70^707^707A8977%%content%3Acontent_en.inc'] = '08ca274664b5565cffd7397fd8a2f7fa';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_08ca274664b5565cffd7397fd8a2f7fa_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08ca274664b5565cffd7397fd8a2f7fa','0');echo smarty_cms_function_cms_selflink(array('href' => 'ustiyants-anna'), $_smarty);
}


function _smarty_tplfunc_08ca274664b5565cffd7397fd8a2f7fa_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08ca274664b5565cffd7397fd8a2f7fa','1');echo smarty_cms_function_cms_selflink(array('href' => 'lyah-konstantin'), $_smarty);
}



?>
