<?php /* Smarty version 2.6.25, created on 2013-03-07 10:43:21
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/214^%%70^707^707A8977%%content%3Acontent_en.inc'] = '6839df1686425bf347cd7b4c1ea1f2e2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_6839df1686425bf347cd7b4c1ea1f2e2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6839df1686425bf347cd7b4c1ea1f2e2','0');echo smarty_cms_function_cms_module(array('module' => 'Quizzard','quiz_id' => '3'), $_smarty);
}



?>
