<?php /* Smarty version 2.6.25, created on 2012-06-19 02:56:21
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/217^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'cab107efbd581a199ff8d039b6396e35';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_cab107efbd581a199ff8d039b6396e35_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cab107efbd581a199ff8d039b6396e35','0');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_cab107efbd581a199ff8d039b6396e35_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cab107efbd581a199ff8d039b6396e35','1');echo smarty_cms_function_cms_selflink(array('href' => 'dementev-andrej-vladimirovich'), $_smarty);
}



?>
