<?php /* Smarty version 2.6.25, created on 2012-06-19 02:58:14
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/224^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'f7b7b228b82406bebd7ddedebb697313';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_f7b7b228b82406bebd7ddedebb697313_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b7b228b82406bebd7ddedebb697313','0');echo smarty_cms_function_cms_selflink(array('href' => 'kohanaya-viktoriya-anatolevna'), $_smarty);
}


function _smarty_tplfunc_f7b7b228b82406bebd7ddedebb697313_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f7b7b228b82406bebd7ddedebb697313','1');echo smarty_cms_function_cms_selflink(array('href' => 'yakimenko-eleonora'), $_smarty);
}



?>
