<?php /* Smarty version 2.6.25, created on 2013-03-07 15:54:14
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/225^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'faa227dc3801c33ca087b2247332f505';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'startExpandCollapse', 'content:content_en', 36, false),array('function', 'stopExpandCollapse', 'content:content_en', 44, false),)), $this); ?>
<?php
function _smarty_tplfunc_faa227dc3801c33ca087b2247332f505_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faa227dc3801c33ca087b2247332f505','0');echo smarty_cms_function_startExpandCollapse(array('id' => 'expand1','title' => 'Программа'), $_smarty);
}


function _smarty_tplfunc_faa227dc3801c33ca087b2247332f505_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faa227dc3801c33ca087b2247332f505','1');echo smarty_cms_function_stopExpandCollapse(array(), $_smarty);
}



?>
