<?php /* Smarty version 2.6.25, created on 2013-03-07 16:42:34
         compiled from print:91 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/22^%%29^298^2987C248%%print%3A91.inc'] = '2ef67a461a084906c8f5910b04553f40';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:91', 2, false),array('function', 'metadata', 'print:91', 2, false),array('function', 'stylesheet', 'print:91', 2, false),array('function', 'content', 'print:91', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2ef67a461a084906c8f5910b04553f40_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ef67a461a084906c8f5910b04553f40','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2ef67a461a084906c8f5910b04553f40_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ef67a461a084906c8f5910b04553f40','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2ef67a461a084906c8f5910b04553f40_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ef67a461a084906c8f5910b04553f40','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2ef67a461a084906c8f5910b04553f40_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ef67a461a084906c8f5910b04553f40','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
