<?php /* Smarty version 2.6.25, created on 2013-03-14 17:23:45
         compiled from print:71 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/22^%%B7^B70^B704EFC6%%print%3A71.inc'] = '103c9afad1bfee310f30013055a3a913';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:71', 2, false),array('function', 'metadata', 'print:71', 2, false),array('function', 'stylesheet', 'print:71', 2, false),array('function', 'content', 'print:71', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_103c9afad1bfee310f30013055a3a913_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('103c9afad1bfee310f30013055a3a913','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_103c9afad1bfee310f30013055a3a913_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('103c9afad1bfee310f30013055a3a913','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_103c9afad1bfee310f30013055a3a913_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('103c9afad1bfee310f30013055a3a913','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_103c9afad1bfee310f30013055a3a913_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('103c9afad1bfee310f30013055a3a913','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
