<?php /* Smarty version 2.6.25, created on 2013-03-07 15:54:18
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/231^%%70^707^707A8977%%content%3Acontent_en.inc'] = '6123b72dcf55c7fcd84d24bb9f75076a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_6123b72dcf55c7fcd84d24bb9f75076a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6123b72dcf55c7fcd84d24bb9f75076a','0');echo smarty_cms_function_cms_selflink(array('href' => 'anohina-olga'), $_smarty);
}



?>
