<?php /* Smarty version 2.6.25, created on 2013-03-07 15:54:15
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/236^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'fcb5b4cd25c818079393278a96360285';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','0');echo smarty_cms_function_cms_selflink(array('href' => 'poryadok-priema'), $_smarty);
}


function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','1');echo smarty_cms_function_cms_selflink(array('href' => 'dragunyak-natalya'), $_smarty);
}


function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','2');echo smarty_cms_function_cms_selflink(array('href' => 'kreslavskij-evgenij'), $_smarty);
}


function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','3');echo smarty_cms_function_cms_selflink(array('href' => 'pavlov-dmitrij'), $_smarty);
}


function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','4');echo smarty_cms_function_cms_selflink(array('href' => 'fedorov-sergej'), $_smarty);
}


function _smarty_tplfunc_fcb5b4cd25c818079393278a96360285_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fcb5b4cd25c818079393278a96360285','5');echo smarty_cms_function_cms_selflink(array('href' => '06_04_2011'), $_smarty);
}



?>
