<?php /* Smarty version 2.6.25, created on 2013-03-25 08:52:33
         compiled from print:157 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%78^78E^78EE905E%%print%3A157.inc'] = 'ca8283c6ac185bede6b6ae9503f49c4b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:157', 2, false),array('function', 'metadata', 'print:157', 2, false),array('function', 'stylesheet', 'print:157', 2, false),array('function', 'content', 'print:157', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca8283c6ac185bede6b6ae9503f49c4b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca8283c6ac185bede6b6ae9503f49c4b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ca8283c6ac185bede6b6ae9503f49c4b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca8283c6ac185bede6b6ae9503f49c4b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ca8283c6ac185bede6b6ae9503f49c4b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca8283c6ac185bede6b6ae9503f49c4b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ca8283c6ac185bede6b6ae9503f49c4b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca8283c6ac185bede6b6ae9503f49c4b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
