<?php /* Smarty version 2.6.25, created on 2013-03-22 01:41:54
         compiled from print:65 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A9^A97^A9721A9E%%print%3A65.inc'] = '56ede2a7ba7466ff1932eabcace3fae1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:65', 2, false),array('function', 'metadata', 'print:65', 2, false),array('function', 'stylesheet', 'print:65', 2, false),array('function', 'content', 'print:65', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_56ede2a7ba7466ff1932eabcace3fae1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('56ede2a7ba7466ff1932eabcace3fae1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_56ede2a7ba7466ff1932eabcace3fae1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('56ede2a7ba7466ff1932eabcace3fae1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_56ede2a7ba7466ff1932eabcace3fae1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('56ede2a7ba7466ff1932eabcace3fae1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_56ede2a7ba7466ff1932eabcace3fae1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('56ede2a7ba7466ff1932eabcace3fae1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
