<?php /* Smarty version 2.6.25, created on 2013-03-21 07:13:01
         compiled from print:193 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D3^D33^D3361B4B%%print%3A193.inc'] = 'c7edff6ff6eda08efc74ff627a9b5e0c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:193', 2, false),array('function', 'metadata', 'print:193', 2, false),array('function', 'stylesheet', 'print:193', 2, false),array('function', 'content', 'print:193', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c7edff6ff6eda08efc74ff627a9b5e0c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c7edff6ff6eda08efc74ff627a9b5e0c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c7edff6ff6eda08efc74ff627a9b5e0c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c7edff6ff6eda08efc74ff627a9b5e0c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c7edff6ff6eda08efc74ff627a9b5e0c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c7edff6ff6eda08efc74ff627a9b5e0c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c7edff6ff6eda08efc74ff627a9b5e0c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c7edff6ff6eda08efc74ff627a9b5e0c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
