<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:47
         compiled from print:98 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%50^505^505B7AEC%%print%3A98.inc'] = '125a5b34287c5e111aa834090366dff7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:98', 2, false),array('function', 'metadata', 'print:98', 2, false),array('function', 'stylesheet', 'print:98', 2, false),array('function', 'content', 'print:98', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_125a5b34287c5e111aa834090366dff7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('125a5b34287c5e111aa834090366dff7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_125a5b34287c5e111aa834090366dff7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('125a5b34287c5e111aa834090366dff7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_125a5b34287c5e111aa834090366dff7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('125a5b34287c5e111aa834090366dff7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_125a5b34287c5e111aa834090366dff7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('125a5b34287c5e111aa834090366dff7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
