<?php /* Smarty version 2.6.25, created on 2013-03-25 07:01:40
         compiled from print:137 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2E^2EB^2EB437D8%%print%3A137.inc'] = '4352e8e6088857429c1b9efeefcb243b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:137', 2, false),array('function', 'metadata', 'print:137', 2, false),array('function', 'stylesheet', 'print:137', 2, false),array('function', 'content', 'print:137', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4352e8e6088857429c1b9efeefcb243b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4352e8e6088857429c1b9efeefcb243b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4352e8e6088857429c1b9efeefcb243b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4352e8e6088857429c1b9efeefcb243b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4352e8e6088857429c1b9efeefcb243b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4352e8e6088857429c1b9efeefcb243b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4352e8e6088857429c1b9efeefcb243b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4352e8e6088857429c1b9efeefcb243b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
