<?php /* Smarty version 2.6.25, created on 2013-03-23 08:01:03
         compiled from print:166 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%24^24C^24C4F30B%%print%3A166.inc'] = 'ba7e92a91be1943b73252abf49e0e88c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:166', 2, false),array('function', 'metadata', 'print:166', 2, false),array('function', 'stylesheet', 'print:166', 2, false),array('function', 'content', 'print:166', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ba7e92a91be1943b73252abf49e0e88c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ba7e92a91be1943b73252abf49e0e88c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ba7e92a91be1943b73252abf49e0e88c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ba7e92a91be1943b73252abf49e0e88c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ba7e92a91be1943b73252abf49e0e88c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ba7e92a91be1943b73252abf49e0e88c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ba7e92a91be1943b73252abf49e0e88c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ba7e92a91be1943b73252abf49e0e88c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
