<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:41
         compiled from print:74 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C7^C76^C76E1B49%%print%3A74.inc'] = '8dce9456e14839cd1d0ea602340f614a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:74', 2, false),array('function', 'metadata', 'print:74', 2, false),array('function', 'stylesheet', 'print:74', 2, false),array('function', 'content', 'print:74', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8dce9456e14839cd1d0ea602340f614a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dce9456e14839cd1d0ea602340f614a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8dce9456e14839cd1d0ea602340f614a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dce9456e14839cd1d0ea602340f614a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8dce9456e14839cd1d0ea602340f614a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dce9456e14839cd1d0ea602340f614a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8dce9456e14839cd1d0ea602340f614a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dce9456e14839cd1d0ea602340f614a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
