<?php /* Smarty version 2.6.25, created on 2013-03-24 23:11:51
         compiled from print:268 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C1^C13^C13A6055%%print%3A268.inc'] = 'a7fb27ef4cd0f56a16382cb5fd2cd5b8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:268', 2, false),array('function', 'metadata', 'print:268', 2, false),array('function', 'stylesheet', 'print:268', 2, false),array('function', 'content', 'print:268', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a7fb27ef4cd0f56a16382cb5fd2cd5b8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a7fb27ef4cd0f56a16382cb5fd2cd5b8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a7fb27ef4cd0f56a16382cb5fd2cd5b8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a7fb27ef4cd0f56a16382cb5fd2cd5b8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a7fb27ef4cd0f56a16382cb5fd2cd5b8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a7fb27ef4cd0f56a16382cb5fd2cd5b8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a7fb27ef4cd0f56a16382cb5fd2cd5b8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a7fb27ef4cd0f56a16382cb5fd2cd5b8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
