<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:48
         compiled from print:106 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%72^729^729E548D%%print%3A106.inc'] = '628ad5f81d77f314607afddefedd91df';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:106', 2, false),array('function', 'metadata', 'print:106', 2, false),array('function', 'stylesheet', 'print:106', 2, false),array('function', 'content', 'print:106', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_628ad5f81d77f314607afddefedd91df_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('628ad5f81d77f314607afddefedd91df','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_628ad5f81d77f314607afddefedd91df_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('628ad5f81d77f314607afddefedd91df','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_628ad5f81d77f314607afddefedd91df_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('628ad5f81d77f314607afddefedd91df','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_628ad5f81d77f314607afddefedd91df_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('628ad5f81d77f314607afddefedd91df','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
