<?php /* Smarty version 2.6.25, created on 2013-03-24 19:11:56
         compiled from print:267 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%51^518^51857DC4%%print%3A267.inc'] = '52a92b425e22aa50613272b852e0bd65';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:267', 2, false),array('function', 'metadata', 'print:267', 2, false),array('function', 'stylesheet', 'print:267', 2, false),array('function', 'content', 'print:267', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_52a92b425e22aa50613272b852e0bd65_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('52a92b425e22aa50613272b852e0bd65','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_52a92b425e22aa50613272b852e0bd65_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('52a92b425e22aa50613272b852e0bd65','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_52a92b425e22aa50613272b852e0bd65_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('52a92b425e22aa50613272b852e0bd65','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_52a92b425e22aa50613272b852e0bd65_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('52a92b425e22aa50613272b852e0bd65','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
