<?php /* Smarty version 2.6.25, created on 2013-03-23 13:39:01
         compiled from print:235 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C2^C2F^C2FCE8AD%%print%3A235.inc'] = 'bc3a036632594cf291f100cc11c662ab';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:235', 2, false),array('function', 'metadata', 'print:235', 2, false),array('function', 'stylesheet', 'print:235', 2, false),array('function', 'content', 'print:235', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bc3a036632594cf291f100cc11c662ab_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc3a036632594cf291f100cc11c662ab','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bc3a036632594cf291f100cc11c662ab_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc3a036632594cf291f100cc11c662ab','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bc3a036632594cf291f100cc11c662ab_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc3a036632594cf291f100cc11c662ab','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bc3a036632594cf291f100cc11c662ab_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc3a036632594cf291f100cc11c662ab','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
