<?php /* Smarty version 2.6.25, created on 2013-03-25 06:08:50
         compiled from print:265 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BF^BF8^BF8B1CE8%%print%3A265.inc'] = 'edfc72a7a18cf7d9630e996b6383f2f7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:265', 2, false),array('function', 'metadata', 'print:265', 2, false),array('function', 'stylesheet', 'print:265', 2, false),array('function', 'content', 'print:265', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_edfc72a7a18cf7d9630e996b6383f2f7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edfc72a7a18cf7d9630e996b6383f2f7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_edfc72a7a18cf7d9630e996b6383f2f7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edfc72a7a18cf7d9630e996b6383f2f7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_edfc72a7a18cf7d9630e996b6383f2f7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edfc72a7a18cf7d9630e996b6383f2f7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_edfc72a7a18cf7d9630e996b6383f2f7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('edfc72a7a18cf7d9630e996b6383f2f7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
