<?php /* Smarty version 2.6.25, created on 2013-03-22 10:17:42
         compiled from print:324 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AD^AD2^AD22834D%%print%3A324.inc'] = '673bf79d0eeccacf61bb32d1691b0218';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:324', 2, false),array('function', 'metadata', 'print:324', 2, false),array('function', 'stylesheet', 'print:324', 2, false),array('function', 'content', 'print:324', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_673bf79d0eeccacf61bb32d1691b0218_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('673bf79d0eeccacf61bb32d1691b0218','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_673bf79d0eeccacf61bb32d1691b0218_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('673bf79d0eeccacf61bb32d1691b0218','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_673bf79d0eeccacf61bb32d1691b0218_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('673bf79d0eeccacf61bb32d1691b0218','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_673bf79d0eeccacf61bb32d1691b0218_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('673bf79d0eeccacf61bb32d1691b0218','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
