<?php /* Smarty version 2.6.25, created on 2013-03-21 15:51:34
         compiled from print:144 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F8^F8F^F8FCF0A5%%print%3A144.inc'] = 'b0e34cb6d9b10948eda55d35dec71eff';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:144', 2, false),array('function', 'metadata', 'print:144', 2, false),array('function', 'stylesheet', 'print:144', 2, false),array('function', 'content', 'print:144', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0e34cb6d9b10948eda55d35dec71eff_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0e34cb6d9b10948eda55d35dec71eff','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0e34cb6d9b10948eda55d35dec71eff_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0e34cb6d9b10948eda55d35dec71eff','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0e34cb6d9b10948eda55d35dec71eff_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0e34cb6d9b10948eda55d35dec71eff','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0e34cb6d9b10948eda55d35dec71eff_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0e34cb6d9b10948eda55d35dec71eff','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
