<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:54
         compiled from print:123 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%30^30C^30C2C280%%print%3A123.inc'] = 'e27b692e66b5f89d4dfbacf0f2356866';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:123', 2, false),array('function', 'metadata', 'print:123', 2, false),array('function', 'stylesheet', 'print:123', 2, false),array('function', 'content', 'print:123', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e27b692e66b5f89d4dfbacf0f2356866_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e27b692e66b5f89d4dfbacf0f2356866','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e27b692e66b5f89d4dfbacf0f2356866_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e27b692e66b5f89d4dfbacf0f2356866','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e27b692e66b5f89d4dfbacf0f2356866_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e27b692e66b5f89d4dfbacf0f2356866','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e27b692e66b5f89d4dfbacf0f2356866_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e27b692e66b5f89d4dfbacf0f2356866','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
