<?php /* Smarty version 2.6.25, created on 2013-03-25 05:01:43
         compiled from print:116 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%6B^6B8^6B8565CC%%print%3A116.inc'] = '1361d7a1d9ea0ea33b900bf8705068ef';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:116', 2, false),array('function', 'metadata', 'print:116', 2, false),array('function', 'stylesheet', 'print:116', 2, false),array('function', 'content', 'print:116', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1361d7a1d9ea0ea33b900bf8705068ef_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1361d7a1d9ea0ea33b900bf8705068ef','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1361d7a1d9ea0ea33b900bf8705068ef_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1361d7a1d9ea0ea33b900bf8705068ef','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1361d7a1d9ea0ea33b900bf8705068ef_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1361d7a1d9ea0ea33b900bf8705068ef','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1361d7a1d9ea0ea33b900bf8705068ef_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1361d7a1d9ea0ea33b900bf8705068ef','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
