<?php /* Smarty version 2.6.25, created on 2013-03-24 21:32:54
         compiled from print:76 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%29^296^29607A65%%print%3A76.inc'] = 'eb1b811733695cc073d8586d4745a702';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:76', 2, false),array('function', 'metadata', 'print:76', 2, false),array('function', 'stylesheet', 'print:76', 2, false),array('function', 'content', 'print:76', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_eb1b811733695cc073d8586d4745a702_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb1b811733695cc073d8586d4745a702','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_eb1b811733695cc073d8586d4745a702_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb1b811733695cc073d8586d4745a702','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_eb1b811733695cc073d8586d4745a702_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb1b811733695cc073d8586d4745a702','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_eb1b811733695cc073d8586d4745a702_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eb1b811733695cc073d8586d4745a702','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
