<?php /* Smarty version 2.6.25, created on 2013-03-22 07:23:59
         compiled from print:125 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D9^D9A^D9A167B5%%print%3A125.inc'] = '04bdc18e4d7458e5eff296224be139e2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:125', 2, false),array('function', 'metadata', 'print:125', 2, false),array('function', 'stylesheet', 'print:125', 2, false),array('function', 'content', 'print:125', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_04bdc18e4d7458e5eff296224be139e2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bdc18e4d7458e5eff296224be139e2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_04bdc18e4d7458e5eff296224be139e2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bdc18e4d7458e5eff296224be139e2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_04bdc18e4d7458e5eff296224be139e2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bdc18e4d7458e5eff296224be139e2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_04bdc18e4d7458e5eff296224be139e2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bdc18e4d7458e5eff296224be139e2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
