<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:42
         compiled from print:151 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%91^918^918D356B%%print%3A151.inc'] = 'bf291faad73a28a538dd77f9d27a4df2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:151', 2, false),array('function', 'metadata', 'print:151', 2, false),array('function', 'stylesheet', 'print:151', 2, false),array('function', 'content', 'print:151', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bf291faad73a28a538dd77f9d27a4df2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf291faad73a28a538dd77f9d27a4df2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bf291faad73a28a538dd77f9d27a4df2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf291faad73a28a538dd77f9d27a4df2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bf291faad73a28a538dd77f9d27a4df2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf291faad73a28a538dd77f9d27a4df2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bf291faad73a28a538dd77f9d27a4df2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf291faad73a28a538dd77f9d27a4df2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
