<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:32
         compiled from print:257 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%7A^7AA^7AA82E07%%print%3A257.inc'] = 'c09af6d968c9706b4c8ed3267e51a465';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:257', 2, false),array('function', 'metadata', 'print:257', 2, false),array('function', 'stylesheet', 'print:257', 2, false),array('function', 'content', 'print:257', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c09af6d968c9706b4c8ed3267e51a465_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c09af6d968c9706b4c8ed3267e51a465','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c09af6d968c9706b4c8ed3267e51a465_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c09af6d968c9706b4c8ed3267e51a465','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c09af6d968c9706b4c8ed3267e51a465_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c09af6d968c9706b4c8ed3267e51a465','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c09af6d968c9706b4c8ed3267e51a465_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c09af6d968c9706b4c8ed3267e51a465','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
