<?php /* Smarty version 2.6.25, created on 2013-03-25 04:13:49
         compiled from print:107 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%05^059^0599641B%%print%3A107.inc'] = '2e951cb07ffaa2c5f0904eb18542c467';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:107', 2, false),array('function', 'metadata', 'print:107', 2, false),array('function', 'stylesheet', 'print:107', 2, false),array('function', 'content', 'print:107', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2e951cb07ffaa2c5f0904eb18542c467_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e951cb07ffaa2c5f0904eb18542c467','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2e951cb07ffaa2c5f0904eb18542c467_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e951cb07ffaa2c5f0904eb18542c467','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2e951cb07ffaa2c5f0904eb18542c467_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e951cb07ffaa2c5f0904eb18542c467','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2e951cb07ffaa2c5f0904eb18542c467_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e951cb07ffaa2c5f0904eb18542c467','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
