<?php /* Smarty version 2.6.25, created on 2013-03-23 01:37:41
         compiled from print:191 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%3D^3D3^3D387A67%%print%3A191.inc'] = '2554eb172700b9128abe0ac7cfdacd9b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:191', 2, false),array('function', 'metadata', 'print:191', 2, false),array('function', 'stylesheet', 'print:191', 2, false),array('function', 'content', 'print:191', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2554eb172700b9128abe0ac7cfdacd9b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2554eb172700b9128abe0ac7cfdacd9b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2554eb172700b9128abe0ac7cfdacd9b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2554eb172700b9128abe0ac7cfdacd9b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2554eb172700b9128abe0ac7cfdacd9b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2554eb172700b9128abe0ac7cfdacd9b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2554eb172700b9128abe0ac7cfdacd9b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2554eb172700b9128abe0ac7cfdacd9b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
