<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:46
         compiled from print:95 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2E^2EE^2EEA0651%%print%3A95.inc'] = '80137b80b3826ca7dab495380fd232c3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:95', 2, false),array('function', 'metadata', 'print:95', 2, false),array('function', 'stylesheet', 'print:95', 2, false),array('function', 'content', 'print:95', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_80137b80b3826ca7dab495380fd232c3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('80137b80b3826ca7dab495380fd232c3','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_80137b80b3826ca7dab495380fd232c3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('80137b80b3826ca7dab495380fd232c3','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_80137b80b3826ca7dab495380fd232c3_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('80137b80b3826ca7dab495380fd232c3','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_80137b80b3826ca7dab495380fd232c3_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('80137b80b3826ca7dab495380fd232c3','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
