<?php /* Smarty version 2.6.25, created on 2013-03-24 21:42:49
         compiled from print:188 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5D^5DF^5DFFF382%%print%3A188.inc'] = '6ca655f7bf7c06d90ecb3e3062ddfb35';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:188', 2, false),array('function', 'metadata', 'print:188', 2, false),array('function', 'stylesheet', 'print:188', 2, false),array('function', 'content', 'print:188', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6ca655f7bf7c06d90ecb3e3062ddfb35_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6ca655f7bf7c06d90ecb3e3062ddfb35','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6ca655f7bf7c06d90ecb3e3062ddfb35_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6ca655f7bf7c06d90ecb3e3062ddfb35','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6ca655f7bf7c06d90ecb3e3062ddfb35_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6ca655f7bf7c06d90ecb3e3062ddfb35','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6ca655f7bf7c06d90ecb3e3062ddfb35_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6ca655f7bf7c06d90ecb3e3062ddfb35','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
