<?php /* Smarty version 2.6.25, created on 2013-03-24 09:10:33
         compiled from print:329 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D3^D39^D393FFF0%%print%3A329.inc'] = 'bc75c03980f987c68677359c42497816';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:329', 2, false),array('function', 'metadata', 'print:329', 2, false),array('function', 'stylesheet', 'print:329', 2, false),array('function', 'content', 'print:329', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bc75c03980f987c68677359c42497816_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc75c03980f987c68677359c42497816','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bc75c03980f987c68677359c42497816_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc75c03980f987c68677359c42497816','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bc75c03980f987c68677359c42497816_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc75c03980f987c68677359c42497816','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bc75c03980f987c68677359c42497816_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bc75c03980f987c68677359c42497816','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
