<?php /* Smarty version 2.6.25, created on 2013-03-22 07:09:48
         compiled from print:100 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%9B^9BF^9BFDF1B8%%print%3A100.inc'] = 'ad448926aaa6253c5bc93fe02b0942e4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:100', 2, false),array('function', 'metadata', 'print:100', 2, false),array('function', 'stylesheet', 'print:100', 2, false),array('function', 'content', 'print:100', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ad448926aaa6253c5bc93fe02b0942e4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad448926aaa6253c5bc93fe02b0942e4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ad448926aaa6253c5bc93fe02b0942e4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad448926aaa6253c5bc93fe02b0942e4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ad448926aaa6253c5bc93fe02b0942e4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad448926aaa6253c5bc93fe02b0942e4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ad448926aaa6253c5bc93fe02b0942e4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad448926aaa6253c5bc93fe02b0942e4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
