<?php /* Smarty version 2.6.25, created on 2013-03-22 10:10:18
         compiled from print:105 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%EB^EB9^EB970537%%print%3A105.inc'] = 'e06d1574325811fe157e53599416dc90';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:105', 2, false),array('function', 'metadata', 'print:105', 2, false),array('function', 'stylesheet', 'print:105', 2, false),array('function', 'content', 'print:105', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e06d1574325811fe157e53599416dc90_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e06d1574325811fe157e53599416dc90','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e06d1574325811fe157e53599416dc90_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e06d1574325811fe157e53599416dc90','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e06d1574325811fe157e53599416dc90_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e06d1574325811fe157e53599416dc90','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e06d1574325811fe157e53599416dc90_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e06d1574325811fe157e53599416dc90','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
