<?php /* Smarty version 2.6.25, created on 2013-03-22 17:55:40
         compiled from print:90 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5E^5E8^5E80F2DE%%print%3A90.inc'] = 'ff8bdc1c10f58cd0aae048efad3a907e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:90', 2, false),array('function', 'metadata', 'print:90', 2, false),array('function', 'stylesheet', 'print:90', 2, false),array('function', 'content', 'print:90', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff8bdc1c10f58cd0aae048efad3a907e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff8bdc1c10f58cd0aae048efad3a907e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ff8bdc1c10f58cd0aae048efad3a907e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff8bdc1c10f58cd0aae048efad3a907e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ff8bdc1c10f58cd0aae048efad3a907e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff8bdc1c10f58cd0aae048efad3a907e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ff8bdc1c10f58cd0aae048efad3a907e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff8bdc1c10f58cd0aae048efad3a907e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
