<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:44
         compiled from print:141 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%88^889^8896042A%%print%3A141.inc'] = 'd49fe535befda0779f5f8fc69e1cbc84';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:141', 2, false),array('function', 'metadata', 'print:141', 2, false),array('function', 'stylesheet', 'print:141', 2, false),array('function', 'content', 'print:141', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d49fe535befda0779f5f8fc69e1cbc84_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d49fe535befda0779f5f8fc69e1cbc84','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d49fe535befda0779f5f8fc69e1cbc84_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d49fe535befda0779f5f8fc69e1cbc84','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d49fe535befda0779f5f8fc69e1cbc84_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d49fe535befda0779f5f8fc69e1cbc84','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d49fe535befda0779f5f8fc69e1cbc84_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d49fe535befda0779f5f8fc69e1cbc84','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
