<?php /* Smarty version 2.6.25, created on 2013-03-22 16:26:02
         compiled from print:255 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%94^94A^94A64F2B%%print%3A255.inc'] = 'aaf4ff61c972825236b333d59e33c9cb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:255', 2, false),array('function', 'metadata', 'print:255', 2, false),array('function', 'stylesheet', 'print:255', 2, false),array('function', 'content', 'print:255', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aaf4ff61c972825236b333d59e33c9cb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aaf4ff61c972825236b333d59e33c9cb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_aaf4ff61c972825236b333d59e33c9cb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aaf4ff61c972825236b333d59e33c9cb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_aaf4ff61c972825236b333d59e33c9cb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aaf4ff61c972825236b333d59e33c9cb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_aaf4ff61c972825236b333d59e33c9cb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aaf4ff61c972825236b333d59e33c9cb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
