<?php /* Smarty version 2.6.25, created on 2013-03-25 12:40:52
         compiled from print:167 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%53^53C^53C3C39D%%print%3A167.inc'] = '585eac472832bc7f7a75e15ef15a5fc4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:167', 2, false),array('function', 'metadata', 'print:167', 2, false),array('function', 'stylesheet', 'print:167', 2, false),array('function', 'content', 'print:167', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_585eac472832bc7f7a75e15ef15a5fc4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('585eac472832bc7f7a75e15ef15a5fc4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_585eac472832bc7f7a75e15ef15a5fc4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('585eac472832bc7f7a75e15ef15a5fc4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_585eac472832bc7f7a75e15ef15a5fc4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('585eac472832bc7f7a75e15ef15a5fc4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_585eac472832bc7f7a75e15ef15a5fc4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('585eac472832bc7f7a75e15ef15a5fc4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
