<?php /* Smarty version 2.6.25, created on 2013-03-24 19:17:15
         compiled from print:133 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%29^29D^29D9F3C1%%print%3A133.inc'] = '9abb02a6c9ffcef6a9204be7b1266058';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:133', 2, false),array('function', 'metadata', 'print:133', 2, false),array('function', 'stylesheet', 'print:133', 2, false),array('function', 'content', 'print:133', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9abb02a6c9ffcef6a9204be7b1266058_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9abb02a6c9ffcef6a9204be7b1266058','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9abb02a6c9ffcef6a9204be7b1266058_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9abb02a6c9ffcef6a9204be7b1266058','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9abb02a6c9ffcef6a9204be7b1266058_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9abb02a6c9ffcef6a9204be7b1266058','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9abb02a6c9ffcef6a9204be7b1266058_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9abb02a6c9ffcef6a9204be7b1266058','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
