<?php /* Smarty version 2.6.25, created on 2013-03-24 09:39:30
         compiled from print:145 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%8F^8FF^8FFBC033%%print%3A145.inc'] = 'aea0ebcc1a204f803a56af7cf560d92e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:145', 2, false),array('function', 'metadata', 'print:145', 2, false),array('function', 'stylesheet', 'print:145', 2, false),array('function', 'content', 'print:145', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aea0ebcc1a204f803a56af7cf560d92e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aea0ebcc1a204f803a56af7cf560d92e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_aea0ebcc1a204f803a56af7cf560d92e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aea0ebcc1a204f803a56af7cf560d92e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_aea0ebcc1a204f803a56af7cf560d92e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aea0ebcc1a204f803a56af7cf560d92e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_aea0ebcc1a204f803a56af7cf560d92e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aea0ebcc1a204f803a56af7cf560d92e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
