<?php /* Smarty version 2.6.25, created on 2013-03-25 02:02:53
         compiled from print:250 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%E4^E4C^E4CCBBA4%%print%3A250.inc'] = '5b46f7fd0cf48058e250aea53a187e23';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:250', 2, false),array('function', 'metadata', 'print:250', 2, false),array('function', 'stylesheet', 'print:250', 2, false),array('function', 'content', 'print:250', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5b46f7fd0cf48058e250aea53a187e23_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b46f7fd0cf48058e250aea53a187e23','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5b46f7fd0cf48058e250aea53a187e23_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b46f7fd0cf48058e250aea53a187e23','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5b46f7fd0cf48058e250aea53a187e23_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b46f7fd0cf48058e250aea53a187e23','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5b46f7fd0cf48058e250aea53a187e23_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b46f7fd0cf48058e250aea53a187e23','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
