<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:27
         compiled from print:207 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%07^07D^07DFDA42%%print%3A207.inc'] = 'de1ce2a85548897bff87a64be1b0a8d0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:207', 2, false),array('function', 'metadata', 'print:207', 2, false),array('function', 'stylesheet', 'print:207', 2, false),array('function', 'content', 'print:207', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_de1ce2a85548897bff87a64be1b0a8d0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de1ce2a85548897bff87a64be1b0a8d0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_de1ce2a85548897bff87a64be1b0a8d0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de1ce2a85548897bff87a64be1b0a8d0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_de1ce2a85548897bff87a64be1b0a8d0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de1ce2a85548897bff87a64be1b0a8d0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_de1ce2a85548897bff87a64be1b0a8d0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de1ce2a85548897bff87a64be1b0a8d0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
