<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:13
         compiled from print:182 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BD^BD2^BD2A1A9C%%print%3A182.inc'] = '37bf0690b4ad48bad6f24da0b8e79be5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:182', 2, false),array('function', 'metadata', 'print:182', 2, false),array('function', 'stylesheet', 'print:182', 2, false),array('function', 'content', 'print:182', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_37bf0690b4ad48bad6f24da0b8e79be5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37bf0690b4ad48bad6f24da0b8e79be5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_37bf0690b4ad48bad6f24da0b8e79be5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37bf0690b4ad48bad6f24da0b8e79be5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_37bf0690b4ad48bad6f24da0b8e79be5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37bf0690b4ad48bad6f24da0b8e79be5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_37bf0690b4ad48bad6f24da0b8e79be5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37bf0690b4ad48bad6f24da0b8e79be5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
