<?php /* Smarty version 2.6.25, created on 2013-03-25 09:43:45
         compiled from print:314 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%86^860^860FD08E%%print%3A314.inc'] = '8e287c45cdf957c97be4caa3dd5c436c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:314', 2, false),array('function', 'metadata', 'print:314', 2, false),array('function', 'stylesheet', 'print:314', 2, false),array('function', 'content', 'print:314', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8e287c45cdf957c97be4caa3dd5c436c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e287c45cdf957c97be4caa3dd5c436c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8e287c45cdf957c97be4caa3dd5c436c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e287c45cdf957c97be4caa3dd5c436c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8e287c45cdf957c97be4caa3dd5c436c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e287c45cdf957c97be4caa3dd5c436c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8e287c45cdf957c97be4caa3dd5c436c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e287c45cdf957c97be4caa3dd5c436c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
