<?php /* Smarty version 2.6.25, created on 2013-03-23 13:32:23
         compiled from print:295 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%38^381^38130027%%print%3A295.inc'] = '467727e76348792bcef6a13a6b150264';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:295', 2, false),array('function', 'metadata', 'print:295', 2, false),array('function', 'stylesheet', 'print:295', 2, false),array('function', 'content', 'print:295', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_467727e76348792bcef6a13a6b150264_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('467727e76348792bcef6a13a6b150264','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_467727e76348792bcef6a13a6b150264_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('467727e76348792bcef6a13a6b150264','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_467727e76348792bcef6a13a6b150264_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('467727e76348792bcef6a13a6b150264','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_467727e76348792bcef6a13a6b150264_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('467727e76348792bcef6a13a6b150264','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
