<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:43
         compiled from print:148 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F1^F14^F14ABC8E%%print%3A148.inc'] = '62620c84db4ba5c92126aeaa2766c432';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:148', 2, false),array('function', 'metadata', 'print:148', 2, false),array('function', 'stylesheet', 'print:148', 2, false),array('function', 'content', 'print:148', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_62620c84db4ba5c92126aeaa2766c432_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62620c84db4ba5c92126aeaa2766c432','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_62620c84db4ba5c92126aeaa2766c432_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62620c84db4ba5c92126aeaa2766c432','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_62620c84db4ba5c92126aeaa2766c432_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62620c84db4ba5c92126aeaa2766c432','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_62620c84db4ba5c92126aeaa2766c432_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62620c84db4ba5c92126aeaa2766c432','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
