<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:41
         compiled from print:163 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%54^54A^54AE0784%%print%3A163.inc'] = 'd5ff8b8e0a1bdabc5f965d9fd1973858';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:163', 2, false),array('function', 'metadata', 'print:163', 2, false),array('function', 'stylesheet', 'print:163', 2, false),array('function', 'content', 'print:163', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d5ff8b8e0a1bdabc5f965d9fd1973858_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d5ff8b8e0a1bdabc5f965d9fd1973858','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d5ff8b8e0a1bdabc5f965d9fd1973858_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d5ff8b8e0a1bdabc5f965d9fd1973858','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d5ff8b8e0a1bdabc5f965d9fd1973858_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d5ff8b8e0a1bdabc5f965d9fd1973858','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d5ff8b8e0a1bdabc5f965d9fd1973858_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d5ff8b8e0a1bdabc5f965d9fd1973858','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
