<?php /* Smarty version 2.6.25, created on 2013-03-24 23:11:49
         compiled from print:266 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%26^268^26824D52%%print%3A266.inc'] = '478257eb9257add3684804a69d5fc6f9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:266', 2, false),array('function', 'metadata', 'print:266', 2, false),array('function', 'stylesheet', 'print:266', 2, false),array('function', 'content', 'print:266', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_478257eb9257add3684804a69d5fc6f9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('478257eb9257add3684804a69d5fc6f9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_478257eb9257add3684804a69d5fc6f9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('478257eb9257add3684804a69d5fc6f9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_478257eb9257add3684804a69d5fc6f9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('478257eb9257add3684804a69d5fc6f9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_478257eb9257add3684804a69d5fc6f9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('478257eb9257add3684804a69d5fc6f9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
