<?php /* Smarty version 2.6.25, created on 2013-03-20 04:37:53
         compiled from print:214 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%87^87C^87CDBAB9%%print%3A214.inc'] = 'b98baeaa1c33f5f0d123847f5b125771';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:214', 2, false),array('function', 'metadata', 'print:214', 2, false),array('function', 'stylesheet', 'print:214', 2, false),array('function', 'content', 'print:214', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b98baeaa1c33f5f0d123847f5b125771_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b98baeaa1c33f5f0d123847f5b125771','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b98baeaa1c33f5f0d123847f5b125771_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b98baeaa1c33f5f0d123847f5b125771','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b98baeaa1c33f5f0d123847f5b125771_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b98baeaa1c33f5f0d123847f5b125771','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b98baeaa1c33f5f0d123847f5b125771_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b98baeaa1c33f5f0d123847f5b125771','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
