<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:41
         compiled from print:337 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2D^2D3^2D30E3B6%%print%3A337.inc'] = '2c0ed198b83f11e112631fd878122dee';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:337', 2, false),array('function', 'metadata', 'print:337', 2, false),array('function', 'stylesheet', 'print:337', 2, false),array('function', 'content', 'print:337', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2c0ed198b83f11e112631fd878122dee_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2c0ed198b83f11e112631fd878122dee','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2c0ed198b83f11e112631fd878122dee_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2c0ed198b83f11e112631fd878122dee','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2c0ed198b83f11e112631fd878122dee_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2c0ed198b83f11e112631fd878122dee','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2c0ed198b83f11e112631fd878122dee_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2c0ed198b83f11e112631fd878122dee','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
