<?php /* Smarty version 2.6.25, created on 2013-03-21 21:41:00
         compiled from print:124 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AE^AEA^AEA65723%%print%3A124.inc'] = '6b06c64fe3c517a4fb1443f592d6b4ca';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:124', 2, false),array('function', 'metadata', 'print:124', 2, false),array('function', 'stylesheet', 'print:124', 2, false),array('function', 'content', 'print:124', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6b06c64fe3c517a4fb1443f592d6b4ca_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b06c64fe3c517a4fb1443f592d6b4ca','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6b06c64fe3c517a4fb1443f592d6b4ca_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b06c64fe3c517a4fb1443f592d6b4ca','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6b06c64fe3c517a4fb1443f592d6b4ca_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b06c64fe3c517a4fb1443f592d6b4ca','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6b06c64fe3c517a4fb1443f592d6b4ca_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b06c64fe3c517a4fb1443f592d6b4ca','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
