<?php /* Smarty version 2.6.25, created on 2013-03-25 06:38:40
         compiled from print:204 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%9E^9ED^9ED68BF8%%print%3A204.inc'] = '9063a89fab052184c1c96f6c984e31d4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:204', 2, false),array('function', 'metadata', 'print:204', 2, false),array('function', 'stylesheet', 'print:204', 2, false),array('function', 'content', 'print:204', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9063a89fab052184c1c96f6c984e31d4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9063a89fab052184c1c96f6c984e31d4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9063a89fab052184c1c96f6c984e31d4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9063a89fab052184c1c96f6c984e31d4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9063a89fab052184c1c96f6c984e31d4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9063a89fab052184c1c96f6c984e31d4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9063a89fab052184c1c96f6c984e31d4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9063a89fab052184c1c96f6c984e31d4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
