<?php /* Smarty version 2.6.25, created on 2013-03-25 11:59:53
         compiled from print:338 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BD^BD8^BD8FFE27%%print%3A338.inc'] = '30358369651e2e7f4ccb23c004f08e8a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:338', 2, false),array('function', 'metadata', 'print:338', 2, false),array('function', 'stylesheet', 'print:338', 2, false),array('function', 'content', 'print:338', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_30358369651e2e7f4ccb23c004f08e8a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30358369651e2e7f4ccb23c004f08e8a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_30358369651e2e7f4ccb23c004f08e8a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30358369651e2e7f4ccb23c004f08e8a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_30358369651e2e7f4ccb23c004f08e8a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30358369651e2e7f4ccb23c004f08e8a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_30358369651e2e7f4ccb23c004f08e8a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30358369651e2e7f4ccb23c004f08e8a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
