<?php /* Smarty version 2.6.25, created on 2013-03-23 18:47:22
         compiled from print:346 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%15^157^157645E7%%print%3A346.inc'] = '32700e2618f32245c8e46b7f7d8ebe86';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:346', 2, false),array('function', 'metadata', 'print:346', 2, false),array('function', 'stylesheet', 'print:346', 2, false),array('function', 'content', 'print:346', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_32700e2618f32245c8e46b7f7d8ebe86_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32700e2618f32245c8e46b7f7d8ebe86','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_32700e2618f32245c8e46b7f7d8ebe86_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32700e2618f32245c8e46b7f7d8ebe86','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_32700e2618f32245c8e46b7f7d8ebe86_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32700e2618f32245c8e46b7f7d8ebe86','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_32700e2618f32245c8e46b7f7d8ebe86_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32700e2618f32245c8e46b7f7d8ebe86','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
