<?php /* Smarty version 2.6.25, created on 2013-03-25 07:43:14
         compiled from print:216 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%69^69C^69C3DB95%%print%3A216.inc'] = 'f2286f4991bd5e59e2e9d8d66f8c59ca';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:216', 2, false),array('function', 'metadata', 'print:216', 2, false),array('function', 'stylesheet', 'print:216', 2, false),array('function', 'content', 'print:216', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f2286f4991bd5e59e2e9d8d66f8c59ca_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2286f4991bd5e59e2e9d8d66f8c59ca','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f2286f4991bd5e59e2e9d8d66f8c59ca_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2286f4991bd5e59e2e9d8d66f8c59ca','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f2286f4991bd5e59e2e9d8d66f8c59ca_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2286f4991bd5e59e2e9d8d66f8c59ca','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f2286f4991bd5e59e2e9d8d66f8c59ca_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2286f4991bd5e59e2e9d8d66f8c59ca','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
