<?php /* Smarty version 2.6.25, created on 2013-03-25 00:47:13
         compiled from print:162 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%23^23A^23A93712%%print%3A162.inc'] = '37ed0f8e7c61ab0aea4f522d9ed5665d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:162', 2, false),array('function', 'metadata', 'print:162', 2, false),array('function', 'stylesheet', 'print:162', 2, false),array('function', 'content', 'print:162', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_37ed0f8e7c61ab0aea4f522d9ed5665d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37ed0f8e7c61ab0aea4f522d9ed5665d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_37ed0f8e7c61ab0aea4f522d9ed5665d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37ed0f8e7c61ab0aea4f522d9ed5665d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_37ed0f8e7c61ab0aea4f522d9ed5665d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37ed0f8e7c61ab0aea4f522d9ed5665d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_37ed0f8e7c61ab0aea4f522d9ed5665d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('37ed0f8e7c61ab0aea4f522d9ed5665d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
