<?php /* Smarty version 2.6.25, created on 2013-03-24 23:53:13
         compiled from print:143 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%66^669^66986506%%print%3A143.inc'] = '9a2afa7abfca516b0c0502adf9694510';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:143', 2, false),array('function', 'metadata', 'print:143', 2, false),array('function', 'stylesheet', 'print:143', 2, false),array('function', 'content', 'print:143', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9a2afa7abfca516b0c0502adf9694510_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9a2afa7abfca516b0c0502adf9694510','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9a2afa7abfca516b0c0502adf9694510_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9a2afa7abfca516b0c0502adf9694510','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9a2afa7abfca516b0c0502adf9694510_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9a2afa7abfca516b0c0502adf9694510','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9a2afa7abfca516b0c0502adf9694510_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9a2afa7abfca516b0c0502adf9694510','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
