<?php /* Smarty version 2.6.25, created on 2013-03-24 09:09:59
         compiled from print:327 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%34^342^342BD2F7%%print%3A327.inc'] = 'bddbc92fe15e27ba7ff6d1334042c85a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:327', 2, false),array('function', 'metadata', 'print:327', 2, false),array('function', 'stylesheet', 'print:327', 2, false),array('function', 'content', 'print:327', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bddbc92fe15e27ba7ff6d1334042c85a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bddbc92fe15e27ba7ff6d1334042c85a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bddbc92fe15e27ba7ff6d1334042c85a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bddbc92fe15e27ba7ff6d1334042c85a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bddbc92fe15e27ba7ff6d1334042c85a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bddbc92fe15e27ba7ff6d1334042c85a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bddbc92fe15e27ba7ff6d1334042c85a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bddbc92fe15e27ba7ff6d1334042c85a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
