<?php /* Smarty version 2.6.25, created on 2013-03-24 17:46:54
         compiled from print:119 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%FB^FB3^FB3A785D%%print%3A119.inc'] = '1a4992985cbd43eccb58fc567b8b3f53';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:119', 2, false),array('function', 'metadata', 'print:119', 2, false),array('function', 'stylesheet', 'print:119', 2, false),array('function', 'content', 'print:119', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1a4992985cbd43eccb58fc567b8b3f53_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a4992985cbd43eccb58fc567b8b3f53','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1a4992985cbd43eccb58fc567b8b3f53_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a4992985cbd43eccb58fc567b8b3f53','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1a4992985cbd43eccb58fc567b8b3f53_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a4992985cbd43eccb58fc567b8b3f53','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1a4992985cbd43eccb58fc567b8b3f53_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a4992985cbd43eccb58fc567b8b3f53','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
