<?php /* Smarty version 2.6.25, created on 2013-03-24 23:08:21
         compiled from print:174 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D3^D3D^D3D1A366%%print%3A174.inc'] = 'cfc3897a4becadd095bed3ed31aea030';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:174', 2, false),array('function', 'metadata', 'print:174', 2, false),array('function', 'stylesheet', 'print:174', 2, false),array('function', 'content', 'print:174', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cfc3897a4becadd095bed3ed31aea030_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfc3897a4becadd095bed3ed31aea030','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cfc3897a4becadd095bed3ed31aea030_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfc3897a4becadd095bed3ed31aea030','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cfc3897a4becadd095bed3ed31aea030_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfc3897a4becadd095bed3ed31aea030','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cfc3897a4becadd095bed3ed31aea030_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfc3897a4becadd095bed3ed31aea030','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
