<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:56
         compiled from print:129 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D0^D01^D0172B9E%%print%3A129.inc'] = '5b5760db7acc47dc0e8254368a4fc10e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:129', 2, false),array('function', 'metadata', 'print:129', 2, false),array('function', 'stylesheet', 'print:129', 2, false),array('function', 'content', 'print:129', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5b5760db7acc47dc0e8254368a4fc10e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b5760db7acc47dc0e8254368a4fc10e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5b5760db7acc47dc0e8254368a4fc10e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b5760db7acc47dc0e8254368a4fc10e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5b5760db7acc47dc0e8254368a4fc10e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b5760db7acc47dc0e8254368a4fc10e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5b5760db7acc47dc0e8254368a4fc10e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5b5760db7acc47dc0e8254368a4fc10e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
