<?php /* Smarty version 2.6.25, created on 2013-03-25 02:58:14
         compiled from print:308 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%96^96A^96A2ADE4%%print%3A308.inc'] = '781190f703de9a371cf4d563159760c5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:308', 2, false),array('function', 'metadata', 'print:308', 2, false),array('function', 'stylesheet', 'print:308', 2, false),array('function', 'content', 'print:308', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_781190f703de9a371cf4d563159760c5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('781190f703de9a371cf4d563159760c5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_781190f703de9a371cf4d563159760c5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('781190f703de9a371cf4d563159760c5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_781190f703de9a371cf4d563159760c5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('781190f703de9a371cf4d563159760c5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_781190f703de9a371cf4d563159760c5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('781190f703de9a371cf4d563159760c5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
