<?php /* Smarty version 2.6.25, created on 2013-03-17 03:55:11
         compiled from print:311 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F6^F66^F6652401%%print%3A311.inc'] = '6a8b5930c41f1e65f95f1648b5e48857';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:311', 2, false),array('function', 'metadata', 'print:311', 2, false),array('function', 'stylesheet', 'print:311', 2, false),array('function', 'content', 'print:311', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6a8b5930c41f1e65f95f1648b5e48857_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a8b5930c41f1e65f95f1648b5e48857','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6a8b5930c41f1e65f95f1648b5e48857_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a8b5930c41f1e65f95f1648b5e48857','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6a8b5930c41f1e65f95f1648b5e48857_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a8b5930c41f1e65f95f1648b5e48857','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6a8b5930c41f1e65f95f1648b5e48857_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a8b5930c41f1e65f95f1648b5e48857','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
