<?php /* Smarty version 2.6.25, created on 2013-03-25 02:18:20
         compiled from print:262 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%21^21E^21EF894B%%print%3A262.inc'] = 'cf9bfe6d38cc115570a7f8ae6e521e3d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:262', 2, false),array('function', 'metadata', 'print:262', 2, false),array('function', 'stylesheet', 'print:262', 2, false),array('function', 'content', 'print:262', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cf9bfe6d38cc115570a7f8ae6e521e3d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cf9bfe6d38cc115570a7f8ae6e521e3d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cf9bfe6d38cc115570a7f8ae6e521e3d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cf9bfe6d38cc115570a7f8ae6e521e3d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cf9bfe6d38cc115570a7f8ae6e521e3d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cf9bfe6d38cc115570a7f8ae6e521e3d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cf9bfe6d38cc115570a7f8ae6e521e3d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cf9bfe6d38cc115570a7f8ae6e521e3d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
