<?php /* Smarty version 2.6.25, created on 2013-03-24 18:59:19
         compiled from print:226 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%42^42E^42EE8856%%print%3A226.inc'] = '5dd0d2a073a1e9cb2bcd410d7248e7ba';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:226', 2, false),array('function', 'metadata', 'print:226', 2, false),array('function', 'stylesheet', 'print:226', 2, false),array('function', 'content', 'print:226', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5dd0d2a073a1e9cb2bcd410d7248e7ba_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5dd0d2a073a1e9cb2bcd410d7248e7ba','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5dd0d2a073a1e9cb2bcd410d7248e7ba_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5dd0d2a073a1e9cb2bcd410d7248e7ba','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5dd0d2a073a1e9cb2bcd410d7248e7ba_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5dd0d2a073a1e9cb2bcd410d7248e7ba','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5dd0d2a073a1e9cb2bcd410d7248e7ba_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5dd0d2a073a1e9cb2bcd410d7248e7ba','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
