<?php /* Smarty version 2.6.25, created on 2013-03-16 23:43:22
         compiled from print:248 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F3^F30^F30C02D7%%print%3A248.inc'] = 'f2dac26ccaf122d98d8dddc610ea9130';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:248', 2, false),array('function', 'metadata', 'print:248', 2, false),array('function', 'stylesheet', 'print:248', 2, false),array('function', 'content', 'print:248', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f2dac26ccaf122d98d8dddc610ea9130_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2dac26ccaf122d98d8dddc610ea9130','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f2dac26ccaf122d98d8dddc610ea9130_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2dac26ccaf122d98d8dddc610ea9130','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f2dac26ccaf122d98d8dddc610ea9130_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2dac26ccaf122d98d8dddc610ea9130','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f2dac26ccaf122d98d8dddc610ea9130_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2dac26ccaf122d98d8dddc610ea9130','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
