<?php /* Smarty version 2.6.25, created on 2013-03-25 10:43:53
         compiled from print:298 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%46^46A^46A27C9A%%print%3A298.inc'] = '005e437af50d5d80c65bc63355abf2a5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:298', 2, false),array('function', 'metadata', 'print:298', 2, false),array('function', 'stylesheet', 'print:298', 2, false),array('function', 'content', 'print:298', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_005e437af50d5d80c65bc63355abf2a5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('005e437af50d5d80c65bc63355abf2a5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_005e437af50d5d80c65bc63355abf2a5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('005e437af50d5d80c65bc63355abf2a5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_005e437af50d5d80c65bc63355abf2a5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('005e437af50d5d80c65bc63355abf2a5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_005e437af50d5d80c65bc63355abf2a5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('005e437af50d5d80c65bc63355abf2a5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
