<?php /* Smarty version 2.6.25, created on 2013-03-23 13:37:48
         compiled from print:175 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A4^A4D^A4D693F0%%print%3A175.inc'] = 'fd10c61184fbe3ed29c0fdc096f2499a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:175', 2, false),array('function', 'metadata', 'print:175', 2, false),array('function', 'stylesheet', 'print:175', 2, false),array('function', 'content', 'print:175', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_fd10c61184fbe3ed29c0fdc096f2499a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fd10c61184fbe3ed29c0fdc096f2499a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_fd10c61184fbe3ed29c0fdc096f2499a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fd10c61184fbe3ed29c0fdc096f2499a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_fd10c61184fbe3ed29c0fdc096f2499a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fd10c61184fbe3ed29c0fdc096f2499a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_fd10c61184fbe3ed29c0fdc096f2499a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fd10c61184fbe3ed29c0fdc096f2499a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
