<?php /* Smarty version 2.6.25, created on 2013-03-20 13:51:40
         compiled from print:237 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2C^2CF^2CF28981%%print%3A237.inc'] = '11f1482c26f8b45cb9990b76ce356f17';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:237', 2, false),array('function', 'metadata', 'print:237', 2, false),array('function', 'stylesheet', 'print:237', 2, false),array('function', 'content', 'print:237', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_11f1482c26f8b45cb9990b76ce356f17_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11f1482c26f8b45cb9990b76ce356f17','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_11f1482c26f8b45cb9990b76ce356f17_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11f1482c26f8b45cb9990b76ce356f17','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_11f1482c26f8b45cb9990b76ce356f17_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11f1482c26f8b45cb9990b76ce356f17','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_11f1482c26f8b45cb9990b76ce356f17_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11f1482c26f8b45cb9990b76ce356f17','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
