<?php /* Smarty version 2.6.25, created on 2013-03-25 10:23:42
         compiled from print:160 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CD^CDA^CDA7563E%%print%3A160.inc'] = 'f2d512d07558ee324c14e67b5de935c8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:160', 2, false),array('function', 'metadata', 'print:160', 2, false),array('function', 'stylesheet', 'print:160', 2, false),array('function', 'content', 'print:160', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f2d512d07558ee324c14e67b5de935c8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2d512d07558ee324c14e67b5de935c8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f2d512d07558ee324c14e67b5de935c8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2d512d07558ee324c14e67b5de935c8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f2d512d07558ee324c14e67b5de935c8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2d512d07558ee324c14e67b5de935c8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f2d512d07558ee324c14e67b5de935c8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f2d512d07558ee324c14e67b5de935c8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
