<?php /* Smarty version 2.6.25, created on 2013-03-15 12:39:21
         compiled from print:228 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A5^A55^A556A551%%print%3A228.inc'] = '171ed5e97fa9494f8e2d28e22fe4db7d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:228', 2, false),array('function', 'metadata', 'print:228', 2, false),array('function', 'stylesheet', 'print:228', 2, false),array('function', 'content', 'print:228', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_171ed5e97fa9494f8e2d28e22fe4db7d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('171ed5e97fa9494f8e2d28e22fe4db7d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_171ed5e97fa9494f8e2d28e22fe4db7d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('171ed5e97fa9494f8e2d28e22fe4db7d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_171ed5e97fa9494f8e2d28e22fe4db7d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('171ed5e97fa9494f8e2d28e22fe4db7d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_171ed5e97fa9494f8e2d28e22fe4db7d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('171ed5e97fa9494f8e2d28e22fe4db7d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
