<?php /* Smarty version 2.6.25, created on 2013-03-25 09:43:47
         compiled from print:318 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%8F^8FB^8FB99CA5%%print%3A318.inc'] = '82bc29f71c3495945afff56c99a1f272';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:318', 2, false),array('function', 'metadata', 'print:318', 2, false),array('function', 'stylesheet', 'print:318', 2, false),array('function', 'content', 'print:318', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_82bc29f71c3495945afff56c99a1f272_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('82bc29f71c3495945afff56c99a1f272','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_82bc29f71c3495945afff56c99a1f272_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('82bc29f71c3495945afff56c99a1f272','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_82bc29f71c3495945afff56c99a1f272_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('82bc29f71c3495945afff56c99a1f272','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_82bc29f71c3495945afff56c99a1f272_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('82bc29f71c3495945afff56c99a1f272','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
