<?php /* Smarty version 2.6.25, created on 2013-03-24 18:22:01
         compiled from print:99 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%27^275^275C4A7A%%print%3A99.inc'] = '06f7dbbd1f64d95efc4faecc7ac9bea8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:99', 2, false),array('function', 'metadata', 'print:99', 2, false),array('function', 'stylesheet', 'print:99', 2, false),array('function', 'content', 'print:99', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_06f7dbbd1f64d95efc4faecc7ac9bea8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('06f7dbbd1f64d95efc4faecc7ac9bea8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_06f7dbbd1f64d95efc4faecc7ac9bea8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('06f7dbbd1f64d95efc4faecc7ac9bea8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_06f7dbbd1f64d95efc4faecc7ac9bea8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('06f7dbbd1f64d95efc4faecc7ac9bea8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_06f7dbbd1f64d95efc4faecc7ac9bea8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('06f7dbbd1f64d95efc4faecc7ac9bea8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
