<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:29
         compiled from print:208 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%97^976^9760C7D3%%print%3A208.inc'] = 'c6a41c7f802255e1e6f0ed768ccdba91';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:208', 2, false),array('function', 'metadata', 'print:208', 2, false),array('function', 'stylesheet', 'print:208', 2, false),array('function', 'content', 'print:208', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c6a41c7f802255e1e6f0ed768ccdba91_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6a41c7f802255e1e6f0ed768ccdba91','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c6a41c7f802255e1e6f0ed768ccdba91_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6a41c7f802255e1e6f0ed768ccdba91','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c6a41c7f802255e1e6f0ed768ccdba91_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6a41c7f802255e1e6f0ed768ccdba91','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c6a41c7f802255e1e6f0ed768ccdba91_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6a41c7f802255e1e6f0ed768ccdba91','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
