<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:42
         compiled from print:222 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%45^458^45834C4F%%print%3A222.inc'] = '63057351b6341396e631e393a1c5c805';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:222', 2, false),array('function', 'metadata', 'print:222', 2, false),array('function', 'stylesheet', 'print:222', 2, false),array('function', 'content', 'print:222', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_63057351b6341396e631e393a1c5c805_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63057351b6341396e631e393a1c5c805','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_63057351b6341396e631e393a1c5c805_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63057351b6341396e631e393a1c5c805','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_63057351b6341396e631e393a1c5c805_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63057351b6341396e631e393a1c5c805','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_63057351b6341396e631e393a1c5c805_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63057351b6341396e631e393a1c5c805','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
