<?php /* Smarty version 2.6.25, created on 2013-03-24 21:37:12
         compiled from print:181 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%24^242^24234B26%%print%3A181.inc'] = '3be98e665af4764febc4c995523849ed';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:181', 2, false),array('function', 'metadata', 'print:181', 2, false),array('function', 'stylesheet', 'print:181', 2, false),array('function', 'content', 'print:181', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3be98e665af4764febc4c995523849ed_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3be98e665af4764febc4c995523849ed','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3be98e665af4764febc4c995523849ed_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3be98e665af4764febc4c995523849ed','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3be98e665af4764febc4c995523849ed_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3be98e665af4764febc4c995523849ed','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3be98e665af4764febc4c995523849ed_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3be98e665af4764febc4c995523849ed','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
