<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:51
         compiled from print:114 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%85^858^858B04E0%%print%3A114.inc'] = '4b5858e7ff43cffeceb8b5cf39945f4f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:114', 2, false),array('function', 'metadata', 'print:114', 2, false),array('function', 'stylesheet', 'print:114', 2, false),array('function', 'content', 'print:114', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4b5858e7ff43cffeceb8b5cf39945f4f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4b5858e7ff43cffeceb8b5cf39945f4f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4b5858e7ff43cffeceb8b5cf39945f4f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4b5858e7ff43cffeceb8b5cf39945f4f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4b5858e7ff43cffeceb8b5cf39945f4f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4b5858e7ff43cffeceb8b5cf39945f4f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4b5858e7ff43cffeceb8b5cf39945f4f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4b5858e7ff43cffeceb8b5cf39945f4f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
