<?php /* Smarty version 2.6.25, created on 2013-03-25 09:42:59
         compiled from print:150 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%E6^E68^E68A05FD%%print%3A150.inc'] = '01cff74bf4d1c7d3a5cd35ada6f94fa6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:150', 2, false),array('function', 'metadata', 'print:150', 2, false),array('function', 'stylesheet', 'print:150', 2, false),array('function', 'content', 'print:150', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_01cff74bf4d1c7d3a5cd35ada6f94fa6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01cff74bf4d1c7d3a5cd35ada6f94fa6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_01cff74bf4d1c7d3a5cd35ada6f94fa6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01cff74bf4d1c7d3a5cd35ada6f94fa6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_01cff74bf4d1c7d3a5cd35ada6f94fa6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01cff74bf4d1c7d3a5cd35ada6f94fa6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_01cff74bf4d1c7d3a5cd35ada6f94fa6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01cff74bf4d1c7d3a5cd35ada6f94fa6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
