<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:50
         compiled from print:109 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%E2^E22^E221491C%%print%3A109.inc'] = 'bcdb211800f80e66cfbc49d83ce797f7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:109', 2, false),array('function', 'metadata', 'print:109', 2, false),array('function', 'stylesheet', 'print:109', 2, false),array('function', 'content', 'print:109', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bcdb211800f80e66cfbc49d83ce797f7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcdb211800f80e66cfbc49d83ce797f7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bcdb211800f80e66cfbc49d83ce797f7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcdb211800f80e66cfbc49d83ce797f7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bcdb211800f80e66cfbc49d83ce797f7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcdb211800f80e66cfbc49d83ce797f7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bcdb211800f80e66cfbc49d83ce797f7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcdb211800f80e66cfbc49d83ce797f7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
