<?php /* Smarty version 2.6.25, created on 2013-03-25 01:38:48
         compiled from print:92 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B0^B08^B08E93F2%%print%3A92.inc'] = '9d55f27f1e75089a1414b47e2079bbb2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:92', 2, false),array('function', 'metadata', 'print:92', 2, false),array('function', 'stylesheet', 'print:92', 2, false),array('function', 'content', 'print:92', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9d55f27f1e75089a1414b47e2079bbb2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d55f27f1e75089a1414b47e2079bbb2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9d55f27f1e75089a1414b47e2079bbb2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d55f27f1e75089a1414b47e2079bbb2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9d55f27f1e75089a1414b47e2079bbb2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d55f27f1e75089a1414b47e2079bbb2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9d55f27f1e75089a1414b47e2079bbb2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9d55f27f1e75089a1414b47e2079bbb2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
