<?php /* Smarty version 2.6.25, created on 2013-03-25 08:45:08
         compiled from print:313 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%18^186^186B452D%%print%3A313.inc'] = '552c003f2d27e69df3ba7c94b4112687';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:313', 2, false),array('function', 'metadata', 'print:313', 2, false),array('function', 'stylesheet', 'print:313', 2, false),array('function', 'content', 'print:313', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_552c003f2d27e69df3ba7c94b4112687_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('552c003f2d27e69df3ba7c94b4112687','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_552c003f2d27e69df3ba7c94b4112687_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('552c003f2d27e69df3ba7c94b4112687','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_552c003f2d27e69df3ba7c94b4112687_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('552c003f2d27e69df3ba7c94b4112687','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_552c003f2d27e69df3ba7c94b4112687_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('552c003f2d27e69df3ba7c94b4112687','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
