<?php /* Smarty version 2.6.25, created on 2013-03-23 13:23:29
         compiled from print:312 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%6F^6F6^6F6C75BB%%print%3A312.inc'] = '7b9fa5e8d9a2c5f59198010e23e103f5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:312', 2, false),array('function', 'metadata', 'print:312', 2, false),array('function', 'stylesheet', 'print:312', 2, false),array('function', 'content', 'print:312', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7b9fa5e8d9a2c5f59198010e23e103f5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b9fa5e8d9a2c5f59198010e23e103f5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7b9fa5e8d9a2c5f59198010e23e103f5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b9fa5e8d9a2c5f59198010e23e103f5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7b9fa5e8d9a2c5f59198010e23e103f5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b9fa5e8d9a2c5f59198010e23e103f5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7b9fa5e8d9a2c5f59198010e23e103f5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b9fa5e8d9a2c5f59198010e23e103f5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
