<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:00
         compiled from print:161 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BA^BAA^BAA066A8%%print%3A161.inc'] = '25e97711547be06c4129a6918143a78e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:161', 2, false),array('function', 'metadata', 'print:161', 2, false),array('function', 'stylesheet', 'print:161', 2, false),array('function', 'content', 'print:161', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_25e97711547be06c4129a6918143a78e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('25e97711547be06c4129a6918143a78e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_25e97711547be06c4129a6918143a78e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('25e97711547be06c4129a6918143a78e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_25e97711547be06c4129a6918143a78e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('25e97711547be06c4129a6918143a78e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_25e97711547be06c4129a6918143a78e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('25e97711547be06c4129a6918143a78e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
