<?php /* Smarty version 2.6.25, created on 2013-03-23 15:55:33
         compiled from print:104 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%9C^9C9^9C9035A1%%print%3A104.inc'] = '7939b2f9b81fd5815ed3169d03a66971';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:104', 2, false),array('function', 'metadata', 'print:104', 2, false),array('function', 'stylesheet', 'print:104', 2, false),array('function', 'content', 'print:104', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7939b2f9b81fd5815ed3169d03a66971_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7939b2f9b81fd5815ed3169d03a66971','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7939b2f9b81fd5815ed3169d03a66971_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7939b2f9b81fd5815ed3169d03a66971','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7939b2f9b81fd5815ed3169d03a66971_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7939b2f9b81fd5815ed3169d03a66971','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7939b2f9b81fd5815ed3169d03a66971_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7939b2f9b81fd5815ed3169d03a66971','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
