<?php /* Smarty version 2.6.25, created on 2013-03-14 15:48:21
         compiled from print:316 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%68^680^6801B1A2%%print%3A316.inc'] = '18c6f83922643024d7fcad317673ddee';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:316', 2, false),array('function', 'metadata', 'print:316', 2, false),array('function', 'stylesheet', 'print:316', 2, false),array('function', 'content', 'print:316', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_18c6f83922643024d7fcad317673ddee_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c6f83922643024d7fcad317673ddee','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_18c6f83922643024d7fcad317673ddee_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c6f83922643024d7fcad317673ddee','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_18c6f83922643024d7fcad317673ddee_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c6f83922643024d7fcad317673ddee','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_18c6f83922643024d7fcad317673ddee_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c6f83922643024d7fcad317673ddee','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
