<?php /* Smarty version 2.6.25, created on 2013-03-24 17:46:53
         compiled from print:115 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F2^F28^F28C3476%%print%3A115.inc'] = '83ffe4a612ab92f1d6f53d936731f5cd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:115', 2, false),array('function', 'metadata', 'print:115', 2, false),array('function', 'stylesheet', 'print:115', 2, false),array('function', 'content', 'print:115', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_83ffe4a612ab92f1d6f53d936731f5cd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83ffe4a612ab92f1d6f53d936731f5cd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_83ffe4a612ab92f1d6f53d936731f5cd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83ffe4a612ab92f1d6f53d936731f5cd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_83ffe4a612ab92f1d6f53d936731f5cd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83ffe4a612ab92f1d6f53d936731f5cd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_83ffe4a612ab92f1d6f53d936731f5cd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83ffe4a612ab92f1d6f53d936731f5cd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
