<?php /* Smarty version 2.6.25, created on 2013-03-22 21:44:53
         compiled from print:70 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C0^C00^C003DF50%%print%3A70.inc'] = '1307308d514bcc6ff04c18ba2ccb1839';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:70', 2, false),array('function', 'metadata', 'print:70', 2, false),array('function', 'stylesheet', 'print:70', 2, false),array('function', 'content', 'print:70', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1307308d514bcc6ff04c18ba2ccb1839_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1307308d514bcc6ff04c18ba2ccb1839','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1307308d514bcc6ff04c18ba2ccb1839_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1307308d514bcc6ff04c18ba2ccb1839','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1307308d514bcc6ff04c18ba2ccb1839_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1307308d514bcc6ff04c18ba2ccb1839','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1307308d514bcc6ff04c18ba2ccb1839_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1307308d514bcc6ff04c18ba2ccb1839','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
