<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:53
         compiled from print:120 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A9^A9C^A9CB933A%%print%3A120.inc'] = 'ec1e2049bbf1d5ec08e619bb7635c6a2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:120', 2, false),array('function', 'metadata', 'print:120', 2, false),array('function', 'stylesheet', 'print:120', 2, false),array('function', 'content', 'print:120', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ec1e2049bbf1d5ec08e619bb7635c6a2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec1e2049bbf1d5ec08e619bb7635c6a2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ec1e2049bbf1d5ec08e619bb7635c6a2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec1e2049bbf1d5ec08e619bb7635c6a2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ec1e2049bbf1d5ec08e619bb7635c6a2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec1e2049bbf1d5ec08e619bb7635c6a2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ec1e2049bbf1d5ec08e619bb7635c6a2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec1e2049bbf1d5ec08e619bb7635c6a2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
