<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:41
         compiled from print:164 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CA^CAC^CACA9227%%print%3A164.inc'] = '181ef1c12323c69fecdd1650123fad09';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:164', 2, false),array('function', 'metadata', 'print:164', 2, false),array('function', 'stylesheet', 'print:164', 2, false),array('function', 'content', 'print:164', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_181ef1c12323c69fecdd1650123fad09_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('181ef1c12323c69fecdd1650123fad09','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_181ef1c12323c69fecdd1650123fad09_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('181ef1c12323c69fecdd1650123fad09','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_181ef1c12323c69fecdd1650123fad09_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('181ef1c12323c69fecdd1650123fad09','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_181ef1c12323c69fecdd1650123fad09_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('181ef1c12323c69fecdd1650123fad09','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
