<?php /* Smarty version 2.6.25, created on 2013-03-25 11:59:51
         compiled from print:334 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B4^B43^B439B20C%%print%3A334.inc'] = '9b9722d930d5a8188d57e244fb670237';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:334', 2, false),array('function', 'metadata', 'print:334', 2, false),array('function', 'stylesheet', 'print:334', 2, false),array('function', 'content', 'print:334', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9b9722d930d5a8188d57e244fb670237_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9b9722d930d5a8188d57e244fb670237','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9b9722d930d5a8188d57e244fb670237_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9b9722d930d5a8188d57e244fb670237','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9b9722d930d5a8188d57e244fb670237_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9b9722d930d5a8188d57e244fb670237','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9b9722d930d5a8188d57e244fb670237_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9b9722d930d5a8188d57e244fb670237','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
