<?php /* Smarty version 2.6.25, created on 2013-03-15 06:13:05
         compiled from print:66 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%30^307^307B4B24%%print%3A66.inc'] = 'c4e17a39a8409a9d4141ceca4e405252';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:66', 2, false),array('function', 'metadata', 'print:66', 2, false),array('function', 'stylesheet', 'print:66', 2, false),array('function', 'content', 'print:66', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c4e17a39a8409a9d4141ceca4e405252_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4e17a39a8409a9d4141ceca4e405252','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c4e17a39a8409a9d4141ceca4e405252_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4e17a39a8409a9d4141ceca4e405252','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c4e17a39a8409a9d4141ceca4e405252_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4e17a39a8409a9d4141ceca4e405252','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c4e17a39a8409a9d4141ceca4e405252_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4e17a39a8409a9d4141ceca4e405252','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
