<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:53
         compiled from print:118 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%8C^8C3^8C3D48CB%%print%3A118.inc'] = '7d074edfe90fe806e86a3ae53399135d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:118', 2, false),array('function', 'metadata', 'print:118', 2, false),array('function', 'stylesheet', 'print:118', 2, false),array('function', 'content', 'print:118', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7d074edfe90fe806e86a3ae53399135d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7d074edfe90fe806e86a3ae53399135d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7d074edfe90fe806e86a3ae53399135d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7d074edfe90fe806e86a3ae53399135d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7d074edfe90fe806e86a3ae53399135d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7d074edfe90fe806e86a3ae53399135d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7d074edfe90fe806e86a3ae53399135d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7d074edfe90fe806e86a3ae53399135d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
