<?php /* Smarty version 2.6.25, created on 2013-03-24 01:37:39
         compiled from print:172 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%3A^3AB^3AB20653%%print%3A172.inc'] = '784f3a6636762c2cc0d1d3275c62c3ca';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:172', 2, false),array('function', 'metadata', 'print:172', 2, false),array('function', 'stylesheet', 'print:172', 2, false),array('function', 'content', 'print:172', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_784f3a6636762c2cc0d1d3275c62c3ca_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('784f3a6636762c2cc0d1d3275c62c3ca','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_784f3a6636762c2cc0d1d3275c62c3ca_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('784f3a6636762c2cc0d1d3275c62c3ca','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_784f3a6636762c2cc0d1d3275c62c3ca_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('784f3a6636762c2cc0d1d3275c62c3ca','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_784f3a6636762c2cc0d1d3275c62c3ca_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('784f3a6636762c2cc0d1d3275c62c3ca','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
