<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:56
         compiled from print:128 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A7^A71^A7101B08%%print%3A128.inc'] = 'cfda9fe3511d26bb931ba195ac972165';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:128', 2, false),array('function', 'metadata', 'print:128', 2, false),array('function', 'stylesheet', 'print:128', 2, false),array('function', 'content', 'print:128', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cfda9fe3511d26bb931ba195ac972165_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfda9fe3511d26bb931ba195ac972165','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cfda9fe3511d26bb931ba195ac972165_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfda9fe3511d26bb931ba195ac972165','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cfda9fe3511d26bb931ba195ac972165_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfda9fe3511d26bb931ba195ac972165','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cfda9fe3511d26bb931ba195ac972165_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cfda9fe3511d26bb931ba195ac972165','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
