<?php /* Smarty version 2.6.25, created on 2013-03-20 07:56:21
         compiled from print:210 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%80^80A^80A07EA0%%print%3A210.inc'] = 'b0c0efa736477831f70292f9b4a70d69';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:210', 2, false),array('function', 'metadata', 'print:210', 2, false),array('function', 'stylesheet', 'print:210', 2, false),array('function', 'content', 'print:210', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0c0efa736477831f70292f9b4a70d69_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c0efa736477831f70292f9b4a70d69','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0c0efa736477831f70292f9b4a70d69_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c0efa736477831f70292f9b4a70d69','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0c0efa736477831f70292f9b4a70d69_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c0efa736477831f70292f9b4a70d69','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0c0efa736477831f70292f9b4a70d69_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c0efa736477831f70292f9b4a70d69','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
