<?php /* Smarty version 2.6.25, created on 2013-03-25 07:55:20
         compiled from print:80 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%47^479^479BC39F%%print%3A80.inc'] = 'bbc80b21240eea7ede8932d23ce2964e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:80', 2, false),array('function', 'metadata', 'print:80', 2, false),array('function', 'stylesheet', 'print:80', 2, false),array('function', 'content', 'print:80', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bbc80b21240eea7ede8932d23ce2964e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bbc80b21240eea7ede8932d23ce2964e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bbc80b21240eea7ede8932d23ce2964e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bbc80b21240eea7ede8932d23ce2964e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bbc80b21240eea7ede8932d23ce2964e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bbc80b21240eea7ede8932d23ce2964e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bbc80b21240eea7ede8932d23ce2964e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bbc80b21240eea7ede8932d23ce2964e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
