<?php /* Smarty version 2.6.25, created on 2013-03-24 20:07:36
         compiled from print:302 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%76^767^767744FA%%print%3A302.inc'] = '94825bd8fa8497124993ad37dae05245';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:302', 2, false),array('function', 'metadata', 'print:302', 2, false),array('function', 'stylesheet', 'print:302', 2, false),array('function', 'content', 'print:302', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_94825bd8fa8497124993ad37dae05245_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('94825bd8fa8497124993ad37dae05245','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_94825bd8fa8497124993ad37dae05245_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('94825bd8fa8497124993ad37dae05245','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_94825bd8fa8497124993ad37dae05245_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('94825bd8fa8497124993ad37dae05245','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_94825bd8fa8497124993ad37dae05245_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('94825bd8fa8497124993ad37dae05245','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
