<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:18
         compiled from print:196 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A3^A35^A35CEFC4%%print%3A196.inc'] = 'ae27153a13cdba40c60a428162f18404';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:196', 2, false),array('function', 'metadata', 'print:196', 2, false),array('function', 'stylesheet', 'print:196', 2, false),array('function', 'content', 'print:196', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ae27153a13cdba40c60a428162f18404_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae27153a13cdba40c60a428162f18404','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ae27153a13cdba40c60a428162f18404_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae27153a13cdba40c60a428162f18404','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ae27153a13cdba40c60a428162f18404_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae27153a13cdba40c60a428162f18404','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ae27153a13cdba40c60a428162f18404_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae27153a13cdba40c60a428162f18404','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
