<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:42
         compiled from print:158 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%E8^E85^E8518DCF%%print%3A158.inc'] = '4179acf147bad68266e6f4ee3c197f09';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:158', 2, false),array('function', 'metadata', 'print:158', 2, false),array('function', 'stylesheet', 'print:158', 2, false),array('function', 'content', 'print:158', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4179acf147bad68266e6f4ee3c197f09_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4179acf147bad68266e6f4ee3c197f09','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4179acf147bad68266e6f4ee3c197f09_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4179acf147bad68266e6f4ee3c197f09','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4179acf147bad68266e6f4ee3c197f09_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4179acf147bad68266e6f4ee3c197f09','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4179acf147bad68266e6f4ee3c197f09_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4179acf147bad68266e6f4ee3c197f09','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
