<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:24
         compiled from print:206 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%70^70D^70D8EAD4%%print%3A206.inc'] = 'ffeb0ddde77d993d97bf523573646525';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:206', 2, false),array('function', 'metadata', 'print:206', 2, false),array('function', 'stylesheet', 'print:206', 2, false),array('function', 'content', 'print:206', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ffeb0ddde77d993d97bf523573646525_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ffeb0ddde77d993d97bf523573646525','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ffeb0ddde77d993d97bf523573646525_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ffeb0ddde77d993d97bf523573646525','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ffeb0ddde77d993d97bf523573646525_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ffeb0ddde77d993d97bf523573646525','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ffeb0ddde77d993d97bf523573646525_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ffeb0ddde77d993d97bf523573646525','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
