<?php /* Smarty version 2.6.25, created on 2013-03-23 17:42:23
         compiled from print:69 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A0^A0C^A0C456B5%%print%3A69.inc'] = 'de40555bbcb03da996e131028220171b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:69', 2, false),array('function', 'metadata', 'print:69', 2, false),array('function', 'stylesheet', 'print:69', 2, false),array('function', 'content', 'print:69', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_de40555bbcb03da996e131028220171b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de40555bbcb03da996e131028220171b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_de40555bbcb03da996e131028220171b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de40555bbcb03da996e131028220171b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_de40555bbcb03da996e131028220171b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de40555bbcb03da996e131028220171b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_de40555bbcb03da996e131028220171b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de40555bbcb03da996e131028220171b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
