<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:58
         compiled from print:297 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D6^D61^D61D610B%%print%3A297.inc'] = '9f8408a53b27cdd292cc501f6f53c6bd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:297', 2, false),array('function', 'metadata', 'print:297', 2, false),array('function', 'stylesheet', 'print:297', 2, false),array('function', 'content', 'print:297', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9f8408a53b27cdd292cc501f6f53c6bd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9f8408a53b27cdd292cc501f6f53c6bd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9f8408a53b27cdd292cc501f6f53c6bd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9f8408a53b27cdd292cc501f6f53c6bd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9f8408a53b27cdd292cc501f6f53c6bd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9f8408a53b27cdd292cc501f6f53c6bd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9f8408a53b27cdd292cc501f6f53c6bd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9f8408a53b27cdd292cc501f6f53c6bd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
