<?php /* Smarty version 2.6.25, created on 2013-03-23 13:23:29
         compiled from print:310 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%81^816^81621497%%print%3A310.inc'] = '8df2b4b9deb3146ce55c0d82d26d7738';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:310', 2, false),array('function', 'metadata', 'print:310', 2, false),array('function', 'stylesheet', 'print:310', 2, false),array('function', 'content', 'print:310', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8df2b4b9deb3146ce55c0d82d26d7738_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8df2b4b9deb3146ce55c0d82d26d7738','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8df2b4b9deb3146ce55c0d82d26d7738_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8df2b4b9deb3146ce55c0d82d26d7738','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8df2b4b9deb3146ce55c0d82d26d7738_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8df2b4b9deb3146ce55c0d82d26d7738','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8df2b4b9deb3146ce55c0d82d26d7738_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8df2b4b9deb3146ce55c0d82d26d7738','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
