<?php /* Smarty version 2.6.25, created on 2013-03-25 00:22:27
         compiled from print:301 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%EF^EF7^EF7E1540%%print%3A301.inc'] = '44fa2c4787a2e696d248ac84d9a912e7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:301', 2, false),array('function', 'metadata', 'print:301', 2, false),array('function', 'stylesheet', 'print:301', 2, false),array('function', 'content', 'print:301', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_44fa2c4787a2e696d248ac84d9a912e7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('44fa2c4787a2e696d248ac84d9a912e7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_44fa2c4787a2e696d248ac84d9a912e7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('44fa2c4787a2e696d248ac84d9a912e7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_44fa2c4787a2e696d248ac84d9a912e7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('44fa2c4787a2e696d248ac84d9a912e7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_44fa2c4787a2e696d248ac84d9a912e7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('44fa2c4787a2e696d248ac84d9a912e7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
