<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:48
         compiled from print:103 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%02^02F^02F4A002%%print%3A103.inc'] = 'c77462a425ddaaa647cb58bd9c47f746';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:103', 2, false),array('function', 'metadata', 'print:103', 2, false),array('function', 'stylesheet', 'print:103', 2, false),array('function', 'content', 'print:103', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c77462a425ddaaa647cb58bd9c47f746_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c77462a425ddaaa647cb58bd9c47f746','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c77462a425ddaaa647cb58bd9c47f746_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c77462a425ddaaa647cb58bd9c47f746','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c77462a425ddaaa647cb58bd9c47f746_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c77462a425ddaaa647cb58bd9c47f746','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c77462a425ddaaa647cb58bd9c47f746_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c77462a425ddaaa647cb58bd9c47f746','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
