<?php /* Smarty version 2.6.25, created on 2013-03-14 18:59:20
         compiled from print:218 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%8E^8E7^8E7BF692%%print%3A218.inc'] = 'c2174618ff3d97195926b9b7725bbb40';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:218', 2, false),array('function', 'metadata', 'print:218', 2, false),array('function', 'stylesheet', 'print:218', 2, false),array('function', 'content', 'print:218', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c2174618ff3d97195926b9b7725bbb40_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c2174618ff3d97195926b9b7725bbb40','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c2174618ff3d97195926b9b7725bbb40_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c2174618ff3d97195926b9b7725bbb40','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c2174618ff3d97195926b9b7725bbb40_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c2174618ff3d97195926b9b7725bbb40','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c2174618ff3d97195926b9b7725bbb40_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c2174618ff3d97195926b9b7725bbb40','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
