<?php /* Smarty version 2.6.25, created on 2013-03-20 13:51:42
         compiled from print:251 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%93^93C^93CB8B32%%print%3A251.inc'] = '0301c5c5122099231eb4cb7708f471d5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:251', 2, false),array('function', 'metadata', 'print:251', 2, false),array('function', 'stylesheet', 'print:251', 2, false),array('function', 'content', 'print:251', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0301c5c5122099231eb4cb7708f471d5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0301c5c5122099231eb4cb7708f471d5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0301c5c5122099231eb4cb7708f471d5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0301c5c5122099231eb4cb7708f471d5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0301c5c5122099231eb4cb7708f471d5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0301c5c5122099231eb4cb7708f471d5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0301c5c5122099231eb4cb7708f471d5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0301c5c5122099231eb4cb7708f471d5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
