<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:45
         compiled from print:139 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C9^C90^C90C1ADF%%print%3A139.inc'] = '719a521c528891531d89888602cd9624';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:139', 2, false),array('function', 'metadata', 'print:139', 2, false),array('function', 'stylesheet', 'print:139', 2, false),array('function', 'content', 'print:139', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_719a521c528891531d89888602cd9624_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('719a521c528891531d89888602cd9624','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_719a521c528891531d89888602cd9624_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('719a521c528891531d89888602cd9624','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_719a521c528891531d89888602cd9624_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('719a521c528891531d89888602cd9624','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_719a521c528891531d89888602cd9624_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('719a521c528891531d89888602cd9624','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
