<?php /* Smarty version 2.6.25, created on 2013-03-25 08:38:03
         compiled from print:299 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%31^31A^31A54C0C%%print%3A299.inc'] = 'a748ac918bda8651cd11b99cdca06ea6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:299', 2, false),array('function', 'metadata', 'print:299', 2, false),array('function', 'stylesheet', 'print:299', 2, false),array('function', 'content', 'print:299', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a748ac918bda8651cd11b99cdca06ea6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a748ac918bda8651cd11b99cdca06ea6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a748ac918bda8651cd11b99cdca06ea6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a748ac918bda8651cd11b99cdca06ea6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a748ac918bda8651cd11b99cdca06ea6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a748ac918bda8651cd11b99cdca06ea6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a748ac918bda8651cd11b99cdca06ea6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a748ac918bda8651cd11b99cdca06ea6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
