<?php /* Smarty version 2.6.25, created on 2013-03-15 09:21:35
         compiled from print:56 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%1B^1B5^1B5618E7%%print%3A56.inc'] = '6f40f587c58eabaf8573187537c32771';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:56', 2, false),array('function', 'metadata', 'print:56', 2, false),array('function', 'stylesheet', 'print:56', 2, false),array('function', 'content', 'print:56', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6f40f587c58eabaf8573187537c32771_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f40f587c58eabaf8573187537c32771','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6f40f587c58eabaf8573187537c32771_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f40f587c58eabaf8573187537c32771','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6f40f587c58eabaf8573187537c32771_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f40f587c58eabaf8573187537c32771','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6f40f587c58eabaf8573187537c32771_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f40f587c58eabaf8573187537c32771','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
