<?php /* Smarty version 2.6.25, created on 2013-03-22 08:23:51
         compiled from print:89 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%3E^3E4^3E477B3B%%print%3A89.inc'] = 'ef254cdd1331589c6fd346209436c41e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:89', 2, false),array('function', 'metadata', 'print:89', 2, false),array('function', 'stylesheet', 'print:89', 2, false),array('function', 'content', 'print:89', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef254cdd1331589c6fd346209436c41e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef254cdd1331589c6fd346209436c41e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ef254cdd1331589c6fd346209436c41e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef254cdd1331589c6fd346209436c41e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ef254cdd1331589c6fd346209436c41e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef254cdd1331589c6fd346209436c41e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ef254cdd1331589c6fd346209436c41e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef254cdd1331589c6fd346209436c41e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
