<?php /* Smarty version 2.6.25, created on 2013-03-22 03:04:01
         compiled from print:94 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%59^59E^59ED36C7%%print%3A94.inc'] = '09e44e91df9ee02a0c7d532febfcac5e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:94', 2, false),array('function', 'metadata', 'print:94', 2, false),array('function', 'stylesheet', 'print:94', 2, false),array('function', 'content', 'print:94', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_09e44e91df9ee02a0c7d532febfcac5e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09e44e91df9ee02a0c7d532febfcac5e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_09e44e91df9ee02a0c7d532febfcac5e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09e44e91df9ee02a0c7d532febfcac5e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_09e44e91df9ee02a0c7d532febfcac5e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09e44e91df9ee02a0c7d532febfcac5e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_09e44e91df9ee02a0c7d532febfcac5e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09e44e91df9ee02a0c7d532febfcac5e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
