<?php /* Smarty version 2.6.25, created on 2013-03-25 04:26:02
         compiled from print:201 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%EE^EEB^EEBC7F77%%print%3A201.inc'] = '63d8585d22d200d15101b1d360c925b0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:201', 2, false),array('function', 'metadata', 'print:201', 2, false),array('function', 'stylesheet', 'print:201', 2, false),array('function', 'content', 'print:201', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_63d8585d22d200d15101b1d360c925b0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63d8585d22d200d15101b1d360c925b0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_63d8585d22d200d15101b1d360c925b0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63d8585d22d200d15101b1d360c925b0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_63d8585d22d200d15101b1d360c925b0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63d8585d22d200d15101b1d360c925b0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_63d8585d22d200d15101b1d360c925b0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63d8585d22d200d15101b1d360c925b0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
