<?php /* Smarty version 2.6.25, created on 2013-03-23 13:38:05
         compiled from print:152 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%08^088^088464D1%%print%3A152.inc'] = 'f3f4058b6bbbd36f1ae0cf13d9b9b77d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:152', 2, false),array('function', 'metadata', 'print:152', 2, false),array('function', 'stylesheet', 'print:152', 2, false),array('function', 'content', 'print:152', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f3f4058b6bbbd36f1ae0cf13d9b9b77d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3f4058b6bbbd36f1ae0cf13d9b9b77d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f3f4058b6bbbd36f1ae0cf13d9b9b77d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3f4058b6bbbd36f1ae0cf13d9b9b77d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f3f4058b6bbbd36f1ae0cf13d9b9b77d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3f4058b6bbbd36f1ae0cf13d9b9b77d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f3f4058b6bbbd36f1ae0cf13d9b9b77d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3f4058b6bbbd36f1ae0cf13d9b9b77d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
