<?php /* Smarty version 2.6.25, created on 2013-03-24 15:50:36
         compiled from print:85 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%37^37F^37F13710%%print%3A85.inc'] = 'd766ddc30ede0077b3b1a03652f285a8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:85', 2, false),array('function', 'metadata', 'print:85', 2, false),array('function', 'stylesheet', 'print:85', 2, false),array('function', 'content', 'print:85', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d766ddc30ede0077b3b1a03652f285a8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d766ddc30ede0077b3b1a03652f285a8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d766ddc30ede0077b3b1a03652f285a8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d766ddc30ede0077b3b1a03652f285a8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d766ddc30ede0077b3b1a03652f285a8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d766ddc30ede0077b3b1a03652f285a8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d766ddc30ede0077b3b1a03652f285a8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d766ddc30ede0077b3b1a03652f285a8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
