<?php /* Smarty version 2.6.25, created on 2013-03-22 16:26:07
         compiled from print:179 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AD^AD6^AD60DFDB%%print%3A179.inc'] = 'f022ccd87d9666239ef0fa0ee0f22e35';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:179', 2, false),array('function', 'metadata', 'print:179', 2, false),array('function', 'stylesheet', 'print:179', 2, false),array('function', 'content', 'print:179', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f022ccd87d9666239ef0fa0ee0f22e35_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f022ccd87d9666239ef0fa0ee0f22e35','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f022ccd87d9666239ef0fa0ee0f22e35_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f022ccd87d9666239ef0fa0ee0f22e35','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f022ccd87d9666239ef0fa0ee0f22e35_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f022ccd87d9666239ef0fa0ee0f22e35','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f022ccd87d9666239ef0fa0ee0f22e35_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f022ccd87d9666239ef0fa0ee0f22e35','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
