<?php /* Smarty version 2.6.25, created on 2013-03-24 23:11:39
         compiled from print:205 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%E9^E9D^E9D1BB6E%%print%3A205.inc'] = 'df8175050415aab689e2788a2efa254b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:205', 2, false),array('function', 'metadata', 'print:205', 2, false),array('function', 'stylesheet', 'print:205', 2, false),array('function', 'content', 'print:205', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_df8175050415aab689e2788a2efa254b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df8175050415aab689e2788a2efa254b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_df8175050415aab689e2788a2efa254b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df8175050415aab689e2788a2efa254b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_df8175050415aab689e2788a2efa254b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df8175050415aab689e2788a2efa254b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_df8175050415aab689e2788a2efa254b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df8175050415aab689e2788a2efa254b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
