<?php /* Smarty version 2.6.25, created on 2013-03-24 18:30:20
         compiled from print:239 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CB^CB4^CB4AA486%%print%3A239.inc'] = 'a2bc376ba0d343df86d0681d4e720644';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:239', 2, false),array('function', 'metadata', 'print:239', 2, false),array('function', 'stylesheet', 'print:239', 2, false),array('function', 'content', 'print:239', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a2bc376ba0d343df86d0681d4e720644_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2bc376ba0d343df86d0681d4e720644','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a2bc376ba0d343df86d0681d4e720644_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2bc376ba0d343df86d0681d4e720644','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a2bc376ba0d343df86d0681d4e720644_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2bc376ba0d343df86d0681d4e720644','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a2bc376ba0d343df86d0681d4e720644_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2bc376ba0d343df86d0681d4e720644','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
