<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:44
         compiled from print:140 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%FF^FF9^FF9134BC%%print%3A140.inc'] = 'f5f98ecc5f29837403f159b1af7ee008';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:140', 2, false),array('function', 'metadata', 'print:140', 2, false),array('function', 'stylesheet', 'print:140', 2, false),array('function', 'content', 'print:140', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f5f98ecc5f29837403f159b1af7ee008_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5f98ecc5f29837403f159b1af7ee008','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f5f98ecc5f29837403f159b1af7ee008_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5f98ecc5f29837403f159b1af7ee008','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f5f98ecc5f29837403f159b1af7ee008_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5f98ecc5f29837403f159b1af7ee008','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f5f98ecc5f29837403f159b1af7ee008_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5f98ecc5f29837403f159b1af7ee008','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
