<?php /* Smarty version 2.6.25, created on 2013-03-23 13:37:48
         compiled from print:173 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%4D^4DB^4DB536C5%%print%3A173.inc'] = '0874b279ef8bfcdfa79f273665537980';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:173', 2, false),array('function', 'metadata', 'print:173', 2, false),array('function', 'stylesheet', 'print:173', 2, false),array('function', 'content', 'print:173', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0874b279ef8bfcdfa79f273665537980_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0874b279ef8bfcdfa79f273665537980','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0874b279ef8bfcdfa79f273665537980_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0874b279ef8bfcdfa79f273665537980','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0874b279ef8bfcdfa79f273665537980_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0874b279ef8bfcdfa79f273665537980','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0874b279ef8bfcdfa79f273665537980_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0874b279ef8bfcdfa79f273665537980','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
