<?php /* Smarty version 2.6.25, created on 2013-03-23 08:49:31
         compiled from print:93 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C7^C78^C789A364%%print%3A93.inc'] = 'cc7fc6585efbb5c9b5c65a4792cb7922';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:93', 2, false),array('function', 'metadata', 'print:93', 2, false),array('function', 'stylesheet', 'print:93', 2, false),array('function', 'content', 'print:93', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cc7fc6585efbb5c9b5c65a4792cb7922_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc7fc6585efbb5c9b5c65a4792cb7922','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cc7fc6585efbb5c9b5c65a4792cb7922_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc7fc6585efbb5c9b5c65a4792cb7922','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cc7fc6585efbb5c9b5c65a4792cb7922_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc7fc6585efbb5c9b5c65a4792cb7922','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cc7fc6585efbb5c9b5c65a4792cb7922_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc7fc6585efbb5c9b5c65a4792cb7922','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
