<?php /* Smarty version 2.6.25, created on 2013-03-22 08:23:38
         compiled from print:78 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CE^CED^CED85762%%print%3A78.inc'] = '6dc5fbb9ed2d9e9887b32ba6e1afc162';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:78', 2, false),array('function', 'metadata', 'print:78', 2, false),array('function', 'stylesheet', 'print:78', 2, false),array('function', 'content', 'print:78', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6dc5fbb9ed2d9e9887b32ba6e1afc162_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6dc5fbb9ed2d9e9887b32ba6e1afc162','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6dc5fbb9ed2d9e9887b32ba6e1afc162_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6dc5fbb9ed2d9e9887b32ba6e1afc162','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6dc5fbb9ed2d9e9887b32ba6e1afc162_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6dc5fbb9ed2d9e9887b32ba6e1afc162','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6dc5fbb9ed2d9e9887b32ba6e1afc162_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6dc5fbb9ed2d9e9887b32ba6e1afc162','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
