<?php /* Smarty version 2.6.25, created on 2013-03-24 11:20:40
         compiled from print:198 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%44^44E^44E4C2C3%%print%3A198.inc'] = '09adcfbdf06fae5f29568eb87d19b015';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:198', 2, false),array('function', 'metadata', 'print:198', 2, false),array('function', 'stylesheet', 'print:198', 2, false),array('function', 'content', 'print:198', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_09adcfbdf06fae5f29568eb87d19b015_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09adcfbdf06fae5f29568eb87d19b015','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_09adcfbdf06fae5f29568eb87d19b015_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09adcfbdf06fae5f29568eb87d19b015','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_09adcfbdf06fae5f29568eb87d19b015_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09adcfbdf06fae5f29568eb87d19b015','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_09adcfbdf06fae5f29568eb87d19b015_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('09adcfbdf06fae5f29568eb87d19b015','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
