<?php /* Smarty version 2.6.25, created on 2013-03-14 21:41:13
         compiled from print:238 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BC^BC4^BC4D9410%%print%3A238.inc'] = '2ca46f85ae86a086cc22fbec5636294b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:238', 2, false),array('function', 'metadata', 'print:238', 2, false),array('function', 'stylesheet', 'print:238', 2, false),array('function', 'content', 'print:238', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2ca46f85ae86a086cc22fbec5636294b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ca46f85ae86a086cc22fbec5636294b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2ca46f85ae86a086cc22fbec5636294b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ca46f85ae86a086cc22fbec5636294b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2ca46f85ae86a086cc22fbec5636294b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ca46f85ae86a086cc22fbec5636294b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2ca46f85ae86a086cc22fbec5636294b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2ca46f85ae86a086cc22fbec5636294b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
