<?php /* Smarty version 2.6.25, created on 2013-03-24 03:46:06
         compiled from print:342 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%12^121^121B81FE%%print%3A342.inc'] = '970b5a2c39182165578d2cd9ccfe034e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:342', 2, false),array('function', 'metadata', 'print:342', 2, false),array('function', 'stylesheet', 'print:342', 2, false),array('function', 'content', 'print:342', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_970b5a2c39182165578d2cd9ccfe034e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('970b5a2c39182165578d2cd9ccfe034e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_970b5a2c39182165578d2cd9ccfe034e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('970b5a2c39182165578d2cd9ccfe034e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_970b5a2c39182165578d2cd9ccfe034e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('970b5a2c39182165578d2cd9ccfe034e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_970b5a2c39182165578d2cd9ccfe034e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('970b5a2c39182165578d2cd9ccfe034e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
