<?php /* Smarty version 2.6.25, created on 2013-03-25 10:02:40
         compiled from print:333 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2A^2A5^2A5D27AF%%print%3A333.inc'] = '117a26045cf64432114bbf85df8c5890';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:333', 2, false),array('function', 'metadata', 'print:333', 2, false),array('function', 'stylesheet', 'print:333', 2, false),array('function', 'content', 'print:333', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_117a26045cf64432114bbf85df8c5890_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('117a26045cf64432114bbf85df8c5890','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_117a26045cf64432114bbf85df8c5890_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('117a26045cf64432114bbf85df8c5890','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_117a26045cf64432114bbf85df8c5890_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('117a26045cf64432114bbf85df8c5890','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_117a26045cf64432114bbf85df8c5890_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('117a26045cf64432114bbf85df8c5890','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
