<?php /* Smarty version 2.6.25, created on 2013-03-25 02:04:03
         compiled from print:168 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C3^C37^C37CDE0C%%print%3A168.inc'] = 'c4466c5c808103834eb899f7ef53eb96';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:168', 2, false),array('function', 'metadata', 'print:168', 2, false),array('function', 'stylesheet', 'print:168', 2, false),array('function', 'content', 'print:168', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c4466c5c808103834eb899f7ef53eb96_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4466c5c808103834eb899f7ef53eb96','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c4466c5c808103834eb899f7ef53eb96_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4466c5c808103834eb899f7ef53eb96','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c4466c5c808103834eb899f7ef53eb96_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4466c5c808103834eb899f7ef53eb96','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c4466c5c808103834eb899f7ef53eb96_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c4466c5c808103834eb899f7ef53eb96','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
