<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:59
         compiled from print:132 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5E^5ED^5EDEC357%%print%3A132.inc'] = 'd1c17226b324cb7d018464deeb0a0fe2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:132', 2, false),array('function', 'metadata', 'print:132', 2, false),array('function', 'stylesheet', 'print:132', 2, false),array('function', 'content', 'print:132', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d1c17226b324cb7d018464deeb0a0fe2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d1c17226b324cb7d018464deeb0a0fe2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d1c17226b324cb7d018464deeb0a0fe2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d1c17226b324cb7d018464deeb0a0fe2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d1c17226b324cb7d018464deeb0a0fe2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d1c17226b324cb7d018464deeb0a0fe2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d1c17226b324cb7d018464deeb0a0fe2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d1c17226b324cb7d018464deeb0a0fe2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
