<?php /* Smarty version 2.6.25, created on 2013-03-22 01:12:57
         compiled from print:108 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%95^952^9526798A%%print%3A108.inc'] = 'a5a4f6c395f32cb5fedb968db7fa6668';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:108', 2, false),array('function', 'metadata', 'print:108', 2, false),array('function', 'stylesheet', 'print:108', 2, false),array('function', 'content', 'print:108', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a5a4f6c395f32cb5fedb968db7fa6668_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a5a4f6c395f32cb5fedb968db7fa6668','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a5a4f6c395f32cb5fedb968db7fa6668_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a5a4f6c395f32cb5fedb968db7fa6668','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a5a4f6c395f32cb5fedb968db7fa6668_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a5a4f6c395f32cb5fedb968db7fa6668','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a5a4f6c395f32cb5fedb968db7fa6668_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a5a4f6c395f32cb5fedb968db7fa6668','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
