<?php /* Smarty version 2.6.25, created on 2013-03-25 05:18:41
         compiled from print:219 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F9^F97^F97CC604%%print%3A219.inc'] = '2b0d92466e6262d1e3bf6ab5a28ace1f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:219', 2, false),array('function', 'metadata', 'print:219', 2, false),array('function', 'stylesheet', 'print:219', 2, false),array('function', 'content', 'print:219', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2b0d92466e6262d1e3bf6ab5a28ace1f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b0d92466e6262d1e3bf6ab5a28ace1f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2b0d92466e6262d1e3bf6ab5a28ace1f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b0d92466e6262d1e3bf6ab5a28ace1f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2b0d92466e6262d1e3bf6ab5a28ace1f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b0d92466e6262d1e3bf6ab5a28ace1f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2b0d92466e6262d1e3bf6ab5a28ace1f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b0d92466e6262d1e3bf6ab5a28ace1f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
