<?php /* Smarty version 2.6.25, created on 2013-03-23 13:42:55
         compiled from print:147 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%61^61F^61F5A11F%%print%3A147.inc'] = '2b2754260ea5fcdd43a1ff7f5d73386a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:147', 2, false),array('function', 'metadata', 'print:147', 2, false),array('function', 'stylesheet', 'print:147', 2, false),array('function', 'content', 'print:147', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2b2754260ea5fcdd43a1ff7f5d73386a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b2754260ea5fcdd43a1ff7f5d73386a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2b2754260ea5fcdd43a1ff7f5d73386a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b2754260ea5fcdd43a1ff7f5d73386a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2b2754260ea5fcdd43a1ff7f5d73386a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b2754260ea5fcdd43a1ff7f5d73386a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2b2754260ea5fcdd43a1ff7f5d73386a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2b2754260ea5fcdd43a1ff7f5d73386a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
