<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:44
         compiled from print:142 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%11^119^119F5590%%print%3A142.inc'] = '1ceeaead1dd406b40eed7d516b10f0d0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:142', 2, false),array('function', 'metadata', 'print:142', 2, false),array('function', 'stylesheet', 'print:142', 2, false),array('function', 'content', 'print:142', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1ceeaead1dd406b40eed7d516b10f0d0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ceeaead1dd406b40eed7d516b10f0d0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1ceeaead1dd406b40eed7d516b10f0d0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ceeaead1dd406b40eed7d516b10f0d0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1ceeaead1dd406b40eed7d516b10f0d0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ceeaead1dd406b40eed7d516b10f0d0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1ceeaead1dd406b40eed7d516b10f0d0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ceeaead1dd406b40eed7d516b10f0d0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
