<?php /* Smarty version 2.6.25, created on 2013-03-23 13:40:11
         compiled from print:223 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%32^328^32847CD9%%print%3A223.inc'] = '00600c3b6d7218ad189ba1fd2b885fff';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:223', 2, false),array('function', 'metadata', 'print:223', 2, false),array('function', 'stylesheet', 'print:223', 2, false),array('function', 'content', 'print:223', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_00600c3b6d7218ad189ba1fd2b885fff_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('00600c3b6d7218ad189ba1fd2b885fff','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_00600c3b6d7218ad189ba1fd2b885fff_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('00600c3b6d7218ad189ba1fd2b885fff','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_00600c3b6d7218ad189ba1fd2b885fff_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('00600c3b6d7218ad189ba1fd2b885fff','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_00600c3b6d7218ad189ba1fd2b885fff_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('00600c3b6d7218ad189ba1fd2b885fff','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
