<?php /* Smarty version 2.6.25, created on 2013-03-24 18:31:49
         compiled from print:264 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C8^C88^C88C2C7E%%print%3A264.inc'] = '1555375df8896cbc9c9259686c2b035b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:264', 2, false),array('function', 'metadata', 'print:264', 2, false),array('function', 'stylesheet', 'print:264', 2, false),array('function', 'content', 'print:264', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1555375df8896cbc9c9259686c2b035b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1555375df8896cbc9c9259686c2b035b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1555375df8896cbc9c9259686c2b035b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1555375df8896cbc9c9259686c2b035b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1555375df8896cbc9c9259686c2b035b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1555375df8896cbc9c9259686c2b035b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1555375df8896cbc9c9259686c2b035b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1555375df8896cbc9c9259686c2b035b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
