<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:45
         compiled from print:138 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BE^BE0^BE0B2A49%%print%3A138.inc'] = '6b7c0ba4a6bf05fc1bcf25869df0f0f3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:138', 2, false),array('function', 'metadata', 'print:138', 2, false),array('function', 'stylesheet', 'print:138', 2, false),array('function', 'content', 'print:138', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6b7c0ba4a6bf05fc1bcf25869df0f0f3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b7c0ba4a6bf05fc1bcf25869df0f0f3','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6b7c0ba4a6bf05fc1bcf25869df0f0f3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b7c0ba4a6bf05fc1bcf25869df0f0f3','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6b7c0ba4a6bf05fc1bcf25869df0f0f3_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b7c0ba4a6bf05fc1bcf25869df0f0f3','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6b7c0ba4a6bf05fc1bcf25869df0f0f3_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6b7c0ba4a6bf05fc1bcf25869df0f0f3','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
