<?php /* Smarty version 2.6.25, created on 2013-03-25 07:45:43
         compiled from print:307 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%06^061^061DB075%%print%3A307.inc'] = 'c29e3b7895d34e34259be05bdd6a642b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:307', 2, false),array('function', 'metadata', 'print:307', 2, false),array('function', 'stylesheet', 'print:307', 2, false),array('function', 'content', 'print:307', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c29e3b7895d34e34259be05bdd6a642b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c29e3b7895d34e34259be05bdd6a642b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c29e3b7895d34e34259be05bdd6a642b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c29e3b7895d34e34259be05bdd6a642b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c29e3b7895d34e34259be05bdd6a642b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c29e3b7895d34e34259be05bdd6a642b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c29e3b7895d34e34259be05bdd6a642b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c29e3b7895d34e34259be05bdd6a642b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
