<?php /* Smarty version 2.6.25, created on 2013-03-21 07:13:00
         compiled from print:194 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%4D^4D5^4D528EE8%%print%3A194.inc'] = 'bf293fb270048d290e77729b8a278f6c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:194', 2, false),array('function', 'metadata', 'print:194', 2, false),array('function', 'stylesheet', 'print:194', 2, false),array('function', 'content', 'print:194', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bf293fb270048d290e77729b8a278f6c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf293fb270048d290e77729b8a278f6c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bf293fb270048d290e77729b8a278f6c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf293fb270048d290e77729b8a278f6c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bf293fb270048d290e77729b8a278f6c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf293fb270048d290e77729b8a278f6c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bf293fb270048d290e77729b8a278f6c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf293fb270048d290e77729b8a278f6c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
