<?php /* Smarty version 2.6.25, created on 2013-03-24 22:46:23
         compiled from print:64 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%DE^DE7^DE752A08%%print%3A64.inc'] = '983715432309f23875c02fbffceac93a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:64', 2, false),array('function', 'metadata', 'print:64', 2, false),array('function', 'stylesheet', 'print:64', 2, false),array('function', 'content', 'print:64', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_983715432309f23875c02fbffceac93a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('983715432309f23875c02fbffceac93a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_983715432309f23875c02fbffceac93a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('983715432309f23875c02fbffceac93a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_983715432309f23875c02fbffceac93a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('983715432309f23875c02fbffceac93a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_983715432309f23875c02fbffceac93a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('983715432309f23875c02fbffceac93a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
