<?php /* Smarty version 2.6.25, created on 2013-03-25 02:37:29
         compiled from print:146 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%16^16F^16F29189%%print%3A146.inc'] = 'fc6f9a4ee95c11a661c722b1e64bd22b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:146', 2, false),array('function', 'metadata', 'print:146', 2, false),array('function', 'stylesheet', 'print:146', 2, false),array('function', 'content', 'print:146', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_fc6f9a4ee95c11a661c722b1e64bd22b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fc6f9a4ee95c11a661c722b1e64bd22b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_fc6f9a4ee95c11a661c722b1e64bd22b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fc6f9a4ee95c11a661c722b1e64bd22b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_fc6f9a4ee95c11a661c722b1e64bd22b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fc6f9a4ee95c11a661c722b1e64bd22b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_fc6f9a4ee95c11a661c722b1e64bd22b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fc6f9a4ee95c11a661c722b1e64bd22b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
