<?php /* Smarty version 2.6.25, created on 2013-03-25 10:59:16
         compiled from print:202 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%77^77B^77B52ECD%%print%3A202.inc'] = 'add62f1b324fe32984a9399b7fc518ea';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:202', 2, false),array('function', 'metadata', 'print:202', 2, false),array('function', 'stylesheet', 'print:202', 2, false),array('function', 'content', 'print:202', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_add62f1b324fe32984a9399b7fc518ea_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('add62f1b324fe32984a9399b7fc518ea','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_add62f1b324fe32984a9399b7fc518ea_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('add62f1b324fe32984a9399b7fc518ea','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_add62f1b324fe32984a9399b7fc518ea_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('add62f1b324fe32984a9399b7fc518ea','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_add62f1b324fe32984a9399b7fc518ea_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('add62f1b324fe32984a9399b7fc518ea','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
