<?php /* Smarty version 2.6.25, created on 2013-03-24 23:11:57
         compiled from print:97 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C0^C0E^C0E4677D%%print%3A97.inc'] = '1d636ad470768b2e64187e932211b1e5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:97', 2, false),array('function', 'metadata', 'print:97', 2, false),array('function', 'stylesheet', 'print:97', 2, false),array('function', 'content', 'print:97', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1d636ad470768b2e64187e932211b1e5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d636ad470768b2e64187e932211b1e5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1d636ad470768b2e64187e932211b1e5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d636ad470768b2e64187e932211b1e5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1d636ad470768b2e64187e932211b1e5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d636ad470768b2e64187e932211b1e5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1d636ad470768b2e64187e932211b1e5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d636ad470768b2e64187e932211b1e5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
