<?php /* Smarty version 2.6.25, created on 2013-03-22 03:53:48
         compiled from print:180 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%53^532^53247BB0%%print%3A180.inc'] = 'eebe50b1940682edb5f686add9575c5a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:180', 2, false),array('function', 'metadata', 'print:180', 2, false),array('function', 'stylesheet', 'print:180', 2, false),array('function', 'content', 'print:180', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_eebe50b1940682edb5f686add9575c5a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eebe50b1940682edb5f686add9575c5a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_eebe50b1940682edb5f686add9575c5a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eebe50b1940682edb5f686add9575c5a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_eebe50b1940682edb5f686add9575c5a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eebe50b1940682edb5f686add9575c5a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_eebe50b1940682edb5f686add9575c5a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('eebe50b1940682edb5f686add9575c5a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
