<?php /* Smarty version 2.6.25, created on 2013-03-07 16:43:23
         compiled from print:240 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%FD^FDD^FDD78AE5%%print%3A240.inc'] = '22d49e224b99de7ec095b213d3672fb2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:240', 2, false),array('function', 'metadata', 'print:240', 2, false),array('function', 'stylesheet', 'print:240', 2, false),array('function', 'content', 'print:240', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_22d49e224b99de7ec095b213d3672fb2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('22d49e224b99de7ec095b213d3672fb2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_22d49e224b99de7ec095b213d3672fb2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('22d49e224b99de7ec095b213d3672fb2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_22d49e224b99de7ec095b213d3672fb2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('22d49e224b99de7ec095b213d3672fb2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_22d49e224b99de7ec095b213d3672fb2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('22d49e224b99de7ec095b213d3672fb2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
