<?php /* Smarty version 2.6.25, created on 2013-03-23 13:41:09
         compiled from print:220 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AB^AB8^AB8D2D63%%print%3A220.inc'] = '2fd72e8c52765ebbf3c39281758976f9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:220', 2, false),array('function', 'metadata', 'print:220', 2, false),array('function', 'stylesheet', 'print:220', 2, false),array('function', 'content', 'print:220', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2fd72e8c52765ebbf3c39281758976f9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fd72e8c52765ebbf3c39281758976f9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2fd72e8c52765ebbf3c39281758976f9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fd72e8c52765ebbf3c39281758976f9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2fd72e8c52765ebbf3c39281758976f9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fd72e8c52765ebbf3c39281758976f9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2fd72e8c52765ebbf3c39281758976f9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fd72e8c52765ebbf3c39281758976f9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
