<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:46
         compiled from print:77 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5E^5E6^5E674AF3%%print%3A77.inc'] = '68274df3c8c9f8feed54ca3a78b666e4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:77', 2, false),array('function', 'metadata', 'print:77', 2, false),array('function', 'stylesheet', 'print:77', 2, false),array('function', 'content', 'print:77', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_68274df3c8c9f8feed54ca3a78b666e4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68274df3c8c9f8feed54ca3a78b666e4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_68274df3c8c9f8feed54ca3a78b666e4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68274df3c8c9f8feed54ca3a78b666e4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_68274df3c8c9f8feed54ca3a78b666e4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68274df3c8c9f8feed54ca3a78b666e4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_68274df3c8c9f8feed54ca3a78b666e4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68274df3c8c9f8feed54ca3a78b666e4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
