<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:51
         compiled from print:112 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%6C^6CE^6CE8A1D5%%print%3A112.inc'] = '47892dbe0530d0893759dea8c853959e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:112', 2, false),array('function', 'metadata', 'print:112', 2, false),array('function', 'stylesheet', 'print:112', 2, false),array('function', 'content', 'print:112', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_47892dbe0530d0893759dea8c853959e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('47892dbe0530d0893759dea8c853959e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_47892dbe0530d0893759dea8c853959e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('47892dbe0530d0893759dea8c853959e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_47892dbe0530d0893759dea8c853959e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('47892dbe0530d0893759dea8c853959e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_47892dbe0530d0893759dea8c853959e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('47892dbe0530d0893759dea8c853959e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
