<?php /* Smarty version 2.6.25, created on 2013-03-23 13:37:53
         compiled from print:236 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5B^5BF^5BF5B917%%print%3A236.inc'] = '5c83ca1764ce98e33b7ba6e82fab18bc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:236', 2, false),array('function', 'metadata', 'print:236', 2, false),array('function', 'stylesheet', 'print:236', 2, false),array('function', 'content', 'print:236', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5c83ca1764ce98e33b7ba6e82fab18bc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c83ca1764ce98e33b7ba6e82fab18bc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5c83ca1764ce98e33b7ba6e82fab18bc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c83ca1764ce98e33b7ba6e82fab18bc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5c83ca1764ce98e33b7ba6e82fab18bc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c83ca1764ce98e33b7ba6e82fab18bc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5c83ca1764ce98e33b7ba6e82fab18bc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c83ca1764ce98e33b7ba6e82fab18bc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
