<?php /* Smarty version 2.6.25, created on 2013-03-21 07:13:00
         compiled from print:169 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B4^B47^B47BEE9A%%print%3A169.inc'] = 'ed38e7dd70885407375f6b88bf149384';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:169', 2, false),array('function', 'metadata', 'print:169', 2, false),array('function', 'stylesheet', 'print:169', 2, false),array('function', 'content', 'print:169', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ed38e7dd70885407375f6b88bf149384_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed38e7dd70885407375f6b88bf149384','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ed38e7dd70885407375f6b88bf149384_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed38e7dd70885407375f6b88bf149384','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ed38e7dd70885407375f6b88bf149384_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed38e7dd70885407375f6b88bf149384','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ed38e7dd70885407375f6b88bf149384_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed38e7dd70885407375f6b88bf149384','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
