<?php /* Smarty version 2.6.25, created on 2013-03-23 08:01:01
         compiled from print:149 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%86^864^864D8C18%%print%3A149.inc'] = '2fbd22963f28402ba8262bbc338f04e5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:149', 2, false),array('function', 'metadata', 'print:149', 2, false),array('function', 'stylesheet', 'print:149', 2, false),array('function', 'content', 'print:149', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2fbd22963f28402ba8262bbc338f04e5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fbd22963f28402ba8262bbc338f04e5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2fbd22963f28402ba8262bbc338f04e5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fbd22963f28402ba8262bbc338f04e5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2fbd22963f28402ba8262bbc338f04e5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fbd22963f28402ba8262bbc338f04e5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2fbd22963f28402ba8262bbc338f04e5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fbd22963f28402ba8262bbc338f04e5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
