<?php /* Smarty version 2.6.25, created on 2013-03-23 16:55:25
         compiled from print:170 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D4^D4B^D4BC677F%%print%3A170.inc'] = '050c6ab40d328d53ba349fdcad07cf5d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:170', 2, false),array('function', 'metadata', 'print:170', 2, false),array('function', 'stylesheet', 'print:170', 2, false),array('function', 'content', 'print:170', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_050c6ab40d328d53ba349fdcad07cf5d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050c6ab40d328d53ba349fdcad07cf5d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_050c6ab40d328d53ba349fdcad07cf5d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050c6ab40d328d53ba349fdcad07cf5d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_050c6ab40d328d53ba349fdcad07cf5d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050c6ab40d328d53ba349fdcad07cf5d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_050c6ab40d328d53ba349fdcad07cf5d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050c6ab40d328d53ba349fdcad07cf5d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
