<?php /* Smarty version 2.6.25, created on 2013-03-23 13:37:07
         compiled from print:247 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%63^63B^63B31F46%%print%3A247.inc'] = '97a422d6d80e6c6d4497429d5f0a90b4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:247', 2, false),array('function', 'metadata', 'print:247', 2, false),array('function', 'stylesheet', 'print:247', 2, false),array('function', 'content', 'print:247', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_97a422d6d80e6c6d4497429d5f0a90b4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97a422d6d80e6c6d4497429d5f0a90b4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_97a422d6d80e6c6d4497429d5f0a90b4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97a422d6d80e6c6d4497429d5f0a90b4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_97a422d6d80e6c6d4497429d5f0a90b4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97a422d6d80e6c6d4497429d5f0a90b4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_97a422d6d80e6c6d4497429d5f0a90b4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97a422d6d80e6c6d4497429d5f0a90b4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
