<?php /* Smarty version 2.6.25, created on 2013-03-23 13:33:48
         compiled from print:289 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%28^28B^28BE7D4D%%print%3A289.inc'] = '7f5a1ecf3ef3f82f65427a963321ee9b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:289', 2, false),array('function', 'metadata', 'print:289', 2, false),array('function', 'stylesheet', 'print:289', 2, false),array('function', 'content', 'print:289', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7f5a1ecf3ef3f82f65427a963321ee9b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f5a1ecf3ef3f82f65427a963321ee9b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7f5a1ecf3ef3f82f65427a963321ee9b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f5a1ecf3ef3f82f65427a963321ee9b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7f5a1ecf3ef3f82f65427a963321ee9b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f5a1ecf3ef3f82f65427a963321ee9b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7f5a1ecf3ef3f82f65427a963321ee9b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f5a1ecf3ef3f82f65427a963321ee9b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
