<?php /* Smarty version 2.6.25, created on 2013-03-20 12:01:01
         compiled from print:319 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F8^F8B^F8BEAC33%%print%3A319.inc'] = '84b4905f083bdf981c7bb5c5bbadb4af';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:319', 2, false),array('function', 'metadata', 'print:319', 2, false),array('function', 'stylesheet', 'print:319', 2, false),array('function', 'content', 'print:319', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_84b4905f083bdf981c7bb5c5bbadb4af_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84b4905f083bdf981c7bb5c5bbadb4af','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_84b4905f083bdf981c7bb5c5bbadb4af_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84b4905f083bdf981c7bb5c5bbadb4af','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_84b4905f083bdf981c7bb5c5bbadb4af_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84b4905f083bdf981c7bb5c5bbadb4af','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_84b4905f083bdf981c7bb5c5bbadb4af_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84b4905f083bdf981c7bb5c5bbadb4af','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
