<?php /* Smarty version 2.6.25, created on 2013-03-23 00:19:13
         compiled from print:291 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%3F^3F7^3F7EC43E%%print%3A291.inc'] = '9ff399f08e5eae48b3bfeff90260dd37';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:291', 2, false),array('function', 'metadata', 'print:291', 2, false),array('function', 'stylesheet', 'print:291', 2, false),array('function', 'content', 'print:291', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9ff399f08e5eae48b3bfeff90260dd37_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ff399f08e5eae48b3bfeff90260dd37','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9ff399f08e5eae48b3bfeff90260dd37_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ff399f08e5eae48b3bfeff90260dd37','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9ff399f08e5eae48b3bfeff90260dd37_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ff399f08e5eae48b3bfeff90260dd37','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9ff399f08e5eae48b3bfeff90260dd37_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9ff399f08e5eae48b3bfeff90260dd37','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
