<?php /* Smarty version 2.6.25, created on 2013-03-23 13:23:22
         compiled from print:330 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B3^B35^B3547615%%print%3A330.inc'] = '88a659c48ae4d6768f69ca5717dcf65f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:330', 2, false),array('function', 'metadata', 'print:330', 2, false),array('function', 'stylesheet', 'print:330', 2, false),array('function', 'content', 'print:330', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_88a659c48ae4d6768f69ca5717dcf65f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88a659c48ae4d6768f69ca5717dcf65f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_88a659c48ae4d6768f69ca5717dcf65f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88a659c48ae4d6768f69ca5717dcf65f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_88a659c48ae4d6768f69ca5717dcf65f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88a659c48ae4d6768f69ca5717dcf65f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_88a659c48ae4d6768f69ca5717dcf65f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88a659c48ae4d6768f69ca5717dcf65f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
