<?php /* Smarty version 2.6.25, created on 2013-03-24 19:55:28
         compiled from print:197 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%D4^D45^D45BDF52%%print%3A197.inc'] = 'd178298ae5e62c16064b058e62b411f5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:197', 2, false),array('function', 'metadata', 'print:197', 2, false),array('function', 'stylesheet', 'print:197', 2, false),array('function', 'content', 'print:197', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d178298ae5e62c16064b058e62b411f5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d178298ae5e62c16064b058e62b411f5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d178298ae5e62c16064b058e62b411f5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d178298ae5e62c16064b058e62b411f5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d178298ae5e62c16064b058e62b411f5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d178298ae5e62c16064b058e62b411f5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d178298ae5e62c16064b058e62b411f5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d178298ae5e62c16064b058e62b411f5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
