<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:50
         compiled from print:256 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%0D^0DA^0DAF1E91%%print%3A256.inc'] = '4376e2145d22cf9426077b2e3b67a370';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:256', 2, false),array('function', 'metadata', 'print:256', 2, false),array('function', 'stylesheet', 'print:256', 2, false),array('function', 'content', 'print:256', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4376e2145d22cf9426077b2e3b67a370_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4376e2145d22cf9426077b2e3b67a370','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4376e2145d22cf9426077b2e3b67a370_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4376e2145d22cf9426077b2e3b67a370','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4376e2145d22cf9426077b2e3b67a370_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4376e2145d22cf9426077b2e3b67a370','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4376e2145d22cf9426077b2e3b67a370_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4376e2145d22cf9426077b2e3b67a370','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
