<?php /* Smarty version 2.6.25, created on 2013-03-25 05:11:33
         compiled from print:189 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%2A^2AF^2AF8C314%%print%3A189.inc'] = '62225a1a1c613319c33098ac8a36932f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:189', 2, false),array('function', 'metadata', 'print:189', 2, false),array('function', 'stylesheet', 'print:189', 2, false),array('function', 'content', 'print:189', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_62225a1a1c613319c33098ac8a36932f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62225a1a1c613319c33098ac8a36932f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_62225a1a1c613319c33098ac8a36932f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62225a1a1c613319c33098ac8a36932f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_62225a1a1c613319c33098ac8a36932f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62225a1a1c613319c33098ac8a36932f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_62225a1a1c613319c33098ac8a36932f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62225a1a1c613319c33098ac8a36932f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
