<?php /* Smarty version 2.6.25, created on 2013-03-23 14:53:21
         compiled from print:343 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%65^651^651CB168%%print%3A343.inc'] = '7e25eac7ebbe6f55d5e09e5c5893dff6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:343', 2, false),array('function', 'metadata', 'print:343', 2, false),array('function', 'stylesheet', 'print:343', 2, false),array('function', 'content', 'print:343', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7e25eac7ebbe6f55d5e09e5c5893dff6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e25eac7ebbe6f55d5e09e5c5893dff6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7e25eac7ebbe6f55d5e09e5c5893dff6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e25eac7ebbe6f55d5e09e5c5893dff6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7e25eac7ebbe6f55d5e09e5c5893dff6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e25eac7ebbe6f55d5e09e5c5893dff6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7e25eac7ebbe6f55d5e09e5c5893dff6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e25eac7ebbe6f55d5e09e5c5893dff6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
