<?php /* Smarty version 2.6.25, created on 2013-03-23 13:38:01
         compiled from print:159 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%9F^9F5^9F56BD59%%print%3A159.inc'] = 'f0644664b9765996f9e05c66a22a2686';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:159', 2, false),array('function', 'metadata', 'print:159', 2, false),array('function', 'stylesheet', 'print:159', 2, false),array('function', 'content', 'print:159', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f0644664b9765996f9e05c66a22a2686_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0644664b9765996f9e05c66a22a2686','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f0644664b9765996f9e05c66a22a2686_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0644664b9765996f9e05c66a22a2686','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f0644664b9765996f9e05c66a22a2686_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0644664b9765996f9e05c66a22a2686','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f0644664b9765996f9e05c66a22a2686_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0644664b9765996f9e05c66a22a2686','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
