<?php /* Smarty version 2.6.25, created on 2013-03-20 12:00:44
         compiled from print:315 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F1^F10^F108E018%%print%3A315.inc'] = 'b8b83c5be92c4ffd6525f83359b08a2a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:315', 2, false),array('function', 'metadata', 'print:315', 2, false),array('function', 'stylesheet', 'print:315', 2, false),array('function', 'content', 'print:315', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b8b83c5be92c4ffd6525f83359b08a2a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8b83c5be92c4ffd6525f83359b08a2a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b8b83c5be92c4ffd6525f83359b08a2a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8b83c5be92c4ffd6525f83359b08a2a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b8b83c5be92c4ffd6525f83359b08a2a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8b83c5be92c4ffd6525f83359b08a2a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b8b83c5be92c4ffd6525f83359b08a2a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8b83c5be92c4ffd6525f83359b08a2a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
