<?php /* Smarty version 2.6.25, created on 2013-03-22 01:39:21
         compiled from print:82 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A9^A99^A995A2B3%%print%3A82.inc'] = '160e2c6cb47e1173214230334a635c4b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:82', 2, false),array('function', 'metadata', 'print:82', 2, false),array('function', 'stylesheet', 'print:82', 2, false),array('function', 'content', 'print:82', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_160e2c6cb47e1173214230334a635c4b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('160e2c6cb47e1173214230334a635c4b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_160e2c6cb47e1173214230334a635c4b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('160e2c6cb47e1173214230334a635c4b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_160e2c6cb47e1173214230334a635c4b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('160e2c6cb47e1173214230334a635c4b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_160e2c6cb47e1173214230334a635c4b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('160e2c6cb47e1173214230334a635c4b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
