<?php /* Smarty version 2.6.25, created on 2013-03-24 13:57:49
         compiled from print:328 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A4^A49^A494CF66%%print%3A328.inc'] = '5f8626eb28c0dd593af35c841169a892';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:328', 2, false),array('function', 'metadata', 'print:328', 2, false),array('function', 'stylesheet', 'print:328', 2, false),array('function', 'content', 'print:328', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5f8626eb28c0dd593af35c841169a892_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f8626eb28c0dd593af35c841169a892','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5f8626eb28c0dd593af35c841169a892_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f8626eb28c0dd593af35c841169a892','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5f8626eb28c0dd593af35c841169a892_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f8626eb28c0dd593af35c841169a892','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5f8626eb28c0dd593af35c841169a892_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f8626eb28c0dd593af35c841169a892','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
