<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:36
         compiled from print:217 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%1E^1EC^1EC4EB03%%print%3A217.inc'] = '9cd5a3098b2ca0e8f924be3cff135970';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:217', 2, false),array('function', 'metadata', 'print:217', 2, false),array('function', 'stylesheet', 'print:217', 2, false),array('function', 'content', 'print:217', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9cd5a3098b2ca0e8f924be3cff135970_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9cd5a3098b2ca0e8f924be3cff135970','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9cd5a3098b2ca0e8f924be3cff135970_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9cd5a3098b2ca0e8f924be3cff135970','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9cd5a3098b2ca0e8f924be3cff135970_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9cd5a3098b2ca0e8f924be3cff135970','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9cd5a3098b2ca0e8f924be3cff135970_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9cd5a3098b2ca0e8f924be3cff135970','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
