<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:52
         compiled from print:285 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%21^210^21083166%%print%3A285.inc'] = '68a31b3049f30d0f745985508b8622eb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:285', 2, false),array('function', 'metadata', 'print:285', 2, false),array('function', 'stylesheet', 'print:285', 2, false),array('function', 'content', 'print:285', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_68a31b3049f30d0f745985508b8622eb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68a31b3049f30d0f745985508b8622eb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_68a31b3049f30d0f745985508b8622eb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68a31b3049f30d0f745985508b8622eb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_68a31b3049f30d0f745985508b8622eb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68a31b3049f30d0f745985508b8622eb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_68a31b3049f30d0f745985508b8622eb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68a31b3049f30d0f745985508b8622eb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
