<?php /* Smarty version 2.6.25, created on 2013-03-23 18:26:58
         compiled from print:122 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%47^47C^47C5F216%%print%3A122.inc'] = 'e52810f5fcba3e0fda17dd9d8a417180';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:122', 2, false),array('function', 'metadata', 'print:122', 2, false),array('function', 'stylesheet', 'print:122', 2, false),array('function', 'content', 'print:122', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e52810f5fcba3e0fda17dd9d8a417180_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e52810f5fcba3e0fda17dd9d8a417180','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e52810f5fcba3e0fda17dd9d8a417180_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e52810f5fcba3e0fda17dd9d8a417180','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e52810f5fcba3e0fda17dd9d8a417180_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e52810f5fcba3e0fda17dd9d8a417180','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e52810f5fcba3e0fda17dd9d8a417180_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e52810f5fcba3e0fda17dd9d8a417180','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
