<?php /* Smarty version 2.6.25, created on 2013-03-25 01:38:48
         compiled from print:339 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CA^CA8^CA88CEB1%%print%3A339.inc'] = 'c3c720d85f5f09d8dab6df12f2e2057d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:339', 2, false),array('function', 'metadata', 'print:339', 2, false),array('function', 'stylesheet', 'print:339', 2, false),array('function', 'content', 'print:339', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c3c720d85f5f09d8dab6df12f2e2057d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3c720d85f5f09d8dab6df12f2e2057d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c3c720d85f5f09d8dab6df12f2e2057d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3c720d85f5f09d8dab6df12f2e2057d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c3c720d85f5f09d8dab6df12f2e2057d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3c720d85f5f09d8dab6df12f2e2057d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c3c720d85f5f09d8dab6df12f2e2057d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3c720d85f5f09d8dab6df12f2e2057d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
