<?php /* Smarty version 2.6.25, created on 2013-03-22 01:13:15
         compiled from print:183 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%CA^CA2^CA2D2A0A%%print%3A183.inc'] = 'ebac3e6c66cfc99ded099d57ed991029';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:183', 2, false),array('function', 'metadata', 'print:183', 2, false),array('function', 'stylesheet', 'print:183', 2, false),array('function', 'content', 'print:183', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ebac3e6c66cfc99ded099d57ed991029_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebac3e6c66cfc99ded099d57ed991029','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ebac3e6c66cfc99ded099d57ed991029_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebac3e6c66cfc99ded099d57ed991029','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ebac3e6c66cfc99ded099d57ed991029_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebac3e6c66cfc99ded099d57ed991029','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ebac3e6c66cfc99ded099d57ed991029_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebac3e6c66cfc99ded099d57ed991029','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
