<?php /* Smarty version 2.6.25, created on 2013-03-25 02:00:31
         compiled from print:110 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%82^82E^82E6C0F9%%print%3A110.inc'] = '271f3e0227d8187fac0e34a87edfc4f0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:110', 2, false),array('function', 'metadata', 'print:110', 2, false),array('function', 'stylesheet', 'print:110', 2, false),array('function', 'content', 'print:110', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_271f3e0227d8187fac0e34a87edfc4f0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('271f3e0227d8187fac0e34a87edfc4f0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_271f3e0227d8187fac0e34a87edfc4f0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('271f3e0227d8187fac0e34a87edfc4f0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_271f3e0227d8187fac0e34a87edfc4f0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('271f3e0227d8187fac0e34a87edfc4f0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_271f3e0227d8187fac0e34a87edfc4f0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('271f3e0227d8187fac0e34a87edfc4f0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
