<?php /* Smarty version 2.6.25, created on 2013-03-22 08:23:35
         compiled from print:340 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%FC^FC1^FC15E0D2%%print%3A340.inc'] = '3242d0d15fab8a6282fac0acd450bd3c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:340', 2, false),array('function', 'metadata', 'print:340', 2, false),array('function', 'stylesheet', 'print:340', 2, false),array('function', 'content', 'print:340', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3242d0d15fab8a6282fac0acd450bd3c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3242d0d15fab8a6282fac0acd450bd3c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3242d0d15fab8a6282fac0acd450bd3c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3242d0d15fab8a6282fac0acd450bd3c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3242d0d15fab8a6282fac0acd450bd3c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3242d0d15fab8a6282fac0acd450bd3c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3242d0d15fab8a6282fac0acd450bd3c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3242d0d15fab8a6282fac0acd450bd3c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
