<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:19
         compiled from print:67 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%47^477^477C7BB2%%print%3A67.inc'] = '4d4bf4d304e50165acfef0b7d9e5f95e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:67', 2, false),array('function', 'metadata', 'print:67', 2, false),array('function', 'stylesheet', 'print:67', 2, false),array('function', 'content', 'print:67', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4d4bf4d304e50165acfef0b7d9e5f95e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d4bf4d304e50165acfef0b7d9e5f95e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4d4bf4d304e50165acfef0b7d9e5f95e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d4bf4d304e50165acfef0b7d9e5f95e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4d4bf4d304e50165acfef0b7d9e5f95e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d4bf4d304e50165acfef0b7d9e5f95e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4d4bf4d304e50165acfef0b7d9e5f95e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d4bf4d304e50165acfef0b7d9e5f95e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
