<?php /* Smarty version 2.6.25, created on 2013-03-22 01:14:00
         compiled from print:300 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%98^987^987925D6%%print%3A300.inc'] = '7541f92188f6826a4696581253e477ce';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:300', 2, false),array('function', 'metadata', 'print:300', 2, false),array('function', 'stylesheet', 'print:300', 2, false),array('function', 'content', 'print:300', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7541f92188f6826a4696581253e477ce_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7541f92188f6826a4696581253e477ce','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7541f92188f6826a4696581253e477ce_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7541f92188f6826a4696581253e477ce','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7541f92188f6826a4696581253e477ce_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7541f92188f6826a4696581253e477ce','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7541f92188f6826a4696581253e477ce_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7541f92188f6826a4696581253e477ce','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
