<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:41
         compiled from print:322 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%44^444^44412678%%print%3A322.inc'] = 'be11e5e684345a4c7f2040195bdc21ad';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:322', 2, false),array('function', 'metadata', 'print:322', 2, false),array('function', 'stylesheet', 'print:322', 2, false),array('function', 'content', 'print:322', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_be11e5e684345a4c7f2040195bdc21ad_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be11e5e684345a4c7f2040195bdc21ad','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_be11e5e684345a4c7f2040195bdc21ad_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be11e5e684345a4c7f2040195bdc21ad','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_be11e5e684345a4c7f2040195bdc21ad_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be11e5e684345a4c7f2040195bdc21ad','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_be11e5e684345a4c7f2040195bdc21ad_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be11e5e684345a4c7f2040195bdc21ad','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
