<?php /* Smarty version 2.6.25, created on 2013-03-23 13:39:04
         compiled from print:231 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C5^C59^C5912CB4%%print%3A231.inc'] = '1406c6320ba11a10e07df03b960552fc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:231', 2, false),array('function', 'metadata', 'print:231', 2, false),array('function', 'stylesheet', 'print:231', 2, false),array('function', 'content', 'print:231', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1406c6320ba11a10e07df03b960552fc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1406c6320ba11a10e07df03b960552fc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1406c6320ba11a10e07df03b960552fc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1406c6320ba11a10e07df03b960552fc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1406c6320ba11a10e07df03b960552fc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1406c6320ba11a10e07df03b960552fc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1406c6320ba11a10e07df03b960552fc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1406c6320ba11a10e07df03b960552fc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
