<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:35
         compiled from print:224 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AC^ACE^ACE0E97A%%print%3A224.inc'] = 'a6e7eb729c39478ca5f7d27a362ef328';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:224', 2, false),array('function', 'metadata', 'print:224', 2, false),array('function', 'stylesheet', 'print:224', 2, false),array('function', 'content', 'print:224', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a6e7eb729c39478ca5f7d27a362ef328_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e7eb729c39478ca5f7d27a362ef328','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a6e7eb729c39478ca5f7d27a362ef328_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e7eb729c39478ca5f7d27a362ef328','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a6e7eb729c39478ca5f7d27a362ef328_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e7eb729c39478ca5f7d27a362ef328','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a6e7eb729c39478ca5f7d27a362ef328_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e7eb729c39478ca5f7d27a362ef328','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
