<?php /* Smarty version 2.6.25, created on 2013-03-22 07:49:00
         compiled from print:126 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%40^40A^40A8360F%%print%3A126.inc'] = '2221803a8ff17672eef935ff297ab99c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:126', 2, false),array('function', 'metadata', 'print:126', 2, false),array('function', 'stylesheet', 'print:126', 2, false),array('function', 'content', 'print:126', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2221803a8ff17672eef935ff297ab99c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2221803a8ff17672eef935ff297ab99c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2221803a8ff17672eef935ff297ab99c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2221803a8ff17672eef935ff297ab99c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2221803a8ff17672eef935ff297ab99c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2221803a8ff17672eef935ff297ab99c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2221803a8ff17672eef935ff297ab99c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2221803a8ff17672eef935ff297ab99c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
