<?php /* Smarty version 2.6.25, created on 2013-03-25 10:08:55
         compiled from print:321 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%DD^DD4^DD4877C2%%print%3A321.inc'] = '97d54b8ab3bc6ef08d9d8d145e05ba44';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:321', 2, false),array('function', 'metadata', 'print:321', 2, false),array('function', 'stylesheet', 'print:321', 2, false),array('function', 'content', 'print:321', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_97d54b8ab3bc6ef08d9d8d145e05ba44_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97d54b8ab3bc6ef08d9d8d145e05ba44','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_97d54b8ab3bc6ef08d9d8d145e05ba44_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97d54b8ab3bc6ef08d9d8d145e05ba44','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_97d54b8ab3bc6ef08d9d8d145e05ba44_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97d54b8ab3bc6ef08d9d8d145e05ba44','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_97d54b8ab3bc6ef08d9d8d145e05ba44_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('97d54b8ab3bc6ef08d9d8d145e05ba44','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
