<?php /* Smarty version 2.6.25, created on 2013-03-25 03:49:26
         compiled from print:345 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%8C^8C7^8C7F145D%%print%3A345.inc'] = 'faedd0ba2a34de797b9d49293fa35068';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:345', 2, false),array('function', 'metadata', 'print:345', 2, false),array('function', 'stylesheet', 'print:345', 2, false),array('function', 'content', 'print:345', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_faedd0ba2a34de797b9d49293fa35068_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faedd0ba2a34de797b9d49293fa35068','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_faedd0ba2a34de797b9d49293fa35068_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faedd0ba2a34de797b9d49293fa35068','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_faedd0ba2a34de797b9d49293fa35068_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faedd0ba2a34de797b9d49293fa35068','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_faedd0ba2a34de797b9d49293fa35068_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('faedd0ba2a34de797b9d49293fa35068','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
