<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:51
         compiled from print:320 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%AA^AA4^AA4F4754%%print%3A320.inc'] = 'ac5dbf973c43fb60c0134ee87eaee7ce';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:320', 2, false),array('function', 'metadata', 'print:320', 2, false),array('function', 'stylesheet', 'print:320', 2, false),array('function', 'content', 'print:320', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ac5dbf973c43fb60c0134ee87eaee7ce_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac5dbf973c43fb60c0134ee87eaee7ce','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ac5dbf973c43fb60c0134ee87eaee7ce_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac5dbf973c43fb60c0134ee87eaee7ce','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ac5dbf973c43fb60c0134ee87eaee7ce_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac5dbf973c43fb60c0134ee87eaee7ce','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ac5dbf973c43fb60c0134ee87eaee7ce_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac5dbf973c43fb60c0134ee87eaee7ce','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
