<?php /* Smarty version 2.6.25, created on 2013-03-23 13:23:23
         compiled from print:317 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%1F^1F0^1F068134%%print%3A317.inc'] = '48ae2ab575be51f3a982b6c7f687dbc2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:317', 2, false),array('function', 'metadata', 'print:317', 2, false),array('function', 'stylesheet', 'print:317', 2, false),array('function', 'content', 'print:317', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_48ae2ab575be51f3a982b6c7f687dbc2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ae2ab575be51f3a982b6c7f687dbc2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_48ae2ab575be51f3a982b6c7f687dbc2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ae2ab575be51f3a982b6c7f687dbc2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_48ae2ab575be51f3a982b6c7f687dbc2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ae2ab575be51f3a982b6c7f687dbc2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_48ae2ab575be51f3a982b6c7f687dbc2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ae2ab575be51f3a982b6c7f687dbc2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
