<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:58
         compiled from print:131 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C7^C7D^C7D792ED%%print%3A131.inc'] = '002d04ba204182b881c29857d84b6267';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:131', 2, false),array('function', 'metadata', 'print:131', 2, false),array('function', 'stylesheet', 'print:131', 2, false),array('function', 'content', 'print:131', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_002d04ba204182b881c29857d84b6267_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('002d04ba204182b881c29857d84b6267','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_002d04ba204182b881c29857d84b6267_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('002d04ba204182b881c29857d84b6267','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_002d04ba204182b881c29857d84b6267_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('002d04ba204182b881c29857d84b6267','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_002d04ba204182b881c29857d84b6267_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('002d04ba204182b881c29857d84b6267','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
