<?php /* Smarty version 2.6.25, created on 2013-03-24 03:21:40
         compiled from print:192 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A4^A43^A4312BDD%%print%3A192.inc'] = 'b2e16e0aea01671dc834034f45c0222c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:192', 2, false),array('function', 'metadata', 'print:192', 2, false),array('function', 'stylesheet', 'print:192', 2, false),array('function', 'content', 'print:192', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b2e16e0aea01671dc834034f45c0222c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2e16e0aea01671dc834034f45c0222c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b2e16e0aea01671dc834034f45c0222c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2e16e0aea01671dc834034f45c0222c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b2e16e0aea01671dc834034f45c0222c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2e16e0aea01671dc834034f45c0222c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b2e16e0aea01671dc834034f45c0222c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2e16e0aea01671dc834034f45c0222c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
