<?php /* Smarty version 2.6.25, created on 2013-03-25 09:43:41
         compiled from print:171 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%A3^A3B^A3BB57E9%%print%3A171.inc'] = 'a9111649ad7cd5f65534d1493bfdd299';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:171', 2, false),array('function', 'metadata', 'print:171', 2, false),array('function', 'stylesheet', 'print:171', 2, false),array('function', 'content', 'print:171', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a9111649ad7cd5f65534d1493bfdd299_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a9111649ad7cd5f65534d1493bfdd299','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a9111649ad7cd5f65534d1493bfdd299_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a9111649ad7cd5f65534d1493bfdd299','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a9111649ad7cd5f65534d1493bfdd299_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a9111649ad7cd5f65534d1493bfdd299','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a9111649ad7cd5f65534d1493bfdd299_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a9111649ad7cd5f65534d1493bfdd299','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
