<?php /* Smarty version 2.6.25, created on 2013-03-25 03:59:31
         compiled from print:186 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%BA^BA4^BA47DE85%%print%3A186.inc'] = 'f58962d93351bac7c7a131c910167357';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:186', 2, false),array('function', 'metadata', 'print:186', 2, false),array('function', 'stylesheet', 'print:186', 2, false),array('function', 'content', 'print:186', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f58962d93351bac7c7a131c910167357_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f58962d93351bac7c7a131c910167357','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f58962d93351bac7c7a131c910167357_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f58962d93351bac7c7a131c910167357','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f58962d93351bac7c7a131c910167357_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f58962d93351bac7c7a131c910167357','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f58962d93351bac7c7a131c910167357_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f58962d93351bac7c7a131c910167357','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
