<?php /* Smarty version 2.6.25, created on 2013-03-21 07:13:01
         compiled from print:190 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%4A^4A3^4A3F4AF1%%print%3A190.inc'] = '9732f45ac19ed36d053828da285dc5e1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:190', 2, false),array('function', 'metadata', 'print:190', 2, false),array('function', 'stylesheet', 'print:190', 2, false),array('function', 'content', 'print:190', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9732f45ac19ed36d053828da285dc5e1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9732f45ac19ed36d053828da285dc5e1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9732f45ac19ed36d053828da285dc5e1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9732f45ac19ed36d053828da285dc5e1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9732f45ac19ed36d053828da285dc5e1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9732f45ac19ed36d053828da285dc5e1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9732f45ac19ed36d053828da285dc5e1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9732f45ac19ed36d053828da285dc5e1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
