<?php /* Smarty version 2.6.25, created on 2013-03-21 07:11:40
         compiled from print:62 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%37^371^37168F3D%%print%3A62.inc'] = '1c29fb35e424ab5447143ebe0305c259';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:62', 2, false),array('function', 'metadata', 'print:62', 2, false),array('function', 'stylesheet', 'print:62', 2, false),array('function', 'content', 'print:62', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1c29fb35e424ab5447143ebe0305c259_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1c29fb35e424ab5447143ebe0305c259','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1c29fb35e424ab5447143ebe0305c259_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1c29fb35e424ab5447143ebe0305c259','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1c29fb35e424ab5447143ebe0305c259_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1c29fb35e424ab5447143ebe0305c259','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1c29fb35e424ab5447143ebe0305c259_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1c29fb35e424ab5447143ebe0305c259','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
