<?php /* Smarty version 2.6.25, created on 2013-03-22 18:15:06
         compiled from print:332 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%5D^5D5^5D5A1739%%print%3A332.inc'] = 'f448d88549f2961f20787cd7cbca76ff';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:332', 2, false),array('function', 'metadata', 'print:332', 2, false),array('function', 'stylesheet', 'print:332', 2, false),array('function', 'content', 'print:332', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f448d88549f2961f20787cd7cbca76ff_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f448d88549f2961f20787cd7cbca76ff','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f448d88549f2961f20787cd7cbca76ff_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f448d88549f2961f20787cd7cbca76ff','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f448d88549f2961f20787cd7cbca76ff_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f448d88549f2961f20787cd7cbca76ff','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f448d88549f2961f20787cd7cbca76ff_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f448d88549f2961f20787cd7cbca76ff','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
