<?php /* Smarty version 2.6.25, created on 2013-03-25 05:48:11
         compiled from print:130 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B0^B0D^B0D0A27B%%print%3A130.inc'] = 'f63598040cea9cb493ab060c0af374c8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:130', 2, false),array('function', 'metadata', 'print:130', 2, false),array('function', 'stylesheet', 'print:130', 2, false),array('function', 'content', 'print:130', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f63598040cea9cb493ab060c0af374c8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f63598040cea9cb493ab060c0af374c8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f63598040cea9cb493ab060c0af374c8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f63598040cea9cb493ab060c0af374c8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f63598040cea9cb493ab060c0af374c8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f63598040cea9cb493ab060c0af374c8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f63598040cea9cb493ab060c0af374c8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f63598040cea9cb493ab060c0af374c8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
