<?php /* Smarty version 2.6.25, created on 2013-03-25 08:08:30
         compiled from print:252 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%0A^0AC^0AC2DA88%%print%3A252.inc'] = '1aa944e428135934049132f5e7caf53a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:252', 2, false),array('function', 'metadata', 'print:252', 2, false),array('function', 'stylesheet', 'print:252', 2, false),array('function', 'content', 'print:252', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1aa944e428135934049132f5e7caf53a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1aa944e428135934049132f5e7caf53a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1aa944e428135934049132f5e7caf53a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1aa944e428135934049132f5e7caf53a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1aa944e428135934049132f5e7caf53a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1aa944e428135934049132f5e7caf53a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1aa944e428135934049132f5e7caf53a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1aa944e428135934049132f5e7caf53a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
