<?php /* Smarty version 2.6.25, created on 2013-03-23 13:40:10
         compiled from print:225 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%DB^DBE^DBE7D9EC%%print%3A225.inc'] = 'be2adfc406e934edac49babfd4a28ec0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:225', 2, false),array('function', 'metadata', 'print:225', 2, false),array('function', 'stylesheet', 'print:225', 2, false),array('function', 'content', 'print:225', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_be2adfc406e934edac49babfd4a28ec0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be2adfc406e934edac49babfd4a28ec0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_be2adfc406e934edac49babfd4a28ec0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be2adfc406e934edac49babfd4a28ec0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_be2adfc406e934edac49babfd4a28ec0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be2adfc406e934edac49babfd4a28ec0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_be2adfc406e934edac49babfd4a28ec0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be2adfc406e934edac49babfd4a28ec0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
