<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:47
         compiled from print:102 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%75^75F^75F39094%%print%3A102.inc'] = '88f426750298adfb283ee6e869374139';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:102', 2, false),array('function', 'metadata', 'print:102', 2, false),array('function', 'stylesheet', 'print:102', 2, false),array('function', 'content', 'print:102', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_88f426750298adfb283ee6e869374139_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88f426750298adfb283ee6e869374139','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_88f426750298adfb283ee6e869374139_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88f426750298adfb283ee6e869374139','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_88f426750298adfb283ee6e869374139_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88f426750298adfb283ee6e869374139','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_88f426750298adfb283ee6e869374139_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88f426750298adfb283ee6e869374139','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
