<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:59
         compiled from print:135 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%C0^C0B^C0BA56F4%%print%3A135.inc'] = '0efeea9bc84610cbd9422825fb2d00c1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:135', 2, false),array('function', 'metadata', 'print:135', 2, false),array('function', 'stylesheet', 'print:135', 2, false),array('function', 'content', 'print:135', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0efeea9bc84610cbd9422825fb2d00c1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0efeea9bc84610cbd9422825fb2d00c1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0efeea9bc84610cbd9422825fb2d00c1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0efeea9bc84610cbd9422825fb2d00c1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0efeea9bc84610cbd9422825fb2d00c1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0efeea9bc84610cbd9422825fb2d00c1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0efeea9bc84610cbd9422825fb2d00c1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0efeea9bc84610cbd9422825fb2d00c1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
