<?php /* Smarty version 2.6.25, created on 2013-03-25 07:41:59
         compiled from print:136 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%59^59B^59B3074E%%print%3A136.inc'] = '12edea838a45db506fa655b728f2c355';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:136', 2, false),array('function', 'metadata', 'print:136', 2, false),array('function', 'stylesheet', 'print:136', 2, false),array('function', 'content', 'print:136', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_12edea838a45db506fa655b728f2c355_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('12edea838a45db506fa655b728f2c355','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_12edea838a45db506fa655b728f2c355_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('12edea838a45db506fa655b728f2c355','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_12edea838a45db506fa655b728f2c355_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('12edea838a45db506fa655b728f2c355','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_12edea838a45db506fa655b728f2c355_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('12edea838a45db506fa655b728f2c355','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
