<?php /* Smarty version 2.6.25, created on 2013-03-23 13:33:48
         compiled from print:286 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%B8^B80^B80160DC%%print%3A286.inc'] = 'f8aef36c5d88dac950a4390585982716';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:286', 2, false),array('function', 'metadata', 'print:286', 2, false),array('function', 'stylesheet', 'print:286', 2, false),array('function', 'content', 'print:286', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f8aef36c5d88dac950a4390585982716_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f8aef36c5d88dac950a4390585982716','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f8aef36c5d88dac950a4390585982716_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f8aef36c5d88dac950a4390585982716','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f8aef36c5d88dac950a4390585982716_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f8aef36c5d88dac950a4390585982716','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f8aef36c5d88dac950a4390585982716_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f8aef36c5d88dac950a4390585982716','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
