<?php /* Smarty version 2.6.25, created on 2013-03-23 13:31:14
         compiled from print:303 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%01^017^0170746C%%print%3A303.inc'] = '0dfb3c1f19ff63779c6ba8f17e7a21af';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:303', 2, false),array('function', 'metadata', 'print:303', 2, false),array('function', 'stylesheet', 'print:303', 2, false),array('function', 'content', 'print:303', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0dfb3c1f19ff63779c6ba8f17e7a21af_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0dfb3c1f19ff63779c6ba8f17e7a21af','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0dfb3c1f19ff63779c6ba8f17e7a21af_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0dfb3c1f19ff63779c6ba8f17e7a21af','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0dfb3c1f19ff63779c6ba8f17e7a21af_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0dfb3c1f19ff63779c6ba8f17e7a21af','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0dfb3c1f19ff63779c6ba8f17e7a21af_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0dfb3c1f19ff63779c6ba8f17e7a21af','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
