<?php /* Smarty version 2.6.25, created on 2013-03-15 22:44:10
         compiled from print:306 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%71^711^711A80E3%%print%3A306.inc'] = 'e4042614e31ead31725240329eee5303';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:306', 2, false),array('function', 'metadata', 'print:306', 2, false),array('function', 'stylesheet', 'print:306', 2, false),array('function', 'content', 'print:306', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e4042614e31ead31725240329eee5303_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4042614e31ead31725240329eee5303','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e4042614e31ead31725240329eee5303_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4042614e31ead31725240329eee5303','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e4042614e31ead31725240329eee5303_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4042614e31ead31725240329eee5303','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e4042614e31ead31725240329eee5303_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4042614e31ead31725240329eee5303','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
