<?php /* Smarty version 2.6.25, created on 2013-03-21 07:12:50
         compiled from print:111 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/23^%%F5^F5E^F5E1F06F%%print%3A111.inc'] = '4ab4bf513f1539f054ad1448978e0018';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:111', 2, false),array('function', 'metadata', 'print:111', 2, false),array('function', 'stylesheet', 'print:111', 2, false),array('function', 'content', 'print:111', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4ab4bf513f1539f054ad1448978e0018_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4ab4bf513f1539f054ad1448978e0018','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4ab4bf513f1539f054ad1448978e0018_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4ab4bf513f1539f054ad1448978e0018','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4ab4bf513f1539f054ad1448978e0018_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4ab4bf513f1539f054ad1448978e0018','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4ab4bf513f1539f054ad1448978e0018_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4ab4bf513f1539f054ad1448978e0018','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
