<?php /* Smarty version 2.6.25, created on 2012-06-19 02:02:06
         compiled from print:308 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%96^96A^96A2ADE4%%print%3A308.inc'] = '59855cb259be250b16708571e3dbbb08';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:308', 2, false),array('function', 'metadata', 'print:308', 2, false),array('function', 'stylesheet', 'print:308', 2, false),array('function', 'content', 'print:308', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_59855cb259be250b16708571e3dbbb08_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59855cb259be250b16708571e3dbbb08','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_59855cb259be250b16708571e3dbbb08_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59855cb259be250b16708571e3dbbb08','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_59855cb259be250b16708571e3dbbb08_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59855cb259be250b16708571e3dbbb08','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_59855cb259be250b16708571e3dbbb08_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59855cb259be250b16708571e3dbbb08','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
