<?php /* Smarty version 2.6.25, created on 2012-06-13 13:16:28
         compiled from print:74 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%C7^C76^C76E1B49%%print%3A74.inc'] = '538aee4a9dbb25568dee9769e20013d6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:74', 2, false),array('function', 'metadata', 'print:74', 2, false),array('function', 'stylesheet', 'print:74', 2, false),array('function', 'content', 'print:74', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_538aee4a9dbb25568dee9769e20013d6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('538aee4a9dbb25568dee9769e20013d6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_538aee4a9dbb25568dee9769e20013d6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('538aee4a9dbb25568dee9769e20013d6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_538aee4a9dbb25568dee9769e20013d6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('538aee4a9dbb25568dee9769e20013d6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_538aee4a9dbb25568dee9769e20013d6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('538aee4a9dbb25568dee9769e20013d6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
