<?php /* Smarty version 2.6.25, created on 2012-06-10 22:28:23
         compiled from print:171 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A3^A3B^A3BB57E9%%print%3A171.inc'] = '9fff85209e8b8b8084cbe898efd67629';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:171', 2, false),array('function', 'metadata', 'print:171', 2, false),array('function', 'stylesheet', 'print:171', 2, false),array('function', 'content', 'print:171', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9fff85209e8b8b8084cbe898efd67629_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9fff85209e8b8b8084cbe898efd67629','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9fff85209e8b8b8084cbe898efd67629_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9fff85209e8b8b8084cbe898efd67629','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9fff85209e8b8b8084cbe898efd67629_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9fff85209e8b8b8084cbe898efd67629','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9fff85209e8b8b8084cbe898efd67629_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9fff85209e8b8b8084cbe898efd67629','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
