<?php /* Smarty version 2.6.25, created on 2012-06-10 21:57:01
         compiled from print:78 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%CE^CED^CED85762%%print%3A78.inc'] = '91393d9f8e78dc9cc648946d1c2f191c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:78', 2, false),array('function', 'metadata', 'print:78', 2, false),array('function', 'stylesheet', 'print:78', 2, false),array('function', 'content', 'print:78', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_91393d9f8e78dc9cc648946d1c2f191c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('91393d9f8e78dc9cc648946d1c2f191c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_91393d9f8e78dc9cc648946d1c2f191c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('91393d9f8e78dc9cc648946d1c2f191c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_91393d9f8e78dc9cc648946d1c2f191c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('91393d9f8e78dc9cc648946d1c2f191c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_91393d9f8e78dc9cc648946d1c2f191c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('91393d9f8e78dc9cc648946d1c2f191c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
