<?php /* Smarty version 2.6.25, created on 2012-06-19 02:43:17
         compiled from print:153 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%7F^7F8^7F835447%%print%3A153.inc'] = 'ef3c23b2f4d29363b14ad957894f68c4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:153', 2, false),array('function', 'metadata', 'print:153', 2, false),array('function', 'stylesheet', 'print:153', 2, false),array('function', 'content', 'print:153', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef3c23b2f4d29363b14ad957894f68c4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef3c23b2f4d29363b14ad957894f68c4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ef3c23b2f4d29363b14ad957894f68c4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef3c23b2f4d29363b14ad957894f68c4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ef3c23b2f4d29363b14ad957894f68c4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef3c23b2f4d29363b14ad957894f68c4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ef3c23b2f4d29363b14ad957894f68c4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef3c23b2f4d29363b14ad957894f68c4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
