<?php /* Smarty version 2.6.25, created on 2012-06-10 22:04:05
         compiled from print:93 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%C7^C78^C789A364%%print%3A93.inc'] = '8c6c08154e6dccbbaec9fb05fde9caa9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:93', 2, false),array('function', 'metadata', 'print:93', 2, false),array('function', 'stylesheet', 'print:93', 2, false),array('function', 'content', 'print:93', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8c6c08154e6dccbbaec9fb05fde9caa9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c6c08154e6dccbbaec9fb05fde9caa9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8c6c08154e6dccbbaec9fb05fde9caa9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c6c08154e6dccbbaec9fb05fde9caa9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8c6c08154e6dccbbaec9fb05fde9caa9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c6c08154e6dccbbaec9fb05fde9caa9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8c6c08154e6dccbbaec9fb05fde9caa9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c6c08154e6dccbbaec9fb05fde9caa9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
