<?php /* Smarty version 2.6.25, created on 2012-06-10 22:40:11
         compiled from print:251 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%93^93C^93CB8B32%%print%3A251.inc'] = '8dfd4b5b9babd7488e48a1a1e9006130';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:251', 2, false),array('function', 'metadata', 'print:251', 2, false),array('function', 'stylesheet', 'print:251', 2, false),array('function', 'content', 'print:251', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8dfd4b5b9babd7488e48a1a1e9006130_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dfd4b5b9babd7488e48a1a1e9006130','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8dfd4b5b9babd7488e48a1a1e9006130_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dfd4b5b9babd7488e48a1a1e9006130','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8dfd4b5b9babd7488e48a1a1e9006130_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dfd4b5b9babd7488e48a1a1e9006130','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8dfd4b5b9babd7488e48a1a1e9006130_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8dfd4b5b9babd7488e48a1a1e9006130','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
