<?php /* Smarty version 2.6.25, created on 2012-06-19 02:37:42
         compiled from print:148 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%F1^F14^F14ABC8E%%print%3A148.inc'] = 'adef6e8fbd74c6ae30924e44d62684b9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:148', 2, false),array('function', 'metadata', 'print:148', 2, false),array('function', 'stylesheet', 'print:148', 2, false),array('function', 'content', 'print:148', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_adef6e8fbd74c6ae30924e44d62684b9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('adef6e8fbd74c6ae30924e44d62684b9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_adef6e8fbd74c6ae30924e44d62684b9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('adef6e8fbd74c6ae30924e44d62684b9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_adef6e8fbd74c6ae30924e44d62684b9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('adef6e8fbd74c6ae30924e44d62684b9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_adef6e8fbd74c6ae30924e44d62684b9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('adef6e8fbd74c6ae30924e44d62684b9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
