<?php /* Smarty version 2.6.25, created on 2012-06-11 10:40:40
         compiled from print:70 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%C0^C00^C003DF50%%print%3A70.inc'] = 'b0573f2e96982593fe6220fb8e160446';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:70', 2, false),array('function', 'metadata', 'print:70', 2, false),array('function', 'stylesheet', 'print:70', 2, false),array('function', 'content', 'print:70', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0573f2e96982593fe6220fb8e160446_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0573f2e96982593fe6220fb8e160446','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0573f2e96982593fe6220fb8e160446_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0573f2e96982593fe6220fb8e160446','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0573f2e96982593fe6220fb8e160446_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0573f2e96982593fe6220fb8e160446','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0573f2e96982593fe6220fb8e160446_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0573f2e96982593fe6220fb8e160446','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
