<?php /* Smarty version 2.6.25, created on 2012-06-16 22:39:30
         compiled from print:150 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%E6^E68^E68A05FD%%print%3A150.inc'] = 'c1dc266d74faef191a26e0d8a7617c97';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:150', 2, false),array('function', 'metadata', 'print:150', 2, false),array('function', 'stylesheet', 'print:150', 2, false),array('function', 'content', 'print:150', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c1dc266d74faef191a26e0d8a7617c97_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1dc266d74faef191a26e0d8a7617c97','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c1dc266d74faef191a26e0d8a7617c97_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1dc266d74faef191a26e0d8a7617c97','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c1dc266d74faef191a26e0d8a7617c97_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1dc266d74faef191a26e0d8a7617c97','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c1dc266d74faef191a26e0d8a7617c97_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1dc266d74faef191a26e0d8a7617c97','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
