<?php /* Smarty version 2.6.25, created on 2012-06-10 22:50:46
         compiled from print:192 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A4^A43^A4312BDD%%print%3A192.inc'] = '745637a2a1b6449c4351bce1c5e0c98d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:192', 2, false),array('function', 'metadata', 'print:192', 2, false),array('function', 'stylesheet', 'print:192', 2, false),array('function', 'content', 'print:192', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_745637a2a1b6449c4351bce1c5e0c98d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('745637a2a1b6449c4351bce1c5e0c98d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_745637a2a1b6449c4351bce1c5e0c98d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('745637a2a1b6449c4351bce1c5e0c98d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_745637a2a1b6449c4351bce1c5e0c98d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('745637a2a1b6449c4351bce1c5e0c98d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_745637a2a1b6449c4351bce1c5e0c98d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('745637a2a1b6449c4351bce1c5e0c98d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
