<?php /* Smarty version 2.6.25, created on 2012-06-11 10:46:07
         compiled from print:197 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%D4^D45^D45BDF52%%print%3A197.inc'] = '547c3db1d044d49460fea11a023af222';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:197', 2, false),array('function', 'metadata', 'print:197', 2, false),array('function', 'stylesheet', 'print:197', 2, false),array('function', 'content', 'print:197', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_547c3db1d044d49460fea11a023af222_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('547c3db1d044d49460fea11a023af222','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_547c3db1d044d49460fea11a023af222_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('547c3db1d044d49460fea11a023af222','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_547c3db1d044d49460fea11a023af222_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('547c3db1d044d49460fea11a023af222','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_547c3db1d044d49460fea11a023af222_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('547c3db1d044d49460fea11a023af222','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
