<?php /* Smarty version 2.6.25, created on 2012-06-10 22:16:59
         compiled from print:300 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%98^987^987925D6%%print%3A300.inc'] = '4e8ead3489e3b6822a1680dbf893bfd0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:300', 2, false),array('function', 'metadata', 'print:300', 2, false),array('function', 'stylesheet', 'print:300', 2, false),array('function', 'content', 'print:300', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4e8ead3489e3b6822a1680dbf893bfd0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4e8ead3489e3b6822a1680dbf893bfd0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4e8ead3489e3b6822a1680dbf893bfd0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4e8ead3489e3b6822a1680dbf893bfd0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4e8ead3489e3b6822a1680dbf893bfd0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4e8ead3489e3b6822a1680dbf893bfd0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4e8ead3489e3b6822a1680dbf893bfd0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4e8ead3489e3b6822a1680dbf893bfd0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
