<?php /* Smarty version 2.6.25, created on 2012-06-19 07:08:27
         compiled from print:84 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%40^40F^40F60786%%print%3A84.inc'] = 'effccfa1813f6fe05e6f82cbee592e52';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:84', 2, false),array('function', 'metadata', 'print:84', 2, false),array('function', 'stylesheet', 'print:84', 2, false),array('function', 'content', 'print:84', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_effccfa1813f6fe05e6f82cbee592e52_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('effccfa1813f6fe05e6f82cbee592e52','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_effccfa1813f6fe05e6f82cbee592e52_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('effccfa1813f6fe05e6f82cbee592e52','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_effccfa1813f6fe05e6f82cbee592e52_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('effccfa1813f6fe05e6f82cbee592e52','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_effccfa1813f6fe05e6f82cbee592e52_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('effccfa1813f6fe05e6f82cbee592e52','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
