<?php /* Smarty version 2.6.25, created on 2012-06-10 22:50:25
         compiled from print:160 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%CD^CDA^CDA7563E%%print%3A160.inc'] = '45d835a2613aecc862cccb2e6470949b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:160', 2, false),array('function', 'metadata', 'print:160', 2, false),array('function', 'stylesheet', 'print:160', 2, false),array('function', 'content', 'print:160', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_45d835a2613aecc862cccb2e6470949b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('45d835a2613aecc862cccb2e6470949b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_45d835a2613aecc862cccb2e6470949b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('45d835a2613aecc862cccb2e6470949b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_45d835a2613aecc862cccb2e6470949b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('45d835a2613aecc862cccb2e6470949b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_45d835a2613aecc862cccb2e6470949b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('45d835a2613aecc862cccb2e6470949b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
