<?php /* Smarty version 2.6.25, created on 2012-06-19 02:58:14
         compiled from print:224 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%AC^ACE^ACE0E97A%%print%3A224.inc'] = '57a73edc57edcf1c5f1e6653e52fe250';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:224', 2, false),array('function', 'metadata', 'print:224', 2, false),array('function', 'stylesheet', 'print:224', 2, false),array('function', 'content', 'print:224', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_57a73edc57edcf1c5f1e6653e52fe250_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57a73edc57edcf1c5f1e6653e52fe250','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_57a73edc57edcf1c5f1e6653e52fe250_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57a73edc57edcf1c5f1e6653e52fe250','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_57a73edc57edcf1c5f1e6653e52fe250_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57a73edc57edcf1c5f1e6653e52fe250','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_57a73edc57edcf1c5f1e6653e52fe250_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57a73edc57edcf1c5f1e6653e52fe250','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
