<?php /* Smarty version 2.6.25, created on 2012-06-10 22:11:40
         compiled from print:179 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%AD^AD6^AD60DFDB%%print%3A179.inc'] = '3c50fccca3f9f89e6e6b8201e8a75ed6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:179', 2, false),array('function', 'metadata', 'print:179', 2, false),array('function', 'stylesheet', 'print:179', 2, false),array('function', 'content', 'print:179', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3c50fccca3f9f89e6e6b8201e8a75ed6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c50fccca3f9f89e6e6b8201e8a75ed6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3c50fccca3f9f89e6e6b8201e8a75ed6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c50fccca3f9f89e6e6b8201e8a75ed6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3c50fccca3f9f89e6e6b8201e8a75ed6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c50fccca3f9f89e6e6b8201e8a75ed6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3c50fccca3f9f89e6e6b8201e8a75ed6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c50fccca3f9f89e6e6b8201e8a75ed6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
