<?php /* Smarty version 2.6.25, created on 2012-06-11 11:08:15
         compiled from print:312 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%6F^6F6^6F6C75BB%%print%3A312.inc'] = '5f3e6115c69dc0b08f5e1e63ce1f1b73';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:312', 2, false),array('function', 'metadata', 'print:312', 2, false),array('function', 'stylesheet', 'print:312', 2, false),array('function', 'content', 'print:312', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5f3e6115c69dc0b08f5e1e63ce1f1b73_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f3e6115c69dc0b08f5e1e63ce1f1b73','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5f3e6115c69dc0b08f5e1e63ce1f1b73_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f3e6115c69dc0b08f5e1e63ce1f1b73','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5f3e6115c69dc0b08f5e1e63ce1f1b73_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f3e6115c69dc0b08f5e1e63ce1f1b73','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5f3e6115c69dc0b08f5e1e63ce1f1b73_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f3e6115c69dc0b08f5e1e63ce1f1b73','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
