<?php /* Smarty version 2.6.25, created on 2012-06-17 10:17:38
         compiled from print:314 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%86^860^860FD08E%%print%3A314.inc'] = '3f6fee9081a589dbb6c97d67b1b7e086';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:314', 2, false),array('function', 'metadata', 'print:314', 2, false),array('function', 'stylesheet', 'print:314', 2, false),array('function', 'content', 'print:314', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3f6fee9081a589dbb6c97d67b1b7e086_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f6fee9081a589dbb6c97d67b1b7e086','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3f6fee9081a589dbb6c97d67b1b7e086_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f6fee9081a589dbb6c97d67b1b7e086','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3f6fee9081a589dbb6c97d67b1b7e086_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f6fee9081a589dbb6c97d67b1b7e086','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3f6fee9081a589dbb6c97d67b1b7e086_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f6fee9081a589dbb6c97d67b1b7e086','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
