<?php /* Smarty version 2.6.25, created on 2012-06-19 02:47:21
         compiled from print:173 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%4D^4DB^4DB536C5%%print%3A173.inc'] = '9631286f2a83247d2dbeb975e7f7fb4d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:173', 2, false),array('function', 'metadata', 'print:173', 2, false),array('function', 'stylesheet', 'print:173', 2, false),array('function', 'content', 'print:173', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9631286f2a83247d2dbeb975e7f7fb4d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9631286f2a83247d2dbeb975e7f7fb4d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9631286f2a83247d2dbeb975e7f7fb4d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9631286f2a83247d2dbeb975e7f7fb4d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9631286f2a83247d2dbeb975e7f7fb4d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9631286f2a83247d2dbeb975e7f7fb4d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9631286f2a83247d2dbeb975e7f7fb4d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9631286f2a83247d2dbeb975e7f7fb4d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
