<?php /* Smarty version 2.6.25, created on 2012-06-10 22:40:14
         compiled from print:198 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%44^44E^44E4C2C3%%print%3A198.inc'] = '5358cedad055ece2caddb490c9db0908';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:198', 2, false),array('function', 'metadata', 'print:198', 2, false),array('function', 'stylesheet', 'print:198', 2, false),array('function', 'content', 'print:198', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5358cedad055ece2caddb490c9db0908_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5358cedad055ece2caddb490c9db0908','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5358cedad055ece2caddb490c9db0908_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5358cedad055ece2caddb490c9db0908','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5358cedad055ece2caddb490c9db0908_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5358cedad055ece2caddb490c9db0908','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5358cedad055ece2caddb490c9db0908_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5358cedad055ece2caddb490c9db0908','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
