<?php /* Smarty version 2.6.25, created on 2012-06-10 21:33:01
         compiled from print:65 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A9^A97^A9721A9E%%print%3A65.inc'] = 'dcacfb575a9384723c05e35b1fc7511b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:65', 2, false),array('function', 'metadata', 'print:65', 2, false),array('function', 'stylesheet', 'print:65', 2, false),array('function', 'content', 'print:65', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_dcacfb575a9384723c05e35b1fc7511b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dcacfb575a9384723c05e35b1fc7511b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_dcacfb575a9384723c05e35b1fc7511b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dcacfb575a9384723c05e35b1fc7511b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_dcacfb575a9384723c05e35b1fc7511b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dcacfb575a9384723c05e35b1fc7511b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_dcacfb575a9384723c05e35b1fc7511b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dcacfb575a9384723c05e35b1fc7511b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
