<?php /* Smarty version 2.6.25, created on 2012-06-19 05:21:15
         compiled from print:228 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A5^A55^A556A551%%print%3A228.inc'] = '1ec9caf68f5d6b2cce46d60e52723cfe';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:228', 2, false),array('function', 'metadata', 'print:228', 2, false),array('function', 'stylesheet', 'print:228', 2, false),array('function', 'content', 'print:228', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1ec9caf68f5d6b2cce46d60e52723cfe_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ec9caf68f5d6b2cce46d60e52723cfe','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1ec9caf68f5d6b2cce46d60e52723cfe_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ec9caf68f5d6b2cce46d60e52723cfe','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1ec9caf68f5d6b2cce46d60e52723cfe_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ec9caf68f5d6b2cce46d60e52723cfe','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1ec9caf68f5d6b2cce46d60e52723cfe_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ec9caf68f5d6b2cce46d60e52723cfe','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
