<?php /* Smarty version 2.6.25, created on 2012-06-19 02:50:46
         compiled from print:175 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A4^A4D^A4D693F0%%print%3A175.inc'] = '30b409d5267c007b08256be9f47de310';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:175', 2, false),array('function', 'metadata', 'print:175', 2, false),array('function', 'stylesheet', 'print:175', 2, false),array('function', 'content', 'print:175', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_30b409d5267c007b08256be9f47de310_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30b409d5267c007b08256be9f47de310','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_30b409d5267c007b08256be9f47de310_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30b409d5267c007b08256be9f47de310','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_30b409d5267c007b08256be9f47de310_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30b409d5267c007b08256be9f47de310','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_30b409d5267c007b08256be9f47de310_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('30b409d5267c007b08256be9f47de310','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
