<?php /* Smarty version 2.6.25, created on 2012-06-15 15:37:14
         compiled from print:82 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A9^A99^A995A2B3%%print%3A82.inc'] = 'bcafa10468012bb76a5d7bcb8f7c4f3a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:82', 2, false),array('function', 'metadata', 'print:82', 2, false),array('function', 'stylesheet', 'print:82', 2, false),array('function', 'content', 'print:82', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bcafa10468012bb76a5d7bcb8f7c4f3a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcafa10468012bb76a5d7bcb8f7c4f3a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bcafa10468012bb76a5d7bcb8f7c4f3a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcafa10468012bb76a5d7bcb8f7c4f3a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bcafa10468012bb76a5d7bcb8f7c4f3a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcafa10468012bb76a5d7bcb8f7c4f3a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bcafa10468012bb76a5d7bcb8f7c4f3a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bcafa10468012bb76a5d7bcb8f7c4f3a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
