<?php /* Smarty version 2.6.25, created on 2012-06-16 22:37:38
         compiled from print:146 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%16^16F^16F29189%%print%3A146.inc'] = 'b4f890dd17035271724c062b3da203ec';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:146', 2, false),array('function', 'metadata', 'print:146', 2, false),array('function', 'stylesheet', 'print:146', 2, false),array('function', 'content', 'print:146', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b4f890dd17035271724c062b3da203ec_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f890dd17035271724c062b3da203ec','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b4f890dd17035271724c062b3da203ec_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f890dd17035271724c062b3da203ec','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b4f890dd17035271724c062b3da203ec_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f890dd17035271724c062b3da203ec','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b4f890dd17035271724c062b3da203ec_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f890dd17035271724c062b3da203ec','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
