<?php /* Smarty version 2.6.25, created on 2012-06-10 21:20:14
         compiled from print:94 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%59^59E^59ED36C7%%print%3A94.inc'] = 'c0cc89c3c15c68e44bc7d617dbd1d173';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:94', 2, false),array('function', 'metadata', 'print:94', 2, false),array('function', 'stylesheet', 'print:94', 2, false),array('function', 'content', 'print:94', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c0cc89c3c15c68e44bc7d617dbd1d173_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc89c3c15c68e44bc7d617dbd1d173','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c0cc89c3c15c68e44bc7d617dbd1d173_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc89c3c15c68e44bc7d617dbd1d173','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c0cc89c3c15c68e44bc7d617dbd1d173_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc89c3c15c68e44bc7d617dbd1d173','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c0cc89c3c15c68e44bc7d617dbd1d173_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc89c3c15c68e44bc7d617dbd1d173','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
