<?php /* Smarty version 2.6.25, created on 2012-06-10 21:43:11
         compiled from print:77 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%5E^5E6^5E674AF3%%print%3A77.inc'] = '5c906086bc3fdc76e6bf8f8a4f5bd5d1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:77', 2, false),array('function', 'metadata', 'print:77', 2, false),array('function', 'stylesheet', 'print:77', 2, false),array('function', 'content', 'print:77', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5c906086bc3fdc76e6bf8f8a4f5bd5d1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c906086bc3fdc76e6bf8f8a4f5bd5d1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5c906086bc3fdc76e6bf8f8a4f5bd5d1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c906086bc3fdc76e6bf8f8a4f5bd5d1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5c906086bc3fdc76e6bf8f8a4f5bd5d1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c906086bc3fdc76e6bf8f8a4f5bd5d1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5c906086bc3fdc76e6bf8f8a4f5bd5d1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5c906086bc3fdc76e6bf8f8a4f5bd5d1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
