<?php /* Smarty version 2.6.25, created on 2012-06-19 07:08:24
         compiled from print:303 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%01^017^0170746C%%print%3A303.inc'] = '571d50cb2d31baf41c5c97cad2647504';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:303', 2, false),array('function', 'metadata', 'print:303', 2, false),array('function', 'stylesheet', 'print:303', 2, false),array('function', 'content', 'print:303', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_571d50cb2d31baf41c5c97cad2647504_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('571d50cb2d31baf41c5c97cad2647504','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_571d50cb2d31baf41c5c97cad2647504_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('571d50cb2d31baf41c5c97cad2647504','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_571d50cb2d31baf41c5c97cad2647504_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('571d50cb2d31baf41c5c97cad2647504','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_571d50cb2d31baf41c5c97cad2647504_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('571d50cb2d31baf41c5c97cad2647504','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
