<?php /* Smarty version 2.6.25, created on 2012-06-11 23:34:46
         compiled from print:319 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%F8^F8B^F8BEAC33%%print%3A319.inc'] = '63e0ba5bd9ddb2de9195b4270b9ffb53';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:319', 2, false),array('function', 'metadata', 'print:319', 2, false),array('function', 'stylesheet', 'print:319', 2, false),array('function', 'content', 'print:319', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_63e0ba5bd9ddb2de9195b4270b9ffb53_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63e0ba5bd9ddb2de9195b4270b9ffb53','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_63e0ba5bd9ddb2de9195b4270b9ffb53_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63e0ba5bd9ddb2de9195b4270b9ffb53','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_63e0ba5bd9ddb2de9195b4270b9ffb53_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63e0ba5bd9ddb2de9195b4270b9ffb53','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_63e0ba5bd9ddb2de9195b4270b9ffb53_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63e0ba5bd9ddb2de9195b4270b9ffb53','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
