<?php /* Smarty version 2.6.25, created on 2012-06-19 02:35:49
         compiled from print:147 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%61^61F^61F5A11F%%print%3A147.inc'] = '13c30f893aff8b56b0121ba29b5bbb99';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:147', 2, false),array('function', 'metadata', 'print:147', 2, false),array('function', 'stylesheet', 'print:147', 2, false),array('function', 'content', 'print:147', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_13c30f893aff8b56b0121ba29b5bbb99_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('13c30f893aff8b56b0121ba29b5bbb99','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_13c30f893aff8b56b0121ba29b5bbb99_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('13c30f893aff8b56b0121ba29b5bbb99','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_13c30f893aff8b56b0121ba29b5bbb99_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('13c30f893aff8b56b0121ba29b5bbb99','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_13c30f893aff8b56b0121ba29b5bbb99_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('13c30f893aff8b56b0121ba29b5bbb99','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
