<?php /* Smarty version 2.6.25, created on 2012-06-10 21:44:32
         compiled from print:67 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%47^477^477C7BB2%%print%3A67.inc'] = '84a6dade99c79c5e392b1674bb5dc19f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:67', 2, false),array('function', 'metadata', 'print:67', 2, false),array('function', 'stylesheet', 'print:67', 2, false),array('function', 'content', 'print:67', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_84a6dade99c79c5e392b1674bb5dc19f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84a6dade99c79c5e392b1674bb5dc19f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_84a6dade99c79c5e392b1674bb5dc19f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84a6dade99c79c5e392b1674bb5dc19f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_84a6dade99c79c5e392b1674bb5dc19f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84a6dade99c79c5e392b1674bb5dc19f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_84a6dade99c79c5e392b1674bb5dc19f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('84a6dade99c79c5e392b1674bb5dc19f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
