<?php /* Smarty version 2.6.25, created on 2012-06-17 14:16:18
         compiled from print:304 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%9F^9F1^9F14E1CF%%print%3A304.inc'] = 'a825d13141669c584f5104f37c097ff7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:304', 2, false),array('function', 'metadata', 'print:304', 2, false),array('function', 'stylesheet', 'print:304', 2, false),array('function', 'content', 'print:304', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a825d13141669c584f5104f37c097ff7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a825d13141669c584f5104f37c097ff7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a825d13141669c584f5104f37c097ff7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a825d13141669c584f5104f37c097ff7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a825d13141669c584f5104f37c097ff7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a825d13141669c584f5104f37c097ff7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a825d13141669c584f5104f37c097ff7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a825d13141669c584f5104f37c097ff7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
