<?php /* Smarty version 2.6.25, created on 2012-06-10 22:50:24
         compiled from print:238 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%BC^BC4^BC4D9410%%print%3A238.inc'] = 'c6cd8c7571599d159a26e17704e8a333';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:238', 2, false),array('function', 'metadata', 'print:238', 2, false),array('function', 'stylesheet', 'print:238', 2, false),array('function', 'content', 'print:238', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c6cd8c7571599d159a26e17704e8a333_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6cd8c7571599d159a26e17704e8a333','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c6cd8c7571599d159a26e17704e8a333_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6cd8c7571599d159a26e17704e8a333','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c6cd8c7571599d159a26e17704e8a333_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6cd8c7571599d159a26e17704e8a333','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c6cd8c7571599d159a26e17704e8a333_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6cd8c7571599d159a26e17704e8a333','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
