<?php /* Smarty version 2.6.25, created on 2012-06-19 02:54:30
         compiled from print:209 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%E0^E06^E067F745%%print%3A209.inc'] = 'd0a575af8776f04060c0d2fca32b3b22';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:209', 2, false),array('function', 'metadata', 'print:209', 2, false),array('function', 'stylesheet', 'print:209', 2, false),array('function', 'content', 'print:209', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d0a575af8776f04060c0d2fca32b3b22_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0a575af8776f04060c0d2fca32b3b22','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d0a575af8776f04060c0d2fca32b3b22_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0a575af8776f04060c0d2fca32b3b22','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d0a575af8776f04060c0d2fca32b3b22_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0a575af8776f04060c0d2fca32b3b22','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d0a575af8776f04060c0d2fca32b3b22_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0a575af8776f04060c0d2fca32b3b22','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
