<?php /* Smarty version 2.6.25, created on 2012-06-10 22:28:24
         compiled from print:227 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%35^35E^35E9B8C0%%print%3A227.inc'] = '2eeea13e19f4a6c9593ad3465d221111';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:227', 2, false),array('function', 'metadata', 'print:227', 2, false),array('function', 'stylesheet', 'print:227', 2, false),array('function', 'content', 'print:227', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2eeea13e19f4a6c9593ad3465d221111_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2eeea13e19f4a6c9593ad3465d221111','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2eeea13e19f4a6c9593ad3465d221111_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2eeea13e19f4a6c9593ad3465d221111','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2eeea13e19f4a6c9593ad3465d221111_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2eeea13e19f4a6c9593ad3465d221111','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2eeea13e19f4a6c9593ad3465d221111_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2eeea13e19f4a6c9593ad3465d221111','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
