<?php /* Smarty version 2.6.25, created on 2012-06-19 02:03:50
         compiled from print:310 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%81^816^81621497%%print%3A310.inc'] = '7107d978cf7798b69633ae2c093c0889';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:310', 2, false),array('function', 'metadata', 'print:310', 2, false),array('function', 'stylesheet', 'print:310', 2, false),array('function', 'content', 'print:310', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7107d978cf7798b69633ae2c093c0889_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7107d978cf7798b69633ae2c093c0889','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7107d978cf7798b69633ae2c093c0889_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7107d978cf7798b69633ae2c093c0889','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7107d978cf7798b69633ae2c093c0889_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7107d978cf7798b69633ae2c093c0889','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7107d978cf7798b69633ae2c093c0889_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7107d978cf7798b69633ae2c093c0889','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
