<?php /* Smarty version 2.6.25, created on 2012-06-10 21:43:09
         compiled from print:90 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%5E^5E8^5E80F2DE%%print%3A90.inc'] = 'c43d8dbd440c31d42f76a989a61a25e6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:90', 2, false),array('function', 'metadata', 'print:90', 2, false),array('function', 'stylesheet', 'print:90', 2, false),array('function', 'content', 'print:90', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c43d8dbd440c31d42f76a989a61a25e6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c43d8dbd440c31d42f76a989a61a25e6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c43d8dbd440c31d42f76a989a61a25e6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c43d8dbd440c31d42f76a989a61a25e6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c43d8dbd440c31d42f76a989a61a25e6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c43d8dbd440c31d42f76a989a61a25e6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c43d8dbd440c31d42f76a989a61a25e6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c43d8dbd440c31d42f76a989a61a25e6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
