<?php /* Smarty version 2.6.25, created on 2012-06-10 22:28:25
         compiled from print:313 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%18^186^186B452D%%print%3A313.inc'] = '62e350b33c34b6faaa319565d4e23844';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:313', 2, false),array('function', 'metadata', 'print:313', 2, false),array('function', 'stylesheet', 'print:313', 2, false),array('function', 'content', 'print:313', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_62e350b33c34b6faaa319565d4e23844_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62e350b33c34b6faaa319565d4e23844','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_62e350b33c34b6faaa319565d4e23844_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62e350b33c34b6faaa319565d4e23844','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_62e350b33c34b6faaa319565d4e23844_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62e350b33c34b6faaa319565d4e23844','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_62e350b33c34b6faaa319565d4e23844_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('62e350b33c34b6faaa319565d4e23844','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
