<?php /* Smarty version 2.6.25, created on 2012-06-19 07:30:09
         compiled from print:276 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%3F^3F9^3F997C13%%print%3A276.inc'] = 'daf3bf9c96e362e269c4e727db5342e4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:276', 2, false),array('function', 'metadata', 'print:276', 2, false),array('function', 'stylesheet', 'print:276', 2, false),array('function', 'content', 'print:276', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_daf3bf9c96e362e269c4e727db5342e4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('daf3bf9c96e362e269c4e727db5342e4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_daf3bf9c96e362e269c4e727db5342e4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('daf3bf9c96e362e269c4e727db5342e4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_daf3bf9c96e362e269c4e727db5342e4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('daf3bf9c96e362e269c4e727db5342e4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_daf3bf9c96e362e269c4e727db5342e4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('daf3bf9c96e362e269c4e727db5342e4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
