<?php /* Smarty version 2.6.25, created on 2012-06-13 23:05:20
         compiled from print:196 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A3^A35^A35CEFC4%%print%3A196.inc'] = 'c6c2b7c6fa9b6fda8813d7ab671104b2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:196', 2, false),array('function', 'metadata', 'print:196', 2, false),array('function', 'stylesheet', 'print:196', 2, false),array('function', 'content', 'print:196', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c6c2b7c6fa9b6fda8813d7ab671104b2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6c2b7c6fa9b6fda8813d7ab671104b2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c6c2b7c6fa9b6fda8813d7ab671104b2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6c2b7c6fa9b6fda8813d7ab671104b2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c6c2b7c6fa9b6fda8813d7ab671104b2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6c2b7c6fa9b6fda8813d7ab671104b2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c6c2b7c6fa9b6fda8813d7ab671104b2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c6c2b7c6fa9b6fda8813d7ab671104b2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
