<?php /* Smarty version 2.6.25, created on 2012-06-19 02:52:37
         compiled from print:203 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%00^00B^00B21E5B%%print%3A203.inc'] = 'ac8b6982003474fda1c3d3f0285bfcaf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:203', 2, false),array('function', 'metadata', 'print:203', 2, false),array('function', 'stylesheet', 'print:203', 2, false),array('function', 'content', 'print:203', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ac8b6982003474fda1c3d3f0285bfcaf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac8b6982003474fda1c3d3f0285bfcaf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ac8b6982003474fda1c3d3f0285bfcaf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac8b6982003474fda1c3d3f0285bfcaf','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ac8b6982003474fda1c3d3f0285bfcaf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac8b6982003474fda1c3d3f0285bfcaf','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ac8b6982003474fda1c3d3f0285bfcaf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ac8b6982003474fda1c3d3f0285bfcaf','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
