<?php /* Smarty version 2.6.25, created on 2012-06-19 02:41:25
         compiled from print:151 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%91^918^918D356B%%print%3A151.inc'] = 'de3c8bf1151f30f5e88d5323faf0506d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:151', 2, false),array('function', 'metadata', 'print:151', 2, false),array('function', 'stylesheet', 'print:151', 2, false),array('function', 'content', 'print:151', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_de3c8bf1151f30f5e88d5323faf0506d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de3c8bf1151f30f5e88d5323faf0506d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_de3c8bf1151f30f5e88d5323faf0506d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de3c8bf1151f30f5e88d5323faf0506d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_de3c8bf1151f30f5e88d5323faf0506d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de3c8bf1151f30f5e88d5323faf0506d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_de3c8bf1151f30f5e88d5323faf0506d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('de3c8bf1151f30f5e88d5323faf0506d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
