<?php /* Smarty version 2.6.25, created on 2012-06-10 21:43:12
         compiled from print:64 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%DE^DE7^DE752A08%%print%3A64.inc'] = '71382012c3ce8a4986b697a904b24f71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:64', 2, false),array('function', 'metadata', 'print:64', 2, false),array('function', 'stylesheet', 'print:64', 2, false),array('function', 'content', 'print:64', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_71382012c3ce8a4986b697a904b24f71_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71382012c3ce8a4986b697a904b24f71','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_71382012c3ce8a4986b697a904b24f71_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71382012c3ce8a4986b697a904b24f71','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_71382012c3ce8a4986b697a904b24f71_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71382012c3ce8a4986b697a904b24f71','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_71382012c3ce8a4986b697a904b24f71_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('71382012c3ce8a4986b697a904b24f71','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
