<?php /* Smarty version 2.6.25, created on 2012-06-19 02:00:06
         compiled from print:301 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%EF^EF7^EF7E1540%%print%3A301.inc'] = '2e4d0c6bdb652544aece004d07865e49';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:301', 2, false),array('function', 'metadata', 'print:301', 2, false),array('function', 'stylesheet', 'print:301', 2, false),array('function', 'content', 'print:301', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2e4d0c6bdb652544aece004d07865e49_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e4d0c6bdb652544aece004d07865e49','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2e4d0c6bdb652544aece004d07865e49_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e4d0c6bdb652544aece004d07865e49','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2e4d0c6bdb652544aece004d07865e49_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e4d0c6bdb652544aece004d07865e49','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2e4d0c6bdb652544aece004d07865e49_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2e4d0c6bdb652544aece004d07865e49','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
