<?php /* Smarty version 2.6.25, created on 2012-06-10 21:31:43
         compiled from print:89 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%3E^3E4^3E477B3B%%print%3A89.inc'] = '04e34e0cf2d300b1471ce8a7b0192840';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:89', 2, false),array('function', 'metadata', 'print:89', 2, false),array('function', 'stylesheet', 'print:89', 2, false),array('function', 'content', 'print:89', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_04e34e0cf2d300b1471ce8a7b0192840_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04e34e0cf2d300b1471ce8a7b0192840','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_04e34e0cf2d300b1471ce8a7b0192840_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04e34e0cf2d300b1471ce8a7b0192840','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_04e34e0cf2d300b1471ce8a7b0192840_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04e34e0cf2d300b1471ce8a7b0192840','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_04e34e0cf2d300b1471ce8a7b0192840_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04e34e0cf2d300b1471ce8a7b0192840','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
