<?php /* Smarty version 2.6.25, created on 2012-06-14 22:14:28
         compiled from print:317 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%1F^1F0^1F068134%%print%3A317.inc'] = '55719ffc8d95751449e31657fd32577e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:317', 2, false),array('function', 'metadata', 'print:317', 2, false),array('function', 'stylesheet', 'print:317', 2, false),array('function', 'content', 'print:317', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_55719ffc8d95751449e31657fd32577e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('55719ffc8d95751449e31657fd32577e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_55719ffc8d95751449e31657fd32577e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('55719ffc8d95751449e31657fd32577e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_55719ffc8d95751449e31657fd32577e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('55719ffc8d95751449e31657fd32577e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_55719ffc8d95751449e31657fd32577e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('55719ffc8d95751449e31657fd32577e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
