<?php /* Smarty version 2.6.25, created on 2012-06-10 21:31:44
         compiled from print:79 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%B9^B9D^B9DF67F4%%print%3A79.inc'] = 'ee9e74640ba3fb0775e3f0fec6697832';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:79', 2, false),array('function', 'metadata', 'print:79', 2, false),array('function', 'stylesheet', 'print:79', 2, false),array('function', 'content', 'print:79', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ee9e74640ba3fb0775e3f0fec6697832_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee9e74640ba3fb0775e3f0fec6697832','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ee9e74640ba3fb0775e3f0fec6697832_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee9e74640ba3fb0775e3f0fec6697832','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ee9e74640ba3fb0775e3f0fec6697832_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee9e74640ba3fb0775e3f0fec6697832','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ee9e74640ba3fb0775e3f0fec6697832_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee9e74640ba3fb0775e3f0fec6697832','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
