<?php /* Smarty version 2.6.25, created on 2012-06-19 02:48:54
         compiled from print:174 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%D3^D3D^D3D1A366%%print%3A174.inc'] = '629a03a5ae43a37a4c0b34686c8fce62';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:174', 2, false),array('function', 'metadata', 'print:174', 2, false),array('function', 'stylesheet', 'print:174', 2, false),array('function', 'content', 'print:174', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_629a03a5ae43a37a4c0b34686c8fce62_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('629a03a5ae43a37a4c0b34686c8fce62','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_629a03a5ae43a37a4c0b34686c8fce62_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('629a03a5ae43a37a4c0b34686c8fce62','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_629a03a5ae43a37a4c0b34686c8fce62_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('629a03a5ae43a37a4c0b34686c8fce62','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_629a03a5ae43a37a4c0b34686c8fce62_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('629a03a5ae43a37a4c0b34686c8fce62','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
