<?php /* Smarty version 2.6.25, created on 2012-06-19 02:45:10
         compiled from print:172 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%3A^3AB^3AB20653%%print%3A172.inc'] = 'e2c1003d36b681286890e395406ed8f0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:172', 2, false),array('function', 'metadata', 'print:172', 2, false),array('function', 'stylesheet', 'print:172', 2, false),array('function', 'content', 'print:172', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e2c1003d36b681286890e395406ed8f0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2c1003d36b681286890e395406ed8f0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e2c1003d36b681286890e395406ed8f0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2c1003d36b681286890e395406ed8f0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e2c1003d36b681286890e395406ed8f0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2c1003d36b681286890e395406ed8f0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e2c1003d36b681286890e395406ed8f0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2c1003d36b681286890e395406ed8f0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
