<?php /* Smarty version 2.6.25, created on 2012-06-19 02:39:34
         compiled from print:149 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%86^864^864D8C18%%print%3A149.inc'] = '31ebcfdfcf00e67a0e358fb54a66cab5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:149', 2, false),array('function', 'metadata', 'print:149', 2, false),array('function', 'stylesheet', 'print:149', 2, false),array('function', 'content', 'print:149', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_31ebcfdfcf00e67a0e358fb54a66cab5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('31ebcfdfcf00e67a0e358fb54a66cab5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_31ebcfdfcf00e67a0e358fb54a66cab5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('31ebcfdfcf00e67a0e358fb54a66cab5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_31ebcfdfcf00e67a0e358fb54a66cab5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('31ebcfdfcf00e67a0e358fb54a66cab5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_31ebcfdfcf00e67a0e358fb54a66cab5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('31ebcfdfcf00e67a0e358fb54a66cab5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
