<?php /* Smarty version 2.6.25, created on 2012-06-10 22:40:12
         compiled from print:218 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%8E^8E7^8E7BF692%%print%3A218.inc'] = 'ed1d6ec353a00269dbfd999a944b4ab6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:218', 2, false),array('function', 'metadata', 'print:218', 2, false),array('function', 'stylesheet', 'print:218', 2, false),array('function', 'content', 'print:218', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ed1d6ec353a00269dbfd999a944b4ab6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed1d6ec353a00269dbfd999a944b4ab6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ed1d6ec353a00269dbfd999a944b4ab6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed1d6ec353a00269dbfd999a944b4ab6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ed1d6ec353a00269dbfd999a944b4ab6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed1d6ec353a00269dbfd999a944b4ab6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ed1d6ec353a00269dbfd999a944b4ab6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed1d6ec353a00269dbfd999a944b4ab6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
