<?php /* Smarty version 2.6.25, created on 2012-06-16 03:49:18
         compiled from print:69 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%A0^A0C^A0C456B5%%print%3A69.inc'] = '90ad6f4f670815feeffe5a7290ea6329';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:69', 2, false),array('function', 'metadata', 'print:69', 2, false),array('function', 'stylesheet', 'print:69', 2, false),array('function', 'content', 'print:69', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_90ad6f4f670815feeffe5a7290ea6329_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90ad6f4f670815feeffe5a7290ea6329','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_90ad6f4f670815feeffe5a7290ea6329_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90ad6f4f670815feeffe5a7290ea6329','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_90ad6f4f670815feeffe5a7290ea6329_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90ad6f4f670815feeffe5a7290ea6329','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_90ad6f4f670815feeffe5a7290ea6329_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('90ad6f4f670815feeffe5a7290ea6329','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
