<?php /* Smarty version 2.6.25, created on 2012-06-15 19:01:23
         compiled from print:219 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%F9^F97^F97CC604%%print%3A219.inc'] = '8ddc4bd30fbd87f18f51b79a98d52dd5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:219', 2, false),array('function', 'metadata', 'print:219', 2, false),array('function', 'stylesheet', 'print:219', 2, false),array('function', 'content', 'print:219', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8ddc4bd30fbd87f18f51b79a98d52dd5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8ddc4bd30fbd87f18f51b79a98d52dd5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8ddc4bd30fbd87f18f51b79a98d52dd5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8ddc4bd30fbd87f18f51b79a98d52dd5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8ddc4bd30fbd87f18f51b79a98d52dd5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8ddc4bd30fbd87f18f51b79a98d52dd5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8ddc4bd30fbd87f18f51b79a98d52dd5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8ddc4bd30fbd87f18f51b79a98d52dd5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
