<?php /* Smarty version 2.6.25, created on 2012-06-16 21:59:24
         compiled from print:86 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%AE^AEF^AEF866AA%%print%3A86.inc'] = '4644696f61f0d65aa21b718045e234f5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:86', 2, false),array('function', 'metadata', 'print:86', 2, false),array('function', 'stylesheet', 'print:86', 2, false),array('function', 'content', 'print:86', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4644696f61f0d65aa21b718045e234f5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4644696f61f0d65aa21b718045e234f5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4644696f61f0d65aa21b718045e234f5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4644696f61f0d65aa21b718045e234f5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4644696f61f0d65aa21b718045e234f5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4644696f61f0d65aa21b718045e234f5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4644696f61f0d65aa21b718045e234f5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4644696f61f0d65aa21b718045e234f5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
