<?php /* Smarty version 2.6.25, created on 2012-06-19 07:30:16
         compiled from print:80 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%47^479^479BC39F%%print%3A80.inc'] = 'f48a4fbbb9e7af1cabfaaa0c545cdc20';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:80', 2, false),array('function', 'metadata', 'print:80', 2, false),array('function', 'stylesheet', 'print:80', 2, false),array('function', 'content', 'print:80', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f48a4fbbb9e7af1cabfaaa0c545cdc20_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f48a4fbbb9e7af1cabfaaa0c545cdc20','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f48a4fbbb9e7af1cabfaaa0c545cdc20_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f48a4fbbb9e7af1cabfaaa0c545cdc20','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f48a4fbbb9e7af1cabfaaa0c545cdc20_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f48a4fbbb9e7af1cabfaaa0c545cdc20','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f48a4fbbb9e7af1cabfaaa0c545cdc20_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f48a4fbbb9e7af1cabfaaa0c545cdc20','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
