<?php /* Smarty version 2.6.25, created on 2012-06-10 21:20:13
         compiled from print:76 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%29^296^29607A65%%print%3A76.inc'] = '96c84c539779ce1697335629d09e4dec';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:76', 2, false),array('function', 'metadata', 'print:76', 2, false),array('function', 'stylesheet', 'print:76', 2, false),array('function', 'content', 'print:76', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_96c84c539779ce1697335629d09e4dec_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('96c84c539779ce1697335629d09e4dec','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_96c84c539779ce1697335629d09e4dec_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('96c84c539779ce1697335629d09e4dec','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_96c84c539779ce1697335629d09e4dec_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('96c84c539779ce1697335629d09e4dec','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_96c84c539779ce1697335629d09e4dec_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('96c84c539779ce1697335629d09e4dec','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
