<?php /* Smarty version 2.6.25, created on 2012-06-10 21:20:12
         compiled from print:92 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%B0^B08^B08E93F2%%print%3A92.inc'] = '7ce771903d44eeebb5aad91c874056c2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:92', 2, false),array('function', 'metadata', 'print:92', 2, false),array('function', 'stylesheet', 'print:92', 2, false),array('function', 'content', 'print:92', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ce771903d44eeebb5aad91c874056c2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ce771903d44eeebb5aad91c874056c2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7ce771903d44eeebb5aad91c874056c2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ce771903d44eeebb5aad91c874056c2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7ce771903d44eeebb5aad91c874056c2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ce771903d44eeebb5aad91c874056c2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7ce771903d44eeebb5aad91c874056c2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ce771903d44eeebb5aad91c874056c2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
