<?php /* Smarty version 2.6.25, created on 2012-06-19 07:29:52
         compiled from print:156 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%0F^0FE^0FE9A0C8%%print%3A156.inc'] = '3c6b194200e19d11bb59fc106257e0e4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:156', 2, false),array('function', 'metadata', 'print:156', 2, false),array('function', 'stylesheet', 'print:156', 2, false),array('function', 'content', 'print:156', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3c6b194200e19d11bb59fc106257e0e4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c6b194200e19d11bb59fc106257e0e4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3c6b194200e19d11bb59fc106257e0e4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c6b194200e19d11bb59fc106257e0e4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3c6b194200e19d11bb59fc106257e0e4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c6b194200e19d11bb59fc106257e0e4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3c6b194200e19d11bb59fc106257e0e4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c6b194200e19d11bb59fc106257e0e4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
