<?php /* Smarty version 2.6.25, created on 2012-06-19 02:56:21
         compiled from print:217 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%1E^1EC^1EC4EB03%%print%3A217.inc'] = '1968045b405299f2162d4282a305bf38';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:217', 2, false),array('function', 'metadata', 'print:217', 2, false),array('function', 'stylesheet', 'print:217', 2, false),array('function', 'content', 'print:217', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1968045b405299f2162d4282a305bf38_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1968045b405299f2162d4282a305bf38','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1968045b405299f2162d4282a305bf38_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1968045b405299f2162d4282a305bf38','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1968045b405299f2162d4282a305bf38_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1968045b405299f2162d4282a305bf38','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1968045b405299f2162d4282a305bf38_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1968045b405299f2162d4282a305bf38','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
