<?php /* Smarty version 2.6.25, created on 2012-06-19 07:08:15
         compiled from print:152 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%08^088^088464D1%%print%3A152.inc'] = 'f3a003b5659d415e6095f5b06a376dbd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:152', 2, false),array('function', 'metadata', 'print:152', 2, false),array('function', 'stylesheet', 'print:152', 2, false),array('function', 'content', 'print:152', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f3a003b5659d415e6095f5b06a376dbd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3a003b5659d415e6095f5b06a376dbd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f3a003b5659d415e6095f5b06a376dbd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3a003b5659d415e6095f5b06a376dbd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f3a003b5659d415e6095f5b06a376dbd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3a003b5659d415e6095f5b06a376dbd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f3a003b5659d415e6095f5b06a376dbd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f3a003b5659d415e6095f5b06a376dbd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
