<?php /* Smarty version 2.6.25, created on 2012-06-11 21:44:07
         compiled from print:57 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%6C^6C5^6C512871%%print%3A57.inc'] = '0292154b84cf81f0e249096c01547377';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:57', 2, false),array('function', 'metadata', 'print:57', 2, false),array('function', 'stylesheet', 'print:57', 2, false),array('function', 'content', 'print:57', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0292154b84cf81f0e249096c01547377_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0292154b84cf81f0e249096c01547377','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0292154b84cf81f0e249096c01547377_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0292154b84cf81f0e249096c01547377','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0292154b84cf81f0e249096c01547377_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0292154b84cf81f0e249096c01547377','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0292154b84cf81f0e249096c01547377_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0292154b84cf81f0e249096c01547377','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
