<?php /* Smarty version 2.6.25, created on 2012-06-09 22:57:46
         compiled from print:284 */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/24^%%56^560^560F01F0%%print%3A284.inc'] = 'b034d7bbbb8717e07ae9c3488c7aed89';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:284', 2, false),array('function', 'metadata', 'print:284', 2, false),array('function', 'stylesheet', 'print:284', 2, false),array('function', 'content', 'print:284', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b034d7bbbb8717e07ae9c3488c7aed89_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b034d7bbbb8717e07ae9c3488c7aed89','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b034d7bbbb8717e07ae9c3488c7aed89_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b034d7bbbb8717e07ae9c3488c7aed89','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b034d7bbbb8717e07ae9c3488c7aed89_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b034d7bbbb8717e07ae9c3488c7aed89','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b034d7bbbb8717e07ae9c3488c7aed89_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b034d7bbbb8717e07ae9c3488c7aed89','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
