<?php /* Smarty version 2.6.25, created on 2013-03-07 11:52:23
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/255^%%70^707^707A8977%%content%3Acontent_en.inc'] = '7601a49f48f9d435ffa5f9d146e512cb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 14, false),)), $this); ?>
<?php
function _smarty_tplfunc_7601a49f48f9d435ffa5f9d146e512cb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7601a49f48f9d435ffa5f9d146e512cb','0');echo smarty_cms_function_cms_selflink(array('href' => 'Zavileyskaya'), $_smarty);
}



?>
