<?php /* Smarty version 2.6.25, created on 2013-03-07 07:42:44
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/256^%%70^707^707A8977%%content%3Acontent_en.inc'] = '6f48c475c1228c2f583f370f0efcad59';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_6f48c475c1228c2f583f370f0efcad59_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f48c475c1228c2f583f370f0efcad59','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}



?>
