<?php /* Smarty version 2.6.25, created on 2012-06-19 10:42:09
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/274^%%70^707^707A8977%%content%3Acontent_en.inc'] = '6d5511ec022e8dfca17d6b975683244e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 10, false),)), $this); ?>
<?php
function _smarty_tplfunc_6d5511ec022e8dfca17d6b975683244e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6d5511ec022e8dfca17d6b975683244e','0');echo smarty_cms_function_cms_selflink(array('href' => 'speakers'), $_smarty);
}



?>
