<?php /* Smarty version 2.6.25, created on 2012-06-09 19:31:55
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/276^%%70^707^707A8977%%content%3Acontent_en.inc'] = '1ad0646eee775e4a1f634aad55dd3e00';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_1ad0646eee775e4a1f634aad55dd3e00_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ad0646eee775e4a1f634aad55dd3e00','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}


function _smarty_tplfunc_1ad0646eee775e4a1f634aad55dd3e00_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ad0646eee775e4a1f634aad55dd3e00','1');echo smarty_cms_function_cms_selflink(array('href' => 'odintsov-vladimir'), $_smarty);
}


function _smarty_tplfunc_1ad0646eee775e4a1f634aad55dd3e00_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ad0646eee775e4a1f634aad55dd3e00','2');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_1ad0646eee775e4a1f634aad55dd3e00_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1ad0646eee775e4a1f634aad55dd3e00','3');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}



?>
