<?php /* Smarty version 2.6.25, created on 2013-03-07 13:50:17
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/283^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'b95aff614aac3e4203c1adbe43153385';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_b95aff614aac3e4203c1adbe43153385_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b95aff614aac3e4203c1adbe43153385','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhyuri'), $_smarty);
}



?>
