<?php /* Smarty version 2.6.25, created on 2013-03-08 19:49:42
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/288^%%70^707^707A8977%%content%3Acontent_en.inc'] = '802eb6fccfdee9210cb36a872a874b3f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 32, false),)), $this); ?>
<?php
function _smarty_tplfunc_802eb6fccfdee9210cb36a872a874b3f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('802eb6fccfdee9210cb36a872a874b3f','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}


function _smarty_tplfunc_802eb6fccfdee9210cb36a872a874b3f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('802eb6fccfdee9210cb36a872a874b3f','1');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_802eb6fccfdee9210cb36a872a874b3f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('802eb6fccfdee9210cb36a872a874b3f','2');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_802eb6fccfdee9210cb36a872a874b3f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('802eb6fccfdee9210cb36a872a874b3f','3');echo smarty_cms_function_cms_selflink(array('href' => 'odintsov-vladimir'), $_smarty);
}



?>
