<?php /* Smarty version 2.6.25, created on 2013-03-07 10:16:56
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/297^%%70^707^707A8977%%content%3Acontent_en.inc'] = '653544ba9c6c69e5651bf7cebf46b2b0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'startExpandCollapse', 'content:content_en', 19, false),array('function', 'stopExpandCollapse', 'content:content_en', 32, false),)), $this); ?>
<?php
function _smarty_tplfunc_653544ba9c6c69e5651bf7cebf46b2b0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('653544ba9c6c69e5651bf7cebf46b2b0','0');echo smarty_cms_function_startExpandCollapse(array('id' => 'expand1','title' => 'Подробнее о жюри'), $_smarty);
}


function _smarty_tplfunc_653544ba9c6c69e5651bf7cebf46b2b0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('653544ba9c6c69e5651bf7cebf46b2b0','1');echo smarty_cms_function_stopExpandCollapse(array(), $_smarty);
}



?>
