<?php /* Smarty version 2.6.25, created on 2013-03-16 02:28:06
         compiled from print:284 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%56^560^560F01F0%%print%3A284.inc'] = '33faaefb3ffac0d28c683381f8b78505';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:284', 2, false),array('function', 'metadata', 'print:284', 2, false),array('function', 'stylesheet', 'print:284', 2, false),array('function', 'content', 'print:284', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_33faaefb3ffac0d28c683381f8b78505_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33faaefb3ffac0d28c683381f8b78505','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_33faaefb3ffac0d28c683381f8b78505_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33faaefb3ffac0d28c683381f8b78505','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_33faaefb3ffac0d28c683381f8b78505_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33faaefb3ffac0d28c683381f8b78505','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_33faaefb3ffac0d28c683381f8b78505_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33faaefb3ffac0d28c683381f8b78505','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
