<?php /* Smarty version 2.6.25, created on 2013-03-25 06:29:36
         compiled from print:274 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%D1^D19^D1971D3F%%print%3A274.inc'] = 'b58f35d6084ca58fd570d8e51f792ea6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:274', 2, false),array('function', 'metadata', 'print:274', 2, false),array('function', 'stylesheet', 'print:274', 2, false),array('function', 'content', 'print:274', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b58f35d6084ca58fd570d8e51f792ea6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b58f35d6084ca58fd570d8e51f792ea6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b58f35d6084ca58fd570d8e51f792ea6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b58f35d6084ca58fd570d8e51f792ea6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b58f35d6084ca58fd570d8e51f792ea6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b58f35d6084ca58fd570d8e51f792ea6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b58f35d6084ca58fd570d8e51f792ea6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b58f35d6084ca58fd570d8e51f792ea6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
