<?php /* Smarty version 2.6.25, created on 2013-03-25 00:31:01
         compiled from print:288 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%5F^5FB^5FB94DDB%%print%3A288.inc'] = 'dd9e86bc586c9c5b341f3c1d668f5234';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:288', 2, false),array('function', 'metadata', 'print:288', 2, false),array('function', 'stylesheet', 'print:288', 2, false),array('function', 'content', 'print:288', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_dd9e86bc586c9c5b341f3c1d668f5234_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dd9e86bc586c9c5b341f3c1d668f5234','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_dd9e86bc586c9c5b341f3c1d668f5234_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dd9e86bc586c9c5b341f3c1d668f5234','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_dd9e86bc586c9c5b341f3c1d668f5234_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dd9e86bc586c9c5b341f3c1d668f5234','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_dd9e86bc586c9c5b341f3c1d668f5234_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dd9e86bc586c9c5b341f3c1d668f5234','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
