<?php /* Smarty version 2.6.25, created on 2013-03-24 23:11:53
         compiled from print:292 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%A6^A67^A6779584%%print%3A292.inc'] = 'a043ed6537adc1d1f04d5a952ba26eec';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:292', 2, false),array('function', 'metadata', 'print:292', 2, false),array('function', 'stylesheet', 'print:292', 2, false),array('function', 'content', 'print:292', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a043ed6537adc1d1f04d5a952ba26eec_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a043ed6537adc1d1f04d5a952ba26eec','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a043ed6537adc1d1f04d5a952ba26eec_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a043ed6537adc1d1f04d5a952ba26eec','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a043ed6537adc1d1f04d5a952ba26eec_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a043ed6537adc1d1f04d5a952ba26eec','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a043ed6537adc1d1f04d5a952ba26eec_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a043ed6537adc1d1f04d5a952ba26eec','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
