<?php /* Smarty version 2.6.25, created on 2013-03-25 07:55:17
         compiled from print:276 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%3F^3F9^3F997C13%%print%3A276.inc'] = '3621cc5c2e71f13abd999d380d618e0f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:276', 2, false),array('function', 'metadata', 'print:276', 2, false),array('function', 'stylesheet', 'print:276', 2, false),array('function', 'content', 'print:276', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3621cc5c2e71f13abd999d380d618e0f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3621cc5c2e71f13abd999d380d618e0f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3621cc5c2e71f13abd999d380d618e0f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3621cc5c2e71f13abd999d380d618e0f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3621cc5c2e71f13abd999d380d618e0f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3621cc5c2e71f13abd999d380d618e0f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3621cc5c2e71f13abd999d380d618e0f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3621cc5c2e71f13abd999d380d618e0f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
