<?php /* Smarty version 2.6.25, created on 2013-03-14 14:12:16
         compiled from print:277 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%48^489^489E4C85%%print%3A277.inc'] = '9e28dc025e546ceaa55cc8cb46b1480e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:277', 2, false),array('function', 'metadata', 'print:277', 2, false),array('function', 'stylesheet', 'print:277', 2, false),array('function', 'content', 'print:277', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9e28dc025e546ceaa55cc8cb46b1480e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e28dc025e546ceaa55cc8cb46b1480e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9e28dc025e546ceaa55cc8cb46b1480e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e28dc025e546ceaa55cc8cb46b1480e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9e28dc025e546ceaa55cc8cb46b1480e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e28dc025e546ceaa55cc8cb46b1480e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9e28dc025e546ceaa55cc8cb46b1480e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e28dc025e546ceaa55cc8cb46b1480e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
