<?php /* Smarty version 2.6.25, created on 2013-03-24 19:55:38
         compiled from print:283 */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/29^%%C8^C86^C86B9453%%print%3A283.inc'] = '27a9d7f4949c0604010618fb2e032237';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:283', 2, false),array('function', 'metadata', 'print:283', 2, false),array('function', 'stylesheet', 'print:283', 2, false),array('function', 'content', 'print:283', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_27a9d7f4949c0604010618fb2e032237_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27a9d7f4949c0604010618fb2e032237','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_27a9d7f4949c0604010618fb2e032237_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27a9d7f4949c0604010618fb2e032237','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_27a9d7f4949c0604010618fb2e032237_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27a9d7f4949c0604010618fb2e032237','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_27a9d7f4949c0604010618fb2e032237_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27a9d7f4949c0604010618fb2e032237','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
