<?php /* Smarty version 2.6.25, created on 2012-06-10 22:28:26
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/314^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'daad9862125a0d62fdf8ebcad5388e3c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 115, false),)), $this); ?>
<?php
function _smarty_tplfunc_daad9862125a0d62fdf8ebcad5388e3c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('daad9862125a0d62fdf8ebcad5388e3c','0');echo smarty_cms_function_cms_selflink(array('href' => 'fotootchet-konferentsii'), $_smarty);
}



?>
