<?php /* Smarty version 2.6.25, created on 2013-03-25 03:57:47
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/56^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ef4ac4f9c7b0a69a1957ef8464dc770f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef4ac4f9c7b0a69a1957ef8464dc770f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4ac4f9c7b0a69a1957ef8464dc770f','0');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'logout'), $_smarty);
}


function _smarty_tplfunc_ef4ac4f9c7b0a69a1957ef8464dc770f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4ac4f9c7b0a69a1957ef8464dc770f','1');echo smarty_cms_function_cms_module(array('module' => 'SelfRegistration','group' => 'registered'), $_smarty);
}



?>
