<?php /* Smarty version 2.6.25, created on 2012-06-10 21:43:12
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/64^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'e3b6294d00567f2159abab87e93f01c3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_e3b6294d00567f2159abab87e93f01c3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e3b6294d00567f2159abab87e93f01c3','0');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'logout'), $_smarty);
}


function _smarty_tplfunc_e3b6294d00567f2159abab87e93f01c3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e3b6294d00567f2159abab87e93f01c3','1');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'login'), $_smarty);
}



?>
