<?php /* Smarty version 2.6.25, created on 2013-03-07 07:55:11
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/67^%%70^707^707A8977%%content%3Acontent_en.inc'] = '3e871fdca424c8e132457ef69dd5ccb9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'contact_form', 'content:content_en', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_3e871fdca424c8e132457ef69dd5ccb9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e871fdca424c8e132457ef69dd5ccb9','0');echo smarty_cms_function_contact_form(array('email' => "o.batrakova@clubcochubey.ru",'captcha' => 'true'), $_smarty);
}



?>
