<?php /* Smarty version 2.6.25, created on 2012-06-11 10:40:41
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/70^%%70^707^707A8977%%content%3Acontent_en.inc'] = '3ab0f03b09c1db288593e7a168cb1b59';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'news', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_3ab0f03b09c1db288593e7a168cb1b59_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3ab0f03b09c1db288593e7a168cb1b59','0');echo smarty_cms_function_news(array('showarchive' => '0'), $_smarty);
}



?>
