<?php /* Smarty version 2.6.25, created on 2013-03-14 17:23:45
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/71^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'c8115b5072575c8303899404553bbf50';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'CGUserDirectory', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_c8115b5072575c8303899404553bbf50_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8115b5072575c8303899404553bbf50','0');echo $_smarty->_plugins['function']['CGUserDirectory'][0][0]->function_plugin(array('group' => 'Authorised','sortby' => "f:last_name"), $_smarty);
}



?>
