<?php /* Smarty version 2.6.25, created on 2012-06-10 21:20:13
         compiled from content:content_en */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/76^%%70^707^707A8977%%content%3Acontent_en.inc'] = '891a7baf25e7f70237de58f5f774b29a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_891a7baf25e7f70237de58f5f774b29a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('891a7baf25e7f70237de58f5f774b29a','0');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
