<?php /* Smarty version 2.6.25, created on 2013-03-07 11:45:23
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/80^%%70^707^707A8977%%content%3Acontent_en.inc'] = '152fc64163e3a8f554944fd66980c488';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 200, false),)), $this); ?>
<?php
function _smarty_tplfunc_152fc64163e3a8f554944fd66980c488_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('152fc64163e3a8f554944fd66980c488','0');echo smarty_cms_function_cms_selflink(array('href' => 'svetenkova-ekaterina-anatolevna'), $_smarty);
}



?>
