<?php /* Smarty version 2.6.25, created on 2013-03-20 15:58:12
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/86^%%70^707^707A8977%%content%3Acontent_en.inc'] = '36f72e4fa4e266d1a7c0ef42d4e1362c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','0');echo smarty_cms_function_cms_selflink(array('href' => 'ant-management'), $_smarty);
}


function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','1');echo smarty_cms_function_cms_selflink(array('href' => 'ObzorZarplat-Ru'), $_smarty);
}


function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','2');echo smarty_cms_function_cms_selflink(array('href' => 'Sokos'), $_smarty);
}


function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','3');echo smarty_cms_function_cms_selflink(array('href' => 'vakansia'), $_smarty);
}


function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','4');echo smarty_cms_function_cms_selflink(array('href' => 'obs'), $_smarty);
}


function _smarty_tplfunc_36f72e4fa4e266d1a7c0ef42d4e1362c_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36f72e4fa4e266d1a7c0ef42d4e1362c','5');echo smarty_cms_function_cms_selflink(array('href' => 'imisp'), $_smarty);
}



?>
