<?php /* Smarty version 2.6.25, created on 2013-03-07 10:06:08
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/docs/tmp/templates_c/90^%%70^707^707A8977%%content%3Acontent_en.inc'] = '178af041e08b91d3e8c7b8ee3010fd03';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_178af041e08b91d3e8c7b8ee3010fd03_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('178af041e08b91d3e8c7b8ee3010fd03','0');echo smarty_cms_function_cms_module(array('module' => 'LinkMgr','category' => 'General'), $_smarty);
}



?>
