<?php /* Smarty version 2.6.25, created on 2012-06-11 00:49:38
         compiled from module_file_tpl:MenuManager%3Bminimal_menu.tpl */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/a7ef9f80e0fe752b32d42dc8ec65a81e^%%A2^A20^A20E1116%%module_file_tpl%3AMenuManager%3Bminimal_menu.tpl.inc'] = '43e238c8b653527f5bad9420a82e2b43';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'repeat', 'module_file_tpl:MenuManager;minimal_menu.tpl', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_43e238c8b653527f5bad9420a82e2b43_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('43e238c8b653527f5bad9420a82e2b43','0');echo smarty_cms_function_repeat(array('string' => "<ul>",'times' => $_smarty->_tpl_vars['node']->depth-$_smarty->_tpl_vars['node']->prevdepth), $_smarty);
}


function _smarty_tplfunc_43e238c8b653527f5bad9420a82e2b43_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('43e238c8b653527f5bad9420a82e2b43','1');echo smarty_cms_function_repeat(array('string' => "</li></ul>",'times' => $_smarty->_tpl_vars['node']->prevdepth-$_smarty->_tpl_vars['node']->depth), $_smarty);
}


function _smarty_tplfunc_43e238c8b653527f5bad9420a82e2b43_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('43e238c8b653527f5bad9420a82e2b43','2');echo smarty_cms_function_repeat(array('string' => "</li></ul>",'times' => $_smarty->_tpl_vars['node']->depth-1), $_smarty);
}



?>
