<?php /* Smarty version 2.6.25, created on 2012-06-09 17:05:45
         compiled from module_db_tpl:News%3Bsummaryrezum */

$this->_cache_serials['/home/zarplata/clubkochubey.ru/docs/tmp/templates_c/News^%%3B^3B2^3B2F7B51%%module_db_tpl%3ANews%3Bsummaryrezum.inc'] = 'ea956b5e2d9018a84f25de43224fc193';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'supersizer', 'module_db_tpl:News;summaryrezum', 10, false),array('function', 'eval', 'module_db_tpl:News;summaryrezum', 12, false),array('modifier', 'cat', 'module_db_tpl:News;summaryrezum', 10, false),array('modifier', 'cms_date_format', 'module_db_tpl:News;summaryrezum', 18, false),array('modifier', 'strip_tags', 'module_db_tpl:News;summaryrezum', 22, false),array('modifier', 'truncate', 'module_db_tpl:News;summaryrezum', 22, false),array('modifier', 'escape', 'module_db_tpl:News;summaryrezum', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_ea956b5e2d9018a84f25de43224fc193_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ea956b5e2d9018a84f25de43224fc193','0');echo smarty_cms_function_supersizer(array('path' => ((is_array($_tmp=((is_array($_tmp=$_smarty->_tpl_vars['loc'])) ? $_smarty->_run_mod_handler('cat', true, $_tmp, '/') : smarty_modifier_cat($_tmp, '/')))) ? $_smarty->_run_mod_handler('cat', true, $_tmp, $_smarty->_tpl_vars['theFile']) : smarty_modifier_cat($_tmp, $_smarty->_tpl_vars['theFile'])),'width' => '90'), $_smarty);
}



?>
