<?php /* Smarty version 2.6.25, created on 2014-02-12 16:22:31
         compiled from tpl_body:23 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%01^013^01360D26%%tpl_body%3A23.inc'] = '3e1dda8dce66b62a377a815daff5e7d8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'anchor', 'tpl_body:23', 7, false),array('function', 'cms_selflink', 'tpl_body:23', 14, false),array('function', 'search', 'tpl_body:23', 18, false),array('function', 'menu', 'tpl_body:23', 34, false),array('function', 'NMS', 'tpl_body:23', 39, false),array('function', 'cms_module', 'tpl_body:23', 42, false),array('function', 'breadcrumbs', 'tpl_body:23', 51, false),array('function', 'oldprint', 'tpl_body:23', 52, false),array('function', 'title', 'tpl_body:23', 56, false),array('function', 'content', 'tpl_body:23', 58, false),array('function', 'global_content', 'tpl_body:23', 80, false),)), $this); ?>
<?php
function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','0');echo smarty_cms_function_anchor(array('anchor' => 'menu_vert','title' => 'Skip to navigation','accesskey' => 'n','text' => 'Skip to navigation'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','1');echo smarty_cms_function_anchor(array('anchor' => 'main','title' => 'Skip to content','accesskey' => 's','text' => 'Skip to content'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','2');echo smarty_cms_function_cms_selflink(array('dir' => 'start','text' => ($_smarty->_tpl_vars['sitename'])), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','3');echo smarty_cms_function_search(array('search_method' => 'post','resultpage' => 'search'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','4');echo smarty_cms_function_menu(array('template' => 'verticalmenu'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','5');echo $_smarty->_plugins['function']['NMS'][0][0]->function_plugin(array('mode' => 'subscribe'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','6');echo smarty_cms_function_cms_module(array('module' => 'polls'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','7');echo smarty_cms_function_breadcrumbs(array('starttext' => '','root' => 'Home','delimiter' => '&gt;'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','8');echo smarty_cms_function_oldprint(array('showbutton' => true), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','9');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','10');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','11');echo smarty_cms_function_menu(array('template' => 'minimal_menu.tpl','start_level' => '1','number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_3e1dda8dce66b62a377a815daff5e7d8_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3e1dda8dce66b62a377a815daff5e7d8','12');echo smarty_cms_function_global_content(array('name' => 'footer'), $_smarty);
}



?>
