<?php /* Smarty version 2.6.25, created on 2014-02-12 02:44:26
         compiled from tpl_body:notemplate */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%11^11A^11A30C36%%tpl_body%3Anotemplate.inc'] = '699a7dba84ff9814dc2eef412e43ba4a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'content', 'tpl_body:notemplate', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_699a7dba84ff9814dc2eef412e43ba4a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('699a7dba84ff9814dc2eef412e43ba4a','0');echo smarty_cms_function_content(array(), $_smarty);
}



?>
