<?php /* Smarty version 2.6.25, created on 2014-01-31 22:04:24
         compiled from tpl_head:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%19^194^194941AA%%tpl_head%3A22.inc'] = '70e66a35171b45df4ccd51bd3cbd4ecf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_70e66a35171b45df4ccd51bd3cbd4ecf_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70e66a35171b45df4ccd51bd3cbd4ecf','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
