<?php /* Smarty version 2.6.25, created on 2014-02-06 13:13:37
         compiled from siteprefs.tpl */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%1B^1B2^1B2DE232%%siteprefs.tpl.inc'] = '249fec6d22b46f000df357cfc4c13661';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'html_options', 'siteprefs.tpl', 25, false),)), $this); ?>
<?php
function _smarty_tplfunc_249fec6d22b46f000df357cfc4c13661_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('249fec6d22b46f000df357cfc4c13661','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['wysiwyg'],'selected' => $_smarty->_tpl_vars['frontendwysiwyg']), $_smarty);
}


function _smarty_tplfunc_249fec6d22b46f000df357cfc4c13661_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('249fec6d22b46f000df357cfc4c13661','1');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['themes'],'selected' => $_smarty->_tpl_vars['logintheme']), $_smarty);
}


function _smarty_tplfunc_249fec6d22b46f000df357cfc4c13661_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('249fec6d22b46f000df357cfc4c13661','2');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['templates'],'selected' => $_smarty->_tpl_vars['custom404template']), $_smarty);
}


function _smarty_tplfunc_249fec6d22b46f000df357cfc4c13661_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('249fec6d22b46f000df357cfc4c13661','3');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_attributes'],'selected' => $_smarty->_tpl_vars['basic_attributes']), $_smarty);
}



?>
