<?php /* Smarty version 2.6.25, created on 2014-02-12 16:22:31
         compiled from tpl_top:23 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%25^25E^25E0F81D%%tpl_top%3A23.inc'] = '1a149f6ae827b9487799c511bbb86cea';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:23', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_1a149f6ae827b9487799c511bbb86cea_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a149f6ae827b9487799c511bbb86cea','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
