<?php /* Smarty version 2.6.25, created on 2014-01-31 22:04:24
         compiled from tpl_top:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = '92c1cbb151c873404bce760f3460cebb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_92c1cbb151c873404bce760f3460cebb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('92c1cbb151c873404bce760f3460cebb','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
