<?php /* Smarty version 2.6.25, created on 2014-02-06 13:18:45
         compiled from systeminfo.tpl */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%54^54D^54D58E70%%systeminfo.tpl.inc'] = '4cd33f4e6b58e4350183ca81959ce033';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'si_lang', 'systeminfo.tpl', 3, false),array('modifier', 'default', 'systeminfo.tpl', 44, false),)), $this); ?>
<?php
function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','0');echo systeminfo_lang(array('a' => 'copy_paste_forum'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','1');echo systeminfo_lang(array('a' => 'help_systeminformation'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','2');echo systeminfo_lang(array('a' => 'cms_install_information'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','3');echo systeminfo_lang(array('a' => 'cms_version'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','4');echo systeminfo_lang(array('a' => 'installed_modules'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','5');echo systeminfo_lang(array('a' => 'config_information'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','6');echo systeminfo_lang(array('a' => 'php_information'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','7');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','8');echo systeminfo_lang(array('a' => 'server_information'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','9');echo systeminfo_lang(array('a' => $_smarty->_tpl_vars['key']), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','10');echo systeminfo_lang(array('a' => 'permission_information'), $_smarty);
}


function _smarty_tplfunc_4cd33f4e6b58e4350183ca81959ce033_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4cd33f4e6b58e4350183ca81959ce033','11');echo systeminfo_lang(array('a' => 'back'), $_smarty);
}



?>
