<?php /* Smarty version 2.6.25, created on 2014-02-13 00:34:41
         compiled from template:notemplate */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%5E^5E7^5E74AD9F%%template%3Anotemplate.inc'] = 'd6a7b987edcd31bbf668c896e2186d44';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'content', 'template:notemplate', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_d6a7b987edcd31bbf668c896e2186d44_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d6a7b987edcd31bbf668c896e2186d44','0');echo smarty_cms_function_content(array(), $_smarty);
}



?>
