<?php /* Smarty version 2.6.25, created on 2014-02-12 16:22:31
         compiled from tpl_head:23 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%6E^6E4^6E4E713C%%tpl_head%3A23.inc'] = 'b04887e24e41120e1125703fe69422b7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:23', 4, false),array('function', 'sitename', 'tpl_head:23', 4, false),array('function', 'metadata', 'tpl_head:23', 7, false),array('function', 'stylesheet', 'tpl_head:23', 14, false),array('function', 'cms_selflink', 'tpl_head:23', 17, false),)), $this); ?>
<?php
function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_b04887e24e41120e1125703fe69422b7_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b04887e24e41120e1125703fe69422b7','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
