<?php /* Smarty version 2.6.25, created on 2014-01-31 22:04:24
         compiled from tpl_body:22 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%76^763^76313DB0%%tpl_body%3A22.inc'] = '5e848bd6a9913cedf391c562a655bffb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'anchor', 'tpl_body:22', 7, false),array('function', 'cms_selflink', 'tpl_body:22', 18, false),array('function', 'search', 'tpl_body:22', 22, false),array('function', 'menu', 'tpl_body:22', 37, false),array('function', 'NMS', 'tpl_body:22', 41, false),array('function', 'cms_module', 'tpl_body:22', 44, false),array('function', 'breadcrumbs', 'tpl_body:22', 53, false),array('function', 'oldprint', 'tpl_body:22', 54, false),array('function', 'title', 'tpl_body:22', 58, false),array('function', 'content', 'tpl_body:22', 61, false),array('function', 'global_content', 'tpl_body:22', 82, false),)), $this); ?>
<?php
function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','0');echo smarty_cms_function_anchor(array('anchor' => 'menu_vert','title' => 'Skip to navigation','accesskey' => 'n','text' => 'Skip to navigation'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','1');echo smarty_cms_function_anchor(array('anchor' => 'main','title' => 'Skip to content','accesskey' => 's','text' => 'Skip to content'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','2');echo smarty_cms_function_cms_selflink(array('dir' => 'start','text' => ($_smarty->_tpl_vars['sitename'])), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','3');echo smarty_cms_function_search(array('search_method' => 'post','resultpage' => 'search'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','4');echo smarty_cms_function_menu(array('template' => 'cssmenu_ulshadow.tpl'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','5');echo $_smarty->_plugins['function']['NMS'][0][0]->function_plugin(array('mode' => 'subscribe'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','6');echo smarty_cms_function_cms_module(array('module' => 'polls'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','7');echo smarty_cms_function_breadcrumbs(array('starttext' => '','root' => 'Home','delimiter' => '&gt;'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','8');echo smarty_cms_function_oldprint(array('showbutton' => true), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','9');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','10');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','11');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','12');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'login'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_13(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','13');echo smarty_cms_function_menu(array('template' => 'minimal_menu.tpl','start_level' => '1','number_of_levels' => '1'), $_smarty);
}


function _smarty_tplfunc_5e848bd6a9913cedf391c562a655bffb_14(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5e848bd6a9913cedf391c562a655bffb','14');echo smarty_cms_function_global_content(array('name' => 'footer'), $_smarty);
}



?>
