<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:41
         compiled from tpl_head:29 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%8E^8E9^8E9B9822%%tpl_head%3A29.inc'] = 'd24f033931df9455ff00df4a58d1886e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:29', 3, false),array('function', 'sitename', 'tpl_head:29', 3, false),array('function', 'metadata', 'tpl_head:29', 6, false),array('function', 'stylesheet', 'tpl_head:29', 8, false),array('function', 'cms_selflink', 'tpl_head:29', 10, false),)), $this); ?>
<?php
function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_d24f033931df9455ff00df4a58d1886e_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d24f033931df9455ff00df4a58d1886e','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
