<?php /* Smarty version 2.6.25, created on 2014-02-06 13:20:32
         compiled from checksum.tpl */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%8E^8E4^8E4C686E%%checksum.tpl.inc'] = 'c8894d389a63b95a6ac7d3dbf12f7c27';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'lang', 'checksum.tpl', 26, false),)), $this); ?>
<?php
function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','0');echo checksum_lang(array('key' => 'perform_validation'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','1');echo checksum_lang(array('key' => 'info_validation'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','2');echo checksum_lang(array('key' => 'upload_cksum_file'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','3');echo checksum_lang(array('key' => 'submit'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','4');echo checksum_lang(array('key' => 'download_cksum_file'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','5');echo checksum_lang(array('key' => 'info_generate_cksum_file'), $_smarty);
}


function _smarty_tplfunc_c8894d389a63b95a6ac7d3dbf12f7c27_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8894d389a63b95a6ac7d3dbf12f7c27','6');echo checksum_lang(array('key' => 'submit'), $_smarty);
}



?>
