<?php /* Smarty version 2.6.25, created on 2014-01-13 16:28:39
         compiled from tpl_body:28 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%96^96E^96E4D4AE%%tpl_body%3A28.inc'] = '2680148fd60c8ce54e3c772e75089192';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'menu', 'tpl_body:28', 210, false),)), $this); ?>
<?php
function _smarty_tplfunc_2680148fd60c8ce54e3c772e75089192_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2680148fd60c8ce54e3c772e75089192','0');echo smarty_cms_function_menu(array('start_level' => '3','template' => 'verticalmenu'), $_smarty);
}



?>
