<?php /* Smarty version 2.6.25, created on 2014-01-13 16:28:39
         compiled from tpl_top:28 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%B2^B23^B2322195%%tpl_top%3A28.inc'] = '1979dc6c68fbb1b29fb102237d8272dd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:28', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_1979dc6c68fbb1b29fb102237d8272dd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1979dc6c68fbb1b29fb102237d8272dd','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
