<?php /* Smarty version 2.6.25, created on 2014-01-13 13:48:19
         compiled from tpl_top:24 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%BB^BB8^BB846DBE%%tpl_top%3A24.inc'] = '9f06a7a854d03c15930cca7a8f85a161';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:24', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_9f06a7a854d03c15930cca7a8f85a161_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9f06a7a854d03c15930cca7a8f85a161','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
