<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:41
         compiled from tpl_top:29 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%C5^C53^C5351103%%tpl_top%3A29.inc'] = 'c24e2ccfc8576fc1d5df72016742a13c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:29', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_c24e2ccfc8576fc1d5df72016742a13c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c24e2ccfc8576fc1d5df72016742a13c','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
