<?php /* Smarty version 2.6.25, created on 2014-01-13 13:39:53
         compiled from globalcontent:footer */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%EE^EE6^EE6D73C2%%globalcontent%3Afooter.inc'] = '3bc3d7a1d54aa33389d7f9bc48a73ee9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'custom_copyright', 'globalcontent:footer', 1, false),array('function', 'cms_version', 'globalcontent:footer', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_3bc3d7a1d54aa33389d7f9bc48a73ee9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3bc3d7a1d54aa33389d7f9bc48a73ee9','0');echo cms_tmp_custom_copyright_userplugin_function(array(), $_smarty);
}


function _smarty_tplfunc_3bc3d7a1d54aa33389d7f9bc48a73ee9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3bc3d7a1d54aa33389d7f9bc48a73ee9','1');echo smarty_cms_function_cms_version(array(), $_smarty);
}



?>
