<?php /* Smarty version 2.6.25, created on 2014-01-13 13:48:19
         compiled from tpl_head:24 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%F0^F02^F02AE49F%%tpl_head%3A24.inc'] = 'e4b212b3428cd1ccbb9521382f13a54d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:24', 4, false),array('function', 'sitename', 'tpl_head:24', 4, false),array('function', 'metadata', 'tpl_head:24', 7, false),array('function', 'stylesheet', 'tpl_head:24', 14, false),array('function', 'cms_selflink', 'tpl_head:24', 17, false),)), $this); ?>
<?php
function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_e4b212b3428cd1ccbb9521382f13a54d_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e4b212b3428cd1ccbb9521382f13a54d','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
