<?php /* Smarty version 2.6.25, created on 2014-01-13 16:28:39
         compiled from tpl_head:28 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/%%F9^F99^F99CA8B4%%tpl_head%3A28.inc'] = '32f4bfd362819dbe9811c297d811d71d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:28', 3, false),array('function', 'sitename', 'tpl_head:28', 3, false),array('function', 'metadata', 'tpl_head:28', 6, false),array('function', 'stylesheet', 'tpl_head:28', 10, false),array('function', 'cms_selflink', 'tpl_head:28', 12, false),array('function', 'get_date', 'tpl_head:28', 54, false),)), $this); ?>
<?php
function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','3');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_32f4bfd362819dbe9811c297d811d71d_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32f4bfd362819dbe9811c297d811d71d','7');echo smarty_cms_function_get_date(array('format' => 'z'), $_smarty);
}



?>
