<?php /* Smarty version 2.6.25, created on 2014-01-14 02:29:04
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/191^%%70^707^707A8977%%content%3Acontent_en.inc'] = '88e7ce156808b755929bfae88d974dd8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_88e7ce156808b755929bfae88d974dd8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88e7ce156808b755929bfae88d974dd8','0');echo smarty_cms_function_cms_selflink(array('href' => 'Contest_korp_sites'), $_smarty);
}


function _smarty_tplfunc_88e7ce156808b755929bfae88d974dd8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88e7ce156808b755929bfae88d974dd8','1');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
