<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:42
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/192^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'f6644b5f4006d5934a905f7def70a184';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 78, false),)), $this); ?>
<?php
function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','0');echo smarty_cms_function_cms_selflink(array('href' => 'Sokos'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','1');echo smarty_cms_function_cms_selflink(array('href' => 'luchshee-korporativnoe-izdanie-2010'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','2');echo smarty_cms_function_cms_selflink(array('href' => 'luchshij-korporativnyj-portal-2010'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','3');echo smarty_cms_function_cms_selflink(array('href' => 'antonchik-tatyana-vyacheslavovna'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','4');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','5');echo smarty_cms_function_cms_selflink(array('href' => 'artsishevskij-ivan-sergeevich'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','6');echo smarty_cms_function_cms_selflink(array('href' => 'vajnberg-oleg-maratovich'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','7');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','8');echo smarty_cms_function_cms_selflink(array('href' => 'kolesnikova-anna'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','9');echo smarty_cms_function_cms_selflink(array('href' => 'oksana-makarenko'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','10');echo smarty_cms_function_cms_selflink(array('href' => 'artem-savko'), $_smarty);
}


function _smarty_tplfunc_f6644b5f4006d5934a905f7def70a184_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6644b5f4006d5934a905f7def70a184','11');echo smarty_cms_function_cms_selflink(array('href' => 'conf_2010_programm'), $_smarty);
}



?>
