<?php /* Smarty version 2.6.25, created on 2014-01-14 02:24:22
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/193^%%70^707^707A8977%%content%3Acontent_en.inc'] = '81ea56d60bd272be46f3e5b349944c8b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','0');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','1');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','2');echo smarty_cms_function_cms_selflink(array('href' => 'artem-savko'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','3');echo smarty_cms_function_cms_selflink(array('href' => 'antonchik-tatyana-vyacheslavovna'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','4');echo smarty_cms_function_cms_selflink(array('href' => 'anzhelika-tihonova'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','5');echo smarty_cms_function_cms_selflink(array('href' => 'kolesnikova-anna'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','6');echo smarty_cms_function_cms_selflink(array('href' => 'vajnberg-oleg-maratovich'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','7');echo smarty_cms_function_cms_selflink(array('href' => 'artsishevskij-ivan-sergeevich'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','8');echo smarty_cms_function_cms_selflink(array('href' => 'luchshee-korporativnoe-izdanie-2010'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','9');echo smarty_cms_function_cms_selflink(array('href' => 'luchshij-korporativnyj-portal-2010'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','10');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','11');echo smarty_cms_function_cms_selflink(array('href' => 'oksana-makarenko'), $_smarty);
}


function _smarty_tplfunc_81ea56d60bd272be46f3e5b349944c8b_12(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81ea56d60bd272be46f3e5b349944c8b','12');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
