<?php /* Smarty version 2.6.25, created on 2014-02-12 16:22:31
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/201^%%70^707^707A8977%%content%3Acontent_en.inc'] = '3086170b342203af5aa4db1dec53fb56';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_3086170b342203af5aa4db1dec53fb56_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3086170b342203af5aa4db1dec53fb56','0');echo smarty_cms_function_cms_selflink(array('href' => 'poryadok-priema'), $_smarty);
}


function _smarty_tplfunc_3086170b342203af5aa4db1dec53fb56_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3086170b342203af5aa4db1dec53fb56','1');echo smarty_cms_function_cms_selflink(array('href' => 'elena-georgievna-moll'), $_smarty);
}



?>
