<?php /* Smarty version 2.6.25, created on 2014-01-15 09:12:16
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/203^%%70^707^707A8977%%content%3Acontent_en.inc'] = '9132b95f4fe2ebe6c2c0991aa4754ded';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_9132b95f4fe2ebe6c2c0991aa4754ded_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9132b95f4fe2ebe6c2c0991aa4754ded','0');echo smarty_cms_function_cms_selflink(array('href' => 'ustiyants-anna'), $_smarty);
}


function _smarty_tplfunc_9132b95f4fe2ebe6c2c0991aa4754ded_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9132b95f4fe2ebe6c2c0991aa4754ded','1');echo smarty_cms_function_cms_selflink(array('href' => 'lyah-konstantin'), $_smarty);
}



?>
