<?php /* Smarty version 2.6.25, created on 2014-01-14 02:23:42
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/209^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ce62375b1955e48fcf47385d4ee554a5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_ce62375b1955e48fcf47385d4ee554a5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce62375b1955e48fcf47385d4ee554a5','0');echo smarty_cms_function_cms_selflink(array('href' => 'duvakina-komarova-vita-gennadievna'), $_smarty);
}


function _smarty_tplfunc_ce62375b1955e48fcf47385d4ee554a5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce62375b1955e48fcf47385d4ee554a5','1');echo smarty_cms_function_cms_selflink(array('href' => 'svetenkova-ekaterina-anatolevna'), $_smarty);
}


function _smarty_tplfunc_ce62375b1955e48fcf47385d4ee554a5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce62375b1955e48fcf47385d4ee554a5','2');echo smarty_cms_function_cms_selflink(array('href' => 'suprun-elena-viktorovna'), $_smarty);
}



?>
