<?php /* Smarty version 2.6.25, created on 2014-01-14 02:26:11
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/214^%%70^707^707A8977%%content%3Acontent_en.inc'] = '4129d27d973958ee0e3befef2fc09662';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_4129d27d973958ee0e3befef2fc09662_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4129d27d973958ee0e3befef2fc09662','0');echo smarty_cms_function_cms_module(array('module' => 'Quizzard','quiz_id' => '3'), $_smarty);
}



?>
