<?php /* Smarty version 2.6.25, created on 2014-01-14 00:47:25
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/217^%%70^707^707A8977%%content%3Acontent_en.inc'] = '132ac04086e47c3a63754976df74a33f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_132ac04086e47c3a63754976df74a33f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('132ac04086e47c3a63754976df74a33f','0');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_132ac04086e47c3a63754976df74a33f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('132ac04086e47c3a63754976df74a33f','1');echo smarty_cms_function_cms_selflink(array('href' => 'dementev-andrej-vladimirovich'), $_smarty);
}



?>
