<?php /* Smarty version 2.6.25, created on 2014-01-15 06:44:19
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/224^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ef21a1eac5a32df5f2ed8e7d3adeced1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef21a1eac5a32df5f2ed8e7d3adeced1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef21a1eac5a32df5f2ed8e7d3adeced1','0');echo smarty_cms_function_cms_selflink(array('href' => 'kohanaya-viktoriya-anatolevna'), $_smarty);
}


function _smarty_tplfunc_ef21a1eac5a32df5f2ed8e7d3adeced1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef21a1eac5a32df5f2ed8e7d3adeced1','1');echo smarty_cms_function_cms_selflink(array('href' => 'yakimenko-eleonora'), $_smarty);
}



?>
