<?php /* Smarty version 2.6.25, created on 2014-01-14 02:24:10
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/225^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ff1317d72d09ee167e5c1d1ff4bcaa9d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'startExpandCollapse', 'content:content_en', 36, false),array('function', 'stopExpandCollapse', 'content:content_en', 44, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff1317d72d09ee167e5c1d1ff4bcaa9d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff1317d72d09ee167e5c1d1ff4bcaa9d','0');echo smarty_cms_function_startExpandCollapse(array('id' => 'expand1','title' => 'Программа'), $_smarty);
}


function _smarty_tplfunc_ff1317d72d09ee167e5c1d1ff4bcaa9d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff1317d72d09ee167e5c1d1ff4bcaa9d','1');echo smarty_cms_function_stopExpandCollapse(array(), $_smarty);
}



?>
