<?php /* Smarty version 2.6.25, created on 2014-01-31 22:05:00
         compiled from print:71 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/22^%%B7^B70^B704EFC6%%print%3A71.inc'] = 'ca60c1ba51345d6ca716f453e93d7c89';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:71', 2, false),array('function', 'metadata', 'print:71', 2, false),array('function', 'stylesheet', 'print:71', 2, false),array('function', 'content', 'print:71', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca60c1ba51345d6ca716f453e93d7c89_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca60c1ba51345d6ca716f453e93d7c89','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ca60c1ba51345d6ca716f453e93d7c89_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca60c1ba51345d6ca716f453e93d7c89','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ca60c1ba51345d6ca716f453e93d7c89_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca60c1ba51345d6ca716f453e93d7c89','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ca60c1ba51345d6ca716f453e93d7c89_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca60c1ba51345d6ca716f453e93d7c89','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
