<?php /* Smarty version 2.6.25, created on 2014-01-14 01:16:03
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/231^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ca603886032a361bf26d2ec0bac2e916';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca603886032a361bf26d2ec0bac2e916_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca603886032a361bf26d2ec0bac2e916','0');echo smarty_cms_function_cms_selflink(array('href' => 'anohina-olga'), $_smarty);
}



?>
