<?php /* Smarty version 2.6.25, created on 2014-01-14 02:32:24
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/236^%%70^707^707A8977%%content%3Acontent_en.inc'] = '323ce11a18b2693f7d74aecf99527a33';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','0');echo smarty_cms_function_cms_selflink(array('href' => 'poryadok-priema'), $_smarty);
}


function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','1');echo smarty_cms_function_cms_selflink(array('href' => 'dragunyak-natalya'), $_smarty);
}


function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','2');echo smarty_cms_function_cms_selflink(array('href' => 'kreslavskij-evgenij'), $_smarty);
}


function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','3');echo smarty_cms_function_cms_selflink(array('href' => 'pavlov-dmitrij'), $_smarty);
}


function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','4');echo smarty_cms_function_cms_selflink(array('href' => 'fedorov-sergej'), $_smarty);
}


function _smarty_tplfunc_323ce11a18b2693f7d74aecf99527a33_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('323ce11a18b2693f7d74aecf99527a33','5');echo smarty_cms_function_cms_selflink(array('href' => '06_04_2011'), $_smarty);
}



?>
