<?php /* Smarty version 2.6.25, created on 2014-02-11 08:35:21
         compiled from print:108 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%95^952^9526798A%%print%3A108.inc'] = '2011eb402792ae43aa45fcc949d98305';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:108', 2, false),array('function', 'metadata', 'print:108', 2, false),array('function', 'stylesheet', 'print:108', 2, false),array('function', 'content', 'print:108', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2011eb402792ae43aa45fcc949d98305_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2011eb402792ae43aa45fcc949d98305','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2011eb402792ae43aa45fcc949d98305_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2011eb402792ae43aa45fcc949d98305','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2011eb402792ae43aa45fcc949d98305_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2011eb402792ae43aa45fcc949d98305','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2011eb402792ae43aa45fcc949d98305_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2011eb402792ae43aa45fcc949d98305','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
