<?php /* Smarty version 2.6.25, created on 2014-02-10 23:22:32
         compiled from print:98 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%50^505^505B7AEC%%print%3A98.inc'] = 'ebde023f263ea5386cb1de2e8c48ee76';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:98', 2, false),array('function', 'metadata', 'print:98', 2, false),array('function', 'stylesheet', 'print:98', 2, false),array('function', 'content', 'print:98', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ebde023f263ea5386cb1de2e8c48ee76_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebde023f263ea5386cb1de2e8c48ee76','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ebde023f263ea5386cb1de2e8c48ee76_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebde023f263ea5386cb1de2e8c48ee76','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ebde023f263ea5386cb1de2e8c48ee76_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebde023f263ea5386cb1de2e8c48ee76','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ebde023f263ea5386cb1de2e8c48ee76_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ebde023f263ea5386cb1de2e8c48ee76','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
