<?php /* Smarty version 2.6.25, created on 2014-02-06 05:27:11
         compiled from print:191 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%3D^3D3^3D387A67%%print%3A191.inc'] = '98fd0caf7147e7a38424753759de699f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:191', 2, false),array('function', 'metadata', 'print:191', 2, false),array('function', 'stylesheet', 'print:191', 2, false),array('function', 'content', 'print:191', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_98fd0caf7147e7a38424753759de699f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98fd0caf7147e7a38424753759de699f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_98fd0caf7147e7a38424753759de699f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98fd0caf7147e7a38424753759de699f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_98fd0caf7147e7a38424753759de699f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98fd0caf7147e7a38424753759de699f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_98fd0caf7147e7a38424753759de699f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98fd0caf7147e7a38424753759de699f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
