<?php /* Smarty version 2.6.25, created on 2014-02-12 15:54:44
         compiled from print:102 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%75^75F^75F39094%%print%3A102.inc'] = 'c1201016add4708516acdfac2846f574';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:102', 2, false),array('function', 'metadata', 'print:102', 2, false),array('function', 'stylesheet', 'print:102', 2, false),array('function', 'content', 'print:102', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c1201016add4708516acdfac2846f574_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1201016add4708516acdfac2846f574','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c1201016add4708516acdfac2846f574_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1201016add4708516acdfac2846f574','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c1201016add4708516acdfac2846f574_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1201016add4708516acdfac2846f574','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c1201016add4708516acdfac2846f574_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c1201016add4708516acdfac2846f574','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
