<?php /* Smarty version 2.6.25, created on 2014-02-02 17:44:50
         compiled from print:239 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CB^CB4^CB4AA486%%print%3A239.inc'] = '65c4df22f2c40e6e4b95793d29555c9d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:239', 2, false),array('function', 'metadata', 'print:239', 2, false),array('function', 'stylesheet', 'print:239', 2, false),array('function', 'content', 'print:239', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_65c4df22f2c40e6e4b95793d29555c9d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65c4df22f2c40e6e4b95793d29555c9d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_65c4df22f2c40e6e4b95793d29555c9d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65c4df22f2c40e6e4b95793d29555c9d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_65c4df22f2c40e6e4b95793d29555c9d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65c4df22f2c40e6e4b95793d29555c9d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_65c4df22f2c40e6e4b95793d29555c9d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65c4df22f2c40e6e4b95793d29555c9d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
