<?php /* Smarty version 2.6.25, created on 2014-02-04 19:56:46
         compiled from print:188 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5D^5DF^5DFFF382%%print%3A188.inc'] = 'bd373b8833310c19bf0e3e442f5991c2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:188', 2, false),array('function', 'metadata', 'print:188', 2, false),array('function', 'stylesheet', 'print:188', 2, false),array('function', 'content', 'print:188', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bd373b8833310c19bf0e3e442f5991c2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bd373b8833310c19bf0e3e442f5991c2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bd373b8833310c19bf0e3e442f5991c2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bd373b8833310c19bf0e3e442f5991c2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bd373b8833310c19bf0e3e442f5991c2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bd373b8833310c19bf0e3e442f5991c2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bd373b8833310c19bf0e3e442f5991c2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bd373b8833310c19bf0e3e442f5991c2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
