<?php /* Smarty version 2.6.25, created on 2014-02-11 05:22:41
         compiled from print:291 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%3F^3F7^3F7EC43E%%print%3A291.inc'] = 'd0e8d883a64ba968de8eb2660c84982a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:291', 2, false),array('function', 'metadata', 'print:291', 2, false),array('function', 'stylesheet', 'print:291', 2, false),array('function', 'content', 'print:291', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d0e8d883a64ba968de8eb2660c84982a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0e8d883a64ba968de8eb2660c84982a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d0e8d883a64ba968de8eb2660c84982a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0e8d883a64ba968de8eb2660c84982a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d0e8d883a64ba968de8eb2660c84982a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0e8d883a64ba968de8eb2660c84982a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d0e8d883a64ba968de8eb2660c84982a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0e8d883a64ba968de8eb2660c84982a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
