<?php /* Smarty version 2.6.25, created on 2014-02-07 22:13:16
         compiled from print:332 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5D^5D5^5D5A1739%%print%3A332.inc'] = 'e81b2fa3e8858e35519a548e111c89ea';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:332', 2, false),array('function', 'metadata', 'print:332', 2, false),array('function', 'stylesheet', 'print:332', 2, false),array('function', 'content', 'print:332', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e81b2fa3e8858e35519a548e111c89ea_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e81b2fa3e8858e35519a548e111c89ea','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e81b2fa3e8858e35519a548e111c89ea_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e81b2fa3e8858e35519a548e111c89ea','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e81b2fa3e8858e35519a548e111c89ea_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e81b2fa3e8858e35519a548e111c89ea','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e81b2fa3e8858e35519a548e111c89ea_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e81b2fa3e8858e35519a548e111c89ea','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
