<?php /* Smarty version 2.6.25, created on 2014-02-01 23:25:31
         compiled from print:107 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%05^059^0599641B%%print%3A107.inc'] = '6a2d7c4b9f4ec81e6806c1f9f647642b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:107', 2, false),array('function', 'metadata', 'print:107', 2, false),array('function', 'stylesheet', 'print:107', 2, false),array('function', 'content', 'print:107', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6a2d7c4b9f4ec81e6806c1f9f647642b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a2d7c4b9f4ec81e6806c1f9f647642b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6a2d7c4b9f4ec81e6806c1f9f647642b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a2d7c4b9f4ec81e6806c1f9f647642b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6a2d7c4b9f4ec81e6806c1f9f647642b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a2d7c4b9f4ec81e6806c1f9f647642b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6a2d7c4b9f4ec81e6806c1f9f647642b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6a2d7c4b9f4ec81e6806c1f9f647642b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
