<?php /* Smarty version 2.6.25, created on 2014-02-10 09:50:18
         compiled from print:168 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C3^C37^C37CDE0C%%print%3A168.inc'] = '5a41c1452eaa60e7b9ccfa1e2e915964';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:168', 2, false),array('function', 'metadata', 'print:168', 2, false),array('function', 'stylesheet', 'print:168', 2, false),array('function', 'content', 'print:168', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5a41c1452eaa60e7b9ccfa1e2e915964_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a41c1452eaa60e7b9ccfa1e2e915964','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5a41c1452eaa60e7b9ccfa1e2e915964_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a41c1452eaa60e7b9ccfa1e2e915964','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5a41c1452eaa60e7b9ccfa1e2e915964_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a41c1452eaa60e7b9ccfa1e2e915964','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5a41c1452eaa60e7b9ccfa1e2e915964_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a41c1452eaa60e7b9ccfa1e2e915964','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
