<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:39
         compiled from print:93 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C7^C78^C789A364%%print%3A93.inc'] = '7cbea990a5ab887150708461998e5aad';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:93', 2, false),array('function', 'metadata', 'print:93', 2, false),array('function', 'stylesheet', 'print:93', 2, false),array('function', 'content', 'print:93', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7cbea990a5ab887150708461998e5aad_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7cbea990a5ab887150708461998e5aad','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7cbea990a5ab887150708461998e5aad_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7cbea990a5ab887150708461998e5aad','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7cbea990a5ab887150708461998e5aad_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7cbea990a5ab887150708461998e5aad','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7cbea990a5ab887150708461998e5aad_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7cbea990a5ab887150708461998e5aad','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
