<?php /* Smarty version 2.6.25, created on 2014-02-11 01:35:59
         compiled from print:167 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%53^53C^53C3C39D%%print%3A167.inc'] = '7a3d4ad5223bc3ea84757800fee97146';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:167', 2, false),array('function', 'metadata', 'print:167', 2, false),array('function', 'stylesheet', 'print:167', 2, false),array('function', 'content', 'print:167', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7a3d4ad5223bc3ea84757800fee97146_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a3d4ad5223bc3ea84757800fee97146','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7a3d4ad5223bc3ea84757800fee97146_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a3d4ad5223bc3ea84757800fee97146','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7a3d4ad5223bc3ea84757800fee97146_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a3d4ad5223bc3ea84757800fee97146','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7a3d4ad5223bc3ea84757800fee97146_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7a3d4ad5223bc3ea84757800fee97146','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
