<?php /* Smarty version 2.6.25, created on 2014-02-11 16:00:57
         compiled from print:122 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%47^47C^47C5F216%%print%3A122.inc'] = 'd9ed3c83bccd9027baf6152f919407dc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:122', 2, false),array('function', 'metadata', 'print:122', 2, false),array('function', 'stylesheet', 'print:122', 2, false),array('function', 'content', 'print:122', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d9ed3c83bccd9027baf6152f919407dc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d9ed3c83bccd9027baf6152f919407dc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d9ed3c83bccd9027baf6152f919407dc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d9ed3c83bccd9027baf6152f919407dc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d9ed3c83bccd9027baf6152f919407dc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d9ed3c83bccd9027baf6152f919407dc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d9ed3c83bccd9027baf6152f919407dc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d9ed3c83bccd9027baf6152f919407dc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
