<?php /* Smarty version 2.6.25, created on 2014-02-07 21:46:45
         compiled from print:143 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%66^669^66986506%%print%3A143.inc'] = 'bfb1355593382b7cdd7086e1ac27e645';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:143', 2, false),array('function', 'metadata', 'print:143', 2, false),array('function', 'stylesheet', 'print:143', 2, false),array('function', 'content', 'print:143', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bfb1355593382b7cdd7086e1ac27e645_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfb1355593382b7cdd7086e1ac27e645','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bfb1355593382b7cdd7086e1ac27e645_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfb1355593382b7cdd7086e1ac27e645','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bfb1355593382b7cdd7086e1ac27e645_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfb1355593382b7cdd7086e1ac27e645','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bfb1355593382b7cdd7086e1ac27e645_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfb1355593382b7cdd7086e1ac27e645','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
