<?php /* Smarty version 2.6.25, created on 2014-02-04 17:58:32
         compiled from print:117 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%1C^1C8^1C82555A%%print%3A117.inc'] = '3707df5ce041d291aeb89478b5c18405';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:117', 2, false),array('function', 'metadata', 'print:117', 2, false),array('function', 'stylesheet', 'print:117', 2, false),array('function', 'content', 'print:117', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3707df5ce041d291aeb89478b5c18405_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3707df5ce041d291aeb89478b5c18405','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3707df5ce041d291aeb89478b5c18405_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3707df5ce041d291aeb89478b5c18405','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3707df5ce041d291aeb89478b5c18405_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3707df5ce041d291aeb89478b5c18405','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3707df5ce041d291aeb89478b5c18405_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3707df5ce041d291aeb89478b5c18405','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
