<?php /* Smarty version 2.6.25, created on 2014-02-11 06:59:06
         compiled from print:65 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A9^A97^A9721A9E%%print%3A65.inc'] = 'a6e6cf3901ff6cafb7282328eb29eb7a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:65', 2, false),array('function', 'metadata', 'print:65', 2, false),array('function', 'stylesheet', 'print:65', 2, false),array('function', 'content', 'print:65', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a6e6cf3901ff6cafb7282328eb29eb7a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e6cf3901ff6cafb7282328eb29eb7a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a6e6cf3901ff6cafb7282328eb29eb7a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e6cf3901ff6cafb7282328eb29eb7a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a6e6cf3901ff6cafb7282328eb29eb7a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e6cf3901ff6cafb7282328eb29eb7a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a6e6cf3901ff6cafb7282328eb29eb7a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6e6cf3901ff6cafb7282328eb29eb7a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
