<?php /* Smarty version 2.6.25, created on 2014-02-12 00:12:44
         compiled from print:319 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F8^F8B^F8BEAC33%%print%3A319.inc'] = 'ca949753bbef2052d9b06f8bcc6b5c82';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:319', 2, false),array('function', 'metadata', 'print:319', 2, false),array('function', 'stylesheet', 'print:319', 2, false),array('function', 'content', 'print:319', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca949753bbef2052d9b06f8bcc6b5c82_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca949753bbef2052d9b06f8bcc6b5c82','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ca949753bbef2052d9b06f8bcc6b5c82_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca949753bbef2052d9b06f8bcc6b5c82','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ca949753bbef2052d9b06f8bcc6b5c82_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca949753bbef2052d9b06f8bcc6b5c82','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ca949753bbef2052d9b06f8bcc6b5c82_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca949753bbef2052d9b06f8bcc6b5c82','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
