<?php /* Smarty version 2.6.25, created on 2014-02-04 20:29:00
         compiled from print:116 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%6B^6B8^6B8565CC%%print%3A116.inc'] = '81c831e3f14f87d4f0b78496e2d538ec';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:116', 2, false),array('function', 'metadata', 'print:116', 2, false),array('function', 'stylesheet', 'print:116', 2, false),array('function', 'content', 'print:116', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_81c831e3f14f87d4f0b78496e2d538ec_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81c831e3f14f87d4f0b78496e2d538ec','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_81c831e3f14f87d4f0b78496e2d538ec_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81c831e3f14f87d4f0b78496e2d538ec','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_81c831e3f14f87d4f0b78496e2d538ec_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81c831e3f14f87d4f0b78496e2d538ec','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_81c831e3f14f87d4f0b78496e2d538ec_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81c831e3f14f87d4f0b78496e2d538ec','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
