<?php /* Smarty version 2.6.25, created on 2014-02-12 18:33:49
         compiled from print:135 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C0^C0B^C0BA56F4%%print%3A135.inc'] = '4c40c5cb25cd150e0af46f6ebef32626';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:135', 2, false),array('function', 'metadata', 'print:135', 2, false),array('function', 'stylesheet', 'print:135', 2, false),array('function', 'content', 'print:135', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4c40c5cb25cd150e0af46f6ebef32626_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c40c5cb25cd150e0af46f6ebef32626','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4c40c5cb25cd150e0af46f6ebef32626_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c40c5cb25cd150e0af46f6ebef32626','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4c40c5cb25cd150e0af46f6ebef32626_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c40c5cb25cd150e0af46f6ebef32626','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4c40c5cb25cd150e0af46f6ebef32626_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c40c5cb25cd150e0af46f6ebef32626','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
