<?php /* Smarty version 2.6.25, created on 2014-02-02 14:23:16
         compiled from print:295 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%38^381^38130027%%print%3A295.inc'] = '836f7b999b3bc577ca813554e3eb4e37';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:295', 2, false),array('function', 'metadata', 'print:295', 2, false),array('function', 'stylesheet', 'print:295', 2, false),array('function', 'content', 'print:295', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_836f7b999b3bc577ca813554e3eb4e37_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('836f7b999b3bc577ca813554e3eb4e37','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_836f7b999b3bc577ca813554e3eb4e37_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('836f7b999b3bc577ca813554e3eb4e37','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_836f7b999b3bc577ca813554e3eb4e37_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('836f7b999b3bc577ca813554e3eb4e37','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_836f7b999b3bc577ca813554e3eb4e37_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('836f7b999b3bc577ca813554e3eb4e37','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
