<?php /* Smarty version 2.6.25, created on 2014-02-10 19:15:49
         compiled from print:285 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%21^210^21083166%%print%3A285.inc'] = '868b755ca5cdabcb08872645021ec00c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:285', 2, false),array('function', 'metadata', 'print:285', 2, false),array('function', 'stylesheet', 'print:285', 2, false),array('function', 'content', 'print:285', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_868b755ca5cdabcb08872645021ec00c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('868b755ca5cdabcb08872645021ec00c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_868b755ca5cdabcb08872645021ec00c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('868b755ca5cdabcb08872645021ec00c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_868b755ca5cdabcb08872645021ec00c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('868b755ca5cdabcb08872645021ec00c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_868b755ca5cdabcb08872645021ec00c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('868b755ca5cdabcb08872645021ec00c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
