<?php /* Smarty version 2.6.25, created on 2014-02-10 12:13:17
         compiled from print:141 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%88^889^8896042A%%print%3A141.inc'] = '01e1951bab678637fe3c4f7942746396';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:141', 2, false),array('function', 'metadata', 'print:141', 2, false),array('function', 'stylesheet', 'print:141', 2, false),array('function', 'content', 'print:141', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_01e1951bab678637fe3c4f7942746396_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01e1951bab678637fe3c4f7942746396','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_01e1951bab678637fe3c4f7942746396_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01e1951bab678637fe3c4f7942746396','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_01e1951bab678637fe3c4f7942746396_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01e1951bab678637fe3c4f7942746396','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_01e1951bab678637fe3c4f7942746396_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('01e1951bab678637fe3c4f7942746396','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
