<?php /* Smarty version 2.6.25, created on 2014-02-07 21:34:58
         compiled from print:361 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B9^B92^B924B2C6%%print%3A361.inc'] = 'f5cc18d6e461dc32ba76c80979286e71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:361', 2, false),array('function', 'metadata', 'print:361', 2, false),array('function', 'stylesheet', 'print:361', 2, false),array('function', 'content', 'print:361', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f5cc18d6e461dc32ba76c80979286e71_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5cc18d6e461dc32ba76c80979286e71','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f5cc18d6e461dc32ba76c80979286e71_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5cc18d6e461dc32ba76c80979286e71','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f5cc18d6e461dc32ba76c80979286e71_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5cc18d6e461dc32ba76c80979286e71','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f5cc18d6e461dc32ba76c80979286e71_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5cc18d6e461dc32ba76c80979286e71','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
