<?php /* Smarty version 2.6.25, created on 2014-02-12 06:22:15
         compiled from print:306 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%71^711^711A80E3%%print%3A306.inc'] = '18c5101552172db93e33d84a10a399b9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:306', 2, false),array('function', 'metadata', 'print:306', 2, false),array('function', 'stylesheet', 'print:306', 2, false),array('function', 'content', 'print:306', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_18c5101552172db93e33d84a10a399b9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c5101552172db93e33d84a10a399b9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_18c5101552172db93e33d84a10a399b9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c5101552172db93e33d84a10a399b9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_18c5101552172db93e33d84a10a399b9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c5101552172db93e33d84a10a399b9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_18c5101552172db93e33d84a10a399b9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('18c5101552172db93e33d84a10a399b9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
