<?php /* Smarty version 2.6.25, created on 2014-02-11 10:02:59
         compiled from print:304 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9F^9F1^9F14E1CF%%print%3A304.inc'] = '1b30ca37bf4a8ea02b19e455997190cc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:304', 2, false),array('function', 'metadata', 'print:304', 2, false),array('function', 'stylesheet', 'print:304', 2, false),array('function', 'content', 'print:304', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1b30ca37bf4a8ea02b19e455997190cc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b30ca37bf4a8ea02b19e455997190cc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1b30ca37bf4a8ea02b19e455997190cc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b30ca37bf4a8ea02b19e455997190cc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1b30ca37bf4a8ea02b19e455997190cc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b30ca37bf4a8ea02b19e455997190cc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1b30ca37bf4a8ea02b19e455997190cc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b30ca37bf4a8ea02b19e455997190cc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
