<?php /* Smarty version 2.6.25, created on 2014-02-01 23:08:27
         compiled from print:142 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%11^119^119F5590%%print%3A142.inc'] = '3b51658fb744e8d1edecd5ceedceb9a1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:142', 2, false),array('function', 'metadata', 'print:142', 2, false),array('function', 'stylesheet', 'print:142', 2, false),array('function', 'content', 'print:142', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3b51658fb744e8d1edecd5ceedceb9a1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b51658fb744e8d1edecd5ceedceb9a1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3b51658fb744e8d1edecd5ceedceb9a1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b51658fb744e8d1edecd5ceedceb9a1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3b51658fb744e8d1edecd5ceedceb9a1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b51658fb744e8d1edecd5ceedceb9a1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3b51658fb744e8d1edecd5ceedceb9a1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b51658fb744e8d1edecd5ceedceb9a1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
