<?php /* Smarty version 2.6.25, created on 2014-02-12 03:09:03
         compiled from print:263 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%56^56E^56E8B9DD%%print%3A263.inc'] = 'a3c48c7643f941979fedce532e4a3ddd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:263', 2, false),array('function', 'metadata', 'print:263', 2, false),array('function', 'stylesheet', 'print:263', 2, false),array('function', 'content', 'print:263', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a3c48c7643f941979fedce532e4a3ddd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3c48c7643f941979fedce532e4a3ddd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a3c48c7643f941979fedce532e4a3ddd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3c48c7643f941979fedce532e4a3ddd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a3c48c7643f941979fedce532e4a3ddd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3c48c7643f941979fedce532e4a3ddd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a3c48c7643f941979fedce532e4a3ddd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3c48c7643f941979fedce532e4a3ddd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
