<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:54
         compiled from print:345 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8C^8C7^8C7F145D%%print%3A345.inc'] = '5a169d6de4b3b8427b0d308b94bd0e5c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:345', 2, false),array('function', 'metadata', 'print:345', 2, false),array('function', 'stylesheet', 'print:345', 2, false),array('function', 'content', 'print:345', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5a169d6de4b3b8427b0d308b94bd0e5c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a169d6de4b3b8427b0d308b94bd0e5c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5a169d6de4b3b8427b0d308b94bd0e5c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a169d6de4b3b8427b0d308b94bd0e5c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5a169d6de4b3b8427b0d308b94bd0e5c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a169d6de4b3b8427b0d308b94bd0e5c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5a169d6de4b3b8427b0d308b94bd0e5c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5a169d6de4b3b8427b0d308b94bd0e5c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
