<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:04
         compiled from print:203 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%00^00B^00B21E5B%%print%3A203.inc'] = '4c6dcb6f2efc049e1ee4947096cbce7c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:203', 2, false),array('function', 'metadata', 'print:203', 2, false),array('function', 'stylesheet', 'print:203', 2, false),array('function', 'content', 'print:203', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4c6dcb6f2efc049e1ee4947096cbce7c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c6dcb6f2efc049e1ee4947096cbce7c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4c6dcb6f2efc049e1ee4947096cbce7c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c6dcb6f2efc049e1ee4947096cbce7c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4c6dcb6f2efc049e1ee4947096cbce7c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c6dcb6f2efc049e1ee4947096cbce7c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4c6dcb6f2efc049e1ee4947096cbce7c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4c6dcb6f2efc049e1ee4947096cbce7c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
