<?php /* Smarty version 2.6.25, created on 2014-02-12 13:33:04
         compiled from print:92 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B0^B08^B08E93F2%%print%3A92.inc'] = 'bf48ddfce9b91d307e001767ad8825e0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:92', 2, false),array('function', 'metadata', 'print:92', 2, false),array('function', 'stylesheet', 'print:92', 2, false),array('function', 'content', 'print:92', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bf48ddfce9b91d307e001767ad8825e0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf48ddfce9b91d307e001767ad8825e0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bf48ddfce9b91d307e001767ad8825e0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf48ddfce9b91d307e001767ad8825e0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bf48ddfce9b91d307e001767ad8825e0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf48ddfce9b91d307e001767ad8825e0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bf48ddfce9b91d307e001767ad8825e0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf48ddfce9b91d307e001767ad8825e0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
