<?php /* Smarty version 2.6.25, created on 2014-02-12 22:42:34
         compiled from print:74 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C7^C76^C76E1B49%%print%3A74.inc'] = '61d806b798965855f5d45967662d6e21';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:74', 2, false),array('function', 'metadata', 'print:74', 2, false),array('function', 'stylesheet', 'print:74', 2, false),array('function', 'content', 'print:74', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_61d806b798965855f5d45967662d6e21_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('61d806b798965855f5d45967662d6e21','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_61d806b798965855f5d45967662d6e21_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('61d806b798965855f5d45967662d6e21','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_61d806b798965855f5d45967662d6e21_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('61d806b798965855f5d45967662d6e21','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_61d806b798965855f5d45967662d6e21_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('61d806b798965855f5d45967662d6e21','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
