<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:05
         compiled from print:265 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BF^BF8^BF8B1CE8%%print%3A265.inc'] = 'b2658a5989a908f9af24f9c635e15f6d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:265', 2, false),array('function', 'metadata', 'print:265', 2, false),array('function', 'stylesheet', 'print:265', 2, false),array('function', 'content', 'print:265', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b2658a5989a908f9af24f9c635e15f6d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2658a5989a908f9af24f9c635e15f6d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b2658a5989a908f9af24f9c635e15f6d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2658a5989a908f9af24f9c635e15f6d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b2658a5989a908f9af24f9c635e15f6d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2658a5989a908f9af24f9c635e15f6d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b2658a5989a908f9af24f9c635e15f6d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2658a5989a908f9af24f9c635e15f6d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
