<?php /* Smarty version 2.6.25, created on 2014-02-04 20:25:47
         compiled from print:133 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%29^29D^29D9F3C1%%print%3A133.inc'] = 'c0cc5de7e48e616d444bc53f8d857caf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:133', 2, false),array('function', 'metadata', 'print:133', 2, false),array('function', 'stylesheet', 'print:133', 2, false),array('function', 'content', 'print:133', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c0cc5de7e48e616d444bc53f8d857caf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc5de7e48e616d444bc53f8d857caf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c0cc5de7e48e616d444bc53f8d857caf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc5de7e48e616d444bc53f8d857caf','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c0cc5de7e48e616d444bc53f8d857caf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc5de7e48e616d444bc53f8d857caf','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c0cc5de7e48e616d444bc53f8d857caf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0cc5de7e48e616d444bc53f8d857caf','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
