<?php /* Smarty version 2.6.25, created on 2014-02-12 02:30:15
         compiled from print:339 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CA^CA8^CA88CEB1%%print%3A339.inc'] = 'd80bd5382dc8778cf3dbace8cd4d9b57';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:339', 2, false),array('function', 'metadata', 'print:339', 2, false),array('function', 'stylesheet', 'print:339', 2, false),array('function', 'content', 'print:339', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d80bd5382dc8778cf3dbace8cd4d9b57_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d80bd5382dc8778cf3dbace8cd4d9b57','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d80bd5382dc8778cf3dbace8cd4d9b57_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d80bd5382dc8778cf3dbace8cd4d9b57','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d80bd5382dc8778cf3dbace8cd4d9b57_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d80bd5382dc8778cf3dbace8cd4d9b57','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d80bd5382dc8778cf3dbace8cd4d9b57_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d80bd5382dc8778cf3dbace8cd4d9b57','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
