<?php /* Smarty version 2.6.25, created on 2014-02-10 18:59:44
         compiled from print:354 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E2^E26^E263158A%%print%3A354.inc'] = '5016091d3e7a53b268a8f974ec743541';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:354', 2, false),array('function', 'metadata', 'print:354', 2, false),array('function', 'stylesheet', 'print:354', 2, false),array('function', 'content', 'print:354', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5016091d3e7a53b268a8f974ec743541_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5016091d3e7a53b268a8f974ec743541','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5016091d3e7a53b268a8f974ec743541_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5016091d3e7a53b268a8f974ec743541','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5016091d3e7a53b268a8f974ec743541_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5016091d3e7a53b268a8f974ec743541','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5016091d3e7a53b268a8f974ec743541_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5016091d3e7a53b268a8f974ec743541','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
