<?php /* Smarty version 2.6.25, created on 2014-02-02 17:07:35
         compiled from print:312 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%6F^6F6^6F6C75BB%%print%3A312.inc'] = 'e2b69e42dafd5f0c0343df344f60e287';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:312', 2, false),array('function', 'metadata', 'print:312', 2, false),array('function', 'stylesheet', 'print:312', 2, false),array('function', 'content', 'print:312', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e2b69e42dafd5f0c0343df344f60e287_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2b69e42dafd5f0c0343df344f60e287','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e2b69e42dafd5f0c0343df344f60e287_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2b69e42dafd5f0c0343df344f60e287','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e2b69e42dafd5f0c0343df344f60e287_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2b69e42dafd5f0c0343df344f60e287','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e2b69e42dafd5f0c0343df344f60e287_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e2b69e42dafd5f0c0343df344f60e287','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
