<?php /* Smarty version 2.6.25, created on 2014-02-12 08:20:56
         compiled from print:179 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AD^AD6^AD60DFDB%%print%3A179.inc'] = '5844b545e7a60eccd0be91d543ca63b4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:179', 2, false),array('function', 'metadata', 'print:179', 2, false),array('function', 'stylesheet', 'print:179', 2, false),array('function', 'content', 'print:179', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5844b545e7a60eccd0be91d543ca63b4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5844b545e7a60eccd0be91d543ca63b4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5844b545e7a60eccd0be91d543ca63b4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5844b545e7a60eccd0be91d543ca63b4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5844b545e7a60eccd0be91d543ca63b4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5844b545e7a60eccd0be91d543ca63b4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5844b545e7a60eccd0be91d543ca63b4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5844b545e7a60eccd0be91d543ca63b4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
