<?php /* Smarty version 2.6.25, created on 2014-02-11 00:32:57
         compiled from print:218 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8E^8E7^8E7BF692%%print%3A218.inc'] = '0e744505d65cac013d98b27a01d3a6e2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:218', 2, false),array('function', 'metadata', 'print:218', 2, false),array('function', 'stylesheet', 'print:218', 2, false),array('function', 'content', 'print:218', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0e744505d65cac013d98b27a01d3a6e2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0e744505d65cac013d98b27a01d3a6e2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0e744505d65cac013d98b27a01d3a6e2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0e744505d65cac013d98b27a01d3a6e2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0e744505d65cac013d98b27a01d3a6e2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0e744505d65cac013d98b27a01d3a6e2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0e744505d65cac013d98b27a01d3a6e2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0e744505d65cac013d98b27a01d3a6e2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
