<?php /* Smarty version 2.6.25, created on 2014-02-07 21:36:56
         compiled from print:298 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%46^46A^46A27C9A%%print%3A298.inc'] = '11eefadd9a01177202ea22358ccb4e9e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:298', 2, false),array('function', 'metadata', 'print:298', 2, false),array('function', 'stylesheet', 'print:298', 2, false),array('function', 'content', 'print:298', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_11eefadd9a01177202ea22358ccb4e9e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11eefadd9a01177202ea22358ccb4e9e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_11eefadd9a01177202ea22358ccb4e9e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11eefadd9a01177202ea22358ccb4e9e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_11eefadd9a01177202ea22358ccb4e9e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11eefadd9a01177202ea22358ccb4e9e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_11eefadd9a01177202ea22358ccb4e9e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('11eefadd9a01177202ea22358ccb4e9e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
