<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:17
         compiled from print:314 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%86^860^860FD08E%%print%3A314.inc'] = 'ee7002edf86240678f9d4abc0864fa18';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:314', 2, false),array('function', 'metadata', 'print:314', 2, false),array('function', 'stylesheet', 'print:314', 2, false),array('function', 'content', 'print:314', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ee7002edf86240678f9d4abc0864fa18_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee7002edf86240678f9d4abc0864fa18','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ee7002edf86240678f9d4abc0864fa18_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee7002edf86240678f9d4abc0864fa18','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ee7002edf86240678f9d4abc0864fa18_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee7002edf86240678f9d4abc0864fa18','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ee7002edf86240678f9d4abc0864fa18_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee7002edf86240678f9d4abc0864fa18','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
