<?php /* Smarty version 2.6.25, created on 2014-02-10 13:43:24
         compiled from print:62 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%37^371^37168F3D%%print%3A62.inc'] = '665f1d78971cc8ba477707ccf8d5a24c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:62', 2, false),array('function', 'metadata', 'print:62', 2, false),array('function', 'stylesheet', 'print:62', 2, false),array('function', 'content', 'print:62', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_665f1d78971cc8ba477707ccf8d5a24c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('665f1d78971cc8ba477707ccf8d5a24c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_665f1d78971cc8ba477707ccf8d5a24c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('665f1d78971cc8ba477707ccf8d5a24c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_665f1d78971cc8ba477707ccf8d5a24c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('665f1d78971cc8ba477707ccf8d5a24c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_665f1d78971cc8ba477707ccf8d5a24c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('665f1d78971cc8ba477707ccf8d5a24c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
