<?php /* Smarty version 2.6.25, created on 2014-02-12 04:28:17
         compiled from print:77 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5E^5E6^5E674AF3%%print%3A77.inc'] = '383cdddb9ba5c88cdab75d301ae6daf0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:77', 2, false),array('function', 'metadata', 'print:77', 2, false),array('function', 'stylesheet', 'print:77', 2, false),array('function', 'content', 'print:77', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_383cdddb9ba5c88cdab75d301ae6daf0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('383cdddb9ba5c88cdab75d301ae6daf0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_383cdddb9ba5c88cdab75d301ae6daf0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('383cdddb9ba5c88cdab75d301ae6daf0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_383cdddb9ba5c88cdab75d301ae6daf0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('383cdddb9ba5c88cdab75d301ae6daf0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_383cdddb9ba5c88cdab75d301ae6daf0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('383cdddb9ba5c88cdab75d301ae6daf0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
