<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:40
         compiled from print:206 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%70^70D^70D8EAD4%%print%3A206.inc'] = '0761ae8a827a26eacb4f79f6e3dd0814';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:206', 2, false),array('function', 'metadata', 'print:206', 2, false),array('function', 'stylesheet', 'print:206', 2, false),array('function', 'content', 'print:206', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0761ae8a827a26eacb4f79f6e3dd0814_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0761ae8a827a26eacb4f79f6e3dd0814','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0761ae8a827a26eacb4f79f6e3dd0814_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0761ae8a827a26eacb4f79f6e3dd0814','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0761ae8a827a26eacb4f79f6e3dd0814_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0761ae8a827a26eacb4f79f6e3dd0814','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0761ae8a827a26eacb4f79f6e3dd0814_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0761ae8a827a26eacb4f79f6e3dd0814','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
