<?php /* Smarty version 2.6.25, created on 2014-02-07 22:14:02
         compiled from print:364 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C9^C94^C94E4649%%print%3A364.inc'] = 'a411bf04b39220ebb930d9ae2254cd82';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:364', 2, false),array('function', 'metadata', 'print:364', 2, false),array('function', 'stylesheet', 'print:364', 2, false),array('function', 'content', 'print:364', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a411bf04b39220ebb930d9ae2254cd82_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a411bf04b39220ebb930d9ae2254cd82','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a411bf04b39220ebb930d9ae2254cd82_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a411bf04b39220ebb930d9ae2254cd82','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a411bf04b39220ebb930d9ae2254cd82_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a411bf04b39220ebb930d9ae2254cd82','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a411bf04b39220ebb930d9ae2254cd82_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a411bf04b39220ebb930d9ae2254cd82','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
