<?php /* Smarty version 2.6.25, created on 2014-02-10 18:26:31
         compiled from print:166 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%24^24C^24C4F30B%%print%3A166.inc'] = '602d561af116ce8068a0579d56f5cb1d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:166', 2, false),array('function', 'metadata', 'print:166', 2, false),array('function', 'stylesheet', 'print:166', 2, false),array('function', 'content', 'print:166', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_602d561af116ce8068a0579d56f5cb1d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('602d561af116ce8068a0579d56f5cb1d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_602d561af116ce8068a0579d56f5cb1d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('602d561af116ce8068a0579d56f5cb1d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_602d561af116ce8068a0579d56f5cb1d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('602d561af116ce8068a0579d56f5cb1d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_602d561af116ce8068a0579d56f5cb1d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('602d561af116ce8068a0579d56f5cb1d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
