<?php /* Smarty version 2.6.25, created on 2014-02-10 19:17:46
         compiled from print:341 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8B^8B1^8B12D044%%print%3A341.inc'] = 'e921d6a8f40b39a7a94c85e065dac667';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:341', 2, false),array('function', 'metadata', 'print:341', 2, false),array('function', 'stylesheet', 'print:341', 2, false),array('function', 'content', 'print:341', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e921d6a8f40b39a7a94c85e065dac667_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e921d6a8f40b39a7a94c85e065dac667','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e921d6a8f40b39a7a94c85e065dac667_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e921d6a8f40b39a7a94c85e065dac667','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e921d6a8f40b39a7a94c85e065dac667_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e921d6a8f40b39a7a94c85e065dac667','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e921d6a8f40b39a7a94c85e065dac667_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e921d6a8f40b39a7a94c85e065dac667','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
