<?php /* Smarty version 2.6.25, created on 2014-02-01 23:06:57
         compiled from print:174 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D3^D3D^D3D1A366%%print%3A174.inc'] = '32cd93c318e89bee5a307d848dbc7509';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:174', 2, false),array('function', 'metadata', 'print:174', 2, false),array('function', 'stylesheet', 'print:174', 2, false),array('function', 'content', 'print:174', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_32cd93c318e89bee5a307d848dbc7509_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32cd93c318e89bee5a307d848dbc7509','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_32cd93c318e89bee5a307d848dbc7509_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32cd93c318e89bee5a307d848dbc7509','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_32cd93c318e89bee5a307d848dbc7509_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32cd93c318e89bee5a307d848dbc7509','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_32cd93c318e89bee5a307d848dbc7509_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('32cd93c318e89bee5a307d848dbc7509','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
