<?php /* Smarty version 2.6.25, created on 2014-02-07 23:01:21
         compiled from print:97 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C0^C0E^C0E4677D%%print%3A97.inc'] = '48f91b479fdcc7f7bfa5094dc69cd94a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:97', 2, false),array('function', 'metadata', 'print:97', 2, false),array('function', 'stylesheet', 'print:97', 2, false),array('function', 'content', 'print:97', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_48f91b479fdcc7f7bfa5094dc69cd94a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48f91b479fdcc7f7bfa5094dc69cd94a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_48f91b479fdcc7f7bfa5094dc69cd94a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48f91b479fdcc7f7bfa5094dc69cd94a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_48f91b479fdcc7f7bfa5094dc69cd94a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48f91b479fdcc7f7bfa5094dc69cd94a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_48f91b479fdcc7f7bfa5094dc69cd94a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48f91b479fdcc7f7bfa5094dc69cd94a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
