<?php /* Smarty version 2.6.25, created on 2014-02-12 20:05:18
         compiled from print:238 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BC^BC4^BC4D9410%%print%3A238.inc'] = '5f59e72297fad19d15499903054017bd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:238', 2, false),array('function', 'metadata', 'print:238', 2, false),array('function', 'stylesheet', 'print:238', 2, false),array('function', 'content', 'print:238', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_5f59e72297fad19d15499903054017bd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f59e72297fad19d15499903054017bd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_5f59e72297fad19d15499903054017bd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f59e72297fad19d15499903054017bd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_5f59e72297fad19d15499903054017bd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f59e72297fad19d15499903054017bd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_5f59e72297fad19d15499903054017bd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('5f59e72297fad19d15499903054017bd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
