<?php /* Smarty version 2.6.25, created on 2014-02-11 22:45:37
         compiled from print:249 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%84^840^840B3241%%print%3A249.inc'] = '98bfdce03017991c0da32407c13a6438';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:249', 2, false),array('function', 'metadata', 'print:249', 2, false),array('function', 'stylesheet', 'print:249', 2, false),array('function', 'content', 'print:249', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_98bfdce03017991c0da32407c13a6438_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98bfdce03017991c0da32407c13a6438','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_98bfdce03017991c0da32407c13a6438_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98bfdce03017991c0da32407c13a6438','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_98bfdce03017991c0da32407c13a6438_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98bfdce03017991c0da32407c13a6438','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_98bfdce03017991c0da32407c13a6438_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('98bfdce03017991c0da32407c13a6438','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
