<?php /* Smarty version 2.6.25, created on 2014-02-11 06:50:50
         compiled from print:322 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%44^444^44412678%%print%3A322.inc'] = '119f7525d2c82d1f74aa250620abbcc4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:322', 2, false),array('function', 'metadata', 'print:322', 2, false),array('function', 'stylesheet', 'print:322', 2, false),array('function', 'content', 'print:322', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_119f7525d2c82d1f74aa250620abbcc4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('119f7525d2c82d1f74aa250620abbcc4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_119f7525d2c82d1f74aa250620abbcc4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('119f7525d2c82d1f74aa250620abbcc4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_119f7525d2c82d1f74aa250620abbcc4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('119f7525d2c82d1f74aa250620abbcc4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_119f7525d2c82d1f74aa250620abbcc4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('119f7525d2c82d1f74aa250620abbcc4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
