<?php /* Smarty version 2.6.25, created on 2014-02-12 20:41:00
         compiled from print:67 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%47^477^477C7BB2%%print%3A67.inc'] = '6adb2d26c47b64e63bb0cf931ccc55a5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:67', 2, false),array('function', 'metadata', 'print:67', 2, false),array('function', 'stylesheet', 'print:67', 2, false),array('function', 'content', 'print:67', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6adb2d26c47b64e63bb0cf931ccc55a5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6adb2d26c47b64e63bb0cf931ccc55a5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6adb2d26c47b64e63bb0cf931ccc55a5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6adb2d26c47b64e63bb0cf931ccc55a5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6adb2d26c47b64e63bb0cf931ccc55a5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6adb2d26c47b64e63bb0cf931ccc55a5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6adb2d26c47b64e63bb0cf931ccc55a5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6adb2d26c47b64e63bb0cf931ccc55a5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
