<?php /* Smarty version 2.6.25, created on 2014-02-11 06:58:38
         compiled from print:324 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AD^AD2^AD22834D%%print%3A324.inc'] = 'd798af384f910cc940bf89e386b687f5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:324', 2, false),array('function', 'metadata', 'print:324', 2, false),array('function', 'stylesheet', 'print:324', 2, false),array('function', 'content', 'print:324', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d798af384f910cc940bf89e386b687f5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d798af384f910cc940bf89e386b687f5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d798af384f910cc940bf89e386b687f5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d798af384f910cc940bf89e386b687f5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d798af384f910cc940bf89e386b687f5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d798af384f910cc940bf89e386b687f5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d798af384f910cc940bf89e386b687f5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d798af384f910cc940bf89e386b687f5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
