<?php /* Smarty version 2.6.25, created on 2014-02-10 13:36:46
         compiled from print:356 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%0C^0C6^0C6D74A6%%print%3A356.inc'] = '59a1837e0805df950911ff0f2f4e1af9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:356', 2, false),array('function', 'metadata', 'print:356', 2, false),array('function', 'stylesheet', 'print:356', 2, false),array('function', 'content', 'print:356', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_59a1837e0805df950911ff0f2f4e1af9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59a1837e0805df950911ff0f2f4e1af9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_59a1837e0805df950911ff0f2f4e1af9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59a1837e0805df950911ff0f2f4e1af9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_59a1837e0805df950911ff0f2f4e1af9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59a1837e0805df950911ff0f2f4e1af9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_59a1837e0805df950911ff0f2f4e1af9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('59a1837e0805df950911ff0f2f4e1af9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
