<?php /* Smarty version 2.6.25, created on 2014-02-12 00:02:16
         compiled from print:303 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%01^017^0170746C%%print%3A303.inc'] = '4dae966b507756802e3392746236e214';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:303', 2, false),array('function', 'metadata', 'print:303', 2, false),array('function', 'stylesheet', 'print:303', 2, false),array('function', 'content', 'print:303', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4dae966b507756802e3392746236e214_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dae966b507756802e3392746236e214','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4dae966b507756802e3392746236e214_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dae966b507756802e3392746236e214','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4dae966b507756802e3392746236e214_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dae966b507756802e3392746236e214','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4dae966b507756802e3392746236e214_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dae966b507756802e3392746236e214','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
