<?php /* Smarty version 2.6.25, created on 2014-02-10 17:26:09
         compiled from print:237 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2C^2CF^2CF28981%%print%3A237.inc'] = 'e46a1c134b2de4e755bab4253caa66f0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:237', 2, false),array('function', 'metadata', 'print:237', 2, false),array('function', 'stylesheet', 'print:237', 2, false),array('function', 'content', 'print:237', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e46a1c134b2de4e755bab4253caa66f0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e46a1c134b2de4e755bab4253caa66f0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e46a1c134b2de4e755bab4253caa66f0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e46a1c134b2de4e755bab4253caa66f0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e46a1c134b2de4e755bab4253caa66f0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e46a1c134b2de4e755bab4253caa66f0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e46a1c134b2de4e755bab4253caa66f0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e46a1c134b2de4e755bab4253caa66f0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
