<?php /* Smarty version 2.6.25, created on 2014-02-11 06:48:55
         compiled from print:246 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%14^14B^14B42FD0%%print%3A246.inc'] = '8b0e55f4ee081325009593bd24a0b73b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:246', 2, false),array('function', 'metadata', 'print:246', 2, false),array('function', 'stylesheet', 'print:246', 2, false),array('function', 'content', 'print:246', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8b0e55f4ee081325009593bd24a0b73b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8b0e55f4ee081325009593bd24a0b73b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8b0e55f4ee081325009593bd24a0b73b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8b0e55f4ee081325009593bd24a0b73b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8b0e55f4ee081325009593bd24a0b73b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8b0e55f4ee081325009593bd24a0b73b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8b0e55f4ee081325009593bd24a0b73b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8b0e55f4ee081325009593bd24a0b73b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
