<?php /* Smarty version 2.6.25, created on 2014-02-02 07:21:48
         compiled from print:146 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%16^16F^16F29189%%print%3A146.inc'] = '774091b392c3ae073fe29327f0b55adb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:146', 2, false),array('function', 'metadata', 'print:146', 2, false),array('function', 'stylesheet', 'print:146', 2, false),array('function', 'content', 'print:146', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_774091b392c3ae073fe29327f0b55adb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('774091b392c3ae073fe29327f0b55adb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_774091b392c3ae073fe29327f0b55adb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('774091b392c3ae073fe29327f0b55adb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_774091b392c3ae073fe29327f0b55adb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('774091b392c3ae073fe29327f0b55adb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_774091b392c3ae073fe29327f0b55adb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('774091b392c3ae073fe29327f0b55adb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
