<?php /* Smarty version 2.6.25, created on 2014-02-10 20:25:37
         compiled from print:95 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2E^2EE^2EEA0651%%print%3A95.inc'] = 'b2ae3b1737c3eb9f355fdad1ad9e3f52';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:95', 2, false),array('function', 'metadata', 'print:95', 2, false),array('function', 'stylesheet', 'print:95', 2, false),array('function', 'content', 'print:95', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b2ae3b1737c3eb9f355fdad1ad9e3f52_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ae3b1737c3eb9f355fdad1ad9e3f52','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b2ae3b1737c3eb9f355fdad1ad9e3f52_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ae3b1737c3eb9f355fdad1ad9e3f52','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b2ae3b1737c3eb9f355fdad1ad9e3f52_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ae3b1737c3eb9f355fdad1ad9e3f52','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b2ae3b1737c3eb9f355fdad1ad9e3f52_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ae3b1737c3eb9f355fdad1ad9e3f52','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
