<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:12
         compiled from print:308 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%96^96A^96A2ADE4%%print%3A308.inc'] = 'b2fc4d2d5cd5c951031e0d6662205c67';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:308', 2, false),array('function', 'metadata', 'print:308', 2, false),array('function', 'stylesheet', 'print:308', 2, false),array('function', 'content', 'print:308', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b2fc4d2d5cd5c951031e0d6662205c67_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2fc4d2d5cd5c951031e0d6662205c67','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b2fc4d2d5cd5c951031e0d6662205c67_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2fc4d2d5cd5c951031e0d6662205c67','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b2fc4d2d5cd5c951031e0d6662205c67_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2fc4d2d5cd5c951031e0d6662205c67','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b2fc4d2d5cd5c951031e0d6662205c67_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2fc4d2d5cd5c951031e0d6662205c67','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
