<?php /* Smarty version 2.6.25, created on 2014-02-03 23:11:10
         compiled from print:137 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2E^2EB^2EB437D8%%print%3A137.inc'] = '3ea664f97cecf91c6172f6cac097982f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:137', 2, false),array('function', 'metadata', 'print:137', 2, false),array('function', 'stylesheet', 'print:137', 2, false),array('function', 'content', 'print:137', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3ea664f97cecf91c6172f6cac097982f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3ea664f97cecf91c6172f6cac097982f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3ea664f97cecf91c6172f6cac097982f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3ea664f97cecf91c6172f6cac097982f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3ea664f97cecf91c6172f6cac097982f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3ea664f97cecf91c6172f6cac097982f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3ea664f97cecf91c6172f6cac097982f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3ea664f97cecf91c6172f6cac097982f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
