<?php /* Smarty version 2.6.25, created on 2014-02-03 11:25:21
         compiled from print:207 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%07^07D^07DFDA42%%print%3A207.inc'] = 'e8c5e861b6204bcaca288dc355e85183';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:207', 2, false),array('function', 'metadata', 'print:207', 2, false),array('function', 'stylesheet', 'print:207', 2, false),array('function', 'content', 'print:207', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e8c5e861b6204bcaca288dc355e85183_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e8c5e861b6204bcaca288dc355e85183','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e8c5e861b6204bcaca288dc355e85183_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e8c5e861b6204bcaca288dc355e85183','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e8c5e861b6204bcaca288dc355e85183_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e8c5e861b6204bcaca288dc355e85183','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e8c5e861b6204bcaca288dc355e85183_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e8c5e861b6204bcaca288dc355e85183','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
