<?php /* Smarty version 2.6.25, created on 2014-02-11 11:20:28
         compiled from print:161 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BA^BAA^BAA066A8%%print%3A161.inc'] = '627fba8f9870e2ad9491f2b8e1582ee7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:161', 2, false),array('function', 'metadata', 'print:161', 2, false),array('function', 'stylesheet', 'print:161', 2, false),array('function', 'content', 'print:161', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_627fba8f9870e2ad9491f2b8e1582ee7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('627fba8f9870e2ad9491f2b8e1582ee7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_627fba8f9870e2ad9491f2b8e1582ee7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('627fba8f9870e2ad9491f2b8e1582ee7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_627fba8f9870e2ad9491f2b8e1582ee7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('627fba8f9870e2ad9491f2b8e1582ee7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_627fba8f9870e2ad9491f2b8e1582ee7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('627fba8f9870e2ad9491f2b8e1582ee7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
