<?php /* Smarty version 2.6.25, created on 2014-02-02 04:08:21
         compiled from print:157 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%78^78E^78EE905E%%print%3A157.inc'] = 'dbaca8900705843ebdbbee219711f92b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:157', 2, false),array('function', 'metadata', 'print:157', 2, false),array('function', 'stylesheet', 'print:157', 2, false),array('function', 'content', 'print:157', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_dbaca8900705843ebdbbee219711f92b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dbaca8900705843ebdbbee219711f92b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_dbaca8900705843ebdbbee219711f92b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dbaca8900705843ebdbbee219711f92b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_dbaca8900705843ebdbbee219711f92b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dbaca8900705843ebdbbee219711f92b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_dbaca8900705843ebdbbee219711f92b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dbaca8900705843ebdbbee219711f92b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
