<?php /* Smarty version 2.6.25, created on 2014-02-12 18:08:58
         compiled from print:99 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%27^275^275C4A7A%%print%3A99.inc'] = '7514272c373023e862d9e80dd359a161';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:99', 2, false),array('function', 'metadata', 'print:99', 2, false),array('function', 'stylesheet', 'print:99', 2, false),array('function', 'content', 'print:99', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7514272c373023e862d9e80dd359a161_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7514272c373023e862d9e80dd359a161','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7514272c373023e862d9e80dd359a161_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7514272c373023e862d9e80dd359a161','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7514272c373023e862d9e80dd359a161_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7514272c373023e862d9e80dd359a161','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7514272c373023e862d9e80dd359a161_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7514272c373023e862d9e80dd359a161','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
