<?php /* Smarty version 2.6.25, created on 2014-02-13 00:33:04
         compiled from print:317 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%1F^1F0^1F068134%%print%3A317.inc'] = '711d50a123e1507a3d636db76f5191ff';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:317', 2, false),array('function', 'metadata', 'print:317', 2, false),array('function', 'stylesheet', 'print:317', 2, false),array('function', 'content', 'print:317', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_711d50a123e1507a3d636db76f5191ff_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('711d50a123e1507a3d636db76f5191ff','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_711d50a123e1507a3d636db76f5191ff_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('711d50a123e1507a3d636db76f5191ff','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_711d50a123e1507a3d636db76f5191ff_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('711d50a123e1507a3d636db76f5191ff','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_711d50a123e1507a3d636db76f5191ff_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('711d50a123e1507a3d636db76f5191ff','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
