<?php /* Smarty version 2.6.25, created on 2014-02-10 11:55:44
         compiled from print:245 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8D^8DB^8DBD7E6A%%print%3A245.inc'] = '825920c5c9a202d039235cf407ae407d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:245', 2, false),array('function', 'metadata', 'print:245', 2, false),array('function', 'stylesheet', 'print:245', 2, false),array('function', 'content', 'print:245', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_825920c5c9a202d039235cf407ae407d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('825920c5c9a202d039235cf407ae407d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_825920c5c9a202d039235cf407ae407d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('825920c5c9a202d039235cf407ae407d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_825920c5c9a202d039235cf407ae407d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('825920c5c9a202d039235cf407ae407d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_825920c5c9a202d039235cf407ae407d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('825920c5c9a202d039235cf407ae407d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
