<?php /* Smarty version 2.6.25, created on 2014-02-11 11:13:07
         compiled from print:78 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CE^CED^CED85762%%print%3A78.inc'] = 'b0c8c2f0245e15786df4446aba79e94f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:78', 2, false),array('function', 'metadata', 'print:78', 2, false),array('function', 'stylesheet', 'print:78', 2, false),array('function', 'content', 'print:78', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0c8c2f0245e15786df4446aba79e94f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c8c2f0245e15786df4446aba79e94f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0c8c2f0245e15786df4446aba79e94f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c8c2f0245e15786df4446aba79e94f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0c8c2f0245e15786df4446aba79e94f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c8c2f0245e15786df4446aba79e94f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0c8c2f0245e15786df4446aba79e94f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c8c2f0245e15786df4446aba79e94f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
