<?php /* Smarty version 2.6.25, created on 2014-02-11 01:47:15
         compiled from print:198 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%44^44E^44E4C2C3%%print%3A198.inc'] = '3fb499a6f040e1bd6191ebce2e9d2316';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:198', 2, false),array('function', 'metadata', 'print:198', 2, false),array('function', 'stylesheet', 'print:198', 2, false),array('function', 'content', 'print:198', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3fb499a6f040e1bd6191ebce2e9d2316_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3fb499a6f040e1bd6191ebce2e9d2316','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3fb499a6f040e1bd6191ebce2e9d2316_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3fb499a6f040e1bd6191ebce2e9d2316','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3fb499a6f040e1bd6191ebce2e9d2316_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3fb499a6f040e1bd6191ebce2e9d2316','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3fb499a6f040e1bd6191ebce2e9d2316_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3fb499a6f040e1bd6191ebce2e9d2316','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
