<?php /* Smarty version 2.6.25, created on 2014-02-10 12:00:06
         compiled from print:70 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C0^C00^C003DF50%%print%3A70.inc'] = 'c38e456f7d5201a2e70ecff6647dd206';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:70', 2, false),array('function', 'metadata', 'print:70', 2, false),array('function', 'stylesheet', 'print:70', 2, false),array('function', 'content', 'print:70', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c38e456f7d5201a2e70ecff6647dd206_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c38e456f7d5201a2e70ecff6647dd206','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c38e456f7d5201a2e70ecff6647dd206_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c38e456f7d5201a2e70ecff6647dd206','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c38e456f7d5201a2e70ecff6647dd206_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c38e456f7d5201a2e70ecff6647dd206','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c38e456f7d5201a2e70ecff6647dd206_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c38e456f7d5201a2e70ecff6647dd206','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
