<?php /* Smarty version 2.6.25, created on 2014-02-07 22:21:07
         compiled from print:152 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%08^088^088464D1%%print%3A152.inc'] = '374b67255b982a19b17cfb41c091d225';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:152', 2, false),array('function', 'metadata', 'print:152', 2, false),array('function', 'stylesheet', 'print:152', 2, false),array('function', 'content', 'print:152', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_374b67255b982a19b17cfb41c091d225_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('374b67255b982a19b17cfb41c091d225','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_374b67255b982a19b17cfb41c091d225_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('374b67255b982a19b17cfb41c091d225','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_374b67255b982a19b17cfb41c091d225_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('374b67255b982a19b17cfb41c091d225','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_374b67255b982a19b17cfb41c091d225_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('374b67255b982a19b17cfb41c091d225','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
