<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:09
         compiled from print:147 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%61^61F^61F5A11F%%print%3A147.inc'] = 'ee287a8864ef21a1896f2860490cba1e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:147', 2, false),array('function', 'metadata', 'print:147', 2, false),array('function', 'stylesheet', 'print:147', 2, false),array('function', 'content', 'print:147', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ee287a8864ef21a1896f2860490cba1e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee287a8864ef21a1896f2860490cba1e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ee287a8864ef21a1896f2860490cba1e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee287a8864ef21a1896f2860490cba1e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ee287a8864ef21a1896f2860490cba1e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee287a8864ef21a1896f2860490cba1e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ee287a8864ef21a1896f2860490cba1e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ee287a8864ef21a1896f2860490cba1e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
