<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:44
         compiled from print:231 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C5^C59^C5912CB4%%print%3A231.inc'] = '2d1487c55f58fb004e84049bcda98218';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:231', 2, false),array('function', 'metadata', 'print:231', 2, false),array('function', 'stylesheet', 'print:231', 2, false),array('function', 'content', 'print:231', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2d1487c55f58fb004e84049bcda98218_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d1487c55f58fb004e84049bcda98218','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2d1487c55f58fb004e84049bcda98218_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d1487c55f58fb004e84049bcda98218','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2d1487c55f58fb004e84049bcda98218_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d1487c55f58fb004e84049bcda98218','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2d1487c55f58fb004e84049bcda98218_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d1487c55f58fb004e84049bcda98218','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
