<?php /* Smarty version 2.6.25, created on 2014-02-12 06:25:42
         compiled from print:120 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A9^A9C^A9CB933A%%print%3A120.inc'] = '68f09cf8ed6433d5644a5ac79f8c8f45';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:120', 2, false),array('function', 'metadata', 'print:120', 2, false),array('function', 'stylesheet', 'print:120', 2, false),array('function', 'content', 'print:120', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_68f09cf8ed6433d5644a5ac79f8c8f45_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68f09cf8ed6433d5644a5ac79f8c8f45','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_68f09cf8ed6433d5644a5ac79f8c8f45_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68f09cf8ed6433d5644a5ac79f8c8f45','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_68f09cf8ed6433d5644a5ac79f8c8f45_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68f09cf8ed6433d5644a5ac79f8c8f45','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_68f09cf8ed6433d5644a5ac79f8c8f45_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('68f09cf8ed6433d5644a5ac79f8c8f45','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
