<?php /* Smarty version 2.6.25, created on 2014-02-04 20:20:20
         compiled from print:297 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D6^D61^D61D610B%%print%3A297.inc'] = 'd551db350f817286e96c792cef227840';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:297', 2, false),array('function', 'metadata', 'print:297', 2, false),array('function', 'stylesheet', 'print:297', 2, false),array('function', 'content', 'print:297', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d551db350f817286e96c792cef227840_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d551db350f817286e96c792cef227840','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d551db350f817286e96c792cef227840_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d551db350f817286e96c792cef227840','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d551db350f817286e96c792cef227840_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d551db350f817286e96c792cef227840','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d551db350f817286e96c792cef227840_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d551db350f817286e96c792cef227840','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
