<?php /* Smarty version 2.6.25, created on 2014-02-03 12:06:38
         compiled from print:254 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E3^E3A^E3A17FBD%%print%3A254.inc'] = '9271145951583a42f7cab899a5dbdfec';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:254', 2, false),array('function', 'metadata', 'print:254', 2, false),array('function', 'stylesheet', 'print:254', 2, false),array('function', 'content', 'print:254', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9271145951583a42f7cab899a5dbdfec_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9271145951583a42f7cab899a5dbdfec','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9271145951583a42f7cab899a5dbdfec_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9271145951583a42f7cab899a5dbdfec','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9271145951583a42f7cab899a5dbdfec_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9271145951583a42f7cab899a5dbdfec','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9271145951583a42f7cab899a5dbdfec_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9271145951583a42f7cab899a5dbdfec','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
