<?php /* Smarty version 2.6.25, created on 2014-02-11 12:08:11
         compiled from print:163 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%54^54A^54AE0784%%print%3A163.inc'] = 'fb1d58e2456fc7bc96b53f2c1903c4ed';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:163', 2, false),array('function', 'metadata', 'print:163', 2, false),array('function', 'stylesheet', 'print:163', 2, false),array('function', 'content', 'print:163', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_fb1d58e2456fc7bc96b53f2c1903c4ed_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fb1d58e2456fc7bc96b53f2c1903c4ed','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_fb1d58e2456fc7bc96b53f2c1903c4ed_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fb1d58e2456fc7bc96b53f2c1903c4ed','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_fb1d58e2456fc7bc96b53f2c1903c4ed_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fb1d58e2456fc7bc96b53f2c1903c4ed','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_fb1d58e2456fc7bc96b53f2c1903c4ed_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fb1d58e2456fc7bc96b53f2c1903c4ed','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
