<?php /* Smarty version 2.6.25, created on 2014-02-12 01:53:05
         compiled from print:186 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BA^BA4^BA47DE85%%print%3A186.inc'] = 'ca038dfd388084e9e5f7979c9e279f88';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:186', 2, false),array('function', 'metadata', 'print:186', 2, false),array('function', 'stylesheet', 'print:186', 2, false),array('function', 'content', 'print:186', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca038dfd388084e9e5f7979c9e279f88_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca038dfd388084e9e5f7979c9e279f88','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ca038dfd388084e9e5f7979c9e279f88_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca038dfd388084e9e5f7979c9e279f88','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ca038dfd388084e9e5f7979c9e279f88_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca038dfd388084e9e5f7979c9e279f88','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ca038dfd388084e9e5f7979c9e279f88_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca038dfd388084e9e5f7979c9e279f88','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
