<?php /* Smarty version 2.6.25, created on 2014-02-03 09:41:36
         compiled from print:226 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%42^42E^42EE8856%%print%3A226.inc'] = 'a2dce8dad7e87c0e3668fdd28a0cc5e5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:226', 2, false),array('function', 'metadata', 'print:226', 2, false),array('function', 'stylesheet', 'print:226', 2, false),array('function', 'content', 'print:226', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a2dce8dad7e87c0e3668fdd28a0cc5e5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2dce8dad7e87c0e3668fdd28a0cc5e5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a2dce8dad7e87c0e3668fdd28a0cc5e5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2dce8dad7e87c0e3668fdd28a0cc5e5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a2dce8dad7e87c0e3668fdd28a0cc5e5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2dce8dad7e87c0e3668fdd28a0cc5e5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a2dce8dad7e87c0e3668fdd28a0cc5e5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2dce8dad7e87c0e3668fdd28a0cc5e5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
