<?php /* Smarty version 2.6.25, created on 2014-02-01 23:09:30
         compiled from print:177 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%4A^4AD^4AD8F2DC%%print%3A177.inc'] = '15bf18ac04012427e0cf7c666504ddb6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:177', 2, false),array('function', 'metadata', 'print:177', 2, false),array('function', 'stylesheet', 'print:177', 2, false),array('function', 'content', 'print:177', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_15bf18ac04012427e0cf7c666504ddb6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('15bf18ac04012427e0cf7c666504ddb6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_15bf18ac04012427e0cf7c666504ddb6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('15bf18ac04012427e0cf7c666504ddb6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_15bf18ac04012427e0cf7c666504ddb6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('15bf18ac04012427e0cf7c666504ddb6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_15bf18ac04012427e0cf7c666504ddb6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('15bf18ac04012427e0cf7c666504ddb6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
