<?php /* Smarty version 2.6.25, created on 2014-02-04 19:00:05
         compiled from print:187 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CD^CD4^CD40EE13%%print%3A187.inc'] = '202058401c04890df4fe7138b517d370';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:187', 2, false),array('function', 'metadata', 'print:187', 2, false),array('function', 'stylesheet', 'print:187', 2, false),array('function', 'content', 'print:187', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_202058401c04890df4fe7138b517d370_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('202058401c04890df4fe7138b517d370','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_202058401c04890df4fe7138b517d370_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('202058401c04890df4fe7138b517d370','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_202058401c04890df4fe7138b517d370_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('202058401c04890df4fe7138b517d370','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_202058401c04890df4fe7138b517d370_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('202058401c04890df4fe7138b517d370','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
