<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:29
         compiled from print:310 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%81^816^81621497%%print%3A310.inc'] = '73bf33a933e858edf88dd6340709c5d0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:310', 2, false),array('function', 'metadata', 'print:310', 2, false),array('function', 'stylesheet', 'print:310', 2, false),array('function', 'content', 'print:310', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_73bf33a933e858edf88dd6340709c5d0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('73bf33a933e858edf88dd6340709c5d0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_73bf33a933e858edf88dd6340709c5d0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('73bf33a933e858edf88dd6340709c5d0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_73bf33a933e858edf88dd6340709c5d0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('73bf33a933e858edf88dd6340709c5d0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_73bf33a933e858edf88dd6340709c5d0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('73bf33a933e858edf88dd6340709c5d0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
