<?php /* Smarty version 2.6.25, created on 2014-02-12 09:37:27
         compiled from print:89 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%3E^3E4^3E477B3B%%print%3A89.inc'] = 'd33b32bcb1284e3033c4ba385d49ea86';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:89', 2, false),array('function', 'metadata', 'print:89', 2, false),array('function', 'stylesheet', 'print:89', 2, false),array('function', 'content', 'print:89', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d33b32bcb1284e3033c4ba385d49ea86_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b32bcb1284e3033c4ba385d49ea86','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d33b32bcb1284e3033c4ba385d49ea86_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b32bcb1284e3033c4ba385d49ea86','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d33b32bcb1284e3033c4ba385d49ea86_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b32bcb1284e3033c4ba385d49ea86','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d33b32bcb1284e3033c4ba385d49ea86_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b32bcb1284e3033c4ba385d49ea86','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
