<?php /* Smarty version 2.6.25, created on 2014-02-07 21:26:25
         compiled from print:105 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%EB^EB9^EB970537%%print%3A105.inc'] = 'c3da0c2c653b62c3b7fa14399a44c8d4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:105', 2, false),array('function', 'metadata', 'print:105', 2, false),array('function', 'stylesheet', 'print:105', 2, false),array('function', 'content', 'print:105', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c3da0c2c653b62c3b7fa14399a44c8d4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3da0c2c653b62c3b7fa14399a44c8d4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c3da0c2c653b62c3b7fa14399a44c8d4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3da0c2c653b62c3b7fa14399a44c8d4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c3da0c2c653b62c3b7fa14399a44c8d4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3da0c2c653b62c3b7fa14399a44c8d4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c3da0c2c653b62c3b7fa14399a44c8d4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3da0c2c653b62c3b7fa14399a44c8d4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
