<?php /* Smarty version 2.6.25, created on 2014-02-03 11:24:13
         compiled from print:300 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%98^987^987925D6%%print%3A300.inc'] = '33e9763c65a24f8bdf6a93e9facabf5c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:300', 2, false),array('function', 'metadata', 'print:300', 2, false),array('function', 'stylesheet', 'print:300', 2, false),array('function', 'content', 'print:300', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_33e9763c65a24f8bdf6a93e9facabf5c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33e9763c65a24f8bdf6a93e9facabf5c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_33e9763c65a24f8bdf6a93e9facabf5c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33e9763c65a24f8bdf6a93e9facabf5c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_33e9763c65a24f8bdf6a93e9facabf5c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33e9763c65a24f8bdf6a93e9facabf5c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_33e9763c65a24f8bdf6a93e9facabf5c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('33e9763c65a24f8bdf6a93e9facabf5c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
