<?php /* Smarty version 2.6.25, created on 2014-02-03 11:42:59
         compiled from print:233 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2B^2B9^2B9F4D98%%print%3A233.inc'] = '10225353b1e7ce1eb8bb1a97501ef997';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:233', 2, false),array('function', 'metadata', 'print:233', 2, false),array('function', 'stylesheet', 'print:233', 2, false),array('function', 'content', 'print:233', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_10225353b1e7ce1eb8bb1a97501ef997_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('10225353b1e7ce1eb8bb1a97501ef997','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_10225353b1e7ce1eb8bb1a97501ef997_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('10225353b1e7ce1eb8bb1a97501ef997','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_10225353b1e7ce1eb8bb1a97501ef997_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('10225353b1e7ce1eb8bb1a97501ef997','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_10225353b1e7ce1eb8bb1a97501ef997_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('10225353b1e7ce1eb8bb1a97501ef997','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
