<?php /* Smarty version 2.6.25, created on 2014-02-04 19:50:16
         compiled from print:289 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%28^28B^28BE7D4D%%print%3A289.inc'] = 'cb3cae79b9b9d6a896080408e30de280';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:289', 2, false),array('function', 'metadata', 'print:289', 2, false),array('function', 'stylesheet', 'print:289', 2, false),array('function', 'content', 'print:289', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cb3cae79b9b9d6a896080408e30de280_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cb3cae79b9b9d6a896080408e30de280','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cb3cae79b9b9d6a896080408e30de280_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cb3cae79b9b9d6a896080408e30de280','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cb3cae79b9b9d6a896080408e30de280_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cb3cae79b9b9d6a896080408e30de280','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cb3cae79b9b9d6a896080408e30de280_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cb3cae79b9b9d6a896080408e30de280','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
