<?php /* Smarty version 2.6.25, created on 2014-02-11 01:19:05
         compiled from print:197 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D4^D45^D45BDF52%%print%3A197.inc'] = 'd0549a23ba85dfac830b8dae972521a6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:197', 2, false),array('function', 'metadata', 'print:197', 2, false),array('function', 'stylesheet', 'print:197', 2, false),array('function', 'content', 'print:197', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d0549a23ba85dfac830b8dae972521a6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0549a23ba85dfac830b8dae972521a6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d0549a23ba85dfac830b8dae972521a6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0549a23ba85dfac830b8dae972521a6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d0549a23ba85dfac830b8dae972521a6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0549a23ba85dfac830b8dae972521a6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d0549a23ba85dfac830b8dae972521a6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d0549a23ba85dfac830b8dae972521a6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
