<?php /* Smarty version 2.6.25, created on 2014-02-12 23:33:30
         compiled from print:90 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5E^5E8^5E80F2DE%%print%3A90.inc'] = '012d268b5452ab84c5990f944f4d40de';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:90', 2, false),array('function', 'metadata', 'print:90', 2, false),array('function', 'stylesheet', 'print:90', 2, false),array('function', 'content', 'print:90', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_012d268b5452ab84c5990f944f4d40de_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('012d268b5452ab84c5990f944f4d40de','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_012d268b5452ab84c5990f944f4d40de_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('012d268b5452ab84c5990f944f4d40de','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_012d268b5452ab84c5990f944f4d40de_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('012d268b5452ab84c5990f944f4d40de','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_012d268b5452ab84c5990f944f4d40de_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('012d268b5452ab84c5990f944f4d40de','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
