<?php /* Smarty version 2.6.25, created on 2014-02-11 06:51:16
         compiled from print:202 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%77^77B^77B52ECD%%print%3A202.inc'] = '2a9af09d8015739a244ae517dc8115fb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:202', 2, false),array('function', 'metadata', 'print:202', 2, false),array('function', 'stylesheet', 'print:202', 2, false),array('function', 'content', 'print:202', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2a9af09d8015739a244ae517dc8115fb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a9af09d8015739a244ae517dc8115fb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2a9af09d8015739a244ae517dc8115fb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a9af09d8015739a244ae517dc8115fb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2a9af09d8015739a244ae517dc8115fb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a9af09d8015739a244ae517dc8115fb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2a9af09d8015739a244ae517dc8115fb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a9af09d8015739a244ae517dc8115fb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
