<?php /* Smarty version 2.6.25, created on 2014-02-12 16:39:47
         compiled from print:76 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%29^296^29607A65%%print%3A76.inc'] = 'efed4055cef198f474dfa1f931beff02';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:76', 2, false),array('function', 'metadata', 'print:76', 2, false),array('function', 'stylesheet', 'print:76', 2, false),array('function', 'content', 'print:76', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_efed4055cef198f474dfa1f931beff02_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efed4055cef198f474dfa1f931beff02','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_efed4055cef198f474dfa1f931beff02_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efed4055cef198f474dfa1f931beff02','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_efed4055cef198f474dfa1f931beff02_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efed4055cef198f474dfa1f931beff02','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_efed4055cef198f474dfa1f931beff02_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('efed4055cef198f474dfa1f931beff02','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
