<?php /* Smarty version 2.6.25, created on 2014-02-11 10:01:54
         compiled from print:343 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%65^651^651CB168%%print%3A343.inc'] = 'ae84e5191fc626e2d0e3c2e99371ffed';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:343', 2, false),array('function', 'metadata', 'print:343', 2, false),array('function', 'stylesheet', 'print:343', 2, false),array('function', 'content', 'print:343', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ae84e5191fc626e2d0e3c2e99371ffed_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae84e5191fc626e2d0e3c2e99371ffed','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ae84e5191fc626e2d0e3c2e99371ffed_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae84e5191fc626e2d0e3c2e99371ffed','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ae84e5191fc626e2d0e3c2e99371ffed_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae84e5191fc626e2d0e3c2e99371ffed','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ae84e5191fc626e2d0e3c2e99371ffed_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ae84e5191fc626e2d0e3c2e99371ffed','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
