<?php /* Smarty version 2.6.25, created on 2014-02-12 03:57:09
         compiled from print:363 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%57^572^572AD3EA%%print%3A363.inc'] = 'b39b9882403c94737c91e9731db128f7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:363', 2, false),array('function', 'metadata', 'print:363', 2, false),array('function', 'stylesheet', 'print:363', 2, false),array('function', 'content', 'print:363', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b39b9882403c94737c91e9731db128f7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b39b9882403c94737c91e9731db128f7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b39b9882403c94737c91e9731db128f7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b39b9882403c94737c91e9731db128f7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b39b9882403c94737c91e9731db128f7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b39b9882403c94737c91e9731db128f7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b39b9882403c94737c91e9731db128f7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b39b9882403c94737c91e9731db128f7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
