<?php /* Smarty version 2.6.25, created on 2014-02-12 17:09:24
         compiled from print:255 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%94^94A^94A64F2B%%print%3A255.inc'] = '35ed8d8edfb95fc39ec63cb7d42fda66';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:255', 2, false),array('function', 'metadata', 'print:255', 2, false),array('function', 'stylesheet', 'print:255', 2, false),array('function', 'content', 'print:255', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_35ed8d8edfb95fc39ec63cb7d42fda66_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35ed8d8edfb95fc39ec63cb7d42fda66','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_35ed8d8edfb95fc39ec63cb7d42fda66_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35ed8d8edfb95fc39ec63cb7d42fda66','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_35ed8d8edfb95fc39ec63cb7d42fda66_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35ed8d8edfb95fc39ec63cb7d42fda66','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_35ed8d8edfb95fc39ec63cb7d42fda66_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35ed8d8edfb95fc39ec63cb7d42fda66','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
