<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:23
         compiled from print:140 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%FF^FF9^FF9134BC%%print%3A140.inc'] = '300f9a64502fef1d2d147c21b9c334cf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:140', 2, false),array('function', 'metadata', 'print:140', 2, false),array('function', 'stylesheet', 'print:140', 2, false),array('function', 'content', 'print:140', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_300f9a64502fef1d2d147c21b9c334cf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('300f9a64502fef1d2d147c21b9c334cf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_300f9a64502fef1d2d147c21b9c334cf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('300f9a64502fef1d2d147c21b9c334cf','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_300f9a64502fef1d2d147c21b9c334cf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('300f9a64502fef1d2d147c21b9c334cf','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_300f9a64502fef1d2d147c21b9c334cf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('300f9a64502fef1d2d147c21b9c334cf','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
