<?php /* Smarty version 2.6.25, created on 2014-02-12 07:09:23
         compiled from print:209 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E0^E06^E067F745%%print%3A209.inc'] = 'a6afc8b9769cd8ca5aa175d049d85166';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:209', 2, false),array('function', 'metadata', 'print:209', 2, false),array('function', 'stylesheet', 'print:209', 2, false),array('function', 'content', 'print:209', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a6afc8b9769cd8ca5aa175d049d85166_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6afc8b9769cd8ca5aa175d049d85166','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a6afc8b9769cd8ca5aa175d049d85166_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6afc8b9769cd8ca5aa175d049d85166','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a6afc8b9769cd8ca5aa175d049d85166_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6afc8b9769cd8ca5aa175d049d85166','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a6afc8b9769cd8ca5aa175d049d85166_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a6afc8b9769cd8ca5aa175d049d85166','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
