<?php /* Smarty version 2.6.25, created on 2014-02-12 04:12:07
         compiled from print:307 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%06^061^061DB075%%print%3A307.inc'] = '739e76a065ff2bfd3bf2f54b423eaf71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:307', 2, false),array('function', 'metadata', 'print:307', 2, false),array('function', 'stylesheet', 'print:307', 2, false),array('function', 'content', 'print:307', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_739e76a065ff2bfd3bf2f54b423eaf71_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('739e76a065ff2bfd3bf2f54b423eaf71','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_739e76a065ff2bfd3bf2f54b423eaf71_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('739e76a065ff2bfd3bf2f54b423eaf71','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_739e76a065ff2bfd3bf2f54b423eaf71_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('739e76a065ff2bfd3bf2f54b423eaf71','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_739e76a065ff2bfd3bf2f54b423eaf71_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('739e76a065ff2bfd3bf2f54b423eaf71','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
