<?php /* Smarty version 2.6.25, created on 2014-02-01 23:12:21
         compiled from print:169 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B4^B47^B47BEE9A%%print%3A169.inc'] = 'b7a2bbd4637d1bd42b56ad7c8b5e820f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:169', 2, false),array('function', 'metadata', 'print:169', 2, false),array('function', 'stylesheet', 'print:169', 2, false),array('function', 'content', 'print:169', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b7a2bbd4637d1bd42b56ad7c8b5e820f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b7a2bbd4637d1bd42b56ad7c8b5e820f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b7a2bbd4637d1bd42b56ad7c8b5e820f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b7a2bbd4637d1bd42b56ad7c8b5e820f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b7a2bbd4637d1bd42b56ad7c8b5e820f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b7a2bbd4637d1bd42b56ad7c8b5e820f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b7a2bbd4637d1bd42b56ad7c8b5e820f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b7a2bbd4637d1bd42b56ad7c8b5e820f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
