<?php /* Smarty version 2.6.25, created on 2014-02-07 22:17:26
         compiled from print:183 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CA^CA2^CA2D2A0A%%print%3A183.inc'] = '050591daa7c4b5390f553a3891a92356';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:183', 2, false),array('function', 'metadata', 'print:183', 2, false),array('function', 'stylesheet', 'print:183', 2, false),array('function', 'content', 'print:183', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_050591daa7c4b5390f553a3891a92356_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050591daa7c4b5390f553a3891a92356','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_050591daa7c4b5390f553a3891a92356_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050591daa7c4b5390f553a3891a92356','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_050591daa7c4b5390f553a3891a92356_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050591daa7c4b5390f553a3891a92356','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_050591daa7c4b5390f553a3891a92356_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('050591daa7c4b5390f553a3891a92356','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
