<?php /* Smarty version 2.6.25, created on 2014-02-04 18:13:39
         compiled from print:205 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E9^E9D^E9D1BB6E%%print%3A205.inc'] = '0ce9f494c9fc0403a6e3cc29dc5b453b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:205', 2, false),array('function', 'metadata', 'print:205', 2, false),array('function', 'stylesheet', 'print:205', 2, false),array('function', 'content', 'print:205', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0ce9f494c9fc0403a6e3cc29dc5b453b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0ce9f494c9fc0403a6e3cc29dc5b453b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0ce9f494c9fc0403a6e3cc29dc5b453b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0ce9f494c9fc0403a6e3cc29dc5b453b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0ce9f494c9fc0403a6e3cc29dc5b453b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0ce9f494c9fc0403a6e3cc29dc5b453b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0ce9f494c9fc0403a6e3cc29dc5b453b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0ce9f494c9fc0403a6e3cc29dc5b453b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
