<?php /* Smarty version 2.6.25, created on 2014-02-13 00:22:21
         compiled from print:104 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9C^9C9^9C9035A1%%print%3A104.inc'] = '848d9317cbbc1d305df0559e7c65883d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:104', 2, false),array('function', 'metadata', 'print:104', 2, false),array('function', 'stylesheet', 'print:104', 2, false),array('function', 'content', 'print:104', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_848d9317cbbc1d305df0559e7c65883d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('848d9317cbbc1d305df0559e7c65883d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_848d9317cbbc1d305df0559e7c65883d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('848d9317cbbc1d305df0559e7c65883d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_848d9317cbbc1d305df0559e7c65883d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('848d9317cbbc1d305df0559e7c65883d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_848d9317cbbc1d305df0559e7c65883d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('848d9317cbbc1d305df0559e7c65883d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
