<?php /* Smarty version 2.6.25, created on 2014-02-11 12:37:29
         compiled from print:259 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9D^9D1^9D100300%%print%3A259.inc'] = '48ac86ee279483d72a698942897dd7bc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:259', 2, false),array('function', 'metadata', 'print:259', 2, false),array('function', 'stylesheet', 'print:259', 2, false),array('function', 'content', 'print:259', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_48ac86ee279483d72a698942897dd7bc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ac86ee279483d72a698942897dd7bc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_48ac86ee279483d72a698942897dd7bc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ac86ee279483d72a698942897dd7bc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_48ac86ee279483d72a698942897dd7bc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ac86ee279483d72a698942897dd7bc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_48ac86ee279483d72a698942897dd7bc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('48ac86ee279483d72a698942897dd7bc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
