<?php /* Smarty version 2.6.25, created on 2014-02-03 11:53:59
         compiled from print:110 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%82^82E^82E6C0F9%%print%3A110.inc'] = 'b8e8d7d83d7fed229de76e62dc10a0ac';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:110', 2, false),array('function', 'metadata', 'print:110', 2, false),array('function', 'stylesheet', 'print:110', 2, false),array('function', 'content', 'print:110', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b8e8d7d83d7fed229de76e62dc10a0ac_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8e8d7d83d7fed229de76e62dc10a0ac','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b8e8d7d83d7fed229de76e62dc10a0ac_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8e8d7d83d7fed229de76e62dc10a0ac','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b8e8d7d83d7fed229de76e62dc10a0ac_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8e8d7d83d7fed229de76e62dc10a0ac','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b8e8d7d83d7fed229de76e62dc10a0ac_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b8e8d7d83d7fed229de76e62dc10a0ac','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
