<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:46
         compiled from print:313 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%18^186^186B452D%%print%3A313.inc'] = '7b5fbb2d84b7ed7563b69b990dabbb0d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:313', 2, false),array('function', 'metadata', 'print:313', 2, false),array('function', 'stylesheet', 'print:313', 2, false),array('function', 'content', 'print:313', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7b5fbb2d84b7ed7563b69b990dabbb0d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b5fbb2d84b7ed7563b69b990dabbb0d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7b5fbb2d84b7ed7563b69b990dabbb0d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b5fbb2d84b7ed7563b69b990dabbb0d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7b5fbb2d84b7ed7563b69b990dabbb0d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b5fbb2d84b7ed7563b69b990dabbb0d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7b5fbb2d84b7ed7563b69b990dabbb0d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7b5fbb2d84b7ed7563b69b990dabbb0d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
