<?php /* Smarty version 2.6.25, created on 2014-02-12 18:50:09
         compiled from print:337 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2D^2D3^2D30E3B6%%print%3A337.inc'] = '9c62eb5482ec6dc8f65058d3ccd2fd90';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:337', 2, false),array('function', 'metadata', 'print:337', 2, false),array('function', 'stylesheet', 'print:337', 2, false),array('function', 'content', 'print:337', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9c62eb5482ec6dc8f65058d3ccd2fd90_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9c62eb5482ec6dc8f65058d3ccd2fd90','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9c62eb5482ec6dc8f65058d3ccd2fd90_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9c62eb5482ec6dc8f65058d3ccd2fd90','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9c62eb5482ec6dc8f65058d3ccd2fd90_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9c62eb5482ec6dc8f65058d3ccd2fd90','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9c62eb5482ec6dc8f65058d3ccd2fd90_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9c62eb5482ec6dc8f65058d3ccd2fd90','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
