<?php /* Smarty version 2.6.25, created on 2014-02-07 22:39:54
         compiled from print:248 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F3^F30^F30C02D7%%print%3A248.inc'] = 'f69a4dd6290d47e0eefb6f8574146de8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:248', 2, false),array('function', 'metadata', 'print:248', 2, false),array('function', 'stylesheet', 'print:248', 2, false),array('function', 'content', 'print:248', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f69a4dd6290d47e0eefb6f8574146de8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f69a4dd6290d47e0eefb6f8574146de8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f69a4dd6290d47e0eefb6f8574146de8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f69a4dd6290d47e0eefb6f8574146de8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f69a4dd6290d47e0eefb6f8574146de8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f69a4dd6290d47e0eefb6f8574146de8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f69a4dd6290d47e0eefb6f8574146de8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f69a4dd6290d47e0eefb6f8574146de8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
