<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:25
         compiled from print:114 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%85^858^858B04E0%%print%3A114.inc'] = 'f9195f534bc6bb2dff4ee8f1da08fe53';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:114', 2, false),array('function', 'metadata', 'print:114', 2, false),array('function', 'stylesheet', 'print:114', 2, false),array('function', 'content', 'print:114', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f9195f534bc6bb2dff4ee8f1da08fe53_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f9195f534bc6bb2dff4ee8f1da08fe53','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f9195f534bc6bb2dff4ee8f1da08fe53_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f9195f534bc6bb2dff4ee8f1da08fe53','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f9195f534bc6bb2dff4ee8f1da08fe53_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f9195f534bc6bb2dff4ee8f1da08fe53','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f9195f534bc6bb2dff4ee8f1da08fe53_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f9195f534bc6bb2dff4ee8f1da08fe53','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
