<?php /* Smarty version 2.6.25, created on 2014-02-12 23:58:45
         compiled from print:159 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9F^9F5^9F56BD59%%print%3A159.inc'] = 'bde59d24002ba520bd46c756dbe82c78';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:159', 2, false),array('function', 'metadata', 'print:159', 2, false),array('function', 'stylesheet', 'print:159', 2, false),array('function', 'content', 'print:159', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bde59d24002ba520bd46c756dbe82c78_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bde59d24002ba520bd46c756dbe82c78','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bde59d24002ba520bd46c756dbe82c78_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bde59d24002ba520bd46c756dbe82c78','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bde59d24002ba520bd46c756dbe82c78_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bde59d24002ba520bd46c756dbe82c78','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bde59d24002ba520bd46c756dbe82c78_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bde59d24002ba520bd46c756dbe82c78','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
