<?php /* Smarty version 2.6.25, created on 2014-02-12 03:09:45
         compiled from print:299 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%31^31A^31A54C0C%%print%3A299.inc'] = 'fdd31d61099814b95f13fe57c43f1802';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:299', 2, false),array('function', 'metadata', 'print:299', 2, false),array('function', 'stylesheet', 'print:299', 2, false),array('function', 'content', 'print:299', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_fdd31d61099814b95f13fe57c43f1802_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fdd31d61099814b95f13fe57c43f1802','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_fdd31d61099814b95f13fe57c43f1802_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fdd31d61099814b95f13fe57c43f1802','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_fdd31d61099814b95f13fe57c43f1802_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fdd31d61099814b95f13fe57c43f1802','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_fdd31d61099814b95f13fe57c43f1802_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fdd31d61099814b95f13fe57c43f1802','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
