<?php /* Smarty version 2.6.25, created on 2014-02-04 19:43:09
         compiled from print:132 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5E^5ED^5EDEC357%%print%3A132.inc'] = 'c8a213e6e8261484bed2a911828e66e0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:132', 2, false),array('function', 'metadata', 'print:132', 2, false),array('function', 'stylesheet', 'print:132', 2, false),array('function', 'content', 'print:132', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c8a213e6e8261484bed2a911828e66e0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8a213e6e8261484bed2a911828e66e0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c8a213e6e8261484bed2a911828e66e0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8a213e6e8261484bed2a911828e66e0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c8a213e6e8261484bed2a911828e66e0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8a213e6e8261484bed2a911828e66e0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c8a213e6e8261484bed2a911828e66e0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8a213e6e8261484bed2a911828e66e0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
