<?php /* Smarty version 2.6.25, created on 2014-02-11 16:02:00
         compiled from print:125 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D9^D9A^D9A167B5%%print%3A125.inc'] = '379374ba8d24fb97c27bbaa9063e641f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:125', 2, false),array('function', 'metadata', 'print:125', 2, false),array('function', 'stylesheet', 'print:125', 2, false),array('function', 'content', 'print:125', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_379374ba8d24fb97c27bbaa9063e641f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('379374ba8d24fb97c27bbaa9063e641f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_379374ba8d24fb97c27bbaa9063e641f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('379374ba8d24fb97c27bbaa9063e641f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_379374ba8d24fb97c27bbaa9063e641f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('379374ba8d24fb97c27bbaa9063e641f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_379374ba8d24fb97c27bbaa9063e641f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('379374ba8d24fb97c27bbaa9063e641f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
