<?php /* Smarty version 2.6.25, created on 2014-02-12 20:49:54
         compiled from print:349 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%85^85C^85C95876%%print%3A349.inc'] = 'e1abf78a554e66383592ec1eb33d117b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:349', 2, false),array('function', 'metadata', 'print:349', 2, false),array('function', 'stylesheet', 'print:349', 2, false),array('function', 'content', 'print:349', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e1abf78a554e66383592ec1eb33d117b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1abf78a554e66383592ec1eb33d117b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e1abf78a554e66383592ec1eb33d117b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1abf78a554e66383592ec1eb33d117b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e1abf78a554e66383592ec1eb33d117b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1abf78a554e66383592ec1eb33d117b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e1abf78a554e66383592ec1eb33d117b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1abf78a554e66383592ec1eb33d117b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
