<?php /* Smarty version 2.6.25, created on 2014-02-10 23:27:53
         compiled from print:139 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C9^C90^C90C1ADF%%print%3A139.inc'] = '57cc91fbee50f5b7da86b250255f6e61';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:139', 2, false),array('function', 'metadata', 'print:139', 2, false),array('function', 'stylesheet', 'print:139', 2, false),array('function', 'content', 'print:139', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_57cc91fbee50f5b7da86b250255f6e61_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57cc91fbee50f5b7da86b250255f6e61','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_57cc91fbee50f5b7da86b250255f6e61_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57cc91fbee50f5b7da86b250255f6e61','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_57cc91fbee50f5b7da86b250255f6e61_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57cc91fbee50f5b7da86b250255f6e61','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_57cc91fbee50f5b7da86b250255f6e61_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('57cc91fbee50f5b7da86b250255f6e61','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
