<?php /* Smarty version 2.6.25, created on 2014-02-12 15:58:23
         compiled from print:347 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%62^627^62717571%%print%3A347.inc'] = '2fce1d926efdc3737a0402c399eefc32';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:347', 2, false),array('function', 'metadata', 'print:347', 2, false),array('function', 'stylesheet', 'print:347', 2, false),array('function', 'content', 'print:347', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2fce1d926efdc3737a0402c399eefc32_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fce1d926efdc3737a0402c399eefc32','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2fce1d926efdc3737a0402c399eefc32_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fce1d926efdc3737a0402c399eefc32','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2fce1d926efdc3737a0402c399eefc32_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fce1d926efdc3737a0402c399eefc32','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2fce1d926efdc3737a0402c399eefc32_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2fce1d926efdc3737a0402c399eefc32','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
