<?php /* Smarty version 2.6.25, created on 2014-02-07 21:48:42
         compiled from print:320 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AA^AA4^AA4F4754%%print%3A320.inc'] = 'a2d4570c8cf374b504521eeeb7c82ec0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:320', 2, false),array('function', 'metadata', 'print:320', 2, false),array('function', 'stylesheet', 'print:320', 2, false),array('function', 'content', 'print:320', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a2d4570c8cf374b504521eeeb7c82ec0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2d4570c8cf374b504521eeeb7c82ec0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a2d4570c8cf374b504521eeeb7c82ec0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2d4570c8cf374b504521eeeb7c82ec0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a2d4570c8cf374b504521eeeb7c82ec0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2d4570c8cf374b504521eeeb7c82ec0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a2d4570c8cf374b504521eeeb7c82ec0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a2d4570c8cf374b504521eeeb7c82ec0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
