<?php /* Smarty version 2.6.25, created on 2014-02-11 07:36:41
         compiled from print:162 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%23^23A^23A93712%%print%3A162.inc'] = '601861b785d26bdaa9b1e73ad01fd5fe';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:162', 2, false),array('function', 'metadata', 'print:162', 2, false),array('function', 'stylesheet', 'print:162', 2, false),array('function', 'content', 'print:162', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_601861b785d26bdaa9b1e73ad01fd5fe_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('601861b785d26bdaa9b1e73ad01fd5fe','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_601861b785d26bdaa9b1e73ad01fd5fe_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('601861b785d26bdaa9b1e73ad01fd5fe','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_601861b785d26bdaa9b1e73ad01fd5fe_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('601861b785d26bdaa9b1e73ad01fd5fe','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_601861b785d26bdaa9b1e73ad01fd5fe_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('601861b785d26bdaa9b1e73ad01fd5fe','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
