<?php /* Smarty version 2.6.25, created on 2014-02-04 17:49:07
         compiled from print:286 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B8^B80^B80160DC%%print%3A286.inc'] = 'b9a973a46b6779a9bd4879e11b589f3b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:286', 2, false),array('function', 'metadata', 'print:286', 2, false),array('function', 'stylesheet', 'print:286', 2, false),array('function', 'content', 'print:286', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b9a973a46b6779a9bd4879e11b589f3b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b9a973a46b6779a9bd4879e11b589f3b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b9a973a46b6779a9bd4879e11b589f3b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b9a973a46b6779a9bd4879e11b589f3b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b9a973a46b6779a9bd4879e11b589f3b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b9a973a46b6779a9bd4879e11b589f3b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b9a973a46b6779a9bd4879e11b589f3b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b9a973a46b6779a9bd4879e11b589f3b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
