<?php /* Smarty version 2.6.25, created on 2014-02-10 09:57:26
         compiled from print:79 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B9^B9D^B9DF67F4%%print%3A79.inc'] = 'e1e1c599eae18ec592dac9ef39aff06b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:79', 2, false),array('function', 'metadata', 'print:79', 2, false),array('function', 'stylesheet', 'print:79', 2, false),array('function', 'content', 'print:79', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e1e1c599eae18ec592dac9ef39aff06b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1e1c599eae18ec592dac9ef39aff06b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e1e1c599eae18ec592dac9ef39aff06b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1e1c599eae18ec592dac9ef39aff06b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e1e1c599eae18ec592dac9ef39aff06b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1e1c599eae18ec592dac9ef39aff06b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e1e1c599eae18ec592dac9ef39aff06b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e1e1c599eae18ec592dac9ef39aff06b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
