<?php /* Smarty version 2.6.25, created on 2014-02-11 06:29:17
         compiled from print:94 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%59^59E^59ED36C7%%print%3A94.inc'] = '9e0ee3438d3391bdbfd085f78044c1f1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:94', 2, false),array('function', 'metadata', 'print:94', 2, false),array('function', 'stylesheet', 'print:94', 2, false),array('function', 'content', 'print:94', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9e0ee3438d3391bdbfd085f78044c1f1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e0ee3438d3391bdbfd085f78044c1f1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9e0ee3438d3391bdbfd085f78044c1f1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e0ee3438d3391bdbfd085f78044c1f1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9e0ee3438d3391bdbfd085f78044c1f1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e0ee3438d3391bdbfd085f78044c1f1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9e0ee3438d3391bdbfd085f78044c1f1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9e0ee3438d3391bdbfd085f78044c1f1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
