<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:26
         compiled from print:155 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%96^96E^96E0F172%%print%3A155.inc'] = '65a27f412a8fcbc799999ae72f6bd7e9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:155', 2, false),array('function', 'metadata', 'print:155', 2, false),array('function', 'stylesheet', 'print:155', 2, false),array('function', 'content', 'print:155', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_65a27f412a8fcbc799999ae72f6bd7e9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65a27f412a8fcbc799999ae72f6bd7e9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_65a27f412a8fcbc799999ae72f6bd7e9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65a27f412a8fcbc799999ae72f6bd7e9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_65a27f412a8fcbc799999ae72f6bd7e9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65a27f412a8fcbc799999ae72f6bd7e9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_65a27f412a8fcbc799999ae72f6bd7e9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('65a27f412a8fcbc799999ae72f6bd7e9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
