<?php /* Smarty version 2.6.25, created on 2014-02-02 08:57:01
         compiled from print:164 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CA^CAC^CACA9227%%print%3A164.inc'] = '8f76cd370c0f305d34314d5885040deb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:164', 2, false),array('function', 'metadata', 'print:164', 2, false),array('function', 'stylesheet', 'print:164', 2, false),array('function', 'content', 'print:164', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8f76cd370c0f305d34314d5885040deb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8f76cd370c0f305d34314d5885040deb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8f76cd370c0f305d34314d5885040deb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8f76cd370c0f305d34314d5885040deb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8f76cd370c0f305d34314d5885040deb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8f76cd370c0f305d34314d5885040deb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8f76cd370c0f305d34314d5885040deb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8f76cd370c0f305d34314d5885040deb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
