<?php /* Smarty version 2.6.25, created on 2014-02-04 18:33:55
         compiled from print:201 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%EE^EEB^EEBC7F77%%print%3A201.inc'] = 'd39bea27e3505d45172e86b106149337';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:201', 2, false),array('function', 'metadata', 'print:201', 2, false),array('function', 'stylesheet', 'print:201', 2, false),array('function', 'content', 'print:201', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d39bea27e3505d45172e86b106149337_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d39bea27e3505d45172e86b106149337','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d39bea27e3505d45172e86b106149337_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d39bea27e3505d45172e86b106149337','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d39bea27e3505d45172e86b106149337_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d39bea27e3505d45172e86b106149337','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d39bea27e3505d45172e86b106149337_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d39bea27e3505d45172e86b106149337','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
