<?php /* Smarty version 2.6.25, created on 2014-02-07 22:51:30
         compiled from print:225 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%DB^DBE^DBE7D9EC%%print%3A225.inc'] = '2a15e2337afae7eb8578483035e48b8f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:225', 2, false),array('function', 'metadata', 'print:225', 2, false),array('function', 'stylesheet', 'print:225', 2, false),array('function', 'content', 'print:225', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2a15e2337afae7eb8578483035e48b8f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a15e2337afae7eb8578483035e48b8f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2a15e2337afae7eb8578483035e48b8f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a15e2337afae7eb8578483035e48b8f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2a15e2337afae7eb8578483035e48b8f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a15e2337afae7eb8578483035e48b8f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2a15e2337afae7eb8578483035e48b8f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2a15e2337afae7eb8578483035e48b8f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
