<?php /* Smarty version 2.6.25, created on 2014-01-21 12:19:33
         compiled from print:112 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%6C^6CE^6CE8A1D5%%print%3A112.inc'] = 'c3f5dcd1ff96ebef5d052c7b3370106d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:112', 2, false),array('function', 'metadata', 'print:112', 2, false),array('function', 'stylesheet', 'print:112', 2, false),array('function', 'content', 'print:112', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c3f5dcd1ff96ebef5d052c7b3370106d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3f5dcd1ff96ebef5d052c7b3370106d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c3f5dcd1ff96ebef5d052c7b3370106d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3f5dcd1ff96ebef5d052c7b3370106d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c3f5dcd1ff96ebef5d052c7b3370106d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3f5dcd1ff96ebef5d052c7b3370106d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c3f5dcd1ff96ebef5d052c7b3370106d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c3f5dcd1ff96ebef5d052c7b3370106d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
