<?php /* Smarty version 2.6.25, created on 2014-02-01 23:04:46
         compiled from print:257 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%7A^7AA^7AA82E07%%print%3A257.inc'] = '0f8c3a351dc9325edaea10813dfdee72';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:257', 2, false),array('function', 'metadata', 'print:257', 2, false),array('function', 'stylesheet', 'print:257', 2, false),array('function', 'content', 'print:257', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0f8c3a351dc9325edaea10813dfdee72_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f8c3a351dc9325edaea10813dfdee72','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0f8c3a351dc9325edaea10813dfdee72_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f8c3a351dc9325edaea10813dfdee72','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0f8c3a351dc9325edaea10813dfdee72_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f8c3a351dc9325edaea10813dfdee72','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0f8c3a351dc9325edaea10813dfdee72_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f8c3a351dc9325edaea10813dfdee72','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
