<?php /* Smarty version 2.6.25, created on 2014-02-04 19:11:29
         compiled from print:204 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9E^9ED^9ED68BF8%%print%3A204.inc'] = 'd3df8199680a32ca38b335e5d0f52052';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:204', 2, false),array('function', 'metadata', 'print:204', 2, false),array('function', 'stylesheet', 'print:204', 2, false),array('function', 'content', 'print:204', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d3df8199680a32ca38b335e5d0f52052_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d3df8199680a32ca38b335e5d0f52052','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d3df8199680a32ca38b335e5d0f52052_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d3df8199680a32ca38b335e5d0f52052','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d3df8199680a32ca38b335e5d0f52052_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d3df8199680a32ca38b335e5d0f52052','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d3df8199680a32ca38b335e5d0f52052_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d3df8199680a32ca38b335e5d0f52052','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
