<?php /* Smarty version 2.6.25, created on 2014-02-08 00:00:02
         compiled from print:128 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A7^A71^A7101B08%%print%3A128.inc'] = '07149645f8f6d24c45331bf2fc4caab6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:128', 2, false),array('function', 'metadata', 'print:128', 2, false),array('function', 'stylesheet', 'print:128', 2, false),array('function', 'content', 'print:128', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_07149645f8f6d24c45331bf2fc4caab6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('07149645f8f6d24c45331bf2fc4caab6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_07149645f8f6d24c45331bf2fc4caab6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('07149645f8f6d24c45331bf2fc4caab6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_07149645f8f6d24c45331bf2fc4caab6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('07149645f8f6d24c45331bf2fc4caab6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_07149645f8f6d24c45331bf2fc4caab6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('07149645f8f6d24c45331bf2fc4caab6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
