<?php /* Smarty version 2.6.25, created on 2014-02-12 06:10:32
         compiled from print:130 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B0^B0D^B0D0A27B%%print%3A130.inc'] = '7ebc43f6fd4c0e3eca566221bdc75f67';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:130', 2, false),array('function', 'metadata', 'print:130', 2, false),array('function', 'stylesheet', 'print:130', 2, false),array('function', 'content', 'print:130', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ebc43f6fd4c0e3eca566221bdc75f67_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ebc43f6fd4c0e3eca566221bdc75f67','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7ebc43f6fd4c0e3eca566221bdc75f67_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ebc43f6fd4c0e3eca566221bdc75f67','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7ebc43f6fd4c0e3eca566221bdc75f67_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ebc43f6fd4c0e3eca566221bdc75f67','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7ebc43f6fd4c0e3eca566221bdc75f67_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ebc43f6fd4c0e3eca566221bdc75f67','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
