<?php /* Smarty version 2.6.25, created on 2014-02-13 00:43:02
         compiled from print:340 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%FC^FC1^FC15E0D2%%print%3A340.inc'] = 'f24d63d5c12d3dc5815175e18526746b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:340', 2, false),array('function', 'metadata', 'print:340', 2, false),array('function', 'stylesheet', 'print:340', 2, false),array('function', 'content', 'print:340', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f24d63d5c12d3dc5815175e18526746b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f24d63d5c12d3dc5815175e18526746b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f24d63d5c12d3dc5815175e18526746b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f24d63d5c12d3dc5815175e18526746b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f24d63d5c12d3dc5815175e18526746b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f24d63d5c12d3dc5815175e18526746b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f24d63d5c12d3dc5815175e18526746b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f24d63d5c12d3dc5815175e18526746b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
