<?php /* Smarty version 2.6.25, created on 2014-02-10 18:07:22
         compiled from print:327 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%34^342^342BD2F7%%print%3A327.inc'] = '054900d917fed11eeee3f80608443f71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:327', 2, false),array('function', 'metadata', 'print:327', 2, false),array('function', 'stylesheet', 'print:327', 2, false),array('function', 'content', 'print:327', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_054900d917fed11eeee3f80608443f71_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('054900d917fed11eeee3f80608443f71','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_054900d917fed11eeee3f80608443f71_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('054900d917fed11eeee3f80608443f71','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_054900d917fed11eeee3f80608443f71_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('054900d917fed11eeee3f80608443f71','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_054900d917fed11eeee3f80608443f71_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('054900d917fed11eeee3f80608443f71','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
