<?php /* Smarty version 2.6.25, created on 2014-02-03 16:06:10
         compiled from print:144 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F8^F8F^F8FCF0A5%%print%3A144.inc'] = '0a7a85fbe1d3e9ef0b7e527161ba4ddf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:144', 2, false),array('function', 'metadata', 'print:144', 2, false),array('function', 'stylesheet', 'print:144', 2, false),array('function', 'content', 'print:144', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0a7a85fbe1d3e9ef0b7e527161ba4ddf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0a7a85fbe1d3e9ef0b7e527161ba4ddf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0a7a85fbe1d3e9ef0b7e527161ba4ddf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0a7a85fbe1d3e9ef0b7e527161ba4ddf','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0a7a85fbe1d3e9ef0b7e527161ba4ddf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0a7a85fbe1d3e9ef0b7e527161ba4ddf','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0a7a85fbe1d3e9ef0b7e527161ba4ddf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0a7a85fbe1d3e9ef0b7e527161ba4ddf','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
