<?php /* Smarty version 2.6.25, created on 2014-02-02 11:44:22
         compiled from print:172 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%3A^3AB^3AB20653%%print%3A172.inc'] = '722ad76c1b04c313b72d06b7082361de';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:172', 2, false),array('function', 'metadata', 'print:172', 2, false),array('function', 'stylesheet', 'print:172', 2, false),array('function', 'content', 'print:172', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_722ad76c1b04c313b72d06b7082361de_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('722ad76c1b04c313b72d06b7082361de','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_722ad76c1b04c313b72d06b7082361de_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('722ad76c1b04c313b72d06b7082361de','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_722ad76c1b04c313b72d06b7082361de_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('722ad76c1b04c313b72d06b7082361de','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_722ad76c1b04c313b72d06b7082361de_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('722ad76c1b04c313b72d06b7082361de','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
