<?php /* Smarty version 2.6.25, created on 2014-02-10 13:35:59
         compiled from print:362 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%20^202^202DE37C%%print%3A362.inc'] = '3db996c167a7c4fdbfcefdfa3ca3f2cc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:362', 2, false),array('function', 'metadata', 'print:362', 2, false),array('function', 'stylesheet', 'print:362', 2, false),array('function', 'content', 'print:362', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3db996c167a7c4fdbfcefdfa3ca3f2cc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3db996c167a7c4fdbfcefdfa3ca3f2cc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3db996c167a7c4fdbfcefdfa3ca3f2cc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3db996c167a7c4fdbfcefdfa3ca3f2cc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3db996c167a7c4fdbfcefdfa3ca3f2cc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3db996c167a7c4fdbfcefdfa3ca3f2cc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3db996c167a7c4fdbfcefdfa3ca3f2cc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3db996c167a7c4fdbfcefdfa3ca3f2cc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
