<?php /* Smarty version 2.6.25, created on 2014-02-12 00:00:33
         compiled from print:358 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%EB^EBD^EBD559A1%%print%3A358.inc'] = '3c1d2ceed53f07dcb6a908d50d4fd4b1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:358', 2, false),array('function', 'metadata', 'print:358', 2, false),array('function', 'stylesheet', 'print:358', 2, false),array('function', 'content', 'print:358', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3c1d2ceed53f07dcb6a908d50d4fd4b1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c1d2ceed53f07dcb6a908d50d4fd4b1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3c1d2ceed53f07dcb6a908d50d4fd4b1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c1d2ceed53f07dcb6a908d50d4fd4b1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3c1d2ceed53f07dcb6a908d50d4fd4b1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c1d2ceed53f07dcb6a908d50d4fd4b1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3c1d2ceed53f07dcb6a908d50d4fd4b1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3c1d2ceed53f07dcb6a908d50d4fd4b1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
