<?php /* Smarty version 2.6.25, created on 2014-02-01 23:07:41
         compiled from print:158 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E8^E85^E8518DCF%%print%3A158.inc'] = 'bf54c837a6c14c1392694294fffab36d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:158', 2, false),array('function', 'metadata', 'print:158', 2, false),array('function', 'stylesheet', 'print:158', 2, false),array('function', 'content', 'print:158', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bf54c837a6c14c1392694294fffab36d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf54c837a6c14c1392694294fffab36d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bf54c837a6c14c1392694294fffab36d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf54c837a6c14c1392694294fffab36d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bf54c837a6c14c1392694294fffab36d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf54c837a6c14c1392694294fffab36d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bf54c837a6c14c1392694294fffab36d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bf54c837a6c14c1392694294fffab36d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
