<?php /* Smarty version 2.6.25, created on 2014-02-07 23:08:15
         compiled from print:121 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%DE^DEC^DECCA3AC%%print%3A121.inc'] = '7348553257dd60d4a34c3442f2df892a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:121', 2, false),array('function', 'metadata', 'print:121', 2, false),array('function', 'stylesheet', 'print:121', 2, false),array('function', 'content', 'print:121', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7348553257dd60d4a34c3442f2df892a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7348553257dd60d4a34c3442f2df892a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7348553257dd60d4a34c3442f2df892a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7348553257dd60d4a34c3442f2df892a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7348553257dd60d4a34c3442f2df892a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7348553257dd60d4a34c3442f2df892a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7348553257dd60d4a34c3442f2df892a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7348553257dd60d4a34c3442f2df892a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
