<?php /* Smarty version 2.6.25, created on 2014-02-12 05:16:34
         compiled from print:145 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8F^8FF^8FFBC033%%print%3A145.inc'] = 'd15768d1d8485b0681dce420b796b9bb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:145', 2, false),array('function', 'metadata', 'print:145', 2, false),array('function', 'stylesheet', 'print:145', 2, false),array('function', 'content', 'print:145', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d15768d1d8485b0681dce420b796b9bb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d15768d1d8485b0681dce420b796b9bb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d15768d1d8485b0681dce420b796b9bb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d15768d1d8485b0681dce420b796b9bb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d15768d1d8485b0681dce420b796b9bb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d15768d1d8485b0681dce420b796b9bb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d15768d1d8485b0681dce420b796b9bb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d15768d1d8485b0681dce420b796b9bb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
