<?php /* Smarty version 2.6.25, created on 2014-02-01 23:08:15
         compiled from print:150 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E6^E68^E68A05FD%%print%3A150.inc'] = '3f1bb2afb2fc5c7b627d0b8d18b0b001';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:150', 2, false),array('function', 'metadata', 'print:150', 2, false),array('function', 'stylesheet', 'print:150', 2, false),array('function', 'content', 'print:150', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3f1bb2afb2fc5c7b627d0b8d18b0b001_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f1bb2afb2fc5c7b627d0b8d18b0b001','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3f1bb2afb2fc5c7b627d0b8d18b0b001_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f1bb2afb2fc5c7b627d0b8d18b0b001','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3f1bb2afb2fc5c7b627d0b8d18b0b001_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f1bb2afb2fc5c7b627d0b8d18b0b001','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3f1bb2afb2fc5c7b627d0b8d18b0b001_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3f1bb2afb2fc5c7b627d0b8d18b0b001','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
