<?php /* Smarty version 2.6.25, created on 2014-02-11 09:56:32
         compiled from print:129 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D0^D01^D0172B9E%%print%3A129.inc'] = 'a1fb5d0a38d3c5c65064e12c537ae152';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:129', 2, false),array('function', 'metadata', 'print:129', 2, false),array('function', 'stylesheet', 'print:129', 2, false),array('function', 'content', 'print:129', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a1fb5d0a38d3c5c65064e12c537ae152_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a1fb5d0a38d3c5c65064e12c537ae152','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a1fb5d0a38d3c5c65064e12c537ae152_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a1fb5d0a38d3c5c65064e12c537ae152','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a1fb5d0a38d3c5c65064e12c537ae152_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a1fb5d0a38d3c5c65064e12c537ae152','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a1fb5d0a38d3c5c65064e12c537ae152_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a1fb5d0a38d3c5c65064e12c537ae152','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
