<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:50
         compiled from print:189 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%2A^2AF^2AF8C314%%print%3A189.inc'] = '89a325045f52976f72ae6f70588a98fe';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:189', 2, false),array('function', 'metadata', 'print:189', 2, false),array('function', 'stylesheet', 'print:189', 2, false),array('function', 'content', 'print:189', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_89a325045f52976f72ae6f70588a98fe_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89a325045f52976f72ae6f70588a98fe','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_89a325045f52976f72ae6f70588a98fe_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89a325045f52976f72ae6f70588a98fe','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_89a325045f52976f72ae6f70588a98fe_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89a325045f52976f72ae6f70588a98fe','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_89a325045f52976f72ae6f70588a98fe_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89a325045f52976f72ae6f70588a98fe','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
