<?php /* Smarty version 2.6.25, created on 2014-02-03 19:04:34
         compiled from print:318 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8F^8FB^8FB99CA5%%print%3A318.inc'] = 'ef7aa5c9bd674bedc5beadf37abd8962';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:318', 2, false),array('function', 'metadata', 'print:318', 2, false),array('function', 'stylesheet', 'print:318', 2, false),array('function', 'content', 'print:318', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef7aa5c9bd674bedc5beadf37abd8962_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef7aa5c9bd674bedc5beadf37abd8962','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ef7aa5c9bd674bedc5beadf37abd8962_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef7aa5c9bd674bedc5beadf37abd8962','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ef7aa5c9bd674bedc5beadf37abd8962_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef7aa5c9bd674bedc5beadf37abd8962','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ef7aa5c9bd674bedc5beadf37abd8962_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef7aa5c9bd674bedc5beadf37abd8962','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
