<?php /* Smarty version 2.6.25, created on 2014-02-12 18:47:37
         compiled from print:348 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F2^F2C^F2CE68E0%%print%3A348.inc'] = '1e0933969a69786903ca69feb761c1f5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:348', 2, false),array('function', 'metadata', 'print:348', 2, false),array('function', 'stylesheet', 'print:348', 2, false),array('function', 'content', 'print:348', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1e0933969a69786903ca69feb761c1f5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1e0933969a69786903ca69feb761c1f5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1e0933969a69786903ca69feb761c1f5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1e0933969a69786903ca69feb761c1f5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1e0933969a69786903ca69feb761c1f5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1e0933969a69786903ca69feb761c1f5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1e0933969a69786903ca69feb761c1f5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1e0933969a69786903ca69feb761c1f5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
