<?php /* Smarty version 2.6.25, created on 2014-02-03 14:39:47
         compiled from print:138 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BE^BE0^BE0B2A49%%print%3A138.inc'] = 'f16acde2b699b5a49be6fd3569402de3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:138', 2, false),array('function', 'metadata', 'print:138', 2, false),array('function', 'stylesheet', 'print:138', 2, false),array('function', 'content', 'print:138', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f16acde2b699b5a49be6fd3569402de3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16acde2b699b5a49be6fd3569402de3','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f16acde2b699b5a49be6fd3569402de3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16acde2b699b5a49be6fd3569402de3','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f16acde2b699b5a49be6fd3569402de3_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16acde2b699b5a49be6fd3569402de3','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f16acde2b699b5a49be6fd3569402de3_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16acde2b699b5a49be6fd3569402de3','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
