<?php /* Smarty version 2.6.25, created on 2014-02-10 09:16:50
         compiled from print:193 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%D3^D33^D3361B4B%%print%3A193.inc'] = '732a35588d2e882cda4ce9a3a7ccfe39';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:193', 2, false),array('function', 'metadata', 'print:193', 2, false),array('function', 'stylesheet', 'print:193', 2, false),array('function', 'content', 'print:193', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_732a35588d2e882cda4ce9a3a7ccfe39_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('732a35588d2e882cda4ce9a3a7ccfe39','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_732a35588d2e882cda4ce9a3a7ccfe39_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('732a35588d2e882cda4ce9a3a7ccfe39','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_732a35588d2e882cda4ce9a3a7ccfe39_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('732a35588d2e882cda4ce9a3a7ccfe39','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_732a35588d2e882cda4ce9a3a7ccfe39_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('732a35588d2e882cda4ce9a3a7ccfe39','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
