<?php /* Smarty version 2.6.25, created on 2014-02-11 04:48:08
         compiled from print:86 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AE^AEF^AEF866AA%%print%3A86.inc'] = 'aa92efe5ba219df14933c1d7ccb1f96e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:86', 2, false),array('function', 'metadata', 'print:86', 2, false),array('function', 'stylesheet', 'print:86', 2, false),array('function', 'content', 'print:86', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aa92efe5ba219df14933c1d7ccb1f96e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aa92efe5ba219df14933c1d7ccb1f96e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_aa92efe5ba219df14933c1d7ccb1f96e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aa92efe5ba219df14933c1d7ccb1f96e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_aa92efe5ba219df14933c1d7ccb1f96e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aa92efe5ba219df14933c1d7ccb1f96e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_aa92efe5ba219df14933c1d7ccb1f96e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aa92efe5ba219df14933c1d7ccb1f96e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
