<?php /* Smarty version 2.6.25, created on 2014-02-12 16:17:40
         compiled from print:118 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%8C^8C3^8C3D48CB%%print%3A118.inc'] = '1f74d9a5c4028d88cfeb630d1f2ad192';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:118', 2, false),array('function', 'metadata', 'print:118', 2, false),array('function', 'stylesheet', 'print:118', 2, false),array('function', 'content', 'print:118', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1f74d9a5c4028d88cfeb630d1f2ad192_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1f74d9a5c4028d88cfeb630d1f2ad192','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1f74d9a5c4028d88cfeb630d1f2ad192_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1f74d9a5c4028d88cfeb630d1f2ad192','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1f74d9a5c4028d88cfeb630d1f2ad192_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1f74d9a5c4028d88cfeb630d1f2ad192','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1f74d9a5c4028d88cfeb630d1f2ad192_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1f74d9a5c4028d88cfeb630d1f2ad192','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
