<?php /* Smarty version 2.6.25, created on 2014-02-04 19:56:44
         compiled from print:124 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AE^AEA^AEA65723%%print%3A124.inc'] = '610cb3d8e0e5b1b136a2ccda61a2f8b7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:124', 2, false),array('function', 'metadata', 'print:124', 2, false),array('function', 'stylesheet', 'print:124', 2, false),array('function', 'content', 'print:124', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_610cb3d8e0e5b1b136a2ccda61a2f8b7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('610cb3d8e0e5b1b136a2ccda61a2f8b7','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_610cb3d8e0e5b1b136a2ccda61a2f8b7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('610cb3d8e0e5b1b136a2ccda61a2f8b7','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_610cb3d8e0e5b1b136a2ccda61a2f8b7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('610cb3d8e0e5b1b136a2ccda61a2f8b7','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_610cb3d8e0e5b1b136a2ccda61a2f8b7_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('610cb3d8e0e5b1b136a2ccda61a2f8b7','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
