<?php /* Smarty version 2.6.25, created on 2014-02-10 14:22:55
         compiled from print:268 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C1^C13^C13A6055%%print%3A268.inc'] = '08aa980b2896e887dbd817ddad92b86e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:268', 2, false),array('function', 'metadata', 'print:268', 2, false),array('function', 'stylesheet', 'print:268', 2, false),array('function', 'content', 'print:268', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_08aa980b2896e887dbd817ddad92b86e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08aa980b2896e887dbd817ddad92b86e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_08aa980b2896e887dbd817ddad92b86e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08aa980b2896e887dbd817ddad92b86e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_08aa980b2896e887dbd817ddad92b86e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08aa980b2896e887dbd817ddad92b86e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_08aa980b2896e887dbd817ddad92b86e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('08aa980b2896e887dbd817ddad92b86e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
