<?php /* Smarty version 2.6.25, created on 2014-02-04 19:56:38
         compiled from print:173 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%4D^4DB^4DB536C5%%print%3A173.inc'] = '1b2f0fb81ecdacb22dc5c98e30934a21';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:173', 2, false),array('function', 'metadata', 'print:173', 2, false),array('function', 'stylesheet', 'print:173', 2, false),array('function', 'content', 'print:173', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1b2f0fb81ecdacb22dc5c98e30934a21_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b2f0fb81ecdacb22dc5c98e30934a21','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1b2f0fb81ecdacb22dc5c98e30934a21_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b2f0fb81ecdacb22dc5c98e30934a21','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1b2f0fb81ecdacb22dc5c98e30934a21_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b2f0fb81ecdacb22dc5c98e30934a21','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1b2f0fb81ecdacb22dc5c98e30934a21_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1b2f0fb81ecdacb22dc5c98e30934a21','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
