<?php /* Smarty version 2.6.25, created on 2014-02-10 14:28:27
         compiled from print:181 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%24^242^24234B26%%print%3A181.inc'] = '7da3c1a8eeac2a37b7c2c2255302f48d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:181', 2, false),array('function', 'metadata', 'print:181', 2, false),array('function', 'stylesheet', 'print:181', 2, false),array('function', 'content', 'print:181', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7da3c1a8eeac2a37b7c2c2255302f48d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7da3c1a8eeac2a37b7c2c2255302f48d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7da3c1a8eeac2a37b7c2c2255302f48d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7da3c1a8eeac2a37b7c2c2255302f48d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7da3c1a8eeac2a37b7c2c2255302f48d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7da3c1a8eeac2a37b7c2c2255302f48d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7da3c1a8eeac2a37b7c2c2255302f48d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7da3c1a8eeac2a37b7c2c2255302f48d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
