<?php /* Smarty version 2.6.25, created on 2014-02-11 07:16:08
         compiled from print:160 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CD^CDA^CDA7563E%%print%3A160.inc'] = '0d6003c033c79154f9802923f44cc8ef';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:160', 2, false),array('function', 'metadata', 'print:160', 2, false),array('function', 'stylesheet', 'print:160', 2, false),array('function', 'content', 'print:160', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0d6003c033c79154f9802923f44cc8ef_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0d6003c033c79154f9802923f44cc8ef','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0d6003c033c79154f9802923f44cc8ef_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0d6003c033c79154f9802923f44cc8ef','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0d6003c033c79154f9802923f44cc8ef_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0d6003c033c79154f9802923f44cc8ef','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0d6003c033c79154f9802923f44cc8ef_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0d6003c033c79154f9802923f44cc8ef','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
