<?php /* Smarty version 2.6.25, created on 2014-02-12 08:07:55
         compiled from print:69 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A0^A0C^A0C456B5%%print%3A69.inc'] = '2d24ef439b758943df27e31bf88886e8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:69', 2, false),array('function', 'metadata', 'print:69', 2, false),array('function', 'stylesheet', 'print:69', 2, false),array('function', 'content', 'print:69', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2d24ef439b758943df27e31bf88886e8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d24ef439b758943df27e31bf88886e8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2d24ef439b758943df27e31bf88886e8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d24ef439b758943df27e31bf88886e8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2d24ef439b758943df27e31bf88886e8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d24ef439b758943df27e31bf88886e8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2d24ef439b758943df27e31bf88886e8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d24ef439b758943df27e31bf88886e8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
