<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:31
         compiled from print:330 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B3^B35^B3547615%%print%3A330.inc'] = 'f98ca282ad2ccd875adea90c56e7e6cb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:330', 2, false),array('function', 'metadata', 'print:330', 2, false),array('function', 'stylesheet', 'print:330', 2, false),array('function', 'content', 'print:330', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f98ca282ad2ccd875adea90c56e7e6cb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f98ca282ad2ccd875adea90c56e7e6cb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f98ca282ad2ccd875adea90c56e7e6cb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f98ca282ad2ccd875adea90c56e7e6cb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f98ca282ad2ccd875adea90c56e7e6cb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f98ca282ad2ccd875adea90c56e7e6cb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f98ca282ad2ccd875adea90c56e7e6cb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f98ca282ad2ccd875adea90c56e7e6cb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
