<?php /* Smarty version 2.6.25, created on 2014-01-29 15:44:48
         compiled from print:214 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%87^87C^87CDBAB9%%print%3A214.inc'] = '3d6a45848de8e93e25b9c382f166dab1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:214', 2, false),array('function', 'metadata', 'print:214', 2, false),array('function', 'stylesheet', 'print:214', 2, false),array('function', 'content', 'print:214', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3d6a45848de8e93e25b9c382f166dab1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3d6a45848de8e93e25b9c382f166dab1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3d6a45848de8e93e25b9c382f166dab1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3d6a45848de8e93e25b9c382f166dab1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3d6a45848de8e93e25b9c382f166dab1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3d6a45848de8e93e25b9c382f166dab1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3d6a45848de8e93e25b9c382f166dab1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3d6a45848de8e93e25b9c382f166dab1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
