<?php /* Smarty version 2.6.25, created on 2014-02-12 03:10:25
         compiled from print:236 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%5B^5BF^5BF5B917%%print%3A236.inc'] = '4739f0c2d985214b5e8f53c7135eb77b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:236', 2, false),array('function', 'metadata', 'print:236', 2, false),array('function', 'stylesheet', 'print:236', 2, false),array('function', 'content', 'print:236', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4739f0c2d985214b5e8f53c7135eb77b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4739f0c2d985214b5e8f53c7135eb77b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4739f0c2d985214b5e8f53c7135eb77b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4739f0c2d985214b5e8f53c7135eb77b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4739f0c2d985214b5e8f53c7135eb77b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4739f0c2d985214b5e8f53c7135eb77b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4739f0c2d985214b5e8f53c7135eb77b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4739f0c2d985214b5e8f53c7135eb77b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
