<?php /* Smarty version 2.6.25, created on 2014-02-12 00:37:09
         compiled from print:220 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AB^AB8^AB8D2D63%%print%3A220.inc'] = '63846431fc36cb059113414b461cd28b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:220', 2, false),array('function', 'metadata', 'print:220', 2, false),array('function', 'stylesheet', 'print:220', 2, false),array('function', 'content', 'print:220', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_63846431fc36cb059113414b461cd28b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63846431fc36cb059113414b461cd28b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_63846431fc36cb059113414b461cd28b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63846431fc36cb059113414b461cd28b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_63846431fc36cb059113414b461cd28b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63846431fc36cb059113414b461cd28b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_63846431fc36cb059113414b461cd28b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('63846431fc36cb059113414b461cd28b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
