<?php /* Smarty version 2.6.25, created on 2014-02-11 12:41:51
         compiled from print:180 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%53^532^53247BB0%%print%3A180.inc'] = '4dd6fde0d1ee7f2fe922e6efe1dc900b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:180', 2, false),array('function', 'metadata', 'print:180', 2, false),array('function', 'stylesheet', 'print:180', 2, false),array('function', 'content', 'print:180', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4dd6fde0d1ee7f2fe922e6efe1dc900b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dd6fde0d1ee7f2fe922e6efe1dc900b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4dd6fde0d1ee7f2fe922e6efe1dc900b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dd6fde0d1ee7f2fe922e6efe1dc900b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4dd6fde0d1ee7f2fe922e6efe1dc900b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dd6fde0d1ee7f2fe922e6efe1dc900b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4dd6fde0d1ee7f2fe922e6efe1dc900b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4dd6fde0d1ee7f2fe922e6efe1dc900b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
