<?php /* Smarty version 2.6.25, created on 2014-02-13 00:44:02
         compiled from print:84 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%40^40F^40F60786%%print%3A84.inc'] = '528ce8347070f4fec272b6fe0564a1fc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:84', 2, false),array('function', 'metadata', 'print:84', 2, false),array('function', 'stylesheet', 'print:84', 2, false),array('function', 'content', 'print:84', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_528ce8347070f4fec272b6fe0564a1fc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('528ce8347070f4fec272b6fe0564a1fc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_528ce8347070f4fec272b6fe0564a1fc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('528ce8347070f4fec272b6fe0564a1fc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_528ce8347070f4fec272b6fe0564a1fc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('528ce8347070f4fec272b6fe0564a1fc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_528ce8347070f4fec272b6fe0564a1fc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('528ce8347070f4fec272b6fe0564a1fc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
