<?php /* Smarty version 2.6.25, created on 2014-02-07 21:21:31
         compiled from print:171 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A3^A3B^A3BB57E9%%print%3A171.inc'] = 'f283d36308bd7ed05b1e9a25139314c2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:171', 2, false),array('function', 'metadata', 'print:171', 2, false),array('function', 'stylesheet', 'print:171', 2, false),array('function', 'content', 'print:171', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f283d36308bd7ed05b1e9a25139314c2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f283d36308bd7ed05b1e9a25139314c2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f283d36308bd7ed05b1e9a25139314c2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f283d36308bd7ed05b1e9a25139314c2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f283d36308bd7ed05b1e9a25139314c2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f283d36308bd7ed05b1e9a25139314c2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f283d36308bd7ed05b1e9a25139314c2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f283d36308bd7ed05b1e9a25139314c2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
