<?php /* Smarty version 2.6.25, created on 2014-02-10 22:15:54
         compiled from print:357 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%7B^7B6^7B6A4430%%print%3A357.inc'] = '4d7f8e1ada938bfabcdab630dbfdbe56';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:357', 2, false),array('function', 'metadata', 'print:357', 2, false),array('function', 'stylesheet', 'print:357', 2, false),array('function', 'content', 'print:357', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4d7f8e1ada938bfabcdab630dbfdbe56_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d7f8e1ada938bfabcdab630dbfdbe56','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4d7f8e1ada938bfabcdab630dbfdbe56_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d7f8e1ada938bfabcdab630dbfdbe56','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4d7f8e1ada938bfabcdab630dbfdbe56_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d7f8e1ada938bfabcdab630dbfdbe56','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4d7f8e1ada938bfabcdab630dbfdbe56_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4d7f8e1ada938bfabcdab630dbfdbe56','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
