<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:30
         compiled from print:261 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%B8^B8E^B8E6D8F1%%print%3A261.inc'] = '666f4843b21edcf1ca624ca19d44c94d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:261', 2, false),array('function', 'metadata', 'print:261', 2, false),array('function', 'stylesheet', 'print:261', 2, false),array('function', 'content', 'print:261', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_666f4843b21edcf1ca624ca19d44c94d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('666f4843b21edcf1ca624ca19d44c94d','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_666f4843b21edcf1ca624ca19d44c94d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('666f4843b21edcf1ca624ca19d44c94d','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_666f4843b21edcf1ca624ca19d44c94d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('666f4843b21edcf1ca624ca19d44c94d','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_666f4843b21edcf1ca624ca19d44c94d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('666f4843b21edcf1ca624ca19d44c94d','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
