<?php /* Smarty version 2.6.25, created on 2014-02-12 18:51:17
         compiled from print:57 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%6C^6C5^6C512871%%print%3A57.inc'] = 'f52ca263d060eac21b53cd0bdca1cd99';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:57', 2, false),array('function', 'metadata', 'print:57', 2, false),array('function', 'stylesheet', 'print:57', 2, false),array('function', 'content', 'print:57', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f52ca263d060eac21b53cd0bdca1cd99_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f52ca263d060eac21b53cd0bdca1cd99','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f52ca263d060eac21b53cd0bdca1cd99_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f52ca263d060eac21b53cd0bdca1cd99','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f52ca263d060eac21b53cd0bdca1cd99_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f52ca263d060eac21b53cd0bdca1cd99','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f52ca263d060eac21b53cd0bdca1cd99_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f52ca263d060eac21b53cd0bdca1cd99','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
