<?php /* Smarty version 2.6.25, created on 2014-02-10 13:10:24
         compiled from print:216 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%69^69C^69C3DB95%%print%3A216.inc'] = 'a48c1b2be64c5d3ce4d6f2f0d0615a33';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:216', 2, false),array('function', 'metadata', 'print:216', 2, false),array('function', 'stylesheet', 'print:216', 2, false),array('function', 'content', 'print:216', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a48c1b2be64c5d3ce4d6f2f0d0615a33_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a48c1b2be64c5d3ce4d6f2f0d0615a33','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a48c1b2be64c5d3ce4d6f2f0d0615a33_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a48c1b2be64c5d3ce4d6f2f0d0615a33','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a48c1b2be64c5d3ce4d6f2f0d0615a33_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a48c1b2be64c5d3ce4d6f2f0d0615a33','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a48c1b2be64c5d3ce4d6f2f0d0615a33_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a48c1b2be64c5d3ce4d6f2f0d0615a33','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
