<?php /* Smarty version 2.6.25, created on 2014-02-11 06:07:46
         compiled from print:192 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A4^A43^A4312BDD%%print%3A192.inc'] = 'df92302683a8d2eb624049ebbcddcd68';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:192', 2, false),array('function', 'metadata', 'print:192', 2, false),array('function', 'stylesheet', 'print:192', 2, false),array('function', 'content', 'print:192', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_df92302683a8d2eb624049ebbcddcd68_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df92302683a8d2eb624049ebbcddcd68','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_df92302683a8d2eb624049ebbcddcd68_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df92302683a8d2eb624049ebbcddcd68','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_df92302683a8d2eb624049ebbcddcd68_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df92302683a8d2eb624049ebbcddcd68','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_df92302683a8d2eb624049ebbcddcd68_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('df92302683a8d2eb624049ebbcddcd68','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
