<?php /* Smarty version 2.6.25, created on 2014-02-11 23:45:25
         compiled from print:360 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%CE^CE2^CE238250%%print%3A360.inc'] = '8e56a3460cb0f92333ad8a710b700b2a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:360', 2, false),array('function', 'metadata', 'print:360', 2, false),array('function', 'stylesheet', 'print:360', 2, false),array('function', 'content', 'print:360', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8e56a3460cb0f92333ad8a710b700b2a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e56a3460cb0f92333ad8a710b700b2a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8e56a3460cb0f92333ad8a710b700b2a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e56a3460cb0f92333ad8a710b700b2a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8e56a3460cb0f92333ad8a710b700b2a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e56a3460cb0f92333ad8a710b700b2a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8e56a3460cb0f92333ad8a710b700b2a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8e56a3460cb0f92333ad8a710b700b2a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
