<?php /* Smarty version 2.6.25, created on 2014-02-03 16:52:12
         compiled from print:224 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%AC^ACE^ACE0E97A%%print%3A224.inc'] = 'a3affd60cea919539dd5309e95f64d74';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:224', 2, false),array('function', 'metadata', 'print:224', 2, false),array('function', 'stylesheet', 'print:224', 2, false),array('function', 'content', 'print:224', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a3affd60cea919539dd5309e95f64d74_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3affd60cea919539dd5309e95f64d74','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a3affd60cea919539dd5309e95f64d74_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3affd60cea919539dd5309e95f64d74','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a3affd60cea919539dd5309e95f64d74_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3affd60cea919539dd5309e95f64d74','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a3affd60cea919539dd5309e95f64d74_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a3affd60cea919539dd5309e95f64d74','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
