<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:24
         compiled from print:252 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%0A^0AC^0AC2DA88%%print%3A252.inc'] = 'b4f14efb1b38196467f554f9cbba8d77';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:252', 2, false),array('function', 'metadata', 'print:252', 2, false),array('function', 'stylesheet', 'print:252', 2, false),array('function', 'content', 'print:252', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b4f14efb1b38196467f554f9cbba8d77_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f14efb1b38196467f554f9cbba8d77','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b4f14efb1b38196467f554f9cbba8d77_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f14efb1b38196467f554f9cbba8d77','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b4f14efb1b38196467f554f9cbba8d77_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f14efb1b38196467f554f9cbba8d77','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b4f14efb1b38196467f554f9cbba8d77_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b4f14efb1b38196467f554f9cbba8d77','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
