<?php /* Smarty version 2.6.25, created on 2014-02-07 21:56:33
         compiled from print:227 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%35^35E^35E9B8C0%%print%3A227.inc'] = '70f353fb93e27a4123e4827acdc736dc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:227', 2, false),array('function', 'metadata', 'print:227', 2, false),array('function', 'stylesheet', 'print:227', 2, false),array('function', 'content', 'print:227', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_70f353fb93e27a4123e4827acdc736dc_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70f353fb93e27a4123e4827acdc736dc','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_70f353fb93e27a4123e4827acdc736dc_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70f353fb93e27a4123e4827acdc736dc','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_70f353fb93e27a4123e4827acdc736dc_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70f353fb93e27a4123e4827acdc736dc','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_70f353fb93e27a4123e4827acdc736dc_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('70f353fb93e27a4123e4827acdc736dc','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
