<?php /* Smarty version 2.6.25, created on 2014-02-10 22:29:30
         compiled from print:346 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%15^157^157645E7%%print%3A346.inc'] = 'd6b4a1c372fb704ca75f3a1d9d789dea';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:346', 2, false),array('function', 'metadata', 'print:346', 2, false),array('function', 'stylesheet', 'print:346', 2, false),array('function', 'content', 'print:346', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d6b4a1c372fb704ca75f3a1d9d789dea_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d6b4a1c372fb704ca75f3a1d9d789dea','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d6b4a1c372fb704ca75f3a1d9d789dea_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d6b4a1c372fb704ca75f3a1d9d789dea','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d6b4a1c372fb704ca75f3a1d9d789dea_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d6b4a1c372fb704ca75f3a1d9d789dea','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d6b4a1c372fb704ca75f3a1d9d789dea_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d6b4a1c372fb704ca75f3a1d9d789dea','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
