<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:38
         compiled from print:109 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E2^E22^E221491C%%print%3A109.inc'] = 'bed58856b8beec67ddf6a67a3d6c1ed0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:109', 2, false),array('function', 'metadata', 'print:109', 2, false),array('function', 'stylesheet', 'print:109', 2, false),array('function', 'content', 'print:109', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bed58856b8beec67ddf6a67a3d6c1ed0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bed58856b8beec67ddf6a67a3d6c1ed0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bed58856b8beec67ddf6a67a3d6c1ed0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bed58856b8beec67ddf6a67a3d6c1ed0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bed58856b8beec67ddf6a67a3d6c1ed0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bed58856b8beec67ddf6a67a3d6c1ed0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bed58856b8beec67ddf6a67a3d6c1ed0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bed58856b8beec67ddf6a67a3d6c1ed0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
