<?php /* Smarty version 2.6.25, created on 2014-02-11 06:31:28
         compiled from print:64 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%DE^DE7^DE752A08%%print%3A64.inc'] = '81e6ef2d8590f064247774cb9eb58c3a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:64', 2, false),array('function', 'metadata', 'print:64', 2, false),array('function', 'stylesheet', 'print:64', 2, false),array('function', 'content', 'print:64', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_81e6ef2d8590f064247774cb9eb58c3a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81e6ef2d8590f064247774cb9eb58c3a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_81e6ef2d8590f064247774cb9eb58c3a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81e6ef2d8590f064247774cb9eb58c3a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_81e6ef2d8590f064247774cb9eb58c3a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81e6ef2d8590f064247774cb9eb58c3a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_81e6ef2d8590f064247774cb9eb58c3a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('81e6ef2d8590f064247774cb9eb58c3a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
