<?php /* Smarty version 2.6.25, created on 2014-02-07 23:48:13
         compiled from print:262 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%21^21E^21EF894B%%print%3A262.inc'] = '696218ea67bc0cbf219494254d885bd6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:262', 2, false),array('function', 'metadata', 'print:262', 2, false),array('function', 'stylesheet', 'print:262', 2, false),array('function', 'content', 'print:262', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_696218ea67bc0cbf219494254d885bd6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('696218ea67bc0cbf219494254d885bd6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_696218ea67bc0cbf219494254d885bd6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('696218ea67bc0cbf219494254d885bd6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_696218ea67bc0cbf219494254d885bd6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('696218ea67bc0cbf219494254d885bd6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_696218ea67bc0cbf219494254d885bd6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('696218ea67bc0cbf219494254d885bd6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
