<?php /* Smarty version 2.6.25, created on 2014-02-04 19:56:35
         compiled from print:103 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%02^02F^02F4A002%%print%3A103.inc'] = '77249467fa1df5e0b936ee43e8ef239a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:103', 2, false),array('function', 'metadata', 'print:103', 2, false),array('function', 'stylesheet', 'print:103', 2, false),array('function', 'content', 'print:103', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_77249467fa1df5e0b936ee43e8ef239a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('77249467fa1df5e0b936ee43e8ef239a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_77249467fa1df5e0b936ee43e8ef239a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('77249467fa1df5e0b936ee43e8ef239a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_77249467fa1df5e0b936ee43e8ef239a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('77249467fa1df5e0b936ee43e8ef239a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_77249467fa1df5e0b936ee43e8ef239a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('77249467fa1df5e0b936ee43e8ef239a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
