<?php /* Smarty version 2.6.25, created on 2014-02-01 23:14:55
         compiled from print:251 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%93^93C^93CB8B32%%print%3A251.inc'] = 'ce15743ba4004135a318b32913009d09';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:251', 2, false),array('function', 'metadata', 'print:251', 2, false),array('function', 'stylesheet', 'print:251', 2, false),array('function', 'content', 'print:251', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ce15743ba4004135a318b32913009d09_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce15743ba4004135a318b32913009d09','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ce15743ba4004135a318b32913009d09_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce15743ba4004135a318b32913009d09','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ce15743ba4004135a318b32913009d09_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce15743ba4004135a318b32913009d09','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ce15743ba4004135a318b32913009d09_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ce15743ba4004135a318b32913009d09','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
