<?php /* Smarty version 2.6.25, created on 2014-02-10 18:05:14
         compiled from print:359 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9C^9CD^9CD26937%%print%3A359.inc'] = 'ef4727910f37f469a1c9097e82df9133';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:359', 2, false),array('function', 'metadata', 'print:359', 2, false),array('function', 'stylesheet', 'print:359', 2, false),array('function', 'content', 'print:359', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef4727910f37f469a1c9097e82df9133_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4727910f37f469a1c9097e82df9133','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ef4727910f37f469a1c9097e82df9133_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4727910f37f469a1c9097e82df9133','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ef4727910f37f469a1c9097e82df9133_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4727910f37f469a1c9097e82df9133','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ef4727910f37f469a1c9097e82df9133_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4727910f37f469a1c9097e82df9133','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
