<?php /* Smarty version 2.6.25, created on 2014-02-01 23:07:47
         compiled from print:156 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%0F^0FE^0FE9A0C8%%print%3A156.inc'] = 'f16405bc2a41aed104ebef98fb823f71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:156', 2, false),array('function', 'metadata', 'print:156', 2, false),array('function', 'stylesheet', 'print:156', 2, false),array('function', 'content', 'print:156', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f16405bc2a41aed104ebef98fb823f71_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16405bc2a41aed104ebef98fb823f71','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f16405bc2a41aed104ebef98fb823f71_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16405bc2a41aed104ebef98fb823f71','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f16405bc2a41aed104ebef98fb823f71_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16405bc2a41aed104ebef98fb823f71','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f16405bc2a41aed104ebef98fb823f71_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f16405bc2a41aed104ebef98fb823f71','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
