<?php /* Smarty version 2.6.25, created on 2014-02-11 15:54:01
         compiled from print:56 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%1B^1B5^1B5618E7%%print%3A56.inc'] = '9689bf26d32f66fc66327a6f28a395a4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:56', 2, false),array('function', 'metadata', 'print:56', 2, false),array('function', 'stylesheet', 'print:56', 2, false),array('function', 'content', 'print:56', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9689bf26d32f66fc66327a6f28a395a4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9689bf26d32f66fc66327a6f28a395a4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_9689bf26d32f66fc66327a6f28a395a4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9689bf26d32f66fc66327a6f28a395a4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_9689bf26d32f66fc66327a6f28a395a4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9689bf26d32f66fc66327a6f28a395a4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_9689bf26d32f66fc66327a6f28a395a4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('9689bf26d32f66fc66327a6f28a395a4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
