<?php /* Smarty version 2.6.25, created on 2014-02-12 16:40:31
         compiled from print:353 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%7C^7C0^7C078029%%print%3A353.inc'] = 'b41095c33a242f123f9ea4fc268ab2b9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:353', 2, false),array('function', 'metadata', 'print:353', 2, false),array('function', 'stylesheet', 'print:353', 2, false),array('function', 'content', 'print:353', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b41095c33a242f123f9ea4fc268ab2b9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b41095c33a242f123f9ea4fc268ab2b9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b41095c33a242f123f9ea4fc268ab2b9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b41095c33a242f123f9ea4fc268ab2b9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b41095c33a242f123f9ea4fc268ab2b9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b41095c33a242f123f9ea4fc268ab2b9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b41095c33a242f123f9ea4fc268ab2b9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b41095c33a242f123f9ea4fc268ab2b9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
