<?php /* Smarty version 2.6.25, created on 2014-02-11 01:22:24
         compiled from print:301 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%EF^EF7^EF7E1540%%print%3A301.inc'] = '8cb7a31f252f0285cd1d5aac6b5d94b8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:301', 2, false),array('function', 'metadata', 'print:301', 2, false),array('function', 'stylesheet', 'print:301', 2, false),array('function', 'content', 'print:301', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8cb7a31f252f0285cd1d5aac6b5d94b8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cb7a31f252f0285cd1d5aac6b5d94b8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8cb7a31f252f0285cd1d5aac6b5d94b8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cb7a31f252f0285cd1d5aac6b5d94b8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8cb7a31f252f0285cd1d5aac6b5d94b8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cb7a31f252f0285cd1d5aac6b5d94b8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8cb7a31f252f0285cd1d5aac6b5d94b8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cb7a31f252f0285cd1d5aac6b5d94b8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
