<?php /* Smarty version 2.6.25, created on 2014-02-12 10:02:17
         compiled from print:352 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%0B^0B0^0B00B0BF%%print%3A352.inc'] = '8380f8e8421636e50b13db4703b89856';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:352', 2, false),array('function', 'metadata', 'print:352', 2, false),array('function', 'stylesheet', 'print:352', 2, false),array('function', 'content', 'print:352', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8380f8e8421636e50b13db4703b89856_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8380f8e8421636e50b13db4703b89856','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8380f8e8421636e50b13db4703b89856_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8380f8e8421636e50b13db4703b89856','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8380f8e8421636e50b13db4703b89856_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8380f8e8421636e50b13db4703b89856','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8380f8e8421636e50b13db4703b89856_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8380f8e8421636e50b13db4703b89856','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
