<?php /* Smarty version 2.6.25, created on 2014-02-06 12:19:44
         compiled from print:85 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%37^37F^37F13710%%print%3A85.inc'] = '793fb3a9fc04278ba2b31948d002e831';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:85', 2, false),array('function', 'metadata', 'print:85', 2, false),array('function', 'stylesheet', 'print:85', 2, false),array('function', 'content', 'print:85', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_793fb3a9fc04278ba2b31948d002e831_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('793fb3a9fc04278ba2b31948d002e831','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_793fb3a9fc04278ba2b31948d002e831_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('793fb3a9fc04278ba2b31948d002e831','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_793fb3a9fc04278ba2b31948d002e831_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('793fb3a9fc04278ba2b31948d002e831','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_793fb3a9fc04278ba2b31948d002e831_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('793fb3a9fc04278ba2b31948d002e831','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
