<?php /* Smarty version 2.6.25, created on 2014-02-04 19:15:33
         compiled from print:182 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%BD^BD2^BD2A1A9C%%print%3A182.inc'] = '4a29f34470315f5533cbec072b427190';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:182', 2, false),array('function', 'metadata', 'print:182', 2, false),array('function', 'stylesheet', 'print:182', 2, false),array('function', 'content', 'print:182', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4a29f34470315f5533cbec072b427190_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4a29f34470315f5533cbec072b427190','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_4a29f34470315f5533cbec072b427190_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4a29f34470315f5533cbec072b427190','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_4a29f34470315f5533cbec072b427190_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4a29f34470315f5533cbec072b427190','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_4a29f34470315f5533cbec072b427190_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4a29f34470315f5533cbec072b427190','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
