<?php /* Smarty version 2.6.25, created on 2014-02-12 06:11:54
         compiled from print:136 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%59^59B^59B3074E%%print%3A136.inc'] = '554435eaad5c70fe58ec8b9ad31b51f6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:136', 2, false),array('function', 'metadata', 'print:136', 2, false),array('function', 'stylesheet', 'print:136', 2, false),array('function', 'content', 'print:136', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_554435eaad5c70fe58ec8b9ad31b51f6_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('554435eaad5c70fe58ec8b9ad31b51f6','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_554435eaad5c70fe58ec8b9ad31b51f6_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('554435eaad5c70fe58ec8b9ad31b51f6','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_554435eaad5c70fe58ec8b9ad31b51f6_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('554435eaad5c70fe58ec8b9ad31b51f6','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_554435eaad5c70fe58ec8b9ad31b51f6_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('554435eaad5c70fe58ec8b9ad31b51f6','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
