<?php /* Smarty version 2.6.25, created on 2014-02-13 00:08:47
         compiled from print:123 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%30^30C^30C2C280%%print%3A123.inc'] = '99eeb9ab747ddd3fdcb72c61e9fde16c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:123', 2, false),array('function', 'metadata', 'print:123', 2, false),array('function', 'stylesheet', 'print:123', 2, false),array('function', 'content', 'print:123', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_99eeb9ab747ddd3fdcb72c61e9fde16c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99eeb9ab747ddd3fdcb72c61e9fde16c','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_99eeb9ab747ddd3fdcb72c61e9fde16c_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99eeb9ab747ddd3fdcb72c61e9fde16c','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_99eeb9ab747ddd3fdcb72c61e9fde16c_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99eeb9ab747ddd3fdcb72c61e9fde16c','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_99eeb9ab747ddd3fdcb72c61e9fde16c_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99eeb9ab747ddd3fdcb72c61e9fde16c','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
