<?php /* Smarty version 2.6.25, created on 2014-02-07 22:13:14
         compiled from print:342 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%12^121^121B81FE%%print%3A342.inc'] = '846b2d35efb02ed6db5ca4c2f09a0287';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:342', 2, false),array('function', 'metadata', 'print:342', 2, false),array('function', 'stylesheet', 'print:342', 2, false),array('function', 'content', 'print:342', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_846b2d35efb02ed6db5ca4c2f09a0287_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('846b2d35efb02ed6db5ca4c2f09a0287','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_846b2d35efb02ed6db5ca4c2f09a0287_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('846b2d35efb02ed6db5ca4c2f09a0287','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_846b2d35efb02ed6db5ca4c2f09a0287_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('846b2d35efb02ed6db5ca4c2f09a0287','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_846b2d35efb02ed6db5ca4c2f09a0287_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('846b2d35efb02ed6db5ca4c2f09a0287','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
