<?php /* Smarty version 2.6.25, created on 2014-02-12 02:42:55
         compiled from print:82 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A9^A99^A995A2B3%%print%3A82.inc'] = '2d3eac6984178f85ea2660c605e572a4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:82', 2, false),array('function', 'metadata', 'print:82', 2, false),array('function', 'stylesheet', 'print:82', 2, false),array('function', 'content', 'print:82', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_2d3eac6984178f85ea2660c605e572a4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d3eac6984178f85ea2660c605e572a4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_2d3eac6984178f85ea2660c605e572a4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d3eac6984178f85ea2660c605e572a4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_2d3eac6984178f85ea2660c605e572a4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d3eac6984178f85ea2660c605e572a4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_2d3eac6984178f85ea2660c605e572a4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('2d3eac6984178f85ea2660c605e572a4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
