<?php /* Smarty version 2.6.25, created on 2014-02-04 19:56:57
         compiled from print:190 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%4A^4A3^4A3F4AF1%%print%3A190.inc'] = 'ad814b194c2fc5118cf2ca3cc9286cc5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:190', 2, false),array('function', 'metadata', 'print:190', 2, false),array('function', 'stylesheet', 'print:190', 2, false),array('function', 'content', 'print:190', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ad814b194c2fc5118cf2ca3cc9286cc5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad814b194c2fc5118cf2ca3cc9286cc5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ad814b194c2fc5118cf2ca3cc9286cc5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad814b194c2fc5118cf2ca3cc9286cc5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ad814b194c2fc5118cf2ca3cc9286cc5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad814b194c2fc5118cf2ca3cc9286cc5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ad814b194c2fc5118cf2ca3cc9286cc5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ad814b194c2fc5118cf2ca3cc9286cc5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
