<?php /* Smarty version 2.6.25, created on 2014-02-12 07:08:07
         compiled from print:247 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%63^63B^63B31F46%%print%3A247.inc'] = '1687c78b453d2f76ccfce8cf67573cdb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:247', 2, false),array('function', 'metadata', 'print:247', 2, false),array('function', 'stylesheet', 'print:247', 2, false),array('function', 'content', 'print:247', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1687c78b453d2f76ccfce8cf67573cdb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1687c78b453d2f76ccfce8cf67573cdb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1687c78b453d2f76ccfce8cf67573cdb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1687c78b453d2f76ccfce8cf67573cdb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1687c78b453d2f76ccfce8cf67573cdb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1687c78b453d2f76ccfce8cf67573cdb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1687c78b453d2f76ccfce8cf67573cdb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1687c78b453d2f76ccfce8cf67573cdb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
