<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:10
         compiled from print:223 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%32^328^32847CD9%%print%3A223.inc'] = 'd33b907a857a70e32afe0399b0519e90';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:223', 2, false),array('function', 'metadata', 'print:223', 2, false),array('function', 'stylesheet', 'print:223', 2, false),array('function', 'content', 'print:223', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d33b907a857a70e32afe0399b0519e90_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b907a857a70e32afe0399b0519e90','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d33b907a857a70e32afe0399b0519e90_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b907a857a70e32afe0399b0519e90','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d33b907a857a70e32afe0399b0519e90_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b907a857a70e32afe0399b0519e90','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d33b907a857a70e32afe0399b0519e90_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d33b907a857a70e32afe0399b0519e90','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
