<?php /* Smarty version 2.6.25, created on 2014-02-12 19:13:09
         compiled from print:151 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%91^918^918D356B%%print%3A151.inc'] = '366ab8f493f44440a6d80829d55c5c40';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:151', 2, false),array('function', 'metadata', 'print:151', 2, false),array('function', 'stylesheet', 'print:151', 2, false),array('function', 'content', 'print:151', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_366ab8f493f44440a6d80829d55c5c40_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('366ab8f493f44440a6d80829d55c5c40','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_366ab8f493f44440a6d80829d55c5c40_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('366ab8f493f44440a6d80829d55c5c40','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_366ab8f493f44440a6d80829d55c5c40_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('366ab8f493f44440a6d80829d55c5c40','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_366ab8f493f44440a6d80829d55c5c40_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('366ab8f493f44440a6d80829d55c5c40','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
