<?php /* Smarty version 2.6.25, created on 2014-02-07 23:21:13
         compiled from print:228 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A5^A55^A556A551%%print%3A228.inc'] = '6942a58ba39ae0cd184e098c87190b91';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:228', 2, false),array('function', 'metadata', 'print:228', 2, false),array('function', 'stylesheet', 'print:228', 2, false),array('function', 'content', 'print:228', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6942a58ba39ae0cd184e098c87190b91_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6942a58ba39ae0cd184e098c87190b91','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6942a58ba39ae0cd184e098c87190b91_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6942a58ba39ae0cd184e098c87190b91','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6942a58ba39ae0cd184e098c87190b91_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6942a58ba39ae0cd184e098c87190b91','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6942a58ba39ae0cd184e098c87190b91_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6942a58ba39ae0cd184e098c87190b91','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
