<?php /* Smarty version 2.6.25, created on 2014-02-12 22:12:47
         compiled from print:256 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%0D^0DA^0DAF1E91%%print%3A256.inc'] = '1d2e30e98e1be92e5a7353fae4d48136';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:256', 2, false),array('function', 'metadata', 'print:256', 2, false),array('function', 'stylesheet', 'print:256', 2, false),array('function', 'content', 'print:256', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_1d2e30e98e1be92e5a7353fae4d48136_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d2e30e98e1be92e5a7353fae4d48136','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1d2e30e98e1be92e5a7353fae4d48136_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d2e30e98e1be92e5a7353fae4d48136','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1d2e30e98e1be92e5a7353fae4d48136_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d2e30e98e1be92e5a7353fae4d48136','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1d2e30e98e1be92e5a7353fae4d48136_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1d2e30e98e1be92e5a7353fae4d48136','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
