<?php /* Smarty version 2.6.25, created on 2014-02-03 22:20:09
         compiled from print:311 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F6^F66^F6652401%%print%3A311.inc'] = '04bf22d376a2e825b67c509d384bf9d1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:311', 2, false),array('function', 'metadata', 'print:311', 2, false),array('function', 'stylesheet', 'print:311', 2, false),array('function', 'content', 'print:311', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_04bf22d376a2e825b67c509d384bf9d1_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bf22d376a2e825b67c509d384bf9d1','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_04bf22d376a2e825b67c509d384bf9d1_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bf22d376a2e825b67c509d384bf9d1','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_04bf22d376a2e825b67c509d384bf9d1_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bf22d376a2e825b67c509d384bf9d1','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_04bf22d376a2e825b67c509d384bf9d1_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('04bf22d376a2e825b67c509d384bf9d1','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
