<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:55
         compiled from print:100 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%9B^9BF^9BFDF1B8%%print%3A100.inc'] = '8c2bee0b3d63ce7d6bed7b02a819cc56';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:100', 2, false),array('function', 'metadata', 'print:100', 2, false),array('function', 'stylesheet', 'print:100', 2, false),array('function', 'content', 'print:100', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_8c2bee0b3d63ce7d6bed7b02a819cc56_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c2bee0b3d63ce7d6bed7b02a819cc56','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_8c2bee0b3d63ce7d6bed7b02a819cc56_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c2bee0b3d63ce7d6bed7b02a819cc56','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_8c2bee0b3d63ce7d6bed7b02a819cc56_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c2bee0b3d63ce7d6bed7b02a819cc56','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_8c2bee0b3d63ce7d6bed7b02a819cc56_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8c2bee0b3d63ce7d6bed7b02a819cc56','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
