<?php /* Smarty version 2.6.25, created on 2014-02-10 20:11:17
         compiled from print:328 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A4^A49^A494CF66%%print%3A328.inc'] = '3b8737d2b8db313efe29e03df18fa97e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:328', 2, false),array('function', 'metadata', 'print:328', 2, false),array('function', 'stylesheet', 'print:328', 2, false),array('function', 'content', 'print:328', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3b8737d2b8db313efe29e03df18fa97e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b8737d2b8db313efe29e03df18fa97e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_3b8737d2b8db313efe29e03df18fa97e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b8737d2b8db313efe29e03df18fa97e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_3b8737d2b8db313efe29e03df18fa97e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b8737d2b8db313efe29e03df18fa97e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_3b8737d2b8db313efe29e03df18fa97e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('3b8737d2b8db313efe29e03df18fa97e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
