<?php /* Smarty version 2.6.25, created on 2014-02-07 23:42:58
         compiled from print:264 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C8^C88^C88C2C7E%%print%3A264.inc'] = 'cc4be96c7213fcdd85e5f1a4b6b97eb8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:264', 2, false),array('function', 'metadata', 'print:264', 2, false),array('function', 'stylesheet', 'print:264', 2, false),array('function', 'content', 'print:264', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cc4be96c7213fcdd85e5f1a4b6b97eb8_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc4be96c7213fcdd85e5f1a4b6b97eb8','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_cc4be96c7213fcdd85e5f1a4b6b97eb8_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc4be96c7213fcdd85e5f1a4b6b97eb8','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_cc4be96c7213fcdd85e5f1a4b6b97eb8_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc4be96c7213fcdd85e5f1a4b6b97eb8','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_cc4be96c7213fcdd85e5f1a4b6b97eb8_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cc4be96c7213fcdd85e5f1a4b6b97eb8','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
