<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:19
         compiled from print:80 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%47^479^479BC39F%%print%3A80.inc'] = 'b0c2c3895c8fda7ec8ad5d8018aac275';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:80', 2, false),array('function', 'metadata', 'print:80', 2, false),array('function', 'stylesheet', 'print:80', 2, false),array('function', 'content', 'print:80', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0c2c3895c8fda7ec8ad5d8018aac275_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c2c3895c8fda7ec8ad5d8018aac275','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0c2c3895c8fda7ec8ad5d8018aac275_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c2c3895c8fda7ec8ad5d8018aac275','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0c2c3895c8fda7ec8ad5d8018aac275_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c2c3895c8fda7ec8ad5d8018aac275','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0c2c3895c8fda7ec8ad5d8018aac275_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0c2c3895c8fda7ec8ad5d8018aac275','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
