<?php /* Smarty version 2.6.25, created on 2014-02-11 01:16:04
         compiled from print:355 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%95^956^9564251C%%print%3A355.inc'] = 'd18bb76483423d072e62b0e03d8e688a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:355', 2, false),array('function', 'metadata', 'print:355', 2, false),array('function', 'stylesheet', 'print:355', 2, false),array('function', 'content', 'print:355', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d18bb76483423d072e62b0e03d8e688a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d18bb76483423d072e62b0e03d8e688a','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d18bb76483423d072e62b0e03d8e688a_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d18bb76483423d072e62b0e03d8e688a','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d18bb76483423d072e62b0e03d8e688a_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d18bb76483423d072e62b0e03d8e688a','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d18bb76483423d072e62b0e03d8e688a_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d18bb76483423d072e62b0e03d8e688a','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
