<?php /* Smarty version 2.6.25, created on 2014-02-10 22:28:57
         compiled from print:321 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%DD^DD4^DD4877C2%%print%3A321.inc'] = '89147cdb30fc4ef9eaabe269870d00e4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:321', 2, false),array('function', 'metadata', 'print:321', 2, false),array('function', 'stylesheet', 'print:321', 2, false),array('function', 'content', 'print:321', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_89147cdb30fc4ef9eaabe269870d00e4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89147cdb30fc4ef9eaabe269870d00e4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_89147cdb30fc4ef9eaabe269870d00e4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89147cdb30fc4ef9eaabe269870d00e4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_89147cdb30fc4ef9eaabe269870d00e4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89147cdb30fc4ef9eaabe269870d00e4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_89147cdb30fc4ef9eaabe269870d00e4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('89147cdb30fc4ef9eaabe269870d00e4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
