<?php /* Smarty version 2.6.25, created on 2014-02-02 19:55:02
         compiled from print:267 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%51^518^51857DC4%%print%3A267.inc'] = '308cc43607905eb5306a455efe7c934e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:267', 2, false),array('function', 'metadata', 'print:267', 2, false),array('function', 'stylesheet', 'print:267', 2, false),array('function', 'content', 'print:267', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_308cc43607905eb5306a455efe7c934e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('308cc43607905eb5306a455efe7c934e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_308cc43607905eb5306a455efe7c934e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('308cc43607905eb5306a455efe7c934e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_308cc43607905eb5306a455efe7c934e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('308cc43607905eb5306a455efe7c934e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_308cc43607905eb5306a455efe7c934e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('308cc43607905eb5306a455efe7c934e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
