<?php /* Smarty version 2.6.25, created on 2014-02-07 21:18:29
         compiled from print:153 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%7F^7F8^7F835447%%print%3A153.inc'] = 'a14627795d891663571108872cd13f56';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:153', 2, false),array('function', 'metadata', 'print:153', 2, false),array('function', 'stylesheet', 'print:153', 2, false),array('function', 'content', 'print:153', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a14627795d891663571108872cd13f56_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a14627795d891663571108872cd13f56','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a14627795d891663571108872cd13f56_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a14627795d891663571108872cd13f56','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a14627795d891663571108872cd13f56_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a14627795d891663571108872cd13f56','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a14627795d891663571108872cd13f56_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a14627795d891663571108872cd13f56','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
