<?php /* Smarty version 2.6.25, created on 2014-02-07 21:42:49
         compiled from print:111 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F5^F5E^F5E1F06F%%print%3A111.inc'] = '40a7a76ddc1d0be089e4504f6f502a6f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:111', 2, false),array('function', 'metadata', 'print:111', 2, false),array('function', 'stylesheet', 'print:111', 2, false),array('function', 'content', 'print:111', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_40a7a76ddc1d0be089e4504f6f502a6f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('40a7a76ddc1d0be089e4504f6f502a6f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_40a7a76ddc1d0be089e4504f6f502a6f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('40a7a76ddc1d0be089e4504f6f502a6f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_40a7a76ddc1d0be089e4504f6f502a6f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('40a7a76ddc1d0be089e4504f6f502a6f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_40a7a76ddc1d0be089e4504f6f502a6f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('40a7a76ddc1d0be089e4504f6f502a6f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
