<?php /* Smarty version 2.6.25, created on 2014-02-12 05:50:02
         compiled from print:335 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C3^C33^C33E829A%%print%3A335.inc'] = '99568bb73e616c2ba933b41bb8fd418f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:335', 2, false),array('function', 'metadata', 'print:335', 2, false),array('function', 'stylesheet', 'print:335', 2, false),array('function', 'content', 'print:335', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_99568bb73e616c2ba933b41bb8fd418f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99568bb73e616c2ba933b41bb8fd418f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_99568bb73e616c2ba933b41bb8fd418f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99568bb73e616c2ba933b41bb8fd418f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_99568bb73e616c2ba933b41bb8fd418f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99568bb73e616c2ba933b41bb8fd418f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_99568bb73e616c2ba933b41bb8fd418f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('99568bb73e616c2ba933b41bb8fd418f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
