<?php /* Smarty version 2.6.25, created on 2014-02-01 23:14:52
         compiled from print:250 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E4^E4C^E4CCBBA4%%print%3A250.inc'] = 'f798d9c95424aa1e97df90a5c8f8bbd3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:250', 2, false),array('function', 'metadata', 'print:250', 2, false),array('function', 'stylesheet', 'print:250', 2, false),array('function', 'content', 'print:250', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f798d9c95424aa1e97df90a5c8f8bbd3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f798d9c95424aa1e97df90a5c8f8bbd3','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f798d9c95424aa1e97df90a5c8f8bbd3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f798d9c95424aa1e97df90a5c8f8bbd3','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f798d9c95424aa1e97df90a5c8f8bbd3_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f798d9c95424aa1e97df90a5c8f8bbd3','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f798d9c95424aa1e97df90a5c8f8bbd3_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f798d9c95424aa1e97df90a5c8f8bbd3','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
