<?php /* Smarty version 2.6.25, created on 2014-02-01 23:08:01
         compiled from print:154 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%E1^E1E^E1E7C1E4%%print%3A154.inc'] = '918621252242c48efeff009c91e6149b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:154', 2, false),array('function', 'metadata', 'print:154', 2, false),array('function', 'stylesheet', 'print:154', 2, false),array('function', 'content', 'print:154', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_918621252242c48efeff009c91e6149b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('918621252242c48efeff009c91e6149b','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_918621252242c48efeff009c91e6149b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('918621252242c48efeff009c91e6149b','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_918621252242c48efeff009c91e6149b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('918621252242c48efeff009c91e6149b','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_918621252242c48efeff009c91e6149b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('918621252242c48efeff009c91e6149b','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
