<?php /* Smarty version 2.6.25, created on 2014-02-12 07:07:04
         compiled from print:115 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F2^F28^F28C3476%%print%3A115.inc'] = '92bd37376b0de743f60fbc1430540b1e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:115', 2, false),array('function', 'metadata', 'print:115', 2, false),array('function', 'stylesheet', 'print:115', 2, false),array('function', 'content', 'print:115', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_92bd37376b0de743f60fbc1430540b1e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('92bd37376b0de743f60fbc1430540b1e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_92bd37376b0de743f60fbc1430540b1e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('92bd37376b0de743f60fbc1430540b1e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_92bd37376b0de743f60fbc1430540b1e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('92bd37376b0de743f60fbc1430540b1e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_92bd37376b0de743f60fbc1430540b1e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('92bd37376b0de743f60fbc1430540b1e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
