<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:21
         compiled from print:149 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%86^864^864D8C18%%print%3A149.inc'] = 'bfdea5b6f6b38b82e0b17b47b3982fcd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:149', 2, false),array('function', 'metadata', 'print:149', 2, false),array('function', 'stylesheet', 'print:149', 2, false),array('function', 'content', 'print:149', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bfdea5b6f6b38b82e0b17b47b3982fcd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfdea5b6f6b38b82e0b17b47b3982fcd','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_bfdea5b6f6b38b82e0b17b47b3982fcd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfdea5b6f6b38b82e0b17b47b3982fcd','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_bfdea5b6f6b38b82e0b17b47b3982fcd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfdea5b6f6b38b82e0b17b47b3982fcd','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_bfdea5b6f6b38b82e0b17b47b3982fcd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('bfdea5b6f6b38b82e0b17b47b3982fcd','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
