<?php /* Smarty version 2.6.25, created on 2014-02-02 07:55:23
         compiled from print:210 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%80^80A^80A07EA0%%print%3A210.inc'] = '127dd5cf419be3e1c4f98fde7583c27e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:210', 2, false),array('function', 'metadata', 'print:210', 2, false),array('function', 'stylesheet', 'print:210', 2, false),array('function', 'content', 'print:210', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_127dd5cf419be3e1c4f98fde7583c27e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('127dd5cf419be3e1c4f98fde7583c27e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_127dd5cf419be3e1c4f98fde7583c27e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('127dd5cf419be3e1c4f98fde7583c27e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_127dd5cf419be3e1c4f98fde7583c27e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('127dd5cf419be3e1c4f98fde7583c27e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_127dd5cf419be3e1c4f98fde7583c27e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('127dd5cf419be3e1c4f98fde7583c27e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
