<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:57
         compiled from print:302 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%76^767^767744FA%%print%3A302.inc'] = 'ec4bebffa4e056d94da4f8636c22c98e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:302', 2, false),array('function', 'metadata', 'print:302', 2, false),array('function', 'stylesheet', 'print:302', 2, false),array('function', 'content', 'print:302', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ec4bebffa4e056d94da4f8636c22c98e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec4bebffa4e056d94da4f8636c22c98e','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ec4bebffa4e056d94da4f8636c22c98e_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec4bebffa4e056d94da4f8636c22c98e','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ec4bebffa4e056d94da4f8636c22c98e_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec4bebffa4e056d94da4f8636c22c98e','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ec4bebffa4e056d94da4f8636c22c98e_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ec4bebffa4e056d94da4f8636c22c98e','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
