<?php /* Smarty version 2.6.25, created on 2014-02-04 19:33:19
         compiled from print:131 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C7^C7D^C7D792ED%%print%3A131.inc'] = '6f89fe4275f82de68061836c5f25d367';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:131', 2, false),array('function', 'metadata', 'print:131', 2, false),array('function', 'stylesheet', 'print:131', 2, false),array('function', 'content', 'print:131', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6f89fe4275f82de68061836c5f25d367_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f89fe4275f82de68061836c5f25d367','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6f89fe4275f82de68061836c5f25d367_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f89fe4275f82de68061836c5f25d367','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6f89fe4275f82de68061836c5f25d367_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f89fe4275f82de68061836c5f25d367','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6f89fe4275f82de68061836c5f25d367_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6f89fe4275f82de68061836c5f25d367','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
