<?php /* Smarty version 2.6.25, created on 2014-02-07 22:14:00
         compiled from print:88 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%49^494^49404BAD%%print%3A88.inc'] = '0b52be24f4606d75f081b5b05b732acb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:88', 2, false),array('function', 'metadata', 'print:88', 2, false),array('function', 'stylesheet', 'print:88', 2, false),array('function', 'content', 'print:88', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0b52be24f4606d75f081b5b05b732acb_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0b52be24f4606d75f081b5b05b732acb','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0b52be24f4606d75f081b5b05b732acb_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0b52be24f4606d75f081b5b05b732acb','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_0b52be24f4606d75f081b5b05b732acb_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0b52be24f4606d75f081b5b05b732acb','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_0b52be24f4606d75f081b5b05b732acb_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0b52be24f4606d75f081b5b05b732acb','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
