<?php /* Smarty version 2.6.25, created on 2014-02-05 22:01:59
         compiled from print:194 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%4D^4D5^4D528EE8%%print%3A194.inc'] = 'b0db59e8ab05c55668b3139b0ebc57ac';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:194', 2, false),array('function', 'metadata', 'print:194', 2, false),array('function', 'stylesheet', 'print:194', 2, false),array('function', 'content', 'print:194', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b0db59e8ab05c55668b3139b0ebc57ac_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0db59e8ab05c55668b3139b0ebc57ac','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_b0db59e8ab05c55668b3139b0ebc57ac_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0db59e8ab05c55668b3139b0ebc57ac','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_b0db59e8ab05c55668b3139b0ebc57ac_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0db59e8ab05c55668b3139b0ebc57ac','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_b0db59e8ab05c55668b3139b0ebc57ac_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b0db59e8ab05c55668b3139b0ebc57ac','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
