<?php /* Smarty version 2.6.25, created on 2014-02-11 17:14:45
         compiled from print:208 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%97^976^9760C7D3%%print%3A208.inc'] = '21a196fa4cef8471616cbca017f2c96f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:208', 2, false),array('function', 'metadata', 'print:208', 2, false),array('function', 'stylesheet', 'print:208', 2, false),array('function', 'content', 'print:208', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_21a196fa4cef8471616cbca017f2c96f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21a196fa4cef8471616cbca017f2c96f','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_21a196fa4cef8471616cbca017f2c96f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21a196fa4cef8471616cbca017f2c96f','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_21a196fa4cef8471616cbca017f2c96f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21a196fa4cef8471616cbca017f2c96f','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_21a196fa4cef8471616cbca017f2c96f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('21a196fa4cef8471616cbca017f2c96f','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
