<?php /* Smarty version 2.6.25, created on 2014-02-12 01:08:12
         compiled from print:351 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%92^920^9209E105%%print%3A351.inc'] = 'f5427933c639dab335155819b18f7f38';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:351', 2, false),array('function', 'metadata', 'print:351', 2, false),array('function', 'stylesheet', 'print:351', 2, false),array('function', 'content', 'print:351', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f5427933c639dab335155819b18f7f38_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5427933c639dab335155819b18f7f38','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_f5427933c639dab335155819b18f7f38_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5427933c639dab335155819b18f7f38','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_f5427933c639dab335155819b18f7f38_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5427933c639dab335155819b18f7f38','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_f5427933c639dab335155819b18f7f38_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f5427933c639dab335155819b18f7f38','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
