<?php /* Smarty version 2.6.25, created on 2014-02-11 02:11:13
         compiled from print:119 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%FB^FB3^FB3A785D%%print%3A119.inc'] = '7f15666da68e7e9f8d274aa55f5376d2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:119', 2, false),array('function', 'metadata', 'print:119', 2, false),array('function', 'stylesheet', 'print:119', 2, false),array('function', 'content', 'print:119', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7f15666da68e7e9f8d274aa55f5376d2_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f15666da68e7e9f8d274aa55f5376d2','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7f15666da68e7e9f8d274aa55f5376d2_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f15666da68e7e9f8d274aa55f5376d2','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7f15666da68e7e9f8d274aa55f5376d2_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f15666da68e7e9f8d274aa55f5376d2','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7f15666da68e7e9f8d274aa55f5376d2_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7f15666da68e7e9f8d274aa55f5376d2','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
