<?php /* Smarty version 2.6.25, created on 2014-02-01 23:08:18
         compiled from print:148 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%F1^F14^F14ABC8E%%print%3A148.inc'] = '27fefbade90a6e532ebfc08bb779c3e0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:148', 2, false),array('function', 'metadata', 'print:148', 2, false),array('function', 'stylesheet', 'print:148', 2, false),array('function', 'content', 'print:148', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_27fefbade90a6e532ebfc08bb779c3e0_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27fefbade90a6e532ebfc08bb779c3e0','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_27fefbade90a6e532ebfc08bb779c3e0_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27fefbade90a6e532ebfc08bb779c3e0','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_27fefbade90a6e532ebfc08bb779c3e0_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27fefbade90a6e532ebfc08bb779c3e0','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_27fefbade90a6e532ebfc08bb779c3e0_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('27fefbade90a6e532ebfc08bb779c3e0','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
