<?php /* Smarty version 2.6.25, created on 2014-02-07 22:10:56
         compiled from print:217 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%1E^1EC^1EC4EB03%%print%3A217.inc'] = 'c8c6a92cf73b5966742d6cdd32a938de';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:217', 2, false),array('function', 'metadata', 'print:217', 2, false),array('function', 'stylesheet', 'print:217', 2, false),array('function', 'content', 'print:217', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c8c6a92cf73b5966742d6cdd32a938de_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8c6a92cf73b5966742d6cdd32a938de','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_c8c6a92cf73b5966742d6cdd32a938de_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8c6a92cf73b5966742d6cdd32a938de','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_c8c6a92cf73b5966742d6cdd32a938de_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8c6a92cf73b5966742d6cdd32a938de','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_c8c6a92cf73b5966742d6cdd32a938de_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c8c6a92cf73b5966742d6cdd32a938de','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
