<?php /* Smarty version 2.6.25, created on 2014-02-03 15:26:29
         compiled from print:175 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%A4^A4D^A4D693F0%%print%3A175.inc'] = 'd63d87e0f1e5e0b8452929fe90ddafe5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:175', 2, false),array('function', 'metadata', 'print:175', 2, false),array('function', 'stylesheet', 'print:175', 2, false),array('function', 'content', 'print:175', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_d63d87e0f1e5e0b8452929fe90ddafe5_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d63d87e0f1e5e0b8452929fe90ddafe5','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_d63d87e0f1e5e0b8452929fe90ddafe5_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d63d87e0f1e5e0b8452929fe90ddafe5','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_d63d87e0f1e5e0b8452929fe90ddafe5_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d63d87e0f1e5e0b8452929fe90ddafe5','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_d63d87e0f1e5e0b8452929fe90ddafe5_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('d63d87e0f1e5e0b8452929fe90ddafe5','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
