<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:35
         compiled from print:235 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%C2^C2F^C2FCE8AD%%print%3A235.inc'] = '7e39a8d2f4c8ef564eacb281c4f1d573';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:235', 2, false),array('function', 'metadata', 'print:235', 2, false),array('function', 'stylesheet', 'print:235', 2, false),array('function', 'content', 'print:235', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7e39a8d2f4c8ef564eacb281c4f1d573_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e39a8d2f4c8ef564eacb281c4f1d573','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7e39a8d2f4c8ef564eacb281c4f1d573_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e39a8d2f4c8ef564eacb281c4f1d573','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7e39a8d2f4c8ef564eacb281c4f1d573_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e39a8d2f4c8ef564eacb281c4f1d573','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7e39a8d2f4c8ef564eacb281c4f1d573_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e39a8d2f4c8ef564eacb281c4f1d573','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
