<?php /* Smarty version 2.6.25, created on 2014-02-07 22:12:19
         compiled from print:222 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/23^%%45^458^45834C4F%%print%3A222.inc'] = '50569323bbed9988e9984ce08d5ccab9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:222', 2, false),array('function', 'metadata', 'print:222', 2, false),array('function', 'stylesheet', 'print:222', 2, false),array('function', 'content', 'print:222', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_50569323bbed9988e9984ce08d5ccab9_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('50569323bbed9988e9984ce08d5ccab9','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_50569323bbed9988e9984ce08d5ccab9_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('50569323bbed9988e9984ce08d5ccab9','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_50569323bbed9988e9984ce08d5ccab9_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('50569323bbed9988e9984ce08d5ccab9','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_50569323bbed9988e9984ce08d5ccab9_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('50569323bbed9988e9984ce08d5ccab9','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
