<?php /* Smarty version 2.6.25, created on 2014-01-15 09:11:52
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/255^%%70^707^707A8977%%content%3Acontent_en.inc'] = '54e3810e0aa944572e45232113f6a96a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 14, false),)), $this); ?>
<?php
function _smarty_tplfunc_54e3810e0aa944572e45232113f6a96a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('54e3810e0aa944572e45232113f6a96a','0');echo smarty_cms_function_cms_selflink(array('href' => 'Zavileyskaya'), $_smarty);
}



?>
