<?php /* Smarty version 2.6.25, created on 2014-01-14 02:27:33
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/256^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ff310005bcc69bfee6e9b201810a1947';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff310005bcc69bfee6e9b201810a1947_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ff310005bcc69bfee6e9b201810a1947','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}



?>
