<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:41
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/274^%%70^707^707A8977%%content%3Acontent_en.inc'] = '83f7d77b62a157a35ad7ea8a3f165d1e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 10, false),)), $this); ?>
<?php
function _smarty_tplfunc_83f7d77b62a157a35ad7ea8a3f165d1e_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83f7d77b62a157a35ad7ea8a3f165d1e','0');echo smarty_cms_function_cms_selflink(array('href' => 'speakers'), $_smarty);
}



?>
