<?php /* Smarty version 2.6.25, created on 2014-01-14 02:33:52
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/276^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'b555c2aa749d48b3be7f704940aebdfe';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_b555c2aa749d48b3be7f704940aebdfe_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b555c2aa749d48b3be7f704940aebdfe','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}


function _smarty_tplfunc_b555c2aa749d48b3be7f704940aebdfe_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b555c2aa749d48b3be7f704940aebdfe','1');echo smarty_cms_function_cms_selflink(array('href' => 'odintsov-vladimir'), $_smarty);
}


function _smarty_tplfunc_b555c2aa749d48b3be7f704940aebdfe_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b555c2aa749d48b3be7f704940aebdfe','2');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_b555c2aa749d48b3be7f704940aebdfe_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b555c2aa749d48b3be7f704940aebdfe','3');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}



?>
