<?php /* Smarty version 2.6.25, created on 2014-01-13 14:56:20
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/283^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'ef4a8c11bebc06d7e307e816afe4432c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_ef4a8c11bebc06d7e307e816afe4432c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ef4a8c11bebc06d7e307e816afe4432c','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhyuri'), $_smarty);
}



?>
