<?php /* Smarty version 2.6.25, created on 2014-01-15 02:49:35
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/288^%%70^707^707A8977%%content%3Acontent_en.inc'] = '83bb05a1f0bc3331b36524c819b2cefd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 32, false),)), $this); ?>
<?php
function _smarty_tplfunc_83bb05a1f0bc3331b36524c819b2cefd_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83bb05a1f0bc3331b36524c819b2cefd','0');echo smarty_cms_function_cms_selflink(array('href' => 'zhdanov-sergej'), $_smarty);
}


function _smarty_tplfunc_83bb05a1f0bc3331b36524c819b2cefd_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83bb05a1f0bc3331b36524c819b2cefd','1');echo smarty_cms_function_cms_selflink(array('href' => 'aristov-sergej-viktorovich'), $_smarty);
}


function _smarty_tplfunc_83bb05a1f0bc3331b36524c819b2cefd_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83bb05a1f0bc3331b36524c819b2cefd','2');echo smarty_cms_function_cms_selflink(array('href' => 'igor-vyacheslavovich-dubinnikov'), $_smarty);
}


function _smarty_tplfunc_83bb05a1f0bc3331b36524c819b2cefd_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('83bb05a1f0bc3331b36524c819b2cefd','3');echo smarty_cms_function_cms_selflink(array('href' => 'odintsov-vladimir'), $_smarty);
}



?>
