<?php /* Smarty version 2.6.25, created on 2014-02-06 13:29:49
         compiled from print:293 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%D1^D17^D170A512%%print%3A293.inc'] = '7ced065f854c29a29152b358dfebeecf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:293', 2, false),array('function', 'metadata', 'print:293', 2, false),array('function', 'stylesheet', 'print:293', 2, false),array('function', 'content', 'print:293', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ced065f854c29a29152b358dfebeecf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ced065f854c29a29152b358dfebeecf','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7ced065f854c29a29152b358dfebeecf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ced065f854c29a29152b358dfebeecf','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7ced065f854c29a29152b358dfebeecf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ced065f854c29a29152b358dfebeecf','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7ced065f854c29a29152b358dfebeecf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ced065f854c29a29152b358dfebeecf','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
