<?php /* Smarty version 2.6.25, created on 2014-02-06 00:15:27
         compiled from print:292 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%A6^A67^A6779584%%print%3A292.inc'] = 'ca67b749301c4c5df39f3ecea676c734';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:292', 2, false),array('function', 'metadata', 'print:292', 2, false),array('function', 'stylesheet', 'print:292', 2, false),array('function', 'content', 'print:292', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ca67b749301c4c5df39f3ecea676c734_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca67b749301c4c5df39f3ecea676c734','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ca67b749301c4c5df39f3ecea676c734_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca67b749301c4c5df39f3ecea676c734','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ca67b749301c4c5df39f3ecea676c734_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca67b749301c4c5df39f3ecea676c734','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ca67b749301c4c5df39f3ecea676c734_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ca67b749301c4c5df39f3ecea676c734','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
