<?php /* Smarty version 2.6.25, created on 2014-01-29 10:31:52
         compiled from print:294 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%4F^4F1^4F1430B1%%print%3A294.inc'] = '6bb23ebd2ad8418425f578ff80ac60b4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:294', 2, false),array('function', 'metadata', 'print:294', 2, false),array('function', 'stylesheet', 'print:294', 2, false),array('function', 'content', 'print:294', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6bb23ebd2ad8418425f578ff80ac60b4_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6bb23ebd2ad8418425f578ff80ac60b4','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_6bb23ebd2ad8418425f578ff80ac60b4_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6bb23ebd2ad8418425f578ff80ac60b4','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_6bb23ebd2ad8418425f578ff80ac60b4_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6bb23ebd2ad8418425f578ff80ac60b4','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_6bb23ebd2ad8418425f578ff80ac60b4_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('6bb23ebd2ad8418425f578ff80ac60b4','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
