<?php /* Smarty version 2.6.25, created on 2014-02-11 00:37:28
         compiled from print:274 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%D1^D19^D1971D3F%%print%3A274.inc'] = 'a69d6ce240853b54b6dcd72a0bed8fff';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:274', 2, false),array('function', 'metadata', 'print:274', 2, false),array('function', 'stylesheet', 'print:274', 2, false),array('function', 'content', 'print:274', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a69d6ce240853b54b6dcd72a0bed8fff_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a69d6ce240853b54b6dcd72a0bed8fff','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_a69d6ce240853b54b6dcd72a0bed8fff_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a69d6ce240853b54b6dcd72a0bed8fff','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_a69d6ce240853b54b6dcd72a0bed8fff_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a69d6ce240853b54b6dcd72a0bed8fff','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_a69d6ce240853b54b6dcd72a0bed8fff_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a69d6ce240853b54b6dcd72a0bed8fff','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
