<?php /* Smarty version 2.6.25, created on 2014-02-12 05:42:25
         compiled from print:283 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%C8^C86^C86B9453%%print%3A283.inc'] = 'e7ed6a96108a7dcd0f37e6175a0c86db';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:283', 2, false),array('function', 'metadata', 'print:283', 2, false),array('function', 'stylesheet', 'print:283', 2, false),array('function', 'content', 'print:283', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e7ed6a96108a7dcd0f37e6175a0c86db_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e7ed6a96108a7dcd0f37e6175a0c86db','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_e7ed6a96108a7dcd0f37e6175a0c86db_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e7ed6a96108a7dcd0f37e6175a0c86db','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_e7ed6a96108a7dcd0f37e6175a0c86db_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e7ed6a96108a7dcd0f37e6175a0c86db','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_e7ed6a96108a7dcd0f37e6175a0c86db_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e7ed6a96108a7dcd0f37e6175a0c86db','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
