<?php /* Smarty version 2.6.25, created on 2014-02-07 22:11:01
         compiled from print:284 */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/29^%%56^560^560F01F0%%print%3A284.inc'] = '7c9ab0a4093f9fa09f6fe7446ca961b3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'print:284', 2, false),array('function', 'metadata', 'print:284', 2, false),array('function', 'stylesheet', 'print:284', 2, false),array('function', 'content', 'print:284', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7c9ab0a4093f9fa09f6fe7446ca961b3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7c9ab0a4093f9fa09f6fe7446ca961b3','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7c9ab0a4093f9fa09f6fe7446ca961b3_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7c9ab0a4093f9fa09f6fe7446ca961b3','1');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_7c9ab0a4093f9fa09f6fe7446ca961b3_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7c9ab0a4093f9fa09f6fe7446ca961b3','2');echo smarty_cms_function_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_7c9ab0a4093f9fa09f6fe7446ca961b3_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7c9ab0a4093f9fa09f6fe7446ca961b3','3');echo smarty_cms_function_content(array(), $_smarty);
}



?>
