<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:39
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/314^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'fd85f713af8dbc3461374b9b054d1f33';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 115, false),)), $this); ?>
<?php
function _smarty_tplfunc_fd85f713af8dbc3461374b9b054d1f33_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('fd85f713af8dbc3461374b9b054d1f33','0');echo smarty_cms_function_cms_selflink(array('href' => 'fotootchet-konferentsii'), $_smarty);
}



?>
