<?php /* Smarty version 2.6.25, created on 2014-02-11 15:54:01
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/56^%%70^707^707A8977%%content%3Acontent_en.inc'] = '35da9ef20637cfbc58801048c3e62f54';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_35da9ef20637cfbc58801048c3e62f54_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35da9ef20637cfbc58801048c3e62f54','0');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'logout'), $_smarty);
}


function _smarty_tplfunc_35da9ef20637cfbc58801048c3e62f54_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('35da9ef20637cfbc58801048c3e62f54','1');echo smarty_cms_function_cms_module(array('module' => 'SelfRegistration','group' => 'registered'), $_smarty);
}



?>
