<?php /* Smarty version 2.6.25, created on 2014-01-13 13:58:34
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/64^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'c0a106ae9762bd8b7f3aed46909f3225';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_c0a106ae9762bd8b7f3aed46909f3225_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0a106ae9762bd8b7f3aed46909f3225','0');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'logout'), $_smarty);
}


function _smarty_tplfunc_c0a106ae9762bd8b7f3aed46909f3225_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('c0a106ae9762bd8b7f3aed46909f3225','1');echo smarty_cms_function_cms_module(array('module' => 'FrontEndUsers','form' => 'login'), $_smarty);
}



?>
