<?php /* Smarty version 2.6.25, created on 2014-01-13 13:58:33
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/67^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'e6efd4ac1e1a279405db85c1c20bb729';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'contact_form', 'content:content_en', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_e6efd4ac1e1a279405db85c1c20bb729_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e6efd4ac1e1a279405db85c1c20bb729','0');echo smarty_cms_function_contact_form(array('email' => "ad.dir@clubcochubey.ru",'captcha' => 'true'), $_smarty);
}



?>
