<?php /* Smarty version 2.6.25, created on 2014-01-31 22:05:00
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/71^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'f6377aa9120c7f30c5692a023019509c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'CGUserDirectory', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_f6377aa9120c7f30c5692a023019509c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f6377aa9120c7f30c5692a023019509c','0');echo $_smarty->_plugins['function']['CGUserDirectory'][0][0]->function_plugin(array('group' => 'Authorised','sortby' => "f:last_name"), $_smarty);
}



?>
