<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:53
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/76^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'aeaff844149fdc0f44a58e32dbf2ee94';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_aeaff844149fdc0f44a58e32dbf2ee94_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('aeaff844149fdc0f44a58e32dbf2ee94','0');echo smarty_cms_function_cms_selflink(array('href' => 'corp_communications_2010_report'), $_smarty);
}



?>
