<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:46
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/80^%%70^707^707A8977%%content%3Acontent_en.inc'] = '424f71f2457deed7073d872809ba461d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 200, false),)), $this); ?>
<?php
function _smarty_tplfunc_424f71f2457deed7073d872809ba461d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('424f71f2457deed7073d872809ba461d','0');echo smarty_cms_function_cms_selflink(array('href' => 'svetenkova-ekaterina-anatolevna'), $_smarty);
}



?>
