<?php /* Smarty version 2.6.25, created on 2014-01-20 16:28:49
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/86^%%70^707^707A8977%%content%3Acontent_en.inc'] = '064a6cc3223e1a10484f186ff9dbee4b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_selflink', 'content:content_en', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_064a6cc3223e1a10484f186ff9dbee4b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('064a6cc3223e1a10484f186ff9dbee4b','0');echo smarty_cms_function_cms_selflink(array('href' => 'ant-management'), $_smarty);
}


function _smarty_tplfunc_064a6cc3223e1a10484f186ff9dbee4b_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('064a6cc3223e1a10484f186ff9dbee4b','1');echo smarty_cms_function_cms_selflink(array('href' => 'ObzorZarplat-Ru'), $_smarty);
}


function _smarty_tplfunc_064a6cc3223e1a10484f186ff9dbee4b_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('064a6cc3223e1a10484f186ff9dbee4b','2');echo smarty_cms_function_cms_selflink(array('href' => 'vakansia'), $_smarty);
}


function _smarty_tplfunc_064a6cc3223e1a10484f186ff9dbee4b_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('064a6cc3223e1a10484f186ff9dbee4b','3');echo smarty_cms_function_cms_selflink(array('href' => 'obs'), $_smarty);
}


function _smarty_tplfunc_064a6cc3223e1a10484f186ff9dbee4b_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('064a6cc3223e1a10484f186ff9dbee4b','4');echo smarty_cms_function_cms_selflink(array('href' => 'imisp'), $_smarty);
}



?>
