<?php /* Smarty version 2.6.25, created on 2014-01-13 13:57:00
         compiled from content:content_en */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/90^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'cca87286819424d7d59114e754a0d638';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_cca87286819424d7d59114e754a0d638_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('cca87286819424d7d59114e754a0d638','0');echo smarty_cms_function_cms_module(array('module' => 'LinkMgr','category' => 'General'), $_smarty);
}



?>
