<?php /* Smarty version 2.6.25, created on 2014-01-13 13:58:26
         compiled from module_db_tpl:News%3BdetailSample */

$this->_cache_serials['/var/www/clubkochubey.ru/www/tmp/templates_c/News^%%E8^E85^E85D59E8%%module_db_tpl%3ANews%3BdetailSample.inc'] = 'be52dea94f393f9e168eaba9a585ca5a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'cms_date_format', 'module_db_tpl:News;detailSample', 12, false),array('modifier', 'cms_escape', 'module_db_tpl:News;detailSample', 15, false),array('function', 'eval', 'module_db_tpl:News;detailSample', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_be52dea94f393f9e168eaba9a585ca5a_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be52dea94f393f9e168eaba9a585ca5a','0');echo smarty_function_eval(array('var' => $_smarty->_tpl_vars['entry']->content), $_smarty);
}



?>
